#include "graphics/Downsample.h"
#include <algorithm>
#include <cmath>
#include <iostream>
#include <limits>
#include <map>
#include <stdexcept>
using namespace compositor;using namespace compositor::graphics;
namespace {
void require(bool v,const char* why){if(!v)throw std::runtime_error(why);}
std::shared_ptr<const Raster> noise(int width,int height){std::vector<Pixel> data(size_t(width)*height);uint32_t state=91;for(auto& p:data){state=state*1664525u+1013904223u;auto a=uint8_t(state>>24);p={uint8_t(unsigned(uint8_t(state>>16))*a/255),uint8_t(unsigned(uint8_t(state>>8))*a/255),uint8_t(unsigned(uint8_t(state))*a/255),a};}return Raster::fromRgba(width,height,reinterpret_cast<const uint8_t*>(data.data()),size_t(width)*4);}
void levels(){for(double factor:{double(NAN),double(INFINITY),-1.,0.,.5,.6,1.})require(DownsampleCache::levelFor(factor)==0,"identity factor guard");require(DownsampleCache::levelFor(.499)==1&&DownsampleCache::levelFor(.3)==1&&DownsampleCache::levelFor(.25)==2&&DownsampleCache::levelFor(.125)==3,"source halving thresholds");require(DownsampleCache::levelFor(std::numeric_limits<double>::denorm_min())==6,"tiny factor maxLevel");DownsampleCache cache;auto result=cache.level(noise(1024,1),100);require(result.image->width==1&&result.image->height==1&&result.level==10,"explicit level stops only at1x1");}
void odd_gray_and_alpha(){auto gray=std::make_shared<GrayRaster>(GrayRaster{9,5,std::vector<uint8_t>(45,173)});auto small=DownsampleCache::halve(*gray);require(small->width==5&&small->height==3&&std::all_of(small->pixels.begin(),small->pixels.end(),[](auto p){return p==173;}),"odd gray repeats edges without alpha/fade");auto color=DownsampleCache::halve(*noise(91,53));require(color->width==46&&color->height==27,"round up dimensions");for(int y=0;y<color->height;++y)for(int x=0;x<color->width;++x){auto p=color->pixel(x,y);require(p.r<=p.a&&p.g<=p.a&&p.b<=p.a,"all premultiplied channels");}auto white=DownsampleCache::halve(*Raster::filled(32,32,{255,255,255,255}));require(white->pixel(0,0).a<255&&white->pixel(8,8).a==255,"RGBA transparent padding edge fades");}
void cache_identity_eviction(){DownsampleCache cache(1024);auto a=noise(64,64),b=noise(64,64);auto ah=cache.image(a,.25);require(cache.entryCount()==1&&cache.retainedPixels()==1280,"current entry retained even above budget");auto bh=cache.image(b,.3);require(cache.entryCount()==1&&cache.retainedPixels()==1024,"oldest other identity evicted");require(cache.image(b,.3)==bh,"cached immutable identity");auto regenerated=cache.image(a,.25);require(regenerated!=ah,"evicted image regenerated");require(cache.image(a,.6)==a,"large scale source identity");cache.clear();require(cache.entryCount()==0&&cache.retainedPixels()==0,"clear releases chain");}
void aligned_piece_phase(){auto source=noise(192,128);std::vector<Pixel> pixels(128*96);for(int y=0;y<96;++y)for(int x=0;x<128;++x)pixels[size_t(y)*128+x]=source->pixel(x+32,y+16);auto crop=Raster::fromRgba(128,96,reinterpret_cast<const uint8_t*>(pixels.data()),128*4);auto whole=DownsampleCache::halve(*source),piece=DownsampleCache::halve(*crop);for(int y=6;y<piece->height-6;++y)for(int x=6;x<piece->width-6;++x)require(piece->pixel(x,y)==whole->pixel(x+16,y+8),"even-aligned piece resampling phase");}
void reduced_coverage(){Layer layer;layer.id=newId();layer.raster=noise(9,5);layer.transform={10,20,9,5,31,true,true};DownsampleCache cache;auto reduced=downsampleLayer(layer,.25,cache);require(reduced.raster->width==3&&reduced.raster->height==2,"ceil chain dimensions");auto oldOrigin=layer.transform.fromUnit({0,0}),newOrigin=reduced.transform.fromUnit({0,0});require(std::hypot(oldOrigin.x-newOrigin.x,oldOrigin.y-newOrigin.y)<1e-12,"coverage source origin retained with flips/rotation");require(reduced.transform.width==12&&reduced.transform.height==8,"coverage extends exact2^level source grid");layer.transform.sampling=Transform::Sampling::Nearest;require(downsampleLayer(layer,.01,cache)==layer,"Nearest bypasses reductions");}
}
int main(){int failed=0;for(auto [name,body]:std::map<std::string,void(*)()>{{"levels",levels},{"odd_gray_and_alpha",odd_gray_and_alpha},{"cache_identity_eviction",cache_identity_eviction},{"aligned_piece_phase",aligned_piece_phase},{"reduced_coverage",reduced_coverage}}){try{body();std::cout<<"PASS "<<name<<'\n';}catch(const std::exception& error){++failed;std::cout<<"FAIL "<<name<<": "<<error.what()<<'\n';}}return failed?1:0;}
