#include "graphics/SamplingSource.h"
#include "graphics/Downsample.h"
#include "graphics/StackRenderer.h"
#include <cmath>
#include <iostream>
#include <map>
#include <stdexcept>
using namespace compositor;using namespace compositor::graphics;
namespace {
void require(bool value,const char* why){if(!value)throw std::runtime_error(why);}
std::shared_ptr<const Raster> noise(int width,int height){std::vector<Pixel> values(size_t(width)*height);uint32_t seed=19;for(auto& p:values){seed=1664525u*seed+1013904223u;const auto a=uint8_t(seed>>24);p={uint8_t((seed>>16&255)*a/255),uint8_t((seed>>8&255)*a/255),uint8_t((seed&255)*a/255),a};}return Raster::fromRgba(width,height,reinterpret_cast<const uint8_t*>(values.data()),size_t(width)*4);}
void eager_equality(){for(auto size:std::array<Point,2>{{{33,19},{513,257}}}){auto source=noise(int(size.x),int(size.y));auto gray=std::make_shared<GrayRaster>(GrayRaster{source->width,source->height,std::vector<uint8_t>(size_t(source->width)*source->height)});for(int y=0;y<source->height;++y)for(int x=0;x<source->width;++x)gray->pixels[size_t(y)*source->width+x]=source->pixel(x,y).r;DownsampleCache eager;ReducedSourceCache lazy;for(int level=1;level<=3;++level){auto color=eager.level(source,level).image;auto reduced=lazy.resolve(samplingSource(source),level);auto mask=eager.level(std::shared_ptr<const GrayRaster>(gray),level).image;auto reducedMask=lazy.resolve(samplingSource(std::shared_ptr<const GrayRaster>(gray)),level);require(reduced->grid().width==color->width&&reduced->grid().height==color->height,"RGBA ceil dimensions");for(int y=0;y<color->height;++y)for(int x=0;x<color->width;++x){require(reduced->pixel(x,y)==color->pixel(x,y),"lazy tile equals full Lanczos chain");require(reducedMask->gray(x,y)==mask->pixel(x,y),"gray tile equals full Lanczos chain");}}}}
void alignment_phase(){auto source=noise(512,256);auto padded=std::make_shared<Raster>(*Raster::filled(547,275));std::vector<Pixel> values(512*256);for(int y=0;y<256;++y)for(int x=0;x<512;++x)values[size_t(y)*512+x]=source->pixel(x,y);auto pixels=padded->replacing(17,5,512,256,values.data(),512);padded=std::make_shared<Raster>(*pixels);padded->samplingOriginX=17;padded->samplingOriginY=5;ReducedSourceCache cache;for(int level=1;level<=3;++level){auto a=cache.resolve(samplingSource(source),level),b=cache.resolve(samplingSource(std::shared_ptr<const Raster>(padded)),level);const int step=1<<level;const auto grid=b->grid();require((17-grid.x)%step==0&&(5-grid.y)%step==0,"crop inherits halving phase");for(int y=64/step;y<192/step;++y)for(int x=64/step;x<448/step;++x)require(a->pixel(x,y)==b->pixel(x+(17-grid.x)/step,y+(5-grid.y)/step),"unchanged interior retains phase after odd negative crop");}}
void cache_bounds(){ReducedSourceCache cache(2,2);auto a=noise(1537,35),b=noise(67,35);auto first=cache.resolve(samplingSource(a),1);require(cache.resolve(samplingSource(a),1)==first,"resolved level identity reused");for(int x=0;x<first->grid().width;x+=200)first->pixel(x,5);require(cache.retainedTiles()<=2,"reduced tile LRU bound");auto second=cache.resolve(samplingSource(b),1);second->pixel(1,1);cache.resolve(samplingSource(noise(35,19)),1);require(cache.retainedSources()<=2&&cache.retainedTiles()<=2,"source and tile budgets");const auto p=first->pixel(4,4);cache.clear();require(cache.retainedTiles()==0&&cache.retainedSources()==0,"cache clear");require(first->pixel(4,4)==p,"live handle survives cache clear");}
void sparse_bound(){auto source=std::make_shared<SamplingSource>();source->width=30000;source->height=30000;source->identity=source;uint64_t reads=0;source->rgba=[&](int,int){++reads;return Pixel{};};ReducedSourceCache cache(16);auto reduced=cache.resolve(source,2);Raster::resetMaterializationCount();require(reduced->pixel(2000,2000)==Pixel{},"sparse pixel");require(reads>0&&reads<10000000&&cache.retainedTiles()<=16,"bounded sparse source work");require(Raster::materializationCount()==0,"no whole image materialization");source->identity.reset();}
void production_path(){auto image=noise(67,35);Layer layer;layer.id=newId();layer.raster=image;layer.transform={7.25,3.5,16.75,8.75};Document d;d.width=40;d.height=25;d.layers={layer};auto& cache=ReducedSourceCache::shared();cache.clear();auto frame=StackRenderer().render(d,0,0,40,25);require(frame&&cache.generatedTiles()>0,"canonical StackRenderer executes reduction");const auto generated=cache.generatedTiles();auto again=StackRenderer().render(d,0,0,40,25);require(again->rgba()==frame->rgba()&&cache.generatedTiles()==generated,"canonical repeated render reuses reduced tiles");d.layers[0].transform.sampling=Transform::Sampling::Nearest;cache.clear();StackRenderer().render(d,0,0,40,25);require(cache.generatedTiles()==0,"Nearest bypass");}
void invalid(){ReducedSourceCache cache;auto source=std::make_shared<SamplingSource>();source->width=30000;source->height=30000;source->identity=std::make_shared<int>(1);source->rgba=[](int,int){return Pixel{};};bool rejected=false;try{cache.resolve(source,17);}catch(const std::invalid_argument&){rejected=true;}require(rejected,"level shift bound");source->alignmentX=INT32_MIN;rejected=false;try{cache.resolve(source,1);}catch(const std::invalid_argument&){rejected=true;}require(rejected,"alignment overflow guard");}
}
int main(){std::cout<<std::unitbuf;int failed=0;for(auto [name,body]:std::map<std::string,void(*)()>{{"eager_equality",eager_equality},{"alignment_phase",alignment_phase},{"cache_bounds",cache_bounds},{"sparse_bound",sparse_bound},{"production_path",production_path},{"invalid",invalid}}){try{body();std::cout<<"PASS "<<name<<'\n';}catch(const std::exception& e){++failed;std::cout<<"FAIL "<<name<<": "<<e.what()<<'\n';}}return failed?1:0;}
