# Recheck the locked inputs at build time, including target-only rebuilds.
if(NOT DEFINED IMAGING_ROOT OR NOT DEFINED RUNTIME_DESTINATION)
  message(FATAL_ERROR "Provide IMAGING_ROOT and RUNTIME_DESTINATION")
endif()
file(READ "${IMAGING_ROOT}/lock.json" runtime_lock)
string(JSON binary_count LENGTH "${runtime_lock}" binaries)
math(EXPR binary_last "${binary_count}-1")
set(runtime_files)
foreach(index RANGE ${binary_last})
  string(JSON binary_path GET "${runtime_lock}" binaries ${index} path)
  string(JSON expected_hash GET "${runtime_lock}" binaries ${index} sha256)
  set(binary_file "${IMAGING_ROOT}/${binary_path}")
  file(SHA256 "${binary_file}" actual_hash)
  if(NOT actual_hash STREQUAL expected_hash)
    message(FATAL_ERROR "Locked imaging runtime checksum mismatch: ${binary_path}")
  endif()
  list(APPEND runtime_files "${binary_file}")
endforeach()
file(MAKE_DIRECTORY "${RUNTIME_DESTINATION}")
foreach(binary_file IN LISTS runtime_files)
  get_filename_component(binary_name "${binary_file}" NAME)
  file(COPY_FILE "${binary_file}" "${RUNTIME_DESTINATION}/${binary_name}" ONLY_IF_DIFFERENT)
endforeach()
