#include "ui/MainWindow.h"
#include "ui/SubjectPanel.h"
#include "imaging/wic_codec.h"
#include <QApplication>
#include <QDialogButtonBox>
#include <QElapsedTimer>
#include <QPushButton>
#include <QTest>
#include <QTimer>
#include <filesystem>
#include <cstdio>
#include <map>
using namespace compositor;
namespace {
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
template<class Fn>void wait(Fn test,const char* message){QElapsedTimer timer;timer.start();while(!test()){if(timer.elapsed()>30000)throw std::runtime_error(message);QApplication::processEvents(QEventLoop::AllEvents,20);QTest::qWait(1);}}
void trigger(MainWindow& window,const char* id){for(auto* action:window.findChildren<QAction*>())if(action->property("commandId")==id){require(action->isEnabled(),"source command enabled");action->trigger();return;}throw std::runtime_error("command missing");}
Document fixture(uint8_t coverage){const auto root=std::filesystem::path(__FILE__).parent_path().parent_path().parent_path();const auto image=imaging::WicCodec::decode(root/L"evidence/imaging/astronaut.png").image;Document d;d.id=newId();d.width=int(image.width);d.height=int(image.height);Layer layer;layer.id=newId();layer.name="Subject";layer.transform={0,0,double(d.width),double(d.height)};layer.raster=Raster::fromRgba(d.width,d.height,image.pixels.data(),image.stride);auto mask=std::make_shared<GrayRaster>();mask->width=d.width;mask->height=d.height;mask->pixels.assign(size_t(d.width)*d.height,coverage);layer.mask=Mask{mask};d.layers={layer};return d;}
QDialog* open(MainWindow& window){trigger(window,"filter.subject");QDialog* result=nullptr;wait([&]{for(auto* candidate:window.findChildren<QDialog*>())if(candidate->isVisible()&&candidate->objectName()=="subjectPanel")result=candidate;return result!=nullptr;},"nonmodal Subject opened");wait([&]{return result->findChild<QPushButton*>("applySubjectMask")->isEnabled();},"real Subject preview ready");return result;}
void apply(QDialog* dialog){QPointer<QDialog> guard=dialog;dialog->findChild<QPushButton*>("applySubjectMask")->click();wait([guard]{return !guard||!guard->isVisible();},"Subject full mask applied");}
void mask_once(){MainWindow window(true);auto original=fixture(128);auto& project=window.addProject(original);window.show();auto* panel=open(window);require(bool(project.effectPreview),"prepared main-canvas Subject preview");const auto preview=SoftwareRenderer().render(*project.effectPreview,0,0,original.width,original.height)->rgba();apply(panel);const auto final=SoftwareRenderer().render(*project.document,0,0,original.width,original.height)->rgba();require(preview.size()==final.size(),"same preview/full raster dimensions");int maximum=0;for(size_t i=0;i<preview.size();++i)maximum=std::max(maximum,std::abs(int(preview[i])-int(final[i])));std::printf("maximum_channel_delta=%d\n",maximum);require(maximum<=1,"existing mask applied once in preview and commit (fixed one-byte quantization bound)");require(project.document->layers[0].raster==original.layers[0].raster,"source pixels remain immutable");}
void current_mask(){MainWindow window(true);auto original=fixture(64);auto& project=window.addProject(original);project.history.begin("Change owned mask",project.document,project.active);auto changed=std::make_shared<GrayRaster>(*original.layers[0].mask->raster);std::fill(changed->pixels.begin(),changed->pixels.end(),128);project.document->layers[0].mask->raster=changed;project.history.end(project.document,project.active);window.show();trigger(window,"tool.move");auto* panel=open(window);require(bool(project.effectPreview),"Subject preview captured");const auto subject=project.effectPreview->layers[0].raster->rgba();window.activateWindow();project.canvas->setFocus();QApplication::processEvents();trigger(window,"edit.undo");require(project.document->layers[0].mask->raster==original.layers[0].mask->raster&&panel->isVisible(),"Undo restores current mask while Subject remains open");apply(panel);const auto& mask=*project.document->layers[0].mask->raster;for(size_t i=0;i<mask.pixels.size();++i)require(mask.pixels[i]==uint8_t((unsigned(subject[i*4+3])*64+127)/255),"Apply combines current compatible owned mask exactly once");require(project.history.undoCount()==1&&project.maskSelected,"replacement mask owns one history entry and edit target");}
void aggregate_budget(){auto document=fixture(255);auto shared=std::make_shared<GrayRaster>();shared->width=shared->height=5000;shared->pixels.assign(25000000,255);for(int i=0;i<4;++i){Layer layer;layer.id=newId();layer.name="Other mask";layer.transform={0,0,1,1};layer.mask=Mask{shared};document.layers.push_back(layer);}document.layers[0].mask.reset();validateDocument(document);bool rejected=false;try{ui::EditPanelHost host;openSubjectPanel(nullptr,document,document.layers[0],std::filesystem::path(L"model-must-not-be-opened.onnx"),{},std::move(host));}catch(const std::exception& error){rejected=std::string(error.what()).find("project mask budget")!=std::string::npos;}require(rejected,"aggregate mask budget rejects before model/source preparation");}
}
int main(int argc,char** argv){QApplication app(argc,argv);const std::map<std::string,void(*)()> cases{{"mask_once",mask_once},{"current_mask",current_mask},{"aggregate_budget",aggregate_budget}};try{require(argc==2&&cases.contains(argv[1]),"provide mask contract case");cases.at(argv[1])();std::printf("PASS %s\n",argv[1]);return 0;}catch(const std::exception& error){std::fprintf(stderr,"FAIL %s: %s\n",argc>1?argv[1]:"argument",error.what());return 1;}}
