#include "ui/MainWindow.h"
#include "ui/PaletteDialog.h"
#include "imaging/wic_codec.h"
#include <QApplication>
#include <QAbstractSpinBox>
#include <QCheckBox>
#include <QColorDialog>
#include <QDialogButtonBox>
#include <QElapsedTimer>
#include <QEventLoop>
#include <QFormLayout>
#include <QLineEdit>
#include <QPushButton>
#include <QTest>
#include <QTimer>
#include <filesystem>
#include <cstdio>
#include <map>
using namespace compositor;
namespace {
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
template<class Fn>void wait(Fn predicate,const char* message){QElapsedTimer timer;timer.start();while(!predicate()){if(timer.elapsed()>30000)throw std::runtime_error(message);QApplication::processEvents(QEventLoop::AllEvents,20);QTest::qWait(1);}}
QAction* action(MainWindow& window,const char* id){for(auto* item:window.findChildren<QAction*>())if(item->property("commandId")==id)return item;throw std::runtime_error(std::string("missing command ")+id);}
void trigger(MainWindow& window,const char* id){auto* item=action(window,id);require(item->isEnabled(),"requested command enabled");item->trigger();}
Document fixture(bool subject){Document d;d.id=newId();d.width=128;d.height=128;Layer layer;layer.id=newId();layer.name="Pixels";layer.transform={0,0,128,128};if(subject){const auto root=std::filesystem::path(__FILE__).parent_path().parent_path().parent_path();const auto image=imaging::WicCodec::decode(root/L"evidence/imaging/astronaut.png").image;layer.raster=Raster::fromRgba(int(image.width),int(image.height),image.pixels.data(),image.stride);}else layer.raster=Raster::filled(128,128,{128,128,128,255});d.layers={layer};return d;}
struct Fixture {MainWindow window{true};EditorProject& project;Document before;explicit Fixture(bool subject=false):project(window.addProject(fixture(subject))),before(*project.document){window.show();QApplication::processEvents();}void unchanged(){require(project.document==before&&project.history.undoCount()==0&&!project.history.modified(),"draft leaves exact canonical document and history unchanged");}Pixel visible(int x=64,int y=64){auto result=project.canvas->viewportProvider(0,0,128,128,1);require(bool(result.raster),"actual viewport provider returned raster");return result.raster->pixel(x,y);}void click(Point point){const auto mapped=project.canvas->viewMapping().toView(point);QTest::mouseClick(project.canvas,Qt::LeftButton,{},QPoint(int(mapped.x),int(mapped.y)));QApplication::processEvents();}};
QPushButton* apply(QDialog& dialog){auto* buttons=dialog.findChild<QDialogButtonBox*>();require(buttons,"panel button box");auto* result=buttons->button(QDialogButtonBox::Apply);require(result,"panel Apply button");return result;}
void ready(QDialog& dialog){wait([&]{return apply(dialog)->isEnabled();},"real preview did not become ready in30 seconds");}
QCheckBox* previewSwitch(QDialog& dialog){for(auto* box:dialog.findChildren<QCheckBox*>())if(box->text()=="Preview")return box;throw std::runtime_error("source FilterSheet68 Preview switch exists");}
template<class Fn>void panel(Fixture& f,const char* command,const QString& title,Fn body){QEventLoop loop;QTimer timer;timer.setInterval(10);QElapsedTimer elapsed;elapsed.start();std::exception_ptr failure;bool visited=false;QObject::connect(&timer,&QTimer::timeout,&f.window,[&]{QPointer<QDialog> found;for(auto* item:f.window.findChildren<QDialog*>())if(item->isVisible()&&item->windowTitle()==title){found=item;break;}if(!found){if(elapsed.elapsed()<30000)return;timer.stop();failure=std::make_exception_ptr(std::runtime_error("owned editor panel not found"));loop.quit();return;}timer.stop();visited=true;try{body(*found);}catch(...){failure=std::current_exception();}if(found&&found->isVisible())found->reject();loop.quit();});timer.start();QTimer::singleShot(0,&f.window,[&]{try{trigger(f.window,command);}catch(...){failure=std::current_exception();timer.stop();loop.quit();}});loop.exec();if(failure)std::rethrow_exception(failure);require(visited,"actual panel visited");QApplication::processEvents();}
QAbstractSpinBox* number(QDialog& dialog,const QString& name){for(auto* field:dialog.findChildren<QAbstractSpinBox*>())if(field->accessibleName()==name)return field;throw std::runtime_error("subject numeric field");}
void subject_nonmodal(){Fixture f(true);panel(f,"filter.subject","Remove Background",[&](QDialog& p){require(p.windowModality()==Qt::NonModal&&QApplication::activeModalWidget()==nullptr&&f.window.isEnabled(),"Remove Background uses source nonmodal Filter panel");f.unchanged();});}
void subject_canvas_preview(){Fixture f(true);panel(f,"filter.subject","Remove Background",[&](QDialog& p){ready(p);require(bool(f.project.effectPreview),"refined subject preview is displayed in main canvas");const auto shown=f.project.canvas->viewportProvider(0,0,128,128,1);const auto original=SoftwareRenderer().render(f.before,0,0,128,128);require(shown.raster->rgba()!=original->rgba(),"real foreground inference changes canvas pixels");f.unchanged();});f.unchanged();}
void subject_preview_toggle(){Fixture f(true);panel(f,"filter.subject","Remove Background",[&](QDialog& p){ready(p);auto* toggle=previewSwitch(p);require(toggle->isChecked()&&bool(f.project.effectPreview),"subject Preview initially enabled");toggle->setChecked(false);require(!f.project.effectPreview,"Preview off restores original main canvas immediately");toggle->setChecked(true);require(bool(f.project.effectPreview),"Preview on restores cached subject result");f.unchanged();});}
void subject_cancel(){Fixture f(true);panel(f,"filter.subject","Remove Background",[&](QDialog& p){p.reject();f.unchanged();require(!f.project.effectPreview,"Cancel clears subject preview");});QTest::qWait(250);QApplication::processEvents();f.unchanged();require(!f.project.effectPreview,"completed cancelled worker cannot publish later");}
void subject_apply(){Fixture f(true);panel(f,"filter.subject","Remove Background",[&](QDialog& p){ready(p);QPointer<QDialog> guard=&p;apply(p)->click();wait([guard]{return !guard||!guard->isVisible();},"source-size mask Apply completed");});const auto& layer=f.project.document->layers[0];require(layer.mask&&layer.mask->enabled&&f.project.maskSelected,"Apply enables mask and selects mask edit target");require(layer.raster==f.before.layers[0].raster&&layer.transform==f.before.layers[0].transform,"Apply retains original immutable raster and transform");require(layer.mask->raster->width==layer.raster->width&&layer.mask->raster->height==layer.raster->height&&f.project.history.undoCount()==1,"full-resolution subject mask is one undo edit");f.window.activateWindow();f.project.canvas->setFocus();QApplication::processEvents();trigger(f.window,"edit.undo");require(f.project.document==f.before,"subject Undo restores exact original");}
void subject_ranges(){Fixture f(true);panel(f,"filter.subject","Remove Background",[&](QDialog& p){auto* quality=p.findChild<QComboBox*>("backgroundQuality");require(quality&&quality->count()==2&&quality->currentIndex()==0,"Basic/Advanced source quality controls");auto* refine=number(p,"Refine");auto* contrast=number(p,"Contrast");auto* shift=number(p,"Shift Edge");require(refine->property("minimum").toDouble()==0&&refine->property("maximum").toDouble()==40&&refine->property("value").toDouble()==12,"Refine source range and default");require(contrast->property("minimum").toDouble()==0&&contrast->property("maximum").toDouble()==100&&contrast->property("value").toDouble()==25,"Contrast source range and default");require(shift->property("minimum").toDouble()==-10&&shift->property("maximum").toDouble()==10&&shift->property("value").toDouble()==0,"Shift source range and default");});}
void subject_shift_step(){Fixture f(true);panel(f,"filter.subject","Remove Background",[&](QDialog& p){ready(p);auto* quality=p.findChild<QComboBox*>("backgroundQuality");require(quality,"background quality selector");quality->setCurrentIndex(1);auto* refine=number(p,"Refine");refine->setFocus();QTest::keyClick(refine,Qt::Key_Up,Qt::ShiftModifier);require(refine->property("value").toDouble()==22,"source Shift arrow uses ten ordinary refinement steps");});}
QPushButton* endpointButton(QDialog& p,bool highlights=false){for(auto* form:p.findChildren<QFormLayout*>())for(int row=0;row<form->rowCount();++row){auto* label=form->itemAt(row,QFormLayout::LabelRole);auto* field=form->itemAt(row,QFormLayout::FieldRole);if(label&&field&&label->widget()&&label->widget()->property("text").toString()==(highlights?"Highlights":"Shadows"))if(auto* button=qobject_cast<QPushButton*>(field->widget()))return button;}throw std::runtime_error("Gradient Map endpoint button");}
template<class Fn>void endpoint(Fixture& f,QDialog& p,Fn body){QEventLoop loop;QTimer timer;timer.setInterval(10);std::exception_ptr failure;bool visited=false;QElapsedTimer elapsed;elapsed.start();QObject::connect(&timer,&QTimer::timeout,&f.window,[&]{QPointer<PaletteDialog> found;QPointer<QColorDialog> other;for(auto* widget:f.window.findChildren<QWidget*>()){if(auto* app=dynamic_cast<PaletteDialog*>(widget);app&&app->isVisible())found=app;if(auto* system=dynamic_cast<QColorDialog*>(widget);system&&system->isVisible())other=system;}if(other&&!found){timer.stop();failure=std::make_exception_ptr(std::runtime_error("Gradient Map must use the application PaletteDialog"));other->reject();loop.quit();return;}if(!found){if(elapsed.elapsed()<30000)return;timer.stop();failure=std::make_exception_ptr(std::runtime_error("endpoint application picker not found"));loop.quit();return;}timer.stop();visited=true;try{body(*found);}catch(...){failure=std::current_exception();}if(found&&found->isVisible())found->reject();loop.quit();});timer.start();QTimer::singleShot(0,&f.window,[&]{try{endpointButton(p)->click();}catch(...){failure=std::current_exception();timer.stop();loop.quit();}});loop.exec();if(failure)std::rethrow_exception(failure);require(visited,"actual endpoint picker visited");}
effects_tools::PaletteColor red(){return {1,0,0};}
void gradient_picker_app(){Fixture f;panel(f,"adjust.gradient_map","Gradient Map",[&](QDialog& p){ready(p);endpoint(f,p,[&](PaletteDialog& picker){require(picker.windowTitle()=="Color Picker (Gradient Map Shadows)"&&picker.windowModality()==Qt::NonModal&&QApplication::activeModalWidget()==nullptr,"named source endpoint picker is nonmodal");f.unchanged();});});}
void gradient_working_cancel(){Fixture f;panel(f,"adjust.gradient_map","Gradient Map",[&](QDialog& p){ready(p);const auto original=f.visible();endpoint(f,p,[&](PaletteDialog& picker){picker.sample(red());wait([&]{return f.visible()!=original;},"working endpoint previews on actual canvas");f.unchanged();picker.reject();wait([&]{return f.visible()==original;},"endpoint Cancel restores original preview");require(endpointButton(p)->text()=="#000000","Cancel restores source endpoint value");});});f.unchanged();}
void gradient_working_apply(){Fixture f;panel(f,"adjust.gradient_map","Gradient Map",[&](QDialog& p){ready(p);endpoint(f,p,[&](PaletteDialog& picker){picker.sample(red());picker.accept();});ready(p);require(endpointButton(p)->text()=="#ff0000","picker Apply retains endpoint value");f.unchanged();QPointer<QDialog> guard=&p;apply(p)->click();wait([guard]{return !guard||!guard->isVisible();},"Gradient Map Apply completed");});require(f.project.document->layers[0].raster!=f.before.layers[0].raster&&f.project.history.undoCount()==1,"parent Apply commits one source image edit");trigger(f.window,"palette.foreground");for(auto* widget:f.window.findChildren<QWidget*>())if(auto* picker=dynamic_cast<PaletteDialog*>(widget);picker&&picker->isVisible()){require(picker->color().hex()=="000000","endpoint does not alter foreground palette");picker->reject();}}
void gradient_parent_cancel(){Fixture f;panel(f,"adjust.gradient_map","Gradient Map",[&](QDialog& p){ready(p);endpoint(f,p,[&](PaletteDialog& picker){QPointer<PaletteDialog> guard=&picker;picker.sample(red());p.reject();wait([guard]{return !guard||!guard->isVisible();},"parent Cancel closes endpoint picker");});});f.unchanged();}
void gradient_parent_apply(){Fixture f;panel(f,"adjust.gradient_map","Gradient Map",[&](QDialog& p){ready(p);endpoint(f,p,[&](PaletteDialog& picker){QPointer<PaletteDialog> pickerGuard=&picker;picker.sample(red());ready(p);QPointer<QDialog> panelGuard=&p;apply(p)->click();wait([panelGuard]{return !panelGuard||!panelGuard->isVisible();},"parent Apply with open endpoint completes");require(!pickerGuard||!pickerGuard->isVisible(),"parent Apply closes endpoint picker");});});require(f.project.history.undoCount()==1&&f.project.document->layers[0].raster->pixel(64,64).r>128,"parent Apply keeps working red endpoint");}
void gradient_canvas_sample(){Fixture f;panel(f,"adjust.gradient_map","Gradient Map",[&](QDialog& p){ready(p);const auto sample=f.visible();endpoint(f,p,[&](PaletteDialog& picker){f.click({64,64});auto expected=effects_tools::PaletteColor{sample.r/255.,sample.g/255.,sample.b/255.};require(picker.color().hex()==expected.hex(),"endpoint picker samples current composite through actual canvas callback");});});}
void gradient_endpoint_exclusion(){Fixture f;panel(f,"adjust.gradient_map","Gradient Map",[&](QDialog& p){ready(p);endpoint(f,p,[&](PaletteDialog& picker){picker.sample(red());endpointButton(p,true)->click();require(picker.isVisible()&&picker.windowTitle()=="Color Picker (Gradient Map Shadows)"&&picker.color().hex()=="FF0000","existing endpoint picker excludes opening another endpoint");});});}
}
int main(int argc,char** argv){QApplication::setAttribute(Qt::AA_DontUseNativeDialogs);QApplication app(argc,argv);const std::map<std::string,void(*)()> cases{{"subject_nonmodal",subject_nonmodal},{"subject_canvas_preview",subject_canvas_preview},{"subject_preview_toggle",subject_preview_toggle},{"subject_cancel",subject_cancel},{"subject_apply",subject_apply},{"subject_ranges",subject_ranges},{"subject_shift_step",subject_shift_step},{"gradient_picker_app",gradient_picker_app},{"gradient_working_cancel",gradient_working_cancel},{"gradient_working_apply",gradient_working_apply},{"gradient_parent_cancel",gradient_parent_cancel},{"gradient_parent_apply",gradient_parent_apply},{"gradient_canvas_sample",gradient_canvas_sample},{"gradient_endpoint_exclusion",gradient_endpoint_exclusion}};try{require(argc==2&&cases.contains(argv[1]),"provide named panel follow-up case");cases.at(argv[1])();std::printf("PASS %s\n",argv[1]);return 0;}catch(const std::exception& error){std::fprintf(stderr,"FAIL %s: %s\n",argc>1?argv[1]:"argument",error.what());return 1;}}
