#include "ui/MainWindow.h"
#include <QApplication>
#include <QKeyEvent>
#include <QLineEdit>
#include <functional>
#include <iostream>
#include <stdexcept>
using namespace compositor;
namespace {
void require(bool condition,const char* message){if(!condition)throw std::runtime_error(message);}
void key(MainWindow& window,int code,Qt::KeyboardModifiers modifiers=Qt::NoModifier,bool release=true){QKeyEvent event(QEvent::KeyPress,code,modifiers);QApplication::sendEvent(&window,&event);if(release){QKeyEvent up(QEvent::KeyRelease,code,modifiers);QApplication::sendEvent(&window,&up);}}
void release(MainWindow& window,int code){QKeyEvent event(QEvent::KeyRelease,code,Qt::NoModifier);QApplication::sendEvent(&window,&event);}
template<class T>T* control(MainWindow& window,const char* name){auto* value=window.findChild<T*>(name);require(value!=nullptr,"Named keyboard control missing");return value;}
void action(MainWindow& window,const char* name){control<QAction>(window,name)->trigger();}
Document example(){Document document;document.id=newId();document.width=64;document.height=48;Layer layer;layer.id=newId();layer.name="Keyboard witness";layer.transform={0,0,64,48,0,false,false,Transform::Sampling::Nearest};std::vector<Pixel> pixels(64*48,{0,0,255,255});for(int y=10;y<20;++y)for(int x=10;x<20;++x)pixels[size_t(y)*64+x]={255,0,0,255};layer.raster=Raster::fromRgba(64,48,reinterpret_cast<const uint8_t*>(pixels.data()),64*4);document.layers.push_back(layer);return document;}
Selection selection(){return *editing::rasterSelection(editing::SelectionOutline::rectangle({10,10,10,10},false),64,48);}
std::shared_ptr<const GrayRaster> gray(uint8_t value){auto result=std::make_shared<GrayRaster>();result->width=64;result->height=48;result->pixels.assign(64*48,value);return result;}
Layer& layer(EditorProject& project){return project.document->layers.front();}
void drag(EditorProject& project,Point start,Point end){project.canvas->pointerDown({start.x,start.y},{});project.canvas->pointerMove({end.x,end.y},{});project.canvas->pointerUp({end.x,end.y},{});}
}
int main(int argc,char** argv){QApplication app(argc,argv);int passed=0,failed=0;auto test=[&](const char* name,const std::function<void()>& run){try{run();++passed;std::cout<<"PASS "<<name<<'\n';}catch(const std::exception& error){++failed;std::cout<<"FAIL "<<name<<": "<<error.what()<<'\n';}};
    test("keyboard_layer_nudge_linked_and_unlinked_mask",[]{MainWindow window(true);auto doc=example();doc.layers.front().mask=Mask{gray(128),true,true,Transform{3,4,64,48}};auto& project=window.addProject(doc);const auto source=layer(project).raster;key(window,Qt::Key_Right);key(window,Qt::Key_Down,Qt::ShiftModifier);require(layer(project).transform.x==1&&layer(project).transform.y==10,"Arrow layer steps differ");require(layer(project).mask->placement->x==4&&layer(project).mask->placement->y==14,"Linked mask was not carried");require(project.history.undoCount()==2&&layer(project).raster==source,"Nudge did not make one immutable transaction per key");layer(project).mask->linked=false;project.maskSelected=true;const auto image=layer(project).transform;key(window,Qt::Key_Left);require(layer(project).transform==image&&layer(project).mask->placement->x==3,"Unlinked selected mask changed image placement");});
    test("keyboard_outline_nudge_retains_offcanvas_geometry",[]{MainWindow window(true);auto doc=example();doc.selection=selection();auto& project=window.addProject(doc);const auto source=layer(project).raster;key(window,Qt::Key_M);for(int i=0;i<3;++i)key(window,Qt::Key_Left,Qt::ShiftModifier);require(project.document->selection->outline->bounds().x==-20,"Offcanvas outline was clipped");for(int i=0;i<3;++i)key(window,Qt::Key_Right,Qt::ShiftModifier);require(project.document->selection->outline->bounds().x==10&&project.document->selection->coverage->pixel(15,15)==255,"Returning outline lost geometry");require(layer(project).raster==source&&project.history.undoCount()==6,"Outline nudge painted or combined history");});
    test("keyboard_ctrl_arrow_moves_pixels_from_any_tool",[]{MainWindow window(true);auto doc=example();doc.selection=selection();auto& project=window.addProject(doc);const auto original=project.document;key(window,Qt::Key_B);key(window,Qt::Key_Right,Qt::ControlModifier|Qt::ShiftModifier);require(layer(project).raster->pixel(15,15).a==0&&layer(project).raster->pixel(25,15)==Pixel{255,0,0,255},"Ctrl arrow failed to lift/move selected pixels");require(project.document->selection->outline->bounds().x==20&&project.document->selection->coverage->pixel(25,15)==255,"Pixel nudge did not move vector selection");require(project.history.undoName()=="Move Pixels"&&project.history.undoCount()==1,"Pixel nudge history");auto undo=project.history.undo();require(undo&&undo->document==original,"Pixel nudge undo lost original");});
    test("keyboard_persistent_transform_nudge_and_focus_interruption",[]{MainWindow window(true);auto& project=window.addProject(example());project.canvas->zoomAt(10,{200,150});control<QCheckBox>(window,"transformSnapping")->setChecked(false);action(window,"freeTransform");key(window,Qt::Key_Right);require(layer(project).transform.x==1&&project.history.undoCount()==0,"Pending transform nudge committed");project.canvas->pointerDown({32,24},{});project.canvas->pointerMove({37,24},{});require(layer(project).transform.x==6,"Persistent drag preview missing");require(bool(project.canvas->pointerInterrupted),"Root interruption callback missing");project.canvas->pointerInterrupted();require(layer(project).transform.x==1&&control<QAction>(window,"applyTransform")->isEnabled(),"Interruption did not restore draft baseline while retaining session");action(window,"applyTransform");require(project.history.undoCount()==1&&layer(project).transform.x==1,"Apply after interruption lost preceding nudge");});
    test("keyboard_space_pans_without_committing_or_changing_tool",[]{MainWindow window(true);auto& project=window.addProject(example());const auto original=project.document;key(window,Qt::Key_G);drag(project,{10,10},{50,10});const auto preview=project.document;project.canvas->zoomAt(1,{200,150});const auto pan=project.canvas->pan;key(window,Qt::Key_Space,Qt::NoModifier,false);const QPointF view{150,120};auto document=project.canvas->documentPoint(view);project.canvas->pointerDown(document,{});for(int i=1;i<=3;++i){document=project.canvas->documentPoint(view+QPointF(i*10,0));project.canvas->pointerMove(document,{});}document=project.canvas->documentPoint(view+QPointF(30,0));project.canvas->pointerUp(document,{});release(window,Qt::Key_Space);require(project.canvas->pan==pan+QPointF(30,0),"Space repeated motion stalled");require(project.document==preview&&project.history.undoCount()==0&&control<QAction>(window,"applyGradient")->isEnabled(),"Space applied/cancelled pending gradient");project.canvas->pointerInterrupted();require(project.document==preview&&project.history.undoCount()==0,"Focus interruption cancelled pending gradient");key(window,Qt::Key_Escape);require(project.history.undoCount()==0&&project.document==original,"Escape failed to cancel the preserved gradient");});
    test("keyboard_delete_selection_empty_and_mask_palette",[]{MainWindow window(true);auto doc=example();doc.selection=Selection{gray(0)};auto& project=window.addProject(doc);const auto original=project.document;key(window,Qt::Key_Delete);require(project.document==original&&project.document->layers.size()==1,"Explicit empty selection deleted layer");project.document->selection=selection();key(window,Qt::Key_Backspace);require(layer(project).raster->pixel(15,15).a==0&&layer(project).raster->pixel(30,15).a==255,"Delete selection cleared wrong region");layer(project).mask=Mask{gray(255)};project.maskSelected=true;key(window,Qt::Key_X);key(window,Qt::Key_Delete);require(layer(project).mask->raster->pixel(15,15)==0&&layer(project).mask->raster->pixel(30,15)==255,"Delete mask omitted source background palette");project.document->selection.reset();key(window,Qt::Key_Backspace);require(!layer(project).mask&&project.document->layers.size()==1,"Delete without selection removed layer instead of mask");project.maskSelected=false;key(window,Qt::Key_Delete);require(project.document->layers.empty(),"Delete without selection retained layer");});
    test("keyboard_fill_palette_shortcuts_and_blend_wrap",[]{MainWindow window(true);auto doc=example();doc.selection=selection();auto& project=window.addProject(doc);key(window,Qt::Key_Backspace,Qt::AltModifier);require(layer(project).raster->pixel(15,15)==Pixel{0,0,0,255},"Alt Backspace did not fill foreground");key(window,Qt::Key_Backspace,Qt::ControlModifier);require(layer(project).raster->pixel(15,15)==Pixel{255,255,255,255},"Ctrl Backspace did not fill background");key(window,Qt::Key_Minus,Qt::ShiftModifier);require(layer(project).blend==Blend::Luminosity,"Reverse blend cycle did not wrap");key(window,Qt::Key_Plus,Qt::ShiftModifier);require(layer(project).blend==Blend::Normal,"Forward blend cycle did not wrap");require(project.history.undoCount()==4,"Fill/blend history count");});
    test("keyboard_shift_u_and_text_focus_guard",[]{MainWindow window(true);auto& project=window.addProject(example());key(window,Qt::Key_U,Qt::ShiftModifier);require(control<QComboBox>(window,"shapeKind")->currentIndex()==0,"First Shift U toggled before choosing shape");key(window,Qt::Key_U,Qt::ShiftModifier);require(control<QComboBox>(window,"shapeKind")->currentIndex()==1,"Second Shift U did not toggle ellipse");const auto before=project.document;auto* input=new QLineEdit(&window);window.show();input->show();input->setFocus();QApplication::processEvents();require(QApplication::focusWidget()==input,"Text focus witness unavailable");key(window,Qt::Key_Delete);key(window,Qt::Key_Right);key(window,Qt::Key_U,Qt::ShiftModifier);require(project.document==before&&control<QComboBox>(window,"shapeKind")->currentIndex()==1,"Editing keys escaped text focus guard");});
    std::cout<<"{\"suite\":\"keyboard_ui\",\"passed\":"<<passed<<",\"failed\":"<<failed<<",\"mac_differential\":false,\"visual_acceptance\":false}\n";return failed?1:0;
}
