// Frozen expectations: growth-contracts.json. Native source-derived invariants;
// these are not CoreGraphics or Mac differential measurements.
#include "retouch/RetouchSession.h"
#include "graphics/RasterSampling.h"
#include <cmath>
#include <functional>
#include <iostream>
#include <stdexcept>
using namespace compositor;
using namespace compositor::retouch;
namespace {
constexpr Pixel oldColor{200,40,20,255}, copiedColor{20,180,60,255};
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
std::shared_ptr<const GrayRaster> gray(int w,int h,uint8_t value){return std::make_shared<GrayRaster>(GrayRaster{w,h,std::vector<uint8_t>(size_t(w)*h,value)});}
Layer layer(){Layer l;l.id="extent-layer";l.name="Retouch metadata";l.parentId="parent";l.maskSourceId="live-mask";l.opacity=.6;l.blend=Blend::Multiply;l.transform={8,8,16,16,0,false,false,Transform::Sampling::Nearest};l.raster=Raster::filled(16,16,oldColor);l.shapeJson="source live metadata";return l;}
Settings tip(Mode mode=Mode::Clone){Settings s;s.mode=mode;s.radius=3;s.hardness=1;s.opacity=1;return s;}
Sources source(int w=64,int h=32){Sources s;s.cloneOffset=Point{};s.currentLayer=Raster::filled(w,h,copiedColor);return s;}
Pixel at(const Layer& l,Point doc){return l.raster?graphics::sampleRaster(*l.raster,l.transform.toUnit(doc),Transform::Sampling::Nearest):Pixel{};}
void geometry(const Layer& before,const graphics::GrowingBrushSnapshot& snapshot){auto after=snapshot.materializeLayer();const auto b=snapshot.sourceBounds();
    for(auto p:std::array<Point,4>{{{.5,.5},{15.5,.5},{.5,15.5},{15.5,15.5}}}){const auto old=before.transform.fromUnit({p.x/16,p.y/16}),now=after.transform.fromUnit({(p.x-b.x)/b.width,(p.y-b.y)/b.height});require(std::abs(old.x-now.x)<=1e-9&&std::abs(old.y-now.y)<=1e-9,"Original pixel center moved");}
    require(after.transform.rotation==before.transform.rotation&&after.transform.flipX==before.transform.flipX&&after.transform.flipY==before.transform.flipY&&after.transform.sampling==before.transform.sampling,"Transform orientation or sampling changed");
    require(after.id==before.id&&after.name==before.name&&after.parentId==before.parentId&&after.maskSourceId==before.maskSourceId&&after.opacity==before.opacity&&after.blend==before.blend&&after.visible==before.visible,"Layer metadata changed");
    require(after.shapeJson.empty(),"Raster edit retained live shape");
}
}
int main(int argc,char** argv){int passed=0,failed=0;std::shared_ptr<graphics::D3D11BrushCoverage> gpu;
    if(argc>1)gpu=std::make_shared<graphics::D3D11BrushCoverage>(argv[1],true);
    const auto test=[&](const char* id,const std::function<void()>& body){try{body();++passed;std::cout<<"PASS "<<id<<'\n';}catch(const std::exception& e){++failed;std::cout<<"FAIL "<<id<<": "<<e.what()<<'\n';}};
    test("negative_source_growth",[&]{auto l=layer();RetouchSession s(l,64,32,tip(),source(),{},gpu);require(s.begin({3,3}),"Negative stroke refused");auto snap=s.commitSnapshot();auto b=snap->sourceBounds();require(b.x<0&&b.y<0,"Negative source bounds missing");require(at(snap->materializeLayer(),{3.5,3.5})==copiedColor,"Negative new pixels missing");require(snap->pixel(8,8)==oldColor,"Original interior changed");geometry(l,*snap);});
    test("rotated_flipped_scaled_growth",[&]{for(int variant=0;variant<4;++variant){auto l=layer();l.transform={24,40,16,16,0,false,false,Transform::Sampling::Nearest};if(variant==0)l.transform.rotation=90;if(variant==1)l.transform.flipX=true;if(variant==2){l.transform.width=32;l.transform.height=8;}if(variant==3){l.transform.rotation=90;l.transform.flipX=true;l.transform.flipY=true;l.transform.width=24;l.transform.height=8;}
        auto target=l.transform.fromUnit({1.8,.5});require(target.x>3&&target.y>3&&target.x<93&&target.y<77,"Transformed control footprint must be inside canvas");RetouchSession s(l,96,80,tip(),source(96,80),{},gpu);s.begin(target);auto snap=s.commitSnapshot();require(snap->changed(),"Transformed growth missing");require(at(snap->materializeLayer(),target)==copiedColor,"Transformed new interior differs");geometry(l,*snap);}});
    test("nil_placement_mask_white_expansion",[&]{for(bool linked:{false,true}){auto l=layer();l.mask=Mask{gray(16,16,64),false,linked};RetouchSession s(l,64,32,tip(),source(),{},gpu);s.begin({40,16});auto snap=s.commitSnapshot();auto result=snap->materializeLayer();auto bounds=snap->sourceBounds();require(result.mask&&!result.mask->placement&&!result.mask->enabled&&result.mask->linked==linked,"Nil placement mask metadata changed");require(result.mask->raster->width==result.raster->width&&result.mask->raster->height==result.raster->height,"Mask expansion grid differs");for(int y=0;y<bounds.height;++y)for(int x=0;x<bounds.width;++x){int sx=bounds.x+x,sy=bounds.y+y;require(result.mask->raster->pixel(x,y)==(sx>=0&&sy>=0&&sx<16&&sy<16?64:255),"Mask expansion is not original gray plus white");}require(l.mask->raster->pixel(0,0)==64,"Original mask mutated");}});
    test("explicit_mask_placement_preserved",[&]{for(bool linked:{false,true}){auto l=layer();l.mask=Mask{gray(7,5,93),true,linked,Transform{3,4,14,10,90,true,false,Transform::Sampling::Nearest}};auto old=l.mask;RetouchSession s(l,64,32,tip(),source(),{},gpu);s.begin({40,16});auto result=s.commitSnapshot()->materializeLayer();require(result.mask==old,"Explicit mask placement/raster/flags changed");}});
    test("mask_blur_fixed_grid",[&]{for(bool placed:{false,true}){auto l=layer();auto mask=std::make_shared<GrayRaster>(GrayRaster{8,4,std::vector<uint8_t>(32,255)});for(int y=0;y<4;++y)for(int x=0;x<4;++x)mask->pixels[size_t(y)*8+x]=0;l.mask=Mask{mask,true,false};if(placed)l.mask->placement=Transform{8,8,16,16};RetouchSession s(l,64,32,tip(Mode::Blur),{}, {},gpu,true);auto originalBounds=s.previewSnapshot()->sourceBounds();s.begin({16,16});s.append({24,16});auto snap=s.commitSnapshot();auto result=snap->materializeLayer();require(snap->isMask()&&snap->sourceBounds()==originalBounds,"Mask extent grew");require(originalBounds.width==(placed?8:16)&&originalBounds.height==(placed?4:16),"Mask grid differs from source placement rule");require(result.transform==l.transform&&result.raster==l.raster&&result.mask->placement==l.mask->placement&&result.mask->linked==l.mask->linked,"Mask edit moved image/placement");require(result.mask->raster->width==originalBounds.width&&result.mask->raster->height==originalBounds.height,"Edited mask grid missing");require(mask->pixel(0,0)==0&&mask->pixel(7,0)==255,"Mask input mutated");}});
    test("placed_mask_small_remaining_budget",[&]{auto l=layer();l.raster=Raster::filled(512,512,oldColor);l.transform={0,0,512,512};auto mask=std::make_shared<GrayRaster>(GrayRaster{8,8,std::vector<uint8_t>(64,255)});for(int y=0;y<8;++y)for(int x=0;x<4;++x)mask->pixels[size_t(y)*8+x]=0;l.mask=Mask{mask,true,true,Transform{8,8,16,16}};RetouchSession s(l,64,32,tip(Mode::Blur),{}, {},gpu,true,64);s.begin({16,16});auto result=s.commitSnapshot()->materializeLayer();require(result.raster==l.raster&&result.mask->raster->width==8&&result.mask->raster->height==8,"Mask budget changed unrelated image/grid");require(result.mask->raster->pixel(4,4)<255,"Valid small mask edit did not execute");});
    test("half_selection_once",[&]{auto l=layer();auto clip=std::make_shared<GrayRaster>(GrayRaster{64,32,std::vector<uint8_t>(2048,128)});for(int y=0;y<32;++y)for(int x=44;x<64;++x)clip->pixels[size_t(y)*64+x]=0;RetouchSession s(l,64,32,tip(),source(),clip,gpu);s.begin({40,16});s.append({48,16});auto snap=s.commitSnapshot();require(snap->pixel(32,8)==Pixel{10,90,30,128},"Selection alpha was not applied exactly once");require(snap->pixel(40,8)==Pixel{},"Selection zero painted outside");});
    test("empty_selection_cancel_immutable",[&]{auto l=layer();RetouchSession empty(l,64,32,tip(),source(),gray(64,32,0),gpu);require(!empty.begin({40,16}),"Empty selection painted");require(empty.commitSnapshot()->materializeLayer()==l,"Empty selection changed layer");RetouchSession s(l,64,32,tip(),source(),{},gpu);s.begin({32,16});auto first=s.previewSnapshot();const auto held=first->pixel(24,8);auto live=s.livePreview();const auto unit=live->layer.transform.toUnit({32.5,16.5});auto heldLive=live->image(unit,Transform::Sampling::Nearest);s.append({48,16});require(first->pixel(24,8)==held&&first->pixel(40,8)==Pixel{},"Old preview mutated");require(live->image(unit,Transform::Sampling::Nearest)==heldLive,"Published callback reads mutable session");auto committed=s.commitSnapshot();require(s.commitSnapshot()==committed,"Commit not idempotent");require(s.cancelSnapshot()->materializeLayer()==l,"Cancel after commit did not restore original");require(committed->pixel(40,8).a>0,"Cancel mutated committed snapshot");require(!s.livePreview(),"Cancelled live override retained");});
    test("allocated_budget_atomic",[&]{auto l=layer();RetouchSession s(l,512,64,tip(),source(512,64),{},gpu,false,256*64);Raster::resetMaterializationCount();s.begin({40,16});auto first=s.previewSnapshot();const auto held=first->pixel(32,8);bool rejected=false;try{s.append({400,16});}catch(const std::runtime_error&){rejected=true;}require(rejected,"Oversized tile union not rejected");require(s.previewSnapshot()==first&&first->pixel(32,8)==held,"Failed budget published partial mutation");require(Raster::materializationCount()==0,"Retouch materialized whole rgba");require(s.cancelSnapshot()->materializeLayer()==l,"Budget cancel lost original");});
    test("warp_unchanged_coverage_recomposition",[&]{for(auto mode:{Mode::Smudge,Mode::Liquify}){auto l=layer();l.transform={0,0,48,32,0,false,false,Transform::Sampling::Nearest};auto image=std::make_shared<Raster>(*Raster::filled(48,32));auto tile=std::make_shared<Raster::Tile>();for(int y=0;y<32;++y)for(int x=0;x<48;++x)tile->pixels[size_t(y)*256+x]={uint8_t(x*5),0,0,255};image->tiles[0]=tile;l.raster=image;auto settings=tip(mode);settings.radius=4;settings.opacity=.5;RetouchSession s(l,48,32,settings,{}, {},gpu),control(image,l.transform,48,32,settings,{}, {},gpu);s.begin({10,16});control.begin({10,16});s.append({11,16});control.append({11,16});auto first=s.livePreview();auto held=first->image({11.5/48,16.5/32},Transform::Sampling::Nearest);for(auto p:std::array<Point,4>{{{12,16},{11,16},{12,16},{13,16}}}){s.append(p);control.append(p);}auto result=s.commitSnapshot()->materializeLayer();auto expected=control.commit();for(int y=0;y<32;++y)for(int x=0;x<48;++x)require(result.raster->pixel(x,y)==expected->pixel(x,y),"Warp repeated sample differs from source composition");require(first->image({11.5/48,16.5/32},Transform::Sampling::Nearest)==held,"Warp live callback mutated");}});
    test("healing_expanded_region_seed_phase",[&]{for(auto mode:{Mode::HealContentAware,Mode::HealCreateTexture,Mode::HealProximity}){auto l=layer();std::array<Pixel,256> pixels;pixels.fill(oldColor);auto full=Raster::filled(64,32)->replacing(8,8,16,16,pixels.data(),16);auto settings=tip(mode);settings.healingSeed=1;RetouchSession s(l,64,32,settings,{}, {},gpu),control(full,Transform{0,0,64,32,0,false,false,Transform::Sampling::Nearest},64,32,settings,{}, {},gpu);s.begin({24,16});control.begin({24,16});auto result=s.commitSnapshot()->materializeLayer();auto expected=control.commit();for(int y=0;y<32;++y)for(int x=0;x<64;++x)require(at(result,{x+.5,y+.5})==expected->pixel(x,y),"Healing expanded ROI/seed phase differs in RGBA");require(s.metrics().healingRegionPixels==64*32,"Healing region clipped to original image");}});
    test("blank_clone_grows_and_preserves_cancel",[&]{auto l=layer();l.raster.reset();RetouchSession s(l,64,32,tip(),source(),{},gpu);s.begin({40,16});auto snap=s.commitSnapshot();require(snap->changed()&&at(snap->materializeLayer(),{40.5,16.5})==copiedColor,"Blank clone growth missing");require(s.cancelSnapshot()->materializeLayer()==l,"Blank clone cancel invented raster");});
    test("owned_warp_preview_mask_placement",[&]{auto l=layer();l.mask=Mask{gray(16,16,64),true,false};RetouchSession s(l,64,32,tip(Mode::Liquify),{}, {},gpu);s.begin({22,16});s.append({26,16});auto preview=s.livePreview();require(preview->layer.mask->placement==l.transform&&preview->layer.mask->raster==l.mask->raster,"Warp live mask moved into document grid");auto pixels=preview->image({26.5/64,16.5/32},Transform::Sampling::Nearest);s.cancelSnapshot();require(preview->image({26.5/64,16.5/32},Transform::Sampling::Nearest)==pixels,"Warp callback lost source after cancellation");});
    test("canvas_sample_preflight_limit",[]{
        validateCanvasExtent(10000,10000);validateCanvasExtent(30000,30000);
        int refused=0;for(auto size:std::array<Point,3>{{{30001,1},{0,32},{32,-1}}})try{validateCanvasExtent(int(size.x),int(size.y));}catch(const std::invalid_argument&){++refused;}
        require(refused==3,"Invalid document dimensions accepted");
        bool allocationRefused=false;try{Raster::filled(30000,30000);}catch(const std::runtime_error&){allocationRefused=true;}
        require(allocationRefused,"Full raster allocation bypassed the100-megapixel guard");
    });
    test("healing_equal_pixels_retains_source_patch_history",[&]{for(auto mode:{Mode::HealContentAware,Mode::HealCreateTexture,Mode::HealProximity})for(uint32_t seed:{1U,42U})for(int fixture=0;fixture<3;++fixture){
        auto l=layer();l.transform={0,0,80,40};std::vector<Pixel> pixels(80*40);for(int y=0;y<40;++y)for(int x=0;x<80;++x)pixels[size_t(y)*80+x]=fixture==1?Pixel{31,31,31,255}:x>=10&&x<20?Pixel{0,255,0,255}:x>=20&&x<30?Pixel{255,0,0,255}:Pixel{0,0,255,255};l.raster=Raster::fromRgba(80,40,reinterpret_cast<const uint8_t*>(pixels.data()),80*4);
        std::shared_ptr<const GrayRaster> clip;if(fixture==2){auto selected=std::make_shared<GrayRaster>(GrayRaster{80,40,std::vector<uint8_t>(3200)});selected->pixels[0]=255;clip=selected;}
        auto settings=tip(mode);settings.radius=2;settings.healingSeed=seed;RetouchSession s(l,80,40,settings,{},clip,gpu);require(s.begin({15,20}),"Nonempty selection prevented Healing source patch");const auto snapshot=s.commitSnapshot();const auto result=snapshot->materializeLayer();require(snapshot->changed()&&result.raster!=l.raster,"Byte-identical Healing lost committed source patch identity");for(int y=0;y<40;++y)for(int x=0;x<80;++x)require(result.raster->pixel(x,y)==l.raster->pixel(x,y),"Equal-pixel Healing regression fixture changed RGBA");
        Document document;document.id="healing-history";document.width=80;document.height=40;document.layers={l};std::optional<Document> current=document;History history;history.begin("Spot Healing",current,l.id);current->layers[0]=result;history.end(current,l.id);require(history.undoCount()==1&&history.undoName()=="Spot Healing","Equal-pixel Healing omitted source history");require(history.undo()->document==document,"Equal-pixel Healing undo lost original identity");require(history.redo()->document==current,"Equal-pixel Healing redo lost committed identity");
        Sources sample;sample.cloneOffset=Point{};sample.currentLayer=l.raster;RetouchSession clone(l,80,40,tip(),sample,clip,gpu);clone.begin({15,20});require(!clone.commitSnapshot()->changed(),"Healing policy changed Clone equal-byte no-op behavior");
    }});
    std::cout<<"{\"schema\":\"RETOUCH_GROWTH_CONTRACT_RESULTS_V1\",\"passed\":"<<passed<<",\"failed\":"<<failed<<",\"warp\":"<<(gpu?"true":"false")<<",\"mac_differential\":false}\n";return failed?1:0;
}

