cmake_minimum_required(VERSION 3.31.6)
if(NOT DEFINED WITNESS OR NOT DEFINED EVIDENCE_ROOT)
  message(FATAL_ERROR "WITNESS and EVIDENCE_ROOT are required")
endif()
# Each invocation preserves its own buffers, including failures.
string(TIMESTAMP stamp "%Y%m%dT%H%M%SZ" UTC)
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef nonce)
set(output "${EVIDENCE_ROOT}/${stamp}-${nonce}")
if(EXISTS "${output}")
  message(FATAL_ERROR "Evidence path already exists: ${output}")
endif()
execute_process(COMMAND "${WITNESS}" "${output}" RESULT_VARIABLE status)
message(STATUS "Retouch extent evidence: ${output}")
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Retouch extent witness failed: ${status}")
endif()
# Strengthen the preserved alpha-loss witness with exact equality of all RGBA
# bytes, so a color regression cannot pass merely by retaining alpha coverage.
foreach(case clone heal_content heal_texture heal_proximity blur smudge liquify)
  set(actual "${output}/${case}-actual.rgba")
  set(reference "${output}/${case}-padded-control.rgba")
  file(SIZE "${actual}" actual_size)
  file(SIZE "${reference}" reference_size)
  file(SHA256 "${actual}" actual_hash)
  file(SHA256 "${reference}" reference_hash)
  if(NOT actual_size EQUAL 8192 OR NOT reference_size EQUAL 8192 OR NOT actual_hash STREQUAL reference_hash)
    message(FATAL_ERROR "Exact 64x32 RGBA comparison failed: ${case}")
  endif()
  message(STATUS "PASS exact_rgba ${case} sha256=${actual_hash}")
endforeach()
