if(NOT DEFINED EXECUTABLE OR NOT DEFINED CASE OR NOT DEFINED EVIDENCE_ROOT)
  message(FATAL_ERROR "EXECUTABLE, CASE and EVIDENCE_ROOT are required")
endif()
string(TIMESTAMP stamp "%Y%m%d-%H%M%S" UTC)
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
set(directory "${EVIDENCE_ROOT}/${CASE}/${stamp}-${nonce}")
file(MAKE_DIRECTORY "${directory}")
execute_process(COMMAND "${EXECUTABLE}" "${CASE}" "${directory}/result.json" RESULT_VARIABLE status OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 60)
file(WRITE "${directory}/stdout.log" "${stdout}")
file(WRITE "${directory}/stderr.log" "${stderr}")
message("${stdout}${stderr}")
if(NOT EXISTS "${directory}/result.json")
  message(FATAL_ERROR "Source scenario report missing; process=${status}")
endif()
file(READ "${directory}/result.json" report)
string(JSON outcome GET "${report}" status)
string(JSON count LENGTH "${report}" checks)
message("SOURCE_REPORT ${directory}/result.json checks=${count}")
if(NOT status EQUAL 0 OR NOT outcome STREQUAL "passed")
  message(FATAL_ERROR "Source scenario result=${outcome}, process=${status}")
endif()
