#include "ui/MainWindow.h"
#include "ui/LayerPanel.h"
#include <QApplication>
#include <QDragEnterEvent>
#include <QDragLeaveEvent>
#include <QMenu>
#include <QMessageBox>
#include <QPushButton>
#include <QTest>
#include <QTimer>
#include <iostream>

using namespace compositor;
namespace {
void require(bool value,const char* why){if(!value)throw std::runtime_error(why);}
QAction* named(MainWindow&w,const char* name){auto* a=w.findChild<QAction*>(name);require(a,"Action missing");return a;}
QAction* textAction(MainWindow&w,const QString& text){for(auto*a:w.findChildren<QAction*>())if(a->text()==text)return a;throw std::runtime_error("Text action missing");}
QTreeWidget* tree(MainWindow&w){auto*t=w.findChild<QTreeWidget*>("layersTree");require(t,"Layer tree missing");return t;}
ui::LayerPanelController* controller(MainWindow&w){auto*c=ui::LayerPanelController::find(tree(w));require(c,"Layer controller missing");return c;}
QTreeWidgetItem* item(MainWindow&w,const std::string&id){for(QTreeWidgetItemIterator it(tree(w));*it;++it)if((*it)->data(0,Qt::UserRole).toString().toStdString()==id)return *it;throw std::runtime_error("Layer row missing");}
QPoint point(MainWindow&w,const std::string&id,int column=0){auto*t=tree(w);auto*r=item(w,id);t->scrollToItem(r);QApplication::processEvents();const auto rect=t->visualItemRect(r);return {t->columnViewportPosition(column)+(column==0?70:t->columnWidth(column)/2),rect.center().y()};}
Layer& layer(EditorProject&p,const std::string&id){for(auto&l:p.document->layers)if(l.id==id)return l;throw std::runtime_error("Layer absent");}
void select(MainWindow&w,EditorProject&p,std::vector<std::string>ids){p.selected=ids;p.active=ids.front();p.maskSelected=false;controller(w)->rebuild();for(auto*object:w.findChildren<QObject*>())if(auto*registry=dynamic_cast<ui::CommandRegistry*>(object))registry->refresh();}
std::shared_ptr<const GrayRaster> gray(int w,int h,uint8_t value){auto g=std::make_shared<GrayRaster>();g->width=w;g->height=h;g->pixels.assign(size_t(w)*h,value);return g;}
Document example(){Document d;d.id=newId();d.width=d.height=32;for(const auto* name:{"a","b","c"}){Layer l;l.id=name;l.name=name;l.transform={0,0,32,32};l.raster=Raster::filled(32,32,{50,80,100,255});d.layers.push_back(l);}Layer g;g.id="folder";g.name="Folder";g.group=true;g.transform={0,0,32,32};d.layers.push_back(g);return d;}
void show(MainWindow&w){w.show();QApplication::processEvents();}
bool drop(MainWindow&w,QMimeData* mime,const QPoint& p,Qt::KeyboardModifiers modifiers=Qt::NoModifier){QDragEnterEvent enter(p,Qt::CopyAction|Qt::MoveAction,mime,Qt::LeftButton,modifiers);QApplication::sendEvent(tree(w)->viewport(),&enter);if(!enter.isAccepted())return false;QDropEvent event(p,Qt::CopyAction|Qt::MoveAction,mime,Qt::LeftButton,modifiers);QApplication::sendEvent(tree(w)->viewport(),&event);return event.isAccepted();}
}
int main(int argc,char**argv){QApplication app(argc,argv);int passed=0,failed=0;auto test=[&](const char*name,const std::function<void()>&fn){try{fn();++passed;std::cout<<"PASS "<<name<<'\n';}catch(const std::exception&e){++failed;std::cout<<"FAIL "<<name<<": "<<e.what()<<'\n';}};
    test("qt_multiselection_group_one_undo",[]{MainWindow w(true);auto&p=w.addProject(example());show(w);QTest::mouseClick(tree(w)->viewport(),Qt::LeftButton,Qt::NoModifier,point(w,"b"));QTest::mouseClick(tree(w)->viewport(),Qt::LeftButton,Qt::ControlModifier,point(w,"c"));require(p.selected.size()==2,"Ctrl row selection lost");textAction(w,"Group Selected")->trigger();const auto group=p.active;require(layer(p,"b").parentId==group&&layer(p,"c").parentId==group&&layer(p,group).group,"Selected layers not grouped");require(p.history.undoCount()==1,"Grouping not a single history transaction");textAction(w,"Undo Group Layers")->trigger();require(p.document->layers.size()==4,"Grouping undo did not restore graph");});
    test("qt_drop_into_group_order_and_alt_duplicate",[]{MainWindow w(true);auto&p=w.addProject(example());show(w);select(w,p,{"c","b"});p.collapsedGroups.insert("folder");controller(w)->rebuild();std::unique_ptr<QMimeData> mime(controller(w)->dragMime());require(drop(w,mime.get(),point(w,"folder")),"Qt group drop rejected");require(layer(p,"b").parentId=="folder"&&layer(p,"c").parentId=="folder","Drop hierarchy wrong");require(p.selected==std::vector<std::string>({"c","b"}),"Moved selection order lost");require(item(w,"folder")->child(0)->data(0,Qt::UserRole).toString()=="c"&&item(w,"folder")->child(1)->data(0,Qt::UserRole).toString()=="b","Within-folder top order reversed");require(!p.collapsedGroups.contains("folder")&&item(w,"folder")->isExpanded(),"Drop did not expand destination");require(p.history.undoCount()==1,"Multi-drop produced several undo steps");select(w,p,{"c"});std::unique_ptr<QMimeData> copy(controller(w)->dragMime());require(drop(w,copy.get(),point(w,"a"),Qt::AltModifier),"Alt-copy failed");require(p.document->layers.size()==5&&layer(p,p.active).raster==layer(p,"c").raster,"Alt-copy lost immutable raster sharing");select(w,p,{"folder"});std::unique_ptr<QMimeData> folder(controller(w)->dragMime());const auto before=p.document;require(!drop(w,folder.get(),point(w,"a"),Qt::AltModifier)&&p.document==before,"Folder Alt-copy should reject atomically");});
    test("qt_mask_drop_cancel_copy_and_cycle_rejection",[]{MainWindow w(true);auto d=example();d.layers[0].mask=Mask{gray(2,2,100),false,false,Transform{4,5,9,10}};auto&p=w.addProject(d);show(w);select(w,p,{"a"});std::unique_ptr<QMimeData> mime(controller(w)->dragMime(true));const auto before=p.document;QDragEnterEvent enter(point(w,"b"),Qt::CopyAction,mime.get(),Qt::LeftButton,Qt::AltModifier);QApplication::sendEvent(tree(w)->viewport(),&enter);require(enter.isAccepted(),"Mask drag did not enter");QDragLeaveEvent leave;QApplication::sendEvent(tree(w)->viewport(),&leave);require(p.document==before&&p.history.undoCount()==0,"Cancelled mask drag changed document/history");require(drop(w,mime.get(),point(w,"b"),Qt::AltModifier),"Mask copy drop rejected");require(layer(p,"b").mask==layer(p,"a").mask&&p.maskSelected&&p.active=="b","Copied mask properties or target changed");require(p.history.undoCount()==1,"Mask copy history missing");layer(p,"c").parentId="folder";controller(w)->rebuild();select(w,p,{"folder"});std::unique_ptr<QMimeData> cycle(controller(w)->dragMime());const auto graph=p.document;require(!drop(w,cycle.get(),point(w,"c"))&&p.document==graph,"Group cycle was allowed");});
    test("qt_add_selection_mask_threshold_target_and_undo",[]{MainWindow w(true);auto d=example();d.layers[0].raster=Raster::filled(4,4,{40,40,40,255});d.layers[0].transform={4,4,8,8};d.selection=editing::rasterSelection(editing::SelectionOutline::rectangle({4,4,4,8},false),32,32);auto&p=w.addProject(d);show(w);select(w,p,{"a"});named(w,"maskAddReveal")->trigger();require(layer(p,"a").mask&&p.maskSelected&&!p.document->selection,"Selection mask did not consume selection and select mask");const auto&g=*layer(p,"a").mask->raster;require(g.width==4&&g.height==4&&g.pixel(0,0)==0&&g.pixel(1,3)==0&&g.pixel(2,0)==255,"Layer-local selection mapping wrong");require(p.history.undoCount()==1&&p.history.undoName()=="Add Mask from Selection","Mask creation transaction wrong");auto* target=w.findChild<QComboBox*>("layerEditTarget");require(target&&target->currentIndex()==1,"Persistent mask target control not updated");target->setCurrentIndex(0);require(!p.maskSelected,"Image target control failed");target->setCurrentIndex(1);require(p.maskSelected,"Mask target control failed");textAction(w,"Undo Add Mask from Selection")->trigger();require(!layer(p,"a").mask&&p.document->selection&&p.document->selection->coverage==d.selection->coverage,"Undo did not restore exact consumed selection");});
    test("qt_thumbnail_alpha_and_black_mask_modifiers",[]{MainWindow w(true);auto d=example();std::vector<Pixel> pixels{{50,0,0,127},{60,0,0,128},{90,0,0,255},{0,0,0,0}};d.layers[0].raster=Raster::fromRgba(2,2,reinterpret_cast<uint8_t*>(pixels.data()),8);d.layers[0].transform={4,4,8,8};auto mask=std::make_shared<GrayRaster>();mask->width=mask->height=2;mask->pixels={0,127,128,255};d.layers[0].mask=Mask{mask,false,true,Transform{16,4,8,8}};auto&p=w.addProject(d);show(w);select(w,p,{"a"});QTest::mouseClick(tree(w)->viewport(),Qt::LeftButton,Qt::ControlModifier,point(w,"a",1));auto g=p.document->selection->coverage;require(g->pixel(6,6)==0&&g->pixel(10,6)==255&&g->pixel(6,10)==255&&g->pixel(10,10)==0,"Image alpha threshold ignored or included mask");QTest::mouseClick(tree(w)->viewport(),Qt::LeftButton,Qt::ControlModifier|Qt::ShiftModifier,point(w,"a",3));g=p.document->selection->coverage;require(g->pixel(18,6)==255&&g->pixel(22,6)==255&&g->pixel(18,10)==0&&g->pixel(10,6)==255,"Mask black area threshold/placement/add wrong");QTest::mouseClick(tree(w)->viewport(),Qt::LeftButton,Qt::ControlModifier|Qt::AltModifier,point(w,"a",1));g=p.document->selection->coverage;require(g->pixel(10,6)==0&&g->pixel(18,6)==255,"Ctrl+Alt did not subtract alpha selection");QTest::mouseClick(tree(w)->viewport(),Qt::LeftButton,Qt::ShiftModifier,point(w,"a",3));require(p.maskSelected&&layer(p,"a").mask->enabled,"Shift mask did not target and enable");QTest::mouseClick(tree(w)->viewport(),Qt::LeftButton,Qt::NoModifier,point(w,"a",0));require(!p.maskSelected,"Name click did not retarget image");});
    test("qt_collapsed_groups_per_project_no_history",[]{MainWindow w(true);auto d=example();d.layers[0].parentId="folder";auto&p=w.addProject(d);show(w);select(w,p,{"a"});item(w,"folder")->setExpanded(false);require(p.collapsedGroups.contains("folder")&&p.active=="folder"&&p.selected==std::vector<std::string>{"folder"},"Collapse did not select containing group");require(p.history.undoCount()==0,"View collapse entered history");auto&p2=w.addProject(example());require(p2.collapsedGroups.empty(),"Collapsed groups leaked to another project");w.findChild<QTabWidget*>()->setCurrentIndex(0);require(!item(w,"folder")->isExpanded()&&p.collapsedGroups.contains("folder"),"Project switch lost collapsed group state");});
    test("qt_mask_link_enable_delete_and_cancel_dependency_dialog",[]{MainWindow w(true);auto d=example();d.layers[0].mask=Mask{gray(1,1,255)};d.layers[1].maskSourceId="a";auto&p=w.addProject(d);show(w);select(w,p,{"a"});named(w,"maskEditMask")->trigger();named(w,"maskToggleLink")->trigger();require(!layer(p,"a").mask->linked&&p.maskSelected,"Unlink changed mask target");named(w,"maskToggleEnabled")->trigger();require(!layer(p,"a").mask->enabled,"Disable did not apply");const auto before=p.document;const auto count=p.history.undoCount();QTimer::singleShot(0,[]{for(auto* widget:QApplication::topLevelWidgets())if(auto* box=qobject_cast<QMessageBox*>(widget))box->reject();});textAction(w,"Delete Layer")->trigger();require(p.document==before&&p.history.undoCount()==count&&p.maskSelected,"Cancelled dependency deletion changed mask or history");w.findChild<QPushButton*>("layerDeleteButton")->click();require(!layer(p,"a").mask&&p.document->layers.size()==4&&!p.maskSelected,"Delete footer did not remove only targeted mask");});
    test("qt_drop_above_self_copy_and_move_noop",[]{MainWindow w(true);auto&p=w.addProject(example());show(w);select(w,p,{"a"});std::unique_ptr<QMimeData> mime(controller(w)->dragMime());const auto before=p.document;require(!drop(w,mime.get(),point(w,"a"))&&p.document==before&&p.history.undoCount()==0,"Moving above self must be an unchanged operation");require(drop(w,mime.get(),point(w,"a"),Qt::AltModifier),"Alt-copy above its own source must remain legal");require(p.document->layers.size()==5&&p.history.undoCount()==1&&p.active!="a","Self-copy did not select one new layer");});
    std::cout<<"{\"suite\":\"layer_mask_ui\",\"passed\":"<<passed<<",\"failed\":"<<failed<<",\"visual_acceptance\":false,\"mac_differential\":false}\n";return failed?1:0;
}
