cmake_policy(SET CMP0054 NEW)
foreach(argument IN ITEMS EXECUTABLE CASE EVIDENCE_ROOT)
    if(NOT DEFINED ${argument})
        message(FATAL_ERROR "Missing ${argument}")
    endif()
endforeach()
string(TIMESTAMP stamp "%Y%m%d-%H%M%S" UTC)
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
set(directory "${EVIDENCE_ROOT}/${CASE}/${stamp}-${nonce}")
file(MAKE_DIRECTORY "${directory}")
execute_process(COMMAND "${EXECUTABLE}" "${CASE}" "${directory}/capture"
    RESULT_VARIABLE status OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 60)
file(WRITE "${directory}/stdout.log" "${stdout}")
file(WRITE "${directory}/stderr.log" "${stderr}")
message("${stdout}${stderr}")
if(NOT "${status}" STREQUAL "0")
    message(FATAL_ERROR "Witness did not exit normally with zero: ${status}")
endif()
file(READ "${directory}/capture/results.json" report)
string(JSON passed GET "${report}" passed)
if(NOT passed)
    message(FATAL_ERROR "Witness predicate failed")
endif()
message("WITNESS_REPORT ${directory}/capture/results.json")
