#include "core/Document.h"
#include "graphics/GrowingBrushSession.h"
#include "graphics/SamplingSource.h"
namespace compositor::reference_growth {using graphics::BrushSessionSettings;using graphics::BrushSessionGeometry;using graphics::BrushSessionMetrics;using graphics::BrushTile;using graphics::D3D11BrushCoverage;}
#define graphics reference_growth
#include "reference42/GrowingBrushSession.h"
#undef graphics
#include <QCoreApplication>
#include <QFile>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <atomic>
#include <cstring>
#include <filesystem>
#include <iostream>
#include <map>
using namespace compositor;
using namespace compositor::graphics;
namespace reference=compositor::reference_growth;
namespace {std::atomic<uint64_t> pixelCalls{},grayCalls{};}
namespace compositor {void brushCompositionPixelRead(){++pixelCalls;}void brushCompositionGrayRead(){++grayCalls;}}
namespace {
std::filesystem::path directory;QJsonObject report;QJsonArray comparisons;uint64_t actualCalls{},referenceCalls{},actualGrayCalls{},referenceGrayCalls{};
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
Layer layer(int mode=0,int width=257,int height=193){Layer l;l.id="composition-control";l.name="Original";l.transform={300.25,210.75,double(width),double(height),0,false,false,Transform::Sampling::Nearest};std::vector<Pixel> pixels(size_t(width)*height);uint32_t seed=29;for(auto& p:pixels){seed=seed*1664525+1013904223;const auto a=uint8_t(mode==0?255:mode==1?0:32+(seed>>24)%192);p={uint8_t((seed>>8)%(uint32_t(a)+1)),uint8_t((seed>>16)%(uint32_t(a)+1)),uint8_t(seed%(uint32_t(a)+1)),a};}auto image=std::make_shared<Raster>(*Raster::fromRgba(width,height,reinterpret_cast<const uint8_t*>(pixels.data()),size_t(width)*4));image->samplingOriginX=-3;image->samplingOriginY=5;l.raster=image;return l;}
std::shared_ptr<const GrayRaster> gray(int w,int h,bool partial=false){auto result=std::make_shared<GrayRaster>(GrayRaster{w,h,std::vector<uint8_t>(size_t(w)*h,255)});if(partial)for(int y=0;y<h;++y)for(int x=0;x<w;++x)result->pixels[size_t(y)*w+x]=uint8_t((x*7+y*19)%256);result->samplingOriginX=7;result->samplingOriginY=-11;return result;}
void sameRaster(const std::shared_ptr<const Raster>& a,const std::shared_ptr<const Raster>& b){require(bool(a)==bool(b),"Raster presence differs");if(!a)return;require(a->width==b->width&&a->height==b->height&&a->samplingOriginX==b->samplingOriginX&&a->samplingOriginY==b->samplingOriginY,"Raster dimensions/phase differ");for(int y=0;y<a->height;++y)for(int x=0;x<a->width;++x)require(a->pixel(x,y)==b->pixel(x,y),"Materialized raster bytes differ");}
void sameLayer(Layer a,Layer b){sameRaster(a.raster,b.raster);a.raster.reset();b.raster.reset();require(bool(a.mask)==bool(b.mask),"Mask presence differs");if(a.mask){const auto& x=*a.mask->raster;const auto& y=*b.mask->raster;require(x.width==y.width&&x.height==y.height&&x.samplingOriginX==y.samplingOriginX&&x.samplingOriginY==y.samplingOriginY&&x.pixels==y.pixels,"Mask grid/phase/bytes differ");a.mask->raster.reset();b.mask->raster.reset();}require(a==b,"Layer metadata differs");}
void saveBytes(const std::string& name,const std::vector<Pixel>& bytes){QFile f(QString::fromStdWString((directory/name).wstring()));const auto size=qint64(bytes.size()*sizeof(Pixel));require(f.open(QIODevice::WriteOnly)&&f.write(reinterpret_cast<const char*>(bytes.data()),size)==size,"Cannot retain pixel evidence");}
template<class A,class B>void snapshots(const A& a,const B& b){const auto x=a->sourceBounds();const auto y=b->sourceBounds();require(x.x==y.x&&x.y==y.y&&x.width==y.width&&x.height==y.height&&a->transform()==b->transform()&&a->changed()==b->changed()&&a->isMask()==b->isMask(),"Snapshot bounds/transform/state differ");
    const int width=x.width+4,height=x.height+4;std::vector<Pixel> actual(size_t(width)*height),control(actual.size()),diff(actual.size());int maxDiff=0;uint64_t changedBytes=0;
    for(int row=0;row<height;++row)for(int col=0;col<width;++col){const auto i=size_t(row)*width+col;actual[i]=a->pixel(x.x+col-2,x.y+row-2);control[i]=b->pixel(x.x+col-2,x.y+row-2);auto* d=reinterpret_cast<uint8_t*>(&diff[i]);const auto* aa=reinterpret_cast<const uint8_t*>(&actual[i]);const auto* bb=reinterpret_cast<const uint8_t*>(&control[i]);for(int c=0;c<4;++c){d[c]=uint8_t(std::abs(int(aa[c])-int(bb[c])));maxDiff=std::max(maxDiff,int(d[c]));changedBytes+=d[c]!=0;}}
    const auto prefix=std::to_string(comparisons.size());saveBytes(prefix+"-actual.rgba",actual);saveBytes(prefix+"-reference.rgba",control);saveBytes(prefix+"-diff.rgba",diff);comparisons.append(QJsonObject{{"prefix",QString::fromStdString(prefix)},{"x",x.x-2},{"y",x.y-2},{"width",width},{"height",height},{"max_difference",maxDiff},{"different_bytes",qint64(changedBytes)}});require(maxDiff==0&&changedBytes==0,"Snapshot pixels differ");
    auto ap=a->renderPreview(),bp=b->renderPreview();require(bool(ap)==bool(bp),"Live renderer presence differs");if(ap){for(auto unit:std::array<Point,5>{{{.01,.02},{.2,.3},{.5,.6},{.8,.7},{.99,.98}}})for(auto sampling:{Transform::Sampling::Nearest,Transform::Sampling::Smooth,Transform::Sampling::High}){if(ap->image)require(ap->image(unit,sampling)==bp->image(unit,sampling),"Live image sampling differs");if(ap->mask)require(ap->mask(unit,sampling,255)==bp->mask(unit,sampling,255),"Live mask sampling differs");}}
}
void coverage(const GrowingBrushSession& a,const reference::GrowingBrushSession& b){const auto aa=a.coverageSnapshot();const auto bb=b.coverageSnapshot();require(aa.size()==bb.size(),"Coverage tile count differs");for(size_t i=0;i<aa.size();++i){const auto& x=aa[i];const auto& y=bb[i];require(x.rect.x==y.rect.x&&x.rect.y==y.rect.y&&x.rect.width==y.rect.width&&x.rect.height==y.rect.height,"Coverage grid differs");require(x.coverage->preview==y.coverage->preview&&x.coverage->permanent.size()==y.coverage->permanent.size()&&std::memcmp(x.coverage->permanent.data(),y.coverage->permanent.data(),x.coverage->permanent.size()*sizeof(float))==0,"Coverage bytes/density differ");}const auto x=a.metrics();const auto y=b.metrics();require(x.snapshots==y.snapshots&&x.sparsePixelTiles==y.sparsePixelTiles&&x.sparsePixelBytes==y.sparsePixelBytes,"Sparse allocation/publication differs");const auto& p=x.coverage;const auto& q=y.coverage;require(p.acceptedSamples==q.acceptedSamples&&p.settledSegments==q.settledSegments&&p.coverageTileAllocations==q.coverageTileAllocations&&p.outputTileAllocations==q.outputTileAllocations&&p.publishedSnapshots==q.publishedSnapshots&&p.touchedTiles==q.touchedTiles&&p.coverageStorageBytes==q.coverageStorageBytes,"Session counters differ");}
void run(Layer original,BrushSessionSettings settings={},std::shared_ptr<const GrayRaster> selection={},bool mask=false,std::vector<Point> points={}){
    if(points.empty()){const auto transform=mask?original.mask->placement.value_or(original.transform):original.transform;for(auto unit:std::array<Point,6>{{{.2,.45},{.28,.48},{.35,.5},{.30,.43},{.45,.45},{.5,.6}}})points.push_back(transform.fromUnit(unit));}
    GrowingBrushSession actual(original,settings,1024,768,{},selection,mask);reference::GrowingBrushSession control(original,settings,1024,768,{},selection,mask);Raster::resetMaterializationCount();
    std::shared_ptr<const GrowingBrushSnapshot> held;std::shared_ptr<const reference::GrowingBrushSnapshot> heldControl;std::vector<Pixel> heldPixels;
    for(size_t event=0;event<points.size();++event){pixelCalls=0;grayCalls=0;const bool a=event?actual.append(points[event]):actual.begin(points[event]);actualCalls+=pixelCalls.exchange(0);actualGrayCalls+=grayCalls.exchange(0);const bool b=event?control.append(points[event]):control.begin(points[event]);referenceCalls+=pixelCalls.exchange(0);referenceGrayCalls+=grayCalls.exchange(0);require(a==b,"Sample acceptance differs");snapshots(actual.preview(),control.preview());coverage(actual,control);if(event==0){held=actual.preview();heldControl=control.preview();for(int y=-4;y<12;++y)for(int x=-4;x<12;++x)heldPixels.push_back(held->pixel(x,y));}else{size_t index=0;for(int y=-4;y<12;++y)for(int x=-4;x<12;++x)require(held->pixel(x,y)==heldPixels[index++],"Published snapshot mutated");}}
    auto result=actual.commit();auto expected=control.commit();snapshots(result,expected);coverage(actual,control);sameLayer(result->materializeLayer(),expected->materializeLayer());snapshots(held,heldControl);require(Raster::materializationCount()==0,"Whole image rgba materialized");require(actual.cancel()->materializeLayer()==original&&control.cancel()->materializeLayer()==original,"Cancel did not preserve original identity");
}
BrushSessionSettings settings(){return {32,.37,.61,{230,41,171},false};}
void ordinary(int mode){run(layer(mode),settings());}
void work(){run(layer(0),settings());report["original_pixel_calls_actual"]=qint64(actualCalls);report["original_pixel_calls_reference"]=qint64(referenceCalls);require(referenceCalls>0,"Work observer did not see scalar reference calls");require(actualCalls==0,"Ordinary image composition still dispatches per-pixel original reads");}
void growth(){auto l=layer(2);std::vector<Point> p;for(auto pixel:std::array<Point,5>{{{-35,60},{-20,90},{20,110},{290,150},{310,180}}})p.push_back(l.transform.fromUnit({pixel.x/257,pixel.y/193}));l.mask=Mask{gray(57,31,true),true,false};run(l,settings(),{},false,p);}
void transformed(){auto l=layer(2);l.transform={270.25,220.75,341,159,23,true,true,Transform::Sampling::High};run(l,settings(),gray(1024,768,true));}
void eraser(){auto s=settings();s.erase=true;run(layer(2),s,gray(1024,768,true));}
void maskGrid(){for(bool placed:{false,true}){auto l=layer(2);l.mask=Mask{gray(57,31,true),true,false};if(placed)l.mask->placement=Transform{305.5,220.25,257,193,-17,true,false,Transform::Sampling::Smooth};run(l,settings(),gray(1024,768,true),true);}}
void blank(){auto l=layer();l.raster.reset();run(l,settings());}
void empty(){auto l=layer();auto selected=std::make_shared<GrayRaster>(GrayRaster{1024,768,std::vector<uint8_t>(1024*768)});GrowingBrushSession a(l,settings(),1024,768,{},selected);reference::GrowingBrushSession b(l,settings(),1024,768,{},selected);require(!a.begin({400,300})&&!b.begin({400,300}),"Empty selection accepted paint");snapshots(a.preview(),b.preview());coverage(a,b);require(a.cancel()->materializeLayer()==l&&b.cancel()->materializeLayer()==l,"Empty selection changed original identity");}
void sharing(){auto l=layer(0,1024,768);l.transform={0,0,1024,768};GrowingBrushSession a(l,settings(),1024,768);reference::GrowingBrushSession b(l,settings(),1024,768);a.begin({70,70});b.begin({70,70});auto x=a.commit()->materializeLayer(),y=b.commit()->materializeLayer();sameLayer(x,y);size_t countA=0,countB=0;for(size_t i=0;i<l.raster->tiles.size();++i){countA+=x.raster->tiles[i]==l.raster->tiles[i];countB+=y.raster->tiles[i]==l.raster->tiles[i];}require(countA==countB&&countA>0,"Original tile sharing changed");}
void failure(){auto l=layer(0,64,64);l.transform={128,64,64,64};auto s=settings();s.radius=8;GrowingBrushSession a(l,s,512,256,{}, {},false,70000);reference::GrowingBrushSession b(l,s,512,256,{}, {},false,70000);a.begin({140,80});b.begin({140,80});auto held=a.preview();auto old=b.preview();bool aa=false,bb=false;try{a.append({450,80});}catch(const std::runtime_error&){aa=true;}try{b.append({450,80});}catch(const std::runtime_error&){bb=true;}require(aa&&bb&&held==a.preview()&&old==b.preview(),"Budget failure published partial output");snapshots(held,old);coverage(a,b);require(a.cancel()->materializeLayer()==l&&b.cancel()->materializeLayer()==l,"Failed stroke cancellation changed source");}
void custom(){auto l=layer(2);auto s=settings();s.radius=120;bool fail=false;int callsA=0,callsB=0;auto compose=[&](int& calls){return [&,counter=&calls](const auto& input,std::span<Pixel> output){++*counter;if(fail&&*counter==2)throw std::runtime_error("Injected custom compositor failure");for(int y=0;y<input.rect.height;++y)for(int x=0;x<input.rect.width;++x){const auto at=size_t(y)*256+x;require(output[at]==input.original[at],"Custom output was not initialized from original base");if(input.rawCoverage[size_t(y)*input.rect.width+x]>127)output[at]={12,23,34,255};}};};
    GrowingBrushSession a(l,s,1024,768,{}, {},false,100000000,compose(callsA));reference::GrowingBrushSession b(l,s,1024,768,{}, {},false,100000000,compose(callsB));a.begin({390,290});b.begin({390,290});snapshots(a.preview(),b.preview());auto held=a.preview();auto old=b.preview();callsA=callsB=0;fail=true;bool aa=false,bb=false;try{a.append({570,430});}catch(const std::runtime_error&){aa=true;}try{b.append({570,430});}catch(const std::runtime_error&){bb=true;}require(aa&&bb&&held==a.preview()&&old==b.preview(),"Custom exception changed publication");snapshots(held,old);fail=false;callsA=callsB=0;a.append({570,430});b.append({570,430});require(callsA==callsB,"Custom compositor invocation count changed");snapshots(a.commit(),b.commit());sameLayer(a.preview()->materializeLayer(),b.preview()->materializeLayer());}
}
int main(int argc,char** argv){QCoreApplication app(argc,argv);std::cout<<std::unitbuf;if(argc!=3)return 2;directory=std::filesystem::path(argv[2]);if(std::filesystem::exists(directory))return 2;std::filesystem::create_directories(directory);const std::string name=argv[1];const std::map<std::string,void(*)()> cases{{"bulk_original_reads",work},{"opaque",[]{ordinary(0);}},{"transparent",[]{ordinary(1);}},{"translucent",[]{ordinary(2);}},{"negative_growth_attached_mask",growth},{"transformed_selection_phase",transformed},{"erase_partial_selection",eraser},{"mask_different_grid_placement",maskGrid},{"blank",blank},{"empty_selection",empty},{"original_tile_sharing",sharing},{"budget_failure",failure},{"custom_compositor_exception",custom}};bool passed=false;std::string error;try{auto it=cases.find(name);require(it!=cases.end(),"Unknown case");it->second();passed=true;}catch(const std::exception& e){error=e.what();}report["schema"]="BRUSH_COMPOSITION_CONTRACTS_V1";report["case"]=QString::fromStdString(name);report["passed"]=passed;report["failed_predicate"]=QString::fromStdString(error);report["comparisons"]=comparisons;report["mac_differential"]=false;QFile file(QString::fromStdWString((directory/L"results.json").wstring()));if(!file.open(QIODevice::WriteOnly)||file.write(QJsonDocument(report).toJson())<0)return 3;std::cout<<(passed?"PASS ":"FAIL ")<<name<<" "<<error<<'\n';return passed?0:1;}
