#include "editing/SelectionGesture.h"
#include <cmath>
#include <iostream>
#include <limits>
#include <map>
#include <stdexcept>
using namespace compositor;
using namespace compositor::editing;
namespace {
void require(bool value,const char* why){if(!value)throw std::runtime_error(why);}
struct Session {
 std::optional<Document> document{Document{}};History history;SelectionGesture gesture;
 Session(){document->id=newId();document->width=document->height=100;Layer layer;layer.id=newId();layer.name="Layer 1";layer.transform={0,0,100,100};document->layers.push_back(layer);validateDocument(*document);}
 std::optional<SelectionOutline> current()const{require(document.has_value(),"source helper requires document");if(!document->selection)return {};require(bool(document->selection->outline),"source helper requires selection outline");return *document->selection->outline;}
 int coverage(int x,int y)const{require(document.has_value()&&document->selection.has_value(),"source coverage helper requires document and selection");const auto& gray=document->selection->coverage;require(gray&&gray->width==100&&gray->height==100&&gray->pixels.size()==10000&&gray->pixels.data(),"source coverage helper requires image, context and byte storage");return gray->pixel(x,y);}
 void finish(){auto result=gesture.finish(current(),100,100);if(result&&result->requestsEdit){history.begin(result->historyName,document,{});document->selection=rasterSelection(result->selection,100,100);history.end(document,{});}}
 void box(Point a,Point b,SelectionMode mode=SelectionMode::Replace,bool square=false,bool center=false,LassoKind kind=LassoKind::Rectangle){gesture.begin(a,kind,mode);gesture.dragMarquee(b,square,center);finish();}
 void lasso(std::initializer_list<Point> points,SelectionMode mode=SelectionMode::Replace){auto it=points.begin();gesture.begin(*it,LassoKind::Freehand,mode);for(++it;it!=points.end();++it)gesture.extend(*it);finish();}
};
void polygon_corners(){Session s;s.gesture.begin({10,10},LassoKind::Polygonal,SelectionMode::Replace);s.gesture.extend({90,10});s.gesture.extend({50,50});s.gesture.removeLast();s.gesture.extend({90,90});s.gesture.extend({10,90});require(s.gesture.draft()->points.size()==4,"source polygon corner count");s.finish();require(s.history.undoName()=="Polygonal Lasso","source Polygonal Lasso history name");require(s.coverage(80,80)==255&&s.coverage(5,50)==0,"source polygon coverage");s.gesture.begin({1,1},LassoKind::Polygonal,SelectionMode::Replace);s.gesture.cancel();require(!s.gesture.active()&&s.current()&&!s.current()->empty(),"source cancel preserves completed selection");}
void click_history(){Session s;const auto count=s.history.undoCount();s.lasso({{10,10},{50,10},{50,50},{10,50}});require(s.history.undoCount()==count+1&&s.history.undoName()=="Lasso","source Lasso undo step");s.lasso({{5,5}});require(!s.document->selection&&s.history.undoName()=="Deselect","source click Deselect");s.document=s.history.undo()->document;require(s.current()&&!s.current()->empty(),"source undo restores selection");s.document=s.history.undo()->document;require(!s.document->selection,"source undo restores absent");s.document=s.history.redo()->document;require(s.coverage(30,30)==255,"source redo coverage");}
void marquee_rounding(){Session s;s.box({60.4,70.6},{20.2,30.3});require(s.history.undoName()=="Rectangular Marquee","source rectangular name");require(s.current()->bounds()==Rect{20,30,40,41},"source rounded reverse box");require(s.coverage(20,30)==255&&s.coverage(19,30)==0,"source whole-pixel edge");s.box({80,80},{90,90},SelectionMode::Add);require(s.coverage(85,85)==255&&s.coverage(40,50)==255,"source added box");s.box({30,40},{50,60},SelectionMode::Subtract);require(s.coverage(40,50)==0&&s.coverage(25,35)==255,"source subtracted box");s.box({5,5},{5,5});require(!s.document->selection,"source marquee click deselects");}
void centered_programmatic(){Session s;s.box({10,10},{40,20},SelectionMode::Replace,true);require(s.current()->bounds()==Rect{10,10,30,30},"source square box");s.box({50,50},{60,55},SelectionMode::Replace,false,true);require(s.current()->bounds()==Rect{40,45,20,10},"source programmatic center box");s.box({50,50},{45,58},SelectionMode::Replace,true,true);require(s.current()->bounds()==Rect{42,42,16,16},"source centered square");}
void ellipse(){Session s;s.box({10,20},{70,60},SelectionMode::Replace,false,false,LassoKind::Ellipse);auto b=s.current()->bounds();require(std::abs(b.x-10)<.5&&std::abs(b.x+b.width-70)<.5&&std::abs(b.y-20)<.5&&std::abs(b.y+b.height-60)<.5,"source ellipse box tolerance");require(s.coverage(40,40)==255,"source ellipse center");require(s.coverage(11,21)==0,"source ellipse corner");s.box({5,5},{45,25},SelectionMode::Replace,true,false,LassoKind::Ellipse);b=s.current()->bounds();require(std::abs(b.width-b.height)<.5,"source ellipse Shift circle");require(s.history.undoName()=="Elliptical Marquee","source ellipse history name");}
void option_marquee(){Session s;s.box({0,0},{100,100});s.gesture.begin({40,40},LassoKind::Rectangle,selectionMode(false,true));s.gesture.move({60,60});s.finish();require(s.coverage(50,50)==0,"source Option dragged box subtracted");require(s.coverage(30,30)==255,"source Option must not draw from center");}
void fresh_shift(){Session s;s.box({5,5},{15,15});s.gesture.begin({40,40},LassoKind::Rectangle,selectionMode(true,false),true);s.gesture.move({70,50},true);s.finish();require(s.coverage(10,10)==255,"source earlier selection kept");require(s.coverage(65,45)==255,"source added rectangle");require(s.coverage(65,60)==0,"source held Shift does not square");s.gesture.begin({20,60},LassoKind::Rectangle,selectionMode(true,false),true);s.gesture.move({30,65},true);s.gesture.move({35,68},false);s.gesture.move({40,70},true);s.finish();require(s.coverage(30,75)==255,"source fresh Shift squares");require(s.coverage(65,45)==255&&s.coverage(10,10)==255,"source still adding");}
void stationary_modifiers(){SelectionGesture g;g.begin({10,10},LassoKind::Rectangle,SelectionMode::Add,true);g.modifiersChanged(false);g.modifiersChanged(true);g.move({40,20},true);require(g.outline().bounds()==Rect{10,10,30,10},"flags before first drag do not arm source latch");g.modifiersChanged(false);g.modifiersChanged(true);require(g.outline().bounds()==Rect{10,10,30,30},"stationary fresh Shift squares stored endpoint");g.modifiersChanged(false);require(g.outline().bounds()==Rect{10,10,30,10},"stationary release unsquares");require(g.cursorMode(false,true,SelectionMode::Replace)==SelectionMode::Add,"draft initial mode remains frozen");}
void polygon_closure(){SelectionGesture g;g.begin({10,10},LassoKind::Polygonal,SelectionMode::Replace);require(g.polygonPress({10.1,10},.1,1)==PolygonPressResult::Ignored,"quarter pixel skipped");require(g.polygonPress({90,10},8,1)==PolygonPressResult::Extended,"cannot single-close with fewer than3 corners");g.polygonPress({90,90},100,1);require(g.polygonPress({10,90},8.0001,1)==PolygonPressResult::Extended,"strict outside8 view-point threshold");g.move({4,8});require(g.draft()->cursor==Point{4,8}&&g.draft()->points.size()==4,"polygon hover changes cursor only");require(g.polygonPress({1000,1000},8,1)==PolygonPressResult::FinishRequested&&g.draft()->points.size()==4,"closure uses view distance and does not append");g.begin({1,1},LassoKind::Polygonal,SelectionMode::Replace);require(g.polygonPress({99,99},1000,2)==PolygonPressResult::FinishRequested,"double click closes even fewer than3 corners");require(!g.finish({},100,100)->selection,"degenerate double click replaces with absent");}
void quarter_pixel(){SelectionGesture g;g.begin({10,10},LassoKind::Freehand,SelectionMode::Replace);require(!g.extend({10.249,10}),"source skips less thanquarter pixel");require(g.extend({10.25,10}),"source includesquarter pixel exactly");require(!g.extend({std::numeric_limits<double>::quiet_NaN(),0}),"source ignores nonfinite extension");g.move({20,30});require(g.draft()->points.size()==3,"freehand move appends one point");g.removeLast();g.removeLast();g.removeLast();require(!g.active(),"removing finalcorner cancels draft");}
void mode_and_interrupt(){SelectionGesture g;require(g.cursorMode(false,false,SelectionMode::Replace)==SelectionMode::Replace,"source New cursor");require(g.cursorMode(true,false,SelectionMode::Replace)==SelectionMode::Add,"source Shift cursor");require(g.cursorMode(true,true,SelectionMode::Replace)==SelectionMode::Subtract,"source Option precedence");require(g.cursorMode(false,false,SelectionMode::Add)==SelectionMode::Add,"source remembered Add choice");g.begin({5,5},LassoKind::Freehand,SelectionMode::Subtract);require(g.cursorMode(false,false,SelectionMode::Replace)==SelectionMode::Subtract&&g.cursorMode(true,false,SelectionMode::Replace)==SelectionMode::Subtract,"source draft cursor mode frozen");g.interrupt();require(!g.active(),"focus loss cancels freehand");g.begin({5,5},LassoKind::Polygonal,SelectionMode::Replace);g.interrupt();require(g.active(),"focus loss retains polygon");g.begin({5,5},LassoKind::Rectangle,SelectionMode::Replace);g.interrupt();require(!g.active(),"focus loss cancels marquee");}
void empty_noop(){Session s;s.lasso({{0,0},{50,0},{50,50},{0,50}},SelectionMode::Subtract);require(!s.document->selection&&s.history.undoCount()==0,"nothing to subtract from");s.lasso({{10,10},{30,10},{30,30},{10,30}});s.lasso({{0,0},{60,0},{60,60},{0,60}},SelectionMode::Subtract);require(s.current()&&s.current()->empty()&&s.coverage(20,20)==0,"source explicit empty selection");const auto before=s.document;const auto count=s.history.undoCount();s.lasso({{5,5}},SelectionMode::Add);require(s.document==before&&s.history.undoCount()==count,"degenerate Add retains identity and history");s.lasso({{5,5}});require(!s.document->selection,"degenerate New deselects explicit empty");}
void move_axis(){require(selectionMoveOffset({0,0},{10.4,29.6},false)==Point{10.4,29.6},"free move offset");require(selectionMoveOffset({10,10},{30,30},true)==Point{20,0},"equal-axis Shift chooses X");require(selectionMoveOffset({10,10},{0,40},true)==Point{0,30},"largest axis Y");require(selectionMoveOffset({10,10},{-30,20},true)==Point{-40,0},"largest axis negativeX");}
void geometry_equality(){const auto box=SelectionOutline::rectangle({10,10,20,20});require(box.geometricallyEquals(SelectionOutline::rectangle({10,10,20,20})),"same independently built geometry");require(!box.geometricallyEquals(SelectionOutline::rectangle({10,10,20,20},false)),"AA differs");auto hole=box.combined(SelectionOutline::rectangle({15,15,5,5}),SelectionMode::Subtract,true);require(!box.geometricallyEquals(hole),"same bounds cannot hide hole");require(!box.geometricallyEquals(SelectionOutline::rectangle({10,10,20.001,20})),"exact bounds preserve tiny geometry change");const auto off=SelectionOutline::rectangle({-30,10,20,20});const auto otherOff=SelectionOutline::rectangle({-40,10,20,20});require(!off.geometricallyEquals(otherOff),"same allzero canvas coverage cannot suppress changed offcanvas geometry");require(SelectionOutline().geometricallyEquals(SelectionOutline()),"two explicit empty outlines equivalent");}
void autoscroll(){const Rect view{0,0,200,100};require(selectionAutoscrollDelta(view,{100,50})==Point{},"inside no scroll");require(selectionAutoscrollDelta(view,{12,12})==Point{},"source margin boundary zero");require(selectionAutoscrollDelta(view,{11,50})==Point{2.4,0},"source left margin acceleration");const auto corner=selectionAutoscrollDelta(view,{200,100});require(std::abs(corner.x+6.8)<1e-12&&std::abs(corner.y+6.8)<1e-12,"right-bottom scroll sign");require(selectionAutoscrollDelta(view,{400,-200})==Point{-40,40},"source40-point frame cap");require(selectionAutoscrollDelta({20,30,200,100},{31,80})==Point{2.4,0},"visible rectangle offset honored");}
}
int main(int argc,char** argv){const std::map<std::string,void(*)()> cases{{"polygon_corners",polygon_corners},{"click_history",click_history},{"marquee_rounding",marquee_rounding},{"centered_programmatic",centered_programmatic},{"ellipse",ellipse},{"option_marquee",option_marquee},{"fresh_shift",fresh_shift},{"stationary_modifiers",stationary_modifiers},{"polygon_closure",polygon_closure},{"quarter_pixel",quarter_pixel},{"mode_and_interrupt",mode_and_interrupt},{"empty_noop",empty_noop},{"move_axis",move_axis},{"autoscroll",autoscroll},{"geometry_equality",geometry_equality}};try{require(argc==2&&cases.contains(argv[1]),"provide valid case");cases.at(argv[1])();std::cout<<"PASS "<<argv[1]<<'\n';return 0;}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<'\n';return 1;}}
