#include "ui/MainWindow.h"
#include <QApplication>
#include <QMouseEvent>
#include <QFocusEvent>
#include <QTest>
#include <iostream>
#include <cmath>
#include <stdexcept>
using namespace compositor;
namespace {
void require(bool value,const char* why){if(!value)throw std::runtime_error(why);}
QAction* command(MainWindow& w,const char* id){for(auto* a:w.findChildren<QAction*>())if(a->property("commandId").toString()==id)return a;throw std::runtime_error("missing command");}
Document document(){Document d;d.id=newId();d.width=d.height=100;Layer l;l.id=newId();l.name="Layer 1";l.transform={0,0,100,100};d.layers.push_back(l);return d;}
struct Fixture {
 MainWindow window{true};EditorProject& project;
 Fixture():project(window.addProject(document())){window.show();QApplication::processEvents();}
 void send(QEvent::Type type,Point point,Qt::KeyboardModifiers flags={}){
  auto* canvas=project.canvas;const auto v=canvas->viewMapping().toView(point);const QPointF at(v.x,v.y);
  const bool release=type==QEvent::MouseButtonRelease;const bool move=type==QEvent::MouseMove;
  QMouseEvent event(type,at,canvas->mapToGlobal(at.toPoint()),move?Qt::NoButton:Qt::LeftButton,release?Qt::NoButton:Qt::LeftButton,flags);QApplication::sendEvent(canvas,&event);
 }
 int coverage(int x,int y)const{return project.document->selection&&project.document->selection->coverage?project.document->selection->coverage->pixel(x,y):-1;}
 void click(Point point){send(QEvent::MouseButtonPress,point);send(QEvent::MouseButtonRelease,point);}
};
void option_marquee(){Fixture f;command(f.window,"tool.marquee")->trigger();command(f.window,"selection.all")->trigger();f.send(QEvent::MouseButtonPress,{40,40},Qt::AltModifier);f.send(QEvent::MouseMove,{60,60},Qt::AltModifier);f.send(QEvent::MouseButtonRelease,{60,60},Qt::AltModifier);std::cout<<"coverage50,50="<<f.coverage(50,50)<<" coverage30,30="<<f.coverage(30,30)<<'\n';require(f.coverage(50,50)==0,"source SelectionTests:376 dragged box subtracted");require(f.coverage(30,30)==255,"source SelectionTests:377 Alt must not draw from center");}
void fresh_shift_marquee(){Fixture f;command(f.window,"tool.marquee")->trigger();f.project.document->selection=editing::rasterSelection(editing::SelectionOutline::rectangle({5,5,10,10}),100,100);f.send(QEvent::MouseButtonPress,{40,40},Qt::ShiftModifier);f.send(QEvent::MouseMove,{70,50},Qt::ShiftModifier);f.send(QEvent::MouseButtonRelease,{70,50},Qt::ShiftModifier);const bool first=f.coverage(10,10)==255&&f.coverage(65,45)==255&&f.coverage(65,60)==0;std::cout<<"first coverage10,10="<<f.coverage(10,10)<<" coverage65,45="<<f.coverage(65,45)<<" coverage65,60="<<f.coverage(65,60)<<'\n';f.send(QEvent::MouseButtonPress,{20,60},Qt::ShiftModifier);f.send(QEvent::MouseMove,{30,65},Qt::ShiftModifier);f.send(QEvent::MouseMove,{35,68});f.send(QEvent::MouseMove,{40,70},Qt::ShiftModifier);f.send(QEvent::MouseButtonRelease,{40,70},Qt::ShiftModifier);require(f.coverage(30,75)==255,"source fresh Shift squares marquee");require(f.coverage(65,45)==255&&f.coverage(10,10)==255,"source fresh Shift still adds");require(first,"source initial Shift must add without squaring");}
void polygon_click_close(){Fixture f;command(f.window,"tool.polygon")->trigger();f.click({10,10});f.click({90,10});f.click({90,90});f.click({10,90});f.click({10,10});std::cout<<"history="<<f.project.history.undoCount()<<" name="<<f.project.history.undoName()<<" coverage80,80="<<f.coverage(80,80)<<'\n';require(f.project.history.undoCount()==1&&f.project.history.undoName()=="Polygonal Lasso","source near-first click closes one Polygonal Lasso edit");require(f.coverage(80,80)==255&&f.coverage(5,50)==0,"source closed polygon coverage");}
void canonical_draft(){Fixture f;command(f.window,"tool.marquee")->trigger();const auto before=f.project.document;f.send(QEvent::MouseButtonPress,{10,10});f.send(QEvent::MouseMove,{60,60});const bool unchanged=f.project.document==before;std::cout<<"canonical_unchanged_during_draft="<<unchanged<<'\n';f.send(QEvent::MouseButtonRelease,{60,60});require(unchanged,"source lasso draft must not mutate canonical selection");require(f.project.history.undoCount()==1,"source completed gesture owns one undo");}
void polygon_backspace_enter(){Fixture f;command(f.window,"tool.polygon")->trigger();f.click({10,10});f.click({90,10});f.click({50,50});QTest::keyClick(f.project.canvas,Qt::Key_Backspace);f.click({90,90});f.click({10,90});require(f.project.canvas->selectionDraft()&&f.project.canvas->selectionDraft()->points.size()==4,"source polygon four corners after remove");QTest::keyClick(f.project.canvas,Qt::Key_Return);require(f.project.history.undoName()=="Polygonal Lasso","source Return closes Polygonal Lasso");require(f.coverage(80,80)==255&&f.coverage(5,50)==0,"source polygon closed coverage");f.click({1,1});QTest::keyClick(f.project.canvas,Qt::Key_Escape);require(!f.project.canvas->selectionDraft()&&f.coverage(80,80)==255,"source cancel keeps selection");}
void polygon_doubleclick(){Fixture f;command(f.window,"tool.polygon")->trigger();f.click({10,10});f.click({90,10});f.click({90,90});f.click({10,90});f.send(QEvent::MouseButtonDblClick,{50,80});f.send(QEvent::MouseButtonRelease,{50,80});require(!f.project.canvas->selectionDraft()&&f.project.history.undoName()=="Polygonal Lasso","source double click closes without appending endpoint");require(f.coverage(20,80)==255,"double click must not add inward corner");}
void stationary_shift(){Fixture f;command(f.window,"tool.marquee")->trigger();f.send(QEvent::MouseButtonPress,{10,10},Qt::ShiftModifier);f.send(QEvent::MouseMove,{40,20},Qt::ShiftModifier);require(f.project.canvas->selectionDraft()->points[2]==Point{40,20},"source held Shift unsquared draft");QTest::keyRelease(f.project.canvas,Qt::Key_Shift);QTest::keyPress(f.project.canvas,Qt::Key_Shift);require(f.project.canvas->selectionDraft()->points[2]==Point{40,40},"source stationary fresh Shift squares draft");f.send(QEvent::MouseButtonRelease,{90,90},Qt::ShiftModifier);require(f.coverage(30,30)==255&&f.coverage(50,50)==0,"source release does not add another drag endpoint");QTest::keyRelease(f.project.canvas,Qt::Key_Shift);}
void focus_retention(){Fixture f;command(f.window,"tool.polygon")->trigger();f.click({10,10});f.click({90,10});QFocusEvent out(QEvent::FocusOut);QApplication::sendEvent(f.project.canvas,&out);require(f.project.canvas->selectionDraft()&&f.project.canvas->selectionDraft()->points.size()==2,"source polygon persists across focus loss");f.click({90,90});QTest::keyClick(f.project.canvas,Qt::Key_Return);require(f.project.history.undoCount()==1,"source resumed polygon closes one edit");command(f.window,"tool.marquee")->trigger();const auto before=f.project.document;f.send(QEvent::MouseButtonPress,{0,0});f.send(QEvent::MouseMove,{50,50});QApplication::sendEvent(f.project.canvas,&out);require(!f.project.canvas->selectionDraft()&&f.project.document==before&&f.project.history.undoCount()==1,"source focus loss cancels non-polygon draft without history");}
void move_click_and_axis(){Fixture f;command(f.window,"tool.marquee")->trigger();f.project.document->selection=editing::rasterSelection(editing::SelectionOutline::rectangle({10,10,20,20}),100,100);f.send(QEvent::MouseButtonPress,{20,20});f.send(QEvent::MouseMove,{40,40},Qt::ShiftModifier);f.send(QEvent::MouseButtonRelease,{40,40},Qt::ShiftModifier);require(f.project.document->selection->outline->bounds()==editing::Rect{30,10,20,20},"source Shift move ties choose X");require(f.project.history.undoName()=="Move Selection"&&f.project.history.undoCount()==1,"source move owns one history");f.click({40,20});require(!f.project.document->selection&&f.project.history.undoName()=="Deselect"&&f.project.history.undoCount()==2,"source click inside unmoved selection deselects");}
void repeated_outline_noop(){Fixture f;command(f.window,"tool.marquee")->trigger();f.project.document->selection=editing::rasterSelection(editing::SelectionOutline::rectangle({10,10,20,20}),100,100);const auto before=f.project.document;f.send(QEvent::MouseButtonPress,{10,10},Qt::ShiftModifier);f.send(QEvent::MouseMove,{30,30},Qt::ShiftModifier);f.send(QEvent::MouseButtonRelease,{30,30},Qt::ShiftModifier);require(f.project.document==before&&f.project.history.undoCount()==0,"identical whole geometry must retain selection identity and no undo");}
void autoscroll_events(){Fixture f;command(f.window,"tool.marquee")->trigger();f.send(QEvent::MouseButtonPress,{10,10});const auto viewPoint=QPointF(f.project.canvas->width()+30,f.project.canvas->height()/2);const auto docPoint=f.project.canvas->documentPoint(viewPoint);const auto pan=f.project.canvas->pan;f.send(QEvent::MouseMove,{docPoint.x(),docPoint.y()});QTest::qWait(65);require(f.project.canvas->pan.x()<pan.x(),"source timer pans toward outside pointer");require(f.project.canvas->selectionDraft()&&f.project.canvas->selectionDraft()->points[1].x>std::round(docPoint.x()),"stationary outside view pointer follows new document mapping");const auto after=f.project.canvas->pan;f.send(QEvent::MouseButtonRelease,{docPoint.x(),docPoint.y()});QTest::qWait(40);require(f.project.canvas->pan==after,"source release stops autoscroll");}
}
int main(int argc,char** argv){QApplication app(argc,argv);try{require(argc==2,"provide case");const std::string c=argv[1];if(c=="option_marquee")option_marquee();else if(c=="fresh_shift_marquee")fresh_shift_marquee();else if(c=="polygon_click_close")polygon_click_close();else if(c=="canonical_draft")canonical_draft();else if(c=="polygon_backspace_enter")polygon_backspace_enter();else if(c=="polygon_doubleclick")polygon_doubleclick();else if(c=="stationary_shift")stationary_shift();else if(c=="focus_retention")focus_retention();else if(c=="move_click_and_axis")move_click_and_axis();else if(c=="repeated_outline_noop")repeated_outline_noop();else if(c=="autoscroll_events")autoscroll_events();else throw std::runtime_error("unknown case");std::cout<<"PASS "<<c<<'\n';return 0;}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<'\n';return 1;}}
