#include "core/Document.h"
#include "effects/Adjustments.h"
#include <algorithm>
#include <cmath>
#include <functional>
#include <iostream>
#include <limits>
#include <map>
#include <set>
#include <stdexcept>
using namespace compositor;
#define REQUIRE(...) do{if(!(__VA_ARGS__))throw std::runtime_error(std::string(__FILE__)+":"+std::to_string(__LINE__)+": " #__VA_ARGS__);}while(false)
Document document(int width,int height,Pixel color={90,40,20,128}){Document d;d.id=newId();d.width=width;d.height=height;Layer layer;layer.id=newId();layer.raster=Raster::filled(width,height,color);layer.transform={0,0,double(width),double(height),0,false,false,Transform::Sampling::Nearest};layer.opacity=.75;d.layers={layer};return d;}
void equal(const Raster& a,const Raster& b){REQUIRE(a.width==b.width&&a.height==b.height);for(int y=0;y<a.height;++y)for(int x=0;x<a.width;++x)REQUIRE(a.pixel(x,y)==b.pixel(x,y));}
size_t unique(const Raster& raster){std::set<const Raster::Tile*> pointers;for(auto& tile:raster.tiles){REQUIRE(tile);pointers.insert(tile.get());}return pointers.size();}
void blank_30000(){Document d;d.width=d.height=30000;CompositeCache cache;Raster::resetMaterializationCount();auto full=cache.render(d);REQUIRE(full->width==30000&&full->height==30000&&full->tiles.size()==13924&&unique(*full)==1);REQUIRE(full->pixel(29999,29999)==Pixel{}&&cache.render(d)==full);auto view=cache.renderViewport(d,0,0,30000,30000);REQUIRE(view.documentWidth==30000&&view.documentHeight==30000&&view.unitsPerPixel==16);REQUIRE(view.raster->tiles.size()==64&&unique(*view.raster)==1&&view.raster->pixel(1874,1874)==Pixel{});REQUIRE(Raster::materializationCount()==0);}
void identity_fastpath(){auto d=document(768,512);d.layers[0].opacity=1;CompositeCache cache;REQUIRE(cache.render(d)==d.layers[0].raster);auto view=cache.renderViewport(d,256,256,256,256);REQUIRE(view.documentX==256&&view.documentY==256&&view.unitsPerPixel==1&&view.raster->tiles.size()==1&&view.raster->tiles[0]==d.layers[0].raster->tiles[4]);}
void normal_equivalence(){auto d=document(513,259);Layer over=d.layers[0];over.id=newId();over.raster=Raster::filled(50,100,{0,160,0,200});over.transform={21.5,48.25,80,170,19,true,false,Transform::Sampling::Smooth};over.blend=Blend::Multiply;d.layers.push_back(over);CompositeCache cache;auto full=cache.render(d);equal(*full,*SoftwareRenderer().render(d,0,0,d.width,d.height));REQUIRE(cache.render(d)==full);auto view=cache.renderViewport(d,260,0,240,258);REQUIRE(view.documentX==256&&view.unitsPerPixel==1);for(int y=0;y<view.raster->height;++y)for(int x=0;x<view.raster->width;++x)REQUIRE(view.raster->pixel(x,y)==full->pixel(x+256,y));}
void offscreen_invalidation(){auto d=document(768,256);CompositeCache cache;auto fullBefore=cache.render(d);auto left=cache.renderViewport(d,0,0,256,256,1,1,3);auto right=cache.renderViewport(d,512,0,256,256,1,1,3);Pixel changed{0,0,255,255};d.layers[0].raster=d.layers[0].raster->replacing(600,50,1,1,&changed,1);auto leftAfter=cache.renderViewport(d,0,0,256,256,1,1,3);REQUIRE(leftAfter.raster->tiles[0]==left.raster->tiles[0]);auto rightAfter=cache.renderViewport(d,512,0,256,256,1,1,3);REQUIRE(rightAfter.raster->tiles[0]!=right.raster->tiles[0]&&rightAfter.raster->pixel(88,50).b==191);auto full=cache.render(d);REQUIRE(full->tiles[0]==fullBefore->tiles[0]&&full->pixel(600,50).b==191);REQUIRE(right.raster->pixel(88,50).b!=191);equal(*full,*SoftwareRenderer().render(d,0,0,768,256));}
void bounded_eviction(){auto d=document(768,256);CompositeCache cache;auto first=cache.renderViewport(d,0,0,256,256,1,1,2);auto middle=cache.renderViewport(d,256,0,256,256,1,1,2);auto last=cache.renderViewport(d,512,0,256,256,1,1,2);auto again=cache.renderViewport(d,0,0,256,256,1,1,2);REQUIRE(again.raster->tiles[0]!=first.raster->tiles[0]);equal(*again.raster,*first.raster);REQUIRE(middle.raster->tiles.size()==1&&last.raster->tiles.size()==1);}
void metadata_and_hidden_source(){auto d=document(513,1,{255,0,0,255});Layer mask=d.layers[0];mask.id=newId();mask.visible=false;mask.opacity=1;mask.raster=Raster::filled(513,1,{0,0,0,128});d.layers[0].maskSourceId=mask.id;d.layers[0].opacity=1;d.layers.push_back(mask);CompositeCache cache;auto before=cache.renderViewport(d,512,0,1,1);REQUIRE(before.raster->pixel(0,0).a==128);d.layers[1].raster=Raster::filled(513,1,{0,0,0,64});cache.renderViewport(d,0,0,1,1);auto after=cache.renderViewport(d,512,0,1,1);REQUIRE(after.raster->pixel(0,0).a==64&&before.raster->pixel(0,0).a==128);d.layers[0].visible=false;auto empty=cache.renderViewport(d,512,0,1,1);REQUIRE(empty.raster->pixel(0,0)==Pixel{});}
void full_after_partial(){auto d=document(513,257);CompositeCache cache;auto partial=cache.renderViewport(d,0,0,32,32);REQUIRE(partial.raster->width==256&&partial.raster->height==256);auto full=cache.render(d);REQUIRE(full->width==513&&full->height==257&&full->tiles.size()==6);equal(*full,*SoftwareRenderer().render(d,0,0,513,257));}
void lod_large_content(){Document d;d.width=d.height=30000;Layer layer;layer.id=newId();layer.raster=Raster::filled(1,1,{30,60,90,255});layer.transform={0,0,30000,30000};d.layers={layer};CompositeCache cache;auto view=cache.renderViewport(d,0,0,30000,30000,1,4,8);REQUIRE(view.unitsPerPixel==64&&view.raster->tiles.size()==4&&view.raster->width==469);REQUIRE(view.raster->pixel(200,200)==Pixel{30,60,90,255});auto zoomed=cache.renderViewport(d,1234,2345,30,30,1,4,8);REQUIRE(zoomed.unitsPerPixel==1&&zoomed.raster->tiles.size()<=4&&zoomed.raster->pixel(10,10)==Pixel{30,60,90,255});auto smallest=cache.renderViewport(d,0,0,30000,30000,30000,1,1);REQUIRE(smallest.raster->width==1&&smallest.unitsPerPixel==30000);}
void scaled_renderer_contract(){auto d=document(10,4);std::vector<Pixel> pixels(40);for(int y=0;y<4;++y)for(int x=0;x<10;++x)pixels[size_t(y)*10+x]={uint8_t(x*20),uint8_t(y*40),0,255};d.layers[0].raster=Raster::fromRgba(10,4,reinterpret_cast<const uint8_t*>(pixels.data()),40);d.layers[0].opacity=1;SoftwareRenderer renderer;equal(*renderer.render(d,0,0,10,4),*renderer.renderScaled(d,0,0,10,4,1));auto scaled=renderer.renderScaled(d,.25,.25,5,2,2);for(int y=0;y<2;++y)for(int x=0;x<5;++x)REQUIRE(scaled->pixel(x,y)==pixels[size_t(y*2+1)*10+x*2+1]);}
void scaled_grain_partition(){auto d=document(1032,8,{100,100,100,255});Layer grain;grain.id=newId();grain.adjustmentJson=effects::defaultAdjustmentJson("Grain");grain.transform={0,0,1032,8};d.layers.push_back(grain);SoftwareRenderer renderer;auto full=renderer.renderScaled(d,0,0,258,2,4);auto left=renderer.renderScaled(d,0,0,256,2,4),right=renderer.renderScaled(d,1024,0,2,2,4);for(int y=0;y<2;++y)for(int x=0;x<258;++x)REQUIRE(full->pixel(x,y)==(x<256?left->pixel(x,y):right->pixel(x-256,y)));}
void outside_and_rejections(){auto d=document(20,20);CompositeCache cache;REQUIRE(!cache.renderViewport(d,21,0,5,5).raster);REQUIRE(!cache.renderViewport(d,0,0,0,0).raster);for(auto action:std::vector<std::function<void()>>{[&]{cache.renderViewport(d,0,0,-1,1);},[&]{cache.renderViewport(d,NAN,0,1,1);},[&]{cache.renderViewport(d,0,0,1,1,0);},[&]{cache.renderViewport(d,0,0,1,1,1,2,1);}}){bool rejected=false;try{action();}catch(const std::invalid_argument&){rejected=true;}REQUIRE(rejected);}for(double units:{0.,-1.,double(NAN),double(INFINITY),1/64.}){bool rejected=false;try{SoftwareRenderer().renderScaled(d,0,0,1,1,units);}catch(const std::invalid_argument&){rejected=true;}REQUIRE(rejected);}auto halfDocument=d;halfDocument.layers[0].opacity=1;const std::array<Pixel,2> pair{{{255,0,0,255},{0,255,0,255}}};halfDocument.layers[0].raster=halfDocument.layers[0].raster->replacing(0,0,2,1,pair.data(),2);auto half=SoftwareRenderer().renderScaled(halfDocument,0,0,4,2,.5);REQUIRE(half->width==4&&half->height==2);for(int y=0;y<2;++y)for(int x=0;x<4;++x)REQUIRE(half->pixel(x,y)==pair[size_t(x/2)]);cache.reset();REQUIRE(cache.renderViewport(d,0,0,20,20).raster->pixel(10,10)==SoftwareRenderer().render(d,10,10,1,1)->pixel(0,0));}
void blank_culling(){Document d;d.width=d.height=30000;Layer l;l.id=newId();l.raster=Raster::filled(1,1,{255,0,0,255});l.transform={-100,-100,1,1};d.layers={l};CompositeCache cache;auto full=cache.render(d);REQUIRE(unique(*full)==1&&full->pixel(0,0)==Pixel{});Layer group;group.id=newId();group.group=true;group.visible=false;l.parentId=group.id;l.transform={0,0,30000,30000};d.layers={group,l};REQUIRE(unique(*cache.render(d))==1);}

void lod_offscreen_invalidation(){auto d=document(768,64);d.width=2304;d.layers[0].transform.width=2304;CompositeCache cache;auto left=cache.renderViewport(d,0,0,512,64,2,1,3);auto right=cache.renderViewport(d,1536,0,512,64,2,1,3);std::vector<Pixel> blue(256*64,{0,0,255,255});d.layers[0].raster=d.layers[0].raster->replacing(512,0,256,64,blue.data(),256);auto leftAfter=cache.renderViewport(d,0,0,512,64,2,1,3);REQUIRE(leftAfter.raster->tiles[0]==left.raster->tiles[0]);auto rightAfter=cache.renderViewport(d,1536,0,512,64,2,1,3);REQUIRE(rightAfter.unitsPerPixel==2&&rightAfter.raster->tiles[0]!=right.raster->tiles[0]&&rightAfter.raster->pixel(0,0).b==191);}
void unsupported_blank_adjustment(){Document d;d.width=d.height=30000;Layer adjustment;adjustment.id=newId();adjustment.adjustmentJson="{\"kind\":\"unsupported\"}";d.layers={adjustment};for(bool viewport:{false,true}){CompositeCache cache;bool rejected=false;try{if(viewport)cache.renderViewport(d,0,0,30000,30000);else cache.render(d);}catch(const std::exception&){rejected=true;}REQUIRE(rejected);}d.layers[0].visible=false;CompositeCache cache;REQUIRE(unique(*cache.render(d))==1);}

int main(int argc,char** argv){std::map<std::string,void(*)()> tests{{"lod_offscreen_invalidation",lod_offscreen_invalidation},{"unsupported_blank_adjustment",unsupported_blank_adjustment},{"blank_30000",blank_30000},{"identity_fastpath",identity_fastpath},{"normal_equivalence",normal_equivalence},{"offscreen_invalidation",offscreen_invalidation},{"bounded_eviction",bounded_eviction},{"metadata_and_hidden_source",metadata_and_hidden_source},{"full_after_partial",full_after_partial},{"lod_large_content",lod_large_content},{"scaled_renderer_contract",scaled_renderer_contract},{"scaled_grain_partition",scaled_grain_partition},{"outside_and_rejections",outside_and_rejections},{"blank_culling",blank_culling}};try{if(argc!=2||!tests.contains(argv[1]))throw std::runtime_error("Specify cache test");tests.at(argv[1])();std::cout<<"PASS "<<argv[1]<<"\n";return 0;}catch(const std::exception& error){std::cerr<<"FAIL "<<error.what()<<"\n";return 1;}}
