cmake_policy(SET CMP0054 NEW)
if(NOT DEFINED EXECUTABLE OR NOT DEFINED CASE OR NOT DEFINED EVIDENCE_ROOT)
  message(FATAL_ERROR "EXECUTABLE, CASE and EVIDENCE_ROOT are required")
endif()
string(TIMESTAMP stamp "%Y%m%d-%H%M%S" UTC)
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
set(directory "${EVIDENCE_ROOT}/${CASE}/${stamp}-${nonce}")
file(MAKE_DIRECTORY "${directory}")
# This is a functional timeout, including ASAN's full sequential comparison.
# The separate frozen performance executable retains its 16.7ms p95 threshold.
execute_process(COMMAND "${EXECUTABLE}" "${CASE}" "${directory}/capture"
  RESULT_VARIABLE status OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 240)
file(WRITE "${directory}/stdout.log" "${stdout}")
file(WRITE "${directory}/stderr.log" "${stderr}")
message("${stdout}${stderr}")
set(report_path "${directory}/capture/results.json")
if(NOT EXISTS "${report_path}")
  message(FATAL_ERROR "Brush batch report missing; process=${status}")
endif()
file(READ "${report_path}" report)
string(JSON passed GET "${report}" passed)
message("WITNESS_REPORT ${report_path}")
if(NOT status EQUAL 0 OR NOT passed)
  message(FATAL_ERROR "Brush batch witness failed; process=${status}")
endif()
