#include "core/DocumentExport.h"
#include "effects/Adjustments.h"
#include "imaging/wic_codec.h"
#include <QCoreApplication>
#include <QTemporaryDir>
#include <QJsonDocument>
#include <QJsonObject>
#include <QFile>
#include <windows.h>
#include <psapi.h>
#include <wincodec.h>
#include <wrl/client.h>
#include <algorithm>
#include <chrono>
#include <fstream>
#include <iostream>
#include <map>
#include <cmath>
using namespace compositor;
using namespace compositor::imaging;
#define REQUIRE(...) do {if(!(__VA_ARGS__))throw std::runtime_error(std::string(__FILE__)+":"+std::to_string(__LINE__)+": " #__VA_ARGS__);}while(false)
template<class F>void rejects(F action){bool rejected=false;try{action();}catch(const std::exception&){rejected=true;}REQUIRE(rejected);}
std::filesystem::path path(const QTemporaryDir& dir,const char* name){return std::filesystem::path(dir.filePath(QString::fromUtf8(name)).toStdWString());}
std::vector<uint8_t> bytes(const std::filesystem::path& name){std::ifstream file(name,std::ios::binary);return {std::istreambuf_iterator<char>(file),std::istreambuf_iterator<char>()};}
void original(const std::filesystem::path& name){std::ofstream file(name,std::ios::binary);file<<"preserve original\0\xff";}
void only(const QTemporaryDir& directory,size_t files){REQUIRE(size_t(std::distance(std::filesystem::directory_iterator(std::filesystem::path(directory.path().toStdWString())),std::filesystem::directory_iterator{}))==files);}
Pixel pixel(const RgbaImage& image,int x,int y){auto*p=image.pixels.data()+size_t(y)*image.stride+size_t(x)*4;return {p[0],p[1],p[2],p[3]};}
void metadata(const std::filesystem::path& filename,ImageFormat format){
 using Microsoft::WRL::ComPtr;ComPtr<IWICImagingFactory> f;REQUIRE(SUCCEEDED(CoCreateInstance(CLSID_WICImagingFactory,nullptr,CLSCTX_INPROC_SERVER,IID_PPV_ARGS(&f))));
 ComPtr<IWICBitmapDecoder> decoder;REQUIRE(SUCCEEDED(f->CreateDecoderFromFilename(filename.c_str(),nullptr,GENERIC_READ,WICDecodeMetadataCacheOnDemand,&decoder)));GUID type{};REQUIRE(SUCCEEDED(decoder->GetContainerFormat(&type)));REQUIRE(type==(format==ImageFormat::Png?GUID_ContainerFormatPng:GUID_ContainerFormatJpeg));UINT frames=0;REQUIRE(SUCCEEDED(decoder->GetFrameCount(&frames))&&frames==1);ComPtr<IWICBitmapFrameDecode> frame;REQUIRE(SUCCEEDED(decoder->GetFrame(0,&frame)));
 if(format==ImageFormat::Png){ComPtr<IWICMetadataQueryReader> reader;REQUIRE(SUCCEEDED(frame->GetMetadataQueryReader(&reader)));PROPVARIANT value;PropVariantInit(&value);REQUIRE(SUCCEEDED(reader->GetMetadataByName(L"/sRGB/RenderingIntent",&value)));REQUIRE(value.vt==VT_UI1&&value.bVal==0);PropVariantClear(&value);}
 else{UINT count=0;REQUIRE(SUCCEEDED(frame->GetColorContexts(0,nullptr,&count))&&count>0);}
}
Document blank(int width,int height){Document d;d.id=newId();d.width=width;d.height=height;return d;}
RgbaRows pattern(){return [](uint32_t y,uint32_t rows,std::span<uint8_t> data,size_t stride){for(uint32_t row=0;row<rows;++row)for(size_t x=0;x<stride/4;++x){auto*p=data.data()+row*stride+x*4;unsigned a=unsigned((x*11+(y+row)*19)%256);p[0]=uint8_t((x*37+(y+row)*17)%(a+1));p[1]=uint8_t((x*11+(y+row)*53)%(a+1));p[2]=uint8_t((x*79+(y+row)*7)%(a+1));p[3]=uint8_t(a);}};}
void extent_guard(){QTemporaryDir temp;auto target=path(temp,"keep.png");original(target);auto before=bytes(target);int calls=0;auto source=[&](uint32_t,uint32_t,std::span<uint8_t>,size_t){++calls;};for(auto dims:{std::pair{30000U,30000U},{30001U,1U},{10001U,10000U},{0U,1U}})rejects([&]{encodeRowsAtomic(target,dims.first,dims.second,source);});auto d=blank(30000,30000);Raster::resetMaterializationCount();rejects([&]{exportDocumentAtomic(d,target);});REQUIRE(calls==0&&Raster::materializationCount()==0&&bytes(target)==before);only(temp,1);validateExportExtent(10000,10000);validateExportExtent(30000,3333);}
void row_png(){QTemporaryDir temp;auto target=path(temp,"rows.png");ExportOptions options;options.dpi=300;StreamExportLimits limits;limits.stripeRows=7;uint32_t next=0;auto fill=pattern();auto result=encodeRowsAtomic(target,19,65,[&](uint32_t y,uint32_t count,std::span<uint8_t> out,size_t stride){REQUIRE(y==next&&count<=7&&stride==76&&out.size()==count*stride);next+=count;fill(y,count,out,stride);},options,limits);REQUIRE(next==65&&result.stripeRows==7&&result.encodedBytes==bytes(target).size());auto decoded=WicCodec::decode(target);RgbaImage expected{19,65,76,std::vector<uint8_t>(19*65*4)};fill(0,65,expected.pixels,76);REQUIRE(decoded.image.pixels==expected.pixels&&result.preview.pixels==expected.pixels);REQUIRE(decoded.metadata.originalOrientation==1&&std::abs(decoded.metadata.dpiX-300)<.02&&std::abs(decoded.metadata.dpiY-300)<.02);metadata(target,ImageFormat::Png);only(temp,1);}
Document mixed(){auto d=blank(1031,131);d.resolution=144;Layer folder;folder.id=newId();folder.name="Folder";folder.group=true;folder.transform={0,0,1031,131};folder.mask=Mask{std::make_shared<GrayRaster>(GrayRaster{3,3,{255,150,255,200,80,255,255,255,255}})};d.layers.push_back(folder);Layer base;base.id=newId();base.name="Pixels";base.parentId=folder.id;base.transform={5.25,3.75,1017,127,3,true,false};auto source=std::vector<uint8_t>(1017*127*4);pattern()(0,127,source,1017*4);base.raster=Raster::fromRgba(1017,127,source.data(),1017*4);d.layers.push_back(base);Layer clip;clip.id=newId();clip.name="Clip";clip.parentId=folder.id;clip.maskSourceId=base.id;clip.opacity=.55;clip.blend=Blend::Screen;clip.transform={-10,2,1040,129};clip.raster=Raster::filled(3,3,{20,80,30,128});clip.mask=Mask{std::make_shared<GrayRaster>(GrayRaster{2,2,{255,255,100,255}}),true,false,Transform{4,1,1000,120,7,false,true}};d.layers.push_back(clip);Layer grain;grain.id=newId();grain.name="Grain";grain.parentId=folder.id;grain.adjustmentJson=effects::defaultAdjustmentJson("Grain");auto object=QJsonDocument::fromJson(QByteArray::fromStdString(grain.adjustmentJson)).object();object["grainSettings"]=QJsonObject{{"amount",65},{"size",2.5},{"roughness",40},{"seed",917}};grain.adjustmentJson=QJsonDocument(object).toJson(QJsonDocument::Compact).toStdString();d.layers.push_back(grain);auto hidden=clip;hidden.id=newId();hidden.visible=false;hidden.maskSourceId.clear();hidden.raster=Raster::filled(1,1,{255,0,0,255});d.layers.push_back(hidden);d.selection=Selection{std::make_shared<GrayRaster>(GrayRaster{d.width,d.height,std::vector<uint8_t>(size_t(d.width)*d.height,0)})};return d;}
void canonical_partition(){QTemporaryDir temp;auto d=mixed();const auto before=d;const auto expected=SoftwareRenderer().render(d,0,0,d.width,d.height)->rgba();for(uint32_t stripe:{1U,7U,64U}){StreamExportLimits limits;limits.stripeRows=stripe;auto target=path(temp,("part-"+std::to_string(stripe)+".png").c_str());Raster::resetMaterializationCount();auto result=exportDocumentAtomic(d,target,{},limits);REQUIRE(Raster::materializationCount()==0&&d==before&&result.maxRenderPixelBytes<=8*1024*1024);auto decoded=WicCodec::decode(target);REQUIRE(decoded.image.pixels==expected);}}
void jpeg_matte_preview(){QTemporaryDir temp;auto d=blank(20,12);for(bool blue:{false,true}){ExportOptions options;options.format=ImageFormat::Jpeg;options.jpegQuality=blue?1:.85;options.matteR=options.matteG=blue?0:255;options.matteB=255;auto target=path(temp,blue?"blue.jpg":"white.jpg");auto result=exportDocumentAtomic(d,target,options);auto decoded=WicCodec::decode(target);REQUIRE(decoded.image.width==20&&decoded.image.height==12&&result.preview.width==20&&result.preview.height==12);auto p=pixel(decoded.image,0,0);REQUIRE(p.a==255&&std::abs(int(p.r)-options.matteR)<8&&std::abs(int(p.g)-options.matteG)<8&&std::abs(int(p.b)-options.matteB)<8);REQUIRE(result.preview.pixels==decoded.image.pixels);metadata(target,ImageFormat::Jpeg);}
 auto target=path(temp,"partial.jpg"),old=path(temp,"old.jpg");RgbaImage rgba{40,23,160,std::vector<uint8_t>(40*23*4)};pattern()(0,23,rgba.pixels,160);ExportOptions options;options.format=ImageFormat::Jpeg;options.matteR=32;options.matteG=128;options.matteB=220;auto result=encodeRowsAtomic(target,40,23,pattern(),options);WicCodec::encode(old,rgba,options);REQUIRE(WicCodec::decode(target).image.pixels==WicCodec::decode(old).image.pixels&&result.preview.pixels==WicCodec::decode(target).image.pixels);}
void cancel_atomic(){QTemporaryDir temp;auto target=path(temp,"cancel.png");original(target);auto before=bytes(target);bool stop=false;ExportOptions options;options.cancelled=[&]{return stop;};int calls=0;bool wasCancelled=false;try{encodeRowsAtomic(target,50,200,[&](uint32_t,uint32_t,std::span<uint8_t> data,size_t){++calls;std::fill(data.begin(),data.end(),0);},options,{},[&](uint32_t,uint32_t){stop=true;});}catch(const ExportCancelled&){wasCancelled=true;}REQUIRE(wasCancelled&&calls==1&&bytes(target)==before);only(temp,1);}
void row_failure_atomic(){
 QTemporaryDir temp;auto target=path(temp,"failure.png");original(target);auto before=bytes(target);
 rejects([&]{encodeRowsAtomic(target,30,200,[](uint32_t y,uint32_t,std::span<uint8_t> data,size_t){if(y)throw std::runtime_error("injected row failure");std::fill(data.begin(),data.end(),0);});});REQUIRE(bytes(target)==before);
 rejects([&]{encodeRowsAtomic(target,1,1,[](uint32_t,uint32_t,std::span<uint8_t> data,size_t){data[0]=255;data[1]=data[2]=data[3]=0;});});REQUIRE(bytes(target)==before);
 for(auto format:{ImageFormat::Tiff,ImageFormat(999)}){ExportOptions option;option.format=format;rejects([&]{encodeRowsAtomic(target,10,10,pattern(),option);});}
 for(double dpi:{0.,-1.,std::numeric_limits<double>::infinity()}){ExportOptions option;option.dpi=dpi;rejects([&]{encodeRowsAtomic(target,10,10,pattern(),option);});}
 ExportOptions nan;nan.jpegQuality=std::numeric_limits<double>::quiet_NaN();rejects([&]{encodeRowsAtomic(target,10,10,pattern(),nan);});
 auto invalid=StreamExportLimits{};invalid.maxBufferBytes=10;rejects([&]{encodeRowsAtomic(target,10,10,pattern(),{},invalid);});
 auto directory=path(temp,"directory");std::filesystem::create_directory(directory);original(directory/"project.comp");auto protectedBytes=bytes(directory/"project.comp");
 rejects([&]{encodeRowsAtomic(directory,10,10,pattern());});REQUIRE(std::filesystem::is_directory(directory)&&bytes(directory/"project.comp")==protectedBytes&&bytes(target)==before);only(temp,2);
 // Empty image layers with masks still export transparency. A malformed live
 // effect must remain an error even though its input has no image pixels.
 auto empty=blank(19,17);Layer emptyLayer;emptyLayer.id=newId();emptyLayer.name="Empty masked layer";emptyLayer.mask=Mask{std::make_shared<GrayRaster>(GrayRaster{1,1,{128}})};empty.layers.push_back(emptyLayer);
 exportDocumentAtomic(empty,target);auto blankImage=WicCodec::decode(target);REQUIRE(std::all_of(blankImage.image.pixels.begin(),blankImage.image.pixels.end(),[](uint8_t value){return value==0;}));const auto savedBlank=bytes(target);
 empty.layers[0].adjustmentJson="{\"kind\":\"Unsupported test effect\"}";rejects([&]{exportDocumentAtomic(empty,target);});REQUIRE(bytes(target)==savedBlank);
 empty.layers[0].adjustmentJson.clear();empty.height=200;bool cancelledBlank=false;ExportOptions blankOptions;blankOptions.cancelled=[&]{return cancelledBlank;};rejects([&]{exportDocumentAtomic(empty,target,blankOptions,{},[&](uint32_t,uint32_t){cancelledBlank=true;});});REQUIRE(bytes(target)==savedBlank);only(temp,2);
}
void copy_atomic(){
 QTemporaryDir temp;auto source=path(temp,"source.bin"),target=path(temp,"target.bin");{std::ofstream out(source,std::ios::binary);std::vector<char> block(1024*1024,'a');for(int i=0;i<4;++i){block[0]=char(i);out.write(block.data(),std::streamsize(block.size()));}}original(target);auto before=bytes(target);
 int polls=0;bool stopped=false;try{copyEncodedAtomic(source,target,[&]{return ++polls==3;});}catch(const ExportCancelled&){stopped=true;}REQUIRE(stopped&&bytes(target)==before);only(temp,2);
 rejects([&]{copyEncodedAtomic(path(temp,"absent.bin"),target);});REQUIRE(bytes(target)==before);only(temp,2);
 auto directory=path(temp,"directory");std::filesystem::create_directory(directory);original(directory/"project.comp");auto protectedBytes=bytes(directory/"project.comp");
 rejects([&]{copyEncodedAtomic(directory,target);});rejects([&]{copyEncodedAtomic(source,directory);});REQUIRE(bytes(target)==before&&bytes(directory/"project.comp")==protectedBytes);only(temp,3);
 copyEncodedAtomic(source,target);REQUIRE(bytes(source)==bytes(target));only(temp,3);
}
void large(bool narrow){QTemporaryDir temp;auto d=blank(narrow?30000:10000,narrow?3333:10000);auto before=d;Raster::resetMaterializationCount();auto start=std::chrono::steady_clock::now();for(auto format:{ImageFormat::Png,ImageFormat::Jpeg}){ExportOptions options;options.format=format;auto file=path(temp,format==ImageFormat::Png?"large.png":"large.jpg");auto result=exportDocumentAtomic(d,file,options);REQUIRE(result.preview.width<=520&&result.preview.height<=320&&!result.preview.pixels.empty());REQUIRE(result.peakOwnedPixelBytes+result.maxRenderPixelBytes<64*1024*1024);auto p=pixel(result.preview,0,0);REQUIRE(p== (format==ImageFormat::Png?Pixel{}:Pixel{255,255,255,255}));metadata(file,format);std::cout<<"format="<<(format==ImageFormat::Png?"png":"jpeg")<<" width="<<d.width<<" height="<<d.height<<" bytes="<<result.encodedBytes<<" owned_pixel_bytes="<<result.peakOwnedPixelBytes<<" render_bound="<<result.maxRenderPixelBytes<<"\n";}PROCESS_MEMORY_COUNTERS_EX memory{};memory.cb=sizeof(memory);REQUIRE(GetProcessMemoryInfo(GetCurrentProcess(),reinterpret_cast<PROCESS_MEMORY_COUNTERS*>(&memory),sizeof(memory)));std::cout<<"peak_working_set="<<memory.PeakWorkingSetSize<<" peak_commit="<<memory.PeakPagefileUsage<<" elapsed_ms="<<std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now()-start).count()<<"\n";std::cout.flush();REQUIRE(memory.PeakWorkingSetSize<256*1024*1024&&memory.PeakPagefileUsage<256*1024*1024);REQUIRE(d==before&&Raster::materializationCount()==0);}
int main(int argc,char**argv){QCoreApplication app(argc,argv);const auto hr=CoInitializeEx(nullptr,COINIT_MULTITHREADED);try{REQUIRE(SUCCEEDED(hr));std::map<std::string,void(*)()> tests{{"extent_guard",extent_guard},{"row_png",row_png},{"canonical_partition",canonical_partition},{"jpeg_matte_preview",jpeg_matte_preview},{"cancel_atomic",cancel_atomic},{"row_failure_atomic",row_failure_atomic},{"copy_atomic",copy_atomic},{"large_blank",[]{large(false);}},{"large_narrow",[]{large(true);}}};REQUIRE(argc==2&&tests.contains(argv[1]));tests.at(argv[1])();std::cout<<"PASS "<<argv[1]<<"\n";CoUninitialize();return 0;}catch(const std::exception&e){std::cerr<<"FAIL "<<e.what()<<"\n";if(SUCCEEDED(hr))CoUninitialize();return 1;}}
