cmake_policy(SET CMP0054 NEW)
if(NOT DEFINED EXECUTABLE OR NOT DEFINED CASE OR NOT DEFINED EVIDENCE_ROOT)
  message(FATAL_ERROR "EXECUTABLE, CASE and EVIDENCE_ROOT are required")
endif()
string(TIMESTAMP stamp "%Y%m%d-%H%M%S" UTC)
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
set(directory "${EVIDENCE_ROOT}/${CASE}/${stamp}-${nonce}")
file(MAKE_DIRECTORY "${directory}")
if(OUTPUT_DIRECTORY)
  set(argument "${directory}/capture")
  set(report_path "${argument}/results.json")
else()
  set(argument "${directory}/result.json")
  set(report_path "${argument}")
endif()
if(NOT DEFINED WITNESS_TIMEOUT_SECONDS)
  set(WITNESS_TIMEOUT_SECONDS 60)
endif()
execute_process(COMMAND "${EXECUTABLE}" "${CASE}" "${argument}"
  RESULT_VARIABLE status OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT ${WITNESS_TIMEOUT_SECONDS})
file(WRITE "${directory}/stdout.log" "${stdout}")
file(WRITE "${directory}/stderr.log" "${stderr}")
message("${stdout}${stderr}")
if(NOT EXISTS "${report_path}")
  message(FATAL_ERROR "Witness report missing; process=${status}")
endif()
file(READ "${report_path}" report)
if(OUTPUT_DIRECTORY)
  string(JSON passed GET "${report}" passed)
else()
  string(JSON outcome GET "${report}" status)
  set(passed FALSE)
  if(outcome STREQUAL "passed")
    set(passed TRUE)
  endif()
endif()
message("WITNESS_REPORT ${report_path}")
if(NOT status EQUAL 0 OR NOT passed)
  message(FATAL_ERROR "Witness failed; process=${status}")
endif()

