if(NOT DEFINED EXECUTABLE OR NOT DEFINED CASE OR NOT DEFINED EVIDENCE_ROOT)
  message(FATAL_ERROR "EXECUTABLE, CASE and EVIDENCE_ROOT are required")
endif()
string(TIMESTAMP stamp "%Y%m%d-%H%M%S" UTC)
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
set(directory "${EVIDENCE_ROOT}/${CASE}/${stamp}-${nonce}")
file(MAKE_DIRECTORY "${directory}")
execute_process(COMMAND "${EXECUTABLE}" "${CASE}" "${directory}/result.json" RESULT_VARIABLE process_status OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 60)
file(WRITE "${directory}/stdout.log" "${stdout}")
file(WRITE "${directory}/stderr.log" "${stderr}")
message("${stdout}${stderr}")
if(NOT EXISTS "${directory}/result.json")
  message(FATAL_ERROR "Histogram report missing; process=${process_status}")
endif()
file(READ "${directory}/result.json" report)
string(JSON outcome GET "${report}" status)
string(JSON report_case GET "${report}" case)
message("HISTOGRAM_REPORT ${directory}/result.json")
if(NOT process_status EQUAL 0 OR NOT outcome STREQUAL "passed" OR NOT report_case STREQUAL CASE)
  message(FATAL_ERROR "Histogram case=${report_case} result=${outcome}, process=${process_status}")
endif()
string(JSON actual GET "${report}" actual)
string(JSON expected GET "${report}" expected)
string(JSON channels LENGTH "${actual}")
string(JSON differences GET "${report}" differing_bins)
if(NOT channels EQUAL 4 OR NOT differences EQUAL 0 OR NOT actual STREQUAL expected)
  message(FATAL_ERROR "Histogram output does not retain four exactly equal channels")
endif()
foreach(channel RANGE 0 3)
  string(JSON bins LENGTH "${actual}" ${channel})
  if(NOT bins EQUAL 256)
    message(FATAL_ERROR "Histogram channel must retain256 bins")
  endif()
endforeach()
