if(NOT DEFINED EXECUTABLE OR NOT DEFINED CASE OR NOT DEFINED EVIDENCE_ROOT)
  message(FATAL_ERROR "EXECUTABLE, CASE and EVIDENCE_ROOT are required")
endif()
set(cases combine modifiers_clip empty_distinct click_undo polygon antialias inverse_tool cursor move_undo offcanvas nudge resize_outline resize_empty mask_black mask_transform layer_alpha marquee_rectangle marquee_center marquee_ellipse option_event m_key fresh_shift l_key draft_press_guard)
set(counts 40 6 9 9 12 802 19 10 15 8 6 18 12 46 8 31 30 4 15 13 12 37 12 0)
list(FIND cases "${CASE}" index)
if(index LESS 0)
  message(FATAL_ERROR "Unknown source Selection case")
endif()
list(GET counts ${index} expected)
string(TIMESTAMP stamp "%Y%m%d-%H%M%S" UTC)
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
set(directory "${EVIDENCE_ROOT}/${CASE}/${stamp}-${nonce}")
file(MAKE_DIRECTORY "${directory}")
execute_process(COMMAND "${EXECUTABLE}" "${CASE}" "${directory}/result.json" RESULT_VARIABLE status OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 90)
file(WRITE "${directory}/stdout.log" "${stdout}")
file(WRITE "${directory}/stderr.log" "${stderr}")
message("${stdout}${stderr}")
if(NOT EXISTS "${directory}/result.json")
  message(FATAL_ERROR "Source scenario report missing; process=${status}")
endif()
file(READ "${directory}/result.json" report)
string(JSON outcome GET "${report}" status)
string(JSON count LENGTH "${report}" checks)
message("SOURCE_REPORT ${directory}/result.json checks=${count}")
if(CASE STREQUAL "draft_press_guard")
  string(JSON native_count LENGTH "${report}" native_checks)
  string(JSON native_failures GET "${report}" native_failures)
  if(NOT native_count EQUAL 10 OR NOT native_failures EQUAL 0)
    message(FATAL_ERROR "Native draft-press contract failed or incomplete")
  endif()
endif()
if(NOT status EQUAL 0 OR NOT outcome STREQUAL "passed" OR NOT count EQUAL expected)
  message(FATAL_ERROR "Source scenario result=${outcome}, process=${status}, checks=${count}/${expected}")
endif()
