#include "ui/MainWindow.h"
#include "ui/LayerPanel.h"
#include "ui/ImportActions.h"
#include <QApplication>
#include <QDockWidget>
#include <QDragEnterEvent>
#include <QDropEvent>
#include <QImage>
#include <QMessageBox>
#include <QMimeData>
#include <QTabBar>
#include <QTemporaryDir>
#include <QTest>
#include <QTimer>
#include <QUrl>
#include <iostream>
#include <map>

using namespace compositor;
namespace {
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
Document sample(){Document d;d.id=newId();d.width=100;d.height=80;Layer layer;layer.id=newId();layer.name="Subject";layer.transform={8,10,20,12};layer.raster=Raster::filled(20,12,{100,20,10,255});auto mask=std::make_shared<GrayRaster>();mask->width=2;mask->height=2;mask->pixels={255,128,64,0};layer.mask=Mask{mask};layer.mask->placement=Transform{7,9,20,12};layer.mask->linked=false;d.layers={layer};return d;}
QAction* command(MainWindow& window,const char* id){for(auto* action:window.findChildren<QAction*>())if(action->property("commandId").toString()==id)return action;throw std::runtime_error("missing command");}
struct Fixture {
    MainWindow window{true};EditorProject *source{},*target{};QTemporaryDir directory;QString image;QStringList errors;QTimer dismiss;
    explicit Fixture(bool sameIds=false,bool group=false){
        require(directory.isValid(),"temporary image directory");image=directory.filePath("Dropped.png");QImage bitmap(7,5,QImage::Format_RGBA8888);bitmap.fill(QColor(Qt::green));require(bitmap.save(image,"PNG"),"image fixture");auto d=sample();
        if(group){Layer folder;folder.id=newId();folder.name="Folder";folder.group=true;folder.transform={4,6,40,24};d.layers[0].parentId=folder.id;Layer clipped=d.layers[0];clipped.id=newId();clipped.name="Clipped";clipped.maskSourceId=d.layers[0].id;d.layers.insert(d.layers.begin(),folder);d.layers.push_back(clipped);}
        source=&window.addProject(d,"Duplicate title");target=&window.addProject(sameIds?d:sample(),"Duplicate title");tabs()->setCurrentIndex(0);
        if(group){source->active=d.layers.front().id;source->selected={source->active};panel()->rebuild();}
        window.show();QApplication::processEvents();dismiss.setInterval(5);QObject::connect(&dismiss,&QTimer::timeout,&window,[this]{for(auto* message:window.findChildren<QMessageBox*>())if(message->isVisible()){errors.append(message->text());message->accept();}});dismiss.start();
    }
    QTabWidget* tabs(){return window.findChild<QTabWidget*>();}
    ui::LayerPanelController* panel(){return ui::LayerPanelController::find(window.findChild<QTreeWidget*>("layersTree"));}
    QPoint tab(int index){return tabs()->tabBar()->mapTo(&window,tabs()->tabBar()->tabRect(index).center());}
    QPoint canvas(EditorProject& p,QPointF documentPoint){const auto view=p.canvas->viewMapping().toView({documentPoint.x(),documentPoint.y()});return p.canvas->mapTo(&window,QPointF(view.x,view.y).toPoint());}
    std::unique_ptr<QMimeData> mime(bool mask=false){return std::unique_ptr<QMimeData>(panel()->dragMime(mask));}
    bool drop(const QMimeData* data,QPoint point,Qt::KeyboardModifiers modifiers={}){QDragEnterEvent enter(point,Qt::CopyAction|Qt::MoveAction,data,Qt::LeftButton,modifiers);QApplication::sendEvent(&window,&enter);if(!enter.isAccepted())return false;QDropEvent event(point,Qt::CopyAction|Qt::MoveAction,data,Qt::LeftButton,modifiers);QApplication::sendEvent(&window,&event);return event.isAccepted();}
    void finish(){QElapsedTimer elapsed;elapsed.start();for(;;){QTest::qWait(5);auto* imports=ui::ImportQueue::find(&window);if((!imports||imports->idle())&&!window.findChild<QObject*>("projectLayerCopyJob"))break;if(elapsed.elapsed()>10000)throw std::runtime_error("drop did not complete");}QApplication::processEvents();}
    void fileAt(QWidget* widget){QMimeData data;data.setUrls({QUrl::fromLocalFile(image)});require(drop(&data,widget->mapTo(&window,widget->rect().center())),"file drop accepted");finish();require(tabs()->count()==2&&tabs()->currentIndex()==0&&source->document->layers.size()==2&&target->document->layers.size()==1,"editor drop must add to current project, not create a tab");const auto& layer=source->document->layers.back();require(layer.transform.x==46&&layer.transform.y==37&&source->history.undoCount()==1,"outside-canvas import uses canvas center and one edit");}
};
void dock_file_targets_current(){Fixture f;f.fileAt(f.window.findChild<QComboBox*>("layerBlend"));}
void toolbox_file_targets_current(){Fixture f;f.fileAt(f.window.findChild<QToolBar*>("tools"));}
void layer_existing_tab_copy(){Fixture f;const auto original=f.source->document;auto data=f.mime();require(f.drop(data.get(),f.tab(1)),"layer drop onto existing tab accepted");f.finish();require(f.tabs()->count()==2&&f.tabs()->currentIndex()==1&&f.source->document==original&&f.source->history.undoCount()==0,"source document/history preserved and destination selected");require(f.target->document->layers.size()==2&&f.target->history.undoCount()==1&&f.target->history.undoName()=="Copy Layers from Project","copy records exactly one destination edit");const auto& copied=f.target->document->layers.back();require(copied.id!=original->layers[0].id&&copied.raster==original->layers[0].raster&&copied.mask->raster==original->layers[0].mask->raster,"copy remaps identity while sharing immutable pixels");require(copied.transform.x==40&&copied.transform.y==34&&copied.mask->placement->x==39&&copied.mask->placement->y==33,"default center offsets image and unlinked mask together");command(f.window,"edit.undo")->trigger();require(f.target->document->layers.size()==1&&f.source->document==original,"destination undo does not affect source");}
void layer_new_target_copy(){Fixture f;auto data=f.mime();require(f.drop(data.get(),QPoint(1,1)),"layer new-project drop accepted");f.finish();require(f.tabs()->count()==3&&f.tabs()->currentIndex()==2,"new layer drop creates/selects a fresh tab");auto* tree=f.window.findChild<QTreeWidget*>("layersTree");require(tree->topLevelItemCount()==2&&f.source->history.undoCount()==0&&f.target->history.undoCount()==0,"new project has source blank layer plus copied layer and independent source histories");command(f.window,"edit.undo")->trigger();require(f.window.findChild<QWidget*>("newCanvasWelcome")->isVisible()||tree->topLevelItemCount()==0,"one undo returns new target to empty session");}
void layer_canvas_point(){Fixture f;auto data=f.mime();f.tabs()->setCurrentIndex(1);QApplication::processEvents();const auto point=f.canvas(*f.target,{31,27});const auto documentPoint=f.target->canvas->documentPoint(f.target->canvas->mapFrom(&f.window,point));require(f.drop(data.get(),point),"layer canvas drop accepted");f.finish();const auto& copied=f.target->document->layers.back();require(f.target->document->layers.size()==2&&std::abs(copied.transform.x-(documentPoint.x()-10))<1e-9&&std::abs(copied.transform.y-(documentPoint.y()-6))<1e-9,"copied root center follows exact converted canvas point (1e-9 arithmetic tolerance)");}
void layer_group_graph_and_mask(){Fixture f(false,true);const auto before=f.source->document;auto data=f.mime();require(f.drop(data.get(),f.tab(1)),"folder drag accepted across projects");f.finish();require(f.target->document->layers.size()==4&&f.source->document==before&&f.target->history.undoCount()==1,"folder and both descendants copied in one edit");const auto& copied=f.target->document->layers;require(copied[1].group&&copied[2].parentId==copied[1].id&&copied[3].parentId==copied[1].id&&copied[3].maskSourceId==copied[2].id,"folder and internal clipping identities remapped together");require(copied[2].mask->raster==before->layers[1].mask->raster&&copied[2].mask->placement->x-before->layers[1].mask->placement->x==26&&copied[2].mask->placement->y-before->layers[1].mask->placement->y==22,"folder anchor offsets explicit mask placement");}
void layer_same_project_rejected(){Fixture f;auto data=f.mime();const auto before=f.source->document;require(!f.drop(data.get(),f.tab(0))&&!f.drop(data.get(),f.canvas(*f.source,{50,40})),"same-project layer drops rejected");f.finish();require(f.source->document==before&&f.source->history.undoCount()==0,"same-project rejection is a no-op");}
void layer_alt_and_mask_rejected(){Fixture f;auto data=f.mime();auto mask=f.mime(true);require(!f.drop(data.get(),f.tab(1),Qt::AltModifier)&&!f.drop(mask.get(),f.tab(1)),"Alt layer duplication and mask-copy drags do not become cross-project copies");f.finish();require(f.target->document->layers.size()==1&&f.target->history.undoCount()==0,"rejected internal drags preserve destination");}
void layer_source_destroyed_rejected(){Fixture f;auto data=f.mime();f.tabs()->tabCloseRequested(0);f.source=nullptr;QCoreApplication::sendPostedEvents(nullptr,QEvent::DeferredDelete);require(f.tabs()->count()==1&&!f.drop(data.get(),f.tab(0)),"stale source session cannot be copied");f.finish();require(f.target->document->layers.size()==1&&f.target->history.undoCount()==0,"stale MIME leaves destination untouched");}
void layer_target_busy_rejected(){Fixture f;auto data=f.mime();f.target->projectBusy=true;require(!f.drop(data.get(),f.tab(1)),"busy target rejects cross-project drag");f.target->projectBusy=false;f.finish();require(f.target->document->layers.size()==1&&f.target->history.undoCount()==0,"busy rejection preserves target");}
void layer_pending_gradient_rejected(){Fixture f;auto data=f.mime();command(f.window,"tool.gradient")->trigger();f.source->canvas->pointerDown({5,20},{});f.source->canvas->pointerMove({55,20},{});f.source->canvas->pointerUp({55,20},{});require(command(f.window,"gradient.apply")->isEnabled(),"pending gradient fixture");require(!f.drop(data.get(),f.tab(1)),"pending source rejects layer drag");require(command(f.window,"gradient.apply")->isEnabled()&&f.source->history.undoCount()==0&&f.target->history.undoCount()==0,"rejection leaves draft and histories unchanged");}
void layer_duplicate_document_ids(){Fixture f(true);auto data=f.mime();require(f.drop(data.get(),f.tab(1)),"distinct sessions with duplicate document/layer IDs can copy");f.finish();require(f.source->document->layers.size()==1&&f.source->history.undoCount()==0&&f.target->document->layers.size()==2&&f.target->history.undoCount()==1,"session identity selects correct source/destination despite duplicate titles and saved IDs");}
#ifdef PROJECT_LAYER_DROP_AFTER
void selectTwo(Fixture& f){auto top=f.source->document->layers[0];top.id=newId();top.name="Top";f.source->document->layers.push_back(top);f.source->active=top.id;f.source->selected={f.source->document->layers[0].id,top.id};f.panel()->rebuild();}
void multiple_rows_keep_order_and_edits(){Fixture f;selectTwo(f);auto data=f.mime();require(f.drop(data.get(),f.tab(1)),"multi-row layer drop accepted");f.finish();require(f.target->document->layers.size()==3&&f.target->document->layers[1].name=="Top"&&f.target->document->layers[2].name=="Subject"&&f.target->history.undoCount()==2,"provider visual order retained with one edit per row");command(f.window,"edit.undo")->trigger();require(f.target->document->layers.size()==2&&f.target->document->layers.back().name=="Top","first undo removes last provider only");command(f.window,"edit.undo")->trigger();require(f.target->document->layers.size()==1&&f.source->document->layers.size()==2&&f.source->history.undoCount()==0,"second undo preserves independent source");}
void multiple_rows_new_projects(){Fixture f;selectTwo(f);auto data=f.mime();auto* slot=f.window.findChild<QWidget*>("newProjectDropTarget");require(slot&&slot->isVisible(),"discoverable new-project drop target exists");require(f.drop(data.get(),slot->mapTo(&f.window,slot->rect().center())),"multi-row new-project drop accepted");f.finish();require(f.tabs()->count()==4&&f.tabs()->currentIndex()==3,"each layer provider creates its own new project");auto* tree=f.window.findChild<QTreeWidget*>("layersTree");require(tree->topLevelItemCount()==2&&tree->topLevelItem(0)->text(0)=="Subject","last new project contains last provider and blank initial layer");f.tabs()->setCurrentIndex(2);require(tree->topLevelItemCount()==2&&tree->topLevelItem(0)->text(0)=="Top","first new project contains first visual provider");}
void serialized_mime_retains_session_identity(){Fixture f;auto data=f.mime();QMimeData serialized;for(const auto& format:data->formats())serialized.setData(format,data->data(format));data.reset();require(f.drop(&serialized,f.tab(1)),"serialized native MIME envelope resolves source session");f.finish();require(f.source->document->layers.size()==1&&f.target->document->layers.size()==2&&f.target->history.undoCount()==1,"serialized drag preserves source identity and destination edit");}
void removed_source_layer_rejected(){Fixture f;auto data=f.mime();f.source->document->layers.clear();f.source->active.clear();f.source->selected.clear();require(!f.drop(data.get(),f.tab(1)),"removed provider layer rejected before work starts");f.finish();require(f.target->document->layers.size()==1&&f.target->history.undoCount()==0,"removed layer cannot modify destination");}
void external_clipping_is_baked(){Fixture f;auto& base=f.source->document->layers[0];base.mask.reset();base.raster=Raster::filled(20,12,{128,0,0,128});auto clipped=base;clipped.id=newId();clipped.name="Clipped";clipped.raster=Raster::filled(20,12,{0,100,0,255});clipped.maskSourceId=base.id;f.source->document->layers.push_back(clipped);f.source->active=clipped.id;f.source->selected={clipped.id};f.panel()->rebuild();const auto before=f.source->document;auto data=f.mime();require(f.drop(data.get(),f.tab(1)),"externally clipped layer drag accepted");f.finish();const auto& copied=f.target->document->layers.back();require(copied.maskSourceId.empty()&&copied.raster->pixel(10,6)==Pixel{0,50,0,128},"external source dependency baked into exact premultiplied pixel");require(f.source->document==before&&f.target->history.undoCount()==1,"dependency bake leaves source unchanged and commits once");}
void destroyed_window_stops_layer_job(){auto f=std::make_unique<Fixture>();auto data=f->mime();require(f->drop(data.get(),f->tab(1)),"owned layer job accepted");QPointer<QObject> job=f->window.findChild<QObject*>("projectLayerCopyJob");require(job,"layer worker owner exists before dispatch");QCoreApplication::sendPostedEvents(job,QEvent::MetaCall);f.reset();require(job.isNull(),"window destroys layer worker before project members");QTest::qWait(50);}
#endif
}
int main(int argc,char** argv){QApplication app(argc,argv);std::cout<<std::unitbuf;const std::map<std::string,void(*)()> cases{{"dock_file_targets_current",dock_file_targets_current},{"toolbox_file_targets_current",toolbox_file_targets_current},{"layer_existing_tab_copy",layer_existing_tab_copy},{"layer_new_target_copy",layer_new_target_copy},{"layer_canvas_point",layer_canvas_point},{"layer_group_graph_and_mask",layer_group_graph_and_mask},{"layer_same_project_rejected",layer_same_project_rejected},{"layer_alt_and_mask_rejected",layer_alt_and_mask_rejected},{"layer_source_destroyed_rejected",layer_source_destroyed_rejected},{"layer_target_busy_rejected",layer_target_busy_rejected},{"layer_pending_gradient_rejected",layer_pending_gradient_rejected},{"layer_duplicate_document_ids",layer_duplicate_document_ids}
#ifdef PROJECT_LAYER_DROP_AFTER
,{"multiple_rows_keep_order_and_edits",multiple_rows_keep_order_and_edits},{"multiple_rows_new_projects",multiple_rows_new_projects},{"serialized_mime_retains_session_identity",serialized_mime_retains_session_identity},{"removed_source_layer_rejected",removed_source_layer_rejected},{"external_clipping_is_baked",external_clipping_is_baked},{"destroyed_window_stops_layer_job",destroyed_window_stops_layer_job}
#endif
};try{require(argc==2&&cases.contains(argv[1]),"provide named layer-drop case");std::cout<<"START "<<argv[1]<<'\n';cases.at(argv[1])();std::cout<<"PASS "<<argv[1]<<'\n';return 0;}catch(const std::exception& error){std::cerr<<"FAIL "<<error.what()<<'\n';return 1;}}
