#include "persistence/ProjectStore.h"
#include <QCoreApplication>
#include <QFile>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QTemporaryDir>
#include <Windows.h>
#include <winioctl.h>
#include <fstream>
#include <iostream>
#include <stdexcept>
using namespace compositor;
namespace fs=std::filesystem;
void check(bool condition,const char* message){if(!condition)throw std::runtime_error(message);}
template<class F>void rejects(F f){bool rejected=false;try{f();}catch(const std::exception&){rejected=true;}check(rejected,"Expected rejection");}
QString q(const fs::path&p){return QString::fromStdWString(p.wstring());}
void write(const fs::path&p,const QByteArray&data){QFile f(q(p));check(f.open(QIODevice::WriteOnly),"Cannot write fixture");check(f.write(data)==data.size(),"Fixture write failed");}
QByteArray read(const fs::path&p){QFile f(q(p));check(f.open(QIODevice::ReadOnly),"Cannot read fixture");return f.readAll();}
QJsonObject json(const fs::path&p){return QJsonDocument::fromJson(read(p)).object();}
void json(const fs::path&p,const QJsonObject&o){write(p,QJsonDocument(o).toJson());}
std::string id(int i){char b[37];std::snprintf(b,sizeof b,"00000000-0000-4000-8000-%012d",i);return b;}
Document blank(){Document d;d.id=id(1);d.width=19;d.height=17;d.resolution=144;Layer l;l.id=id(2);l.name="Paint & sky \xF0\x9F\x8C\xA4";l.transform={-2.25,3.5,17,13,38,true,false,Transform::Sampling::Nearest};d.layers.push_back(l);return d;}
// Test-only codec: an IHDR-shaped header followed by raw bytes. It deliberately does not
// masquerade as production PNG/WIC verification; it exercises persistence independently.
QByteArray header(int w,int h,bool gray){QByteArray a(33,0);const unsigned char sig[]{137,80,78,71,13,10,26,10};for(int i=0;i<8;++i)a[i]=char(sig[i]);a[11]=13;a.replace(12,4,"IHDR");for(int i=0;i<4;++i){a[16+i]=char(uint32_t(w)>>(24-i*8));a[20+i]=char(uint32_t(h)>>(24-i*8));}a[24]=8;a[25]=gray?0:6;return a;}
int sizeAt(const QByteArray&a,int i){return int((uint32_t(uint8_t(a[i]))<<24)|(uint32_t(uint8_t(a[i+1]))<<16)|(uint32_t(uint8_t(a[i+2]))<<8)|uint8_t(a[i+3]));}
ProjectAssetCodec codec(int* reads=nullptr){ProjectAssetCodec c;
 c.readColor=[reads](const fs::path&p){if(reads)++*reads;auto a=read(p);int w=sizeAt(a,16),h=sizeAt(a,20);check(a.size()==33+qsizetype(w)*h*4,"Invalid mock color payload");return Raster::fromRgba(w,h,reinterpret_cast<const uint8_t*>(a.constData()+33),size_t(w)*4);};
 c.readGray=[reads](const fs::path&p){if(reads)++*reads;auto a=read(p);auto r=std::make_shared<GrayRaster>();r->width=sizeAt(a,16);r->height=sizeAt(a,20);check(a.size()==33+qsizetype(r->width)*r->height,"Invalid mock gray payload");r->pixels.assign(a.constData()+33,a.constData()+a.size());return std::shared_ptr<const GrayRaster>(r);};
 c.writeColor=[](const fs::path&p,const Raster&r){auto a=header(r.width,r.height,false);auto b=r.rgba();a.append(reinterpret_cast<const char*>(b.data()),qsizetype(b.size()));write(p,a);};
 c.writeGray=[](const fs::path&p,const GrayRaster&r){auto a=header(r.width,r.height,true);a.append(reinterpret_cast<const char*>(r.pixels.data()),qsizetype(r.pixels.size()));write(p,a);};return c;}
void mutate(const fs::path&p,const std::function<void(QJsonObject&)>&f){auto o=json(p/L"manifest.json");f(o);json(p/L"manifest.json",o);}
void mutateLayer(const fs::path&p,const std::function<void(QJsonObject&)>&f){mutate(p,[&](QJsonObject&o){auto a=o["layers"].toArray();auto l=a[0].toObject();f(l);a[0]=l;o["layers"]=a;});}
fs::path suffix(const fs::path&p,const std::string&s){return p.parent_path()/(p.filename().string()+s);}
void journal(const fs::path&p,const std::string&tx,const std::string&phase,bool original){json(suffix(p,".compositor-save.json"),{{"transaction",QString::fromStdString(tx)},{"target",q(p.filename())},{"stage",q(suffix(p,".stage-"+tx).filename())},{"backup",q(suffix(p,".backup-"+tx).filename())},{"phase",QString::fromStdString(phase)},{"hadOriginal",original}});}
bool junction(const fs::path&link,const fs::path&target){fs::create_directory(link);std::wstring substitute=L"\\??\\"+target.wstring(),printed=target.wstring();struct Buffer{DWORD tag;WORD length,reserved,subOffset,subLength,printOffset,printLength;WCHAR path[2048];}b{};b.tag=IO_REPARSE_TAG_MOUNT_POINT;b.subLength=WORD(substitute.size()*sizeof(WCHAR));b.printOffset=WORD(b.subLength+sizeof(WCHAR));b.printLength=WORD(printed.size()*sizeof(WCHAR));b.length=WORD(8+b.printOffset+b.printLength+sizeof(WCHAR));std::copy(substitute.begin(),substitute.end(),b.path);std::copy(printed.begin(),printed.end(),b.path+substitute.size()+1);auto handle=CreateFileW(link.c_str(),GENERIC_WRITE,0,nullptr,OPEN_EXISTING,FILE_FLAG_OPEN_REPARSE_POINT|FILE_FLAG_BACKUP_SEMANTICS,nullptr);if(handle==INVALID_HANDLE_VALUE){fs::remove(link);return false;}DWORD returned=0;bool ok=DeviceIoControl(handle,FSCTL_SET_REPARSE_POINT,&b,b.length+8,nullptr,0,&returned,nullptr)!=0;CloseHandle(handle);if(!ok)fs::remove(link);return ok;}
int main(int argc,char**argv){QCoreApplication app(argc,argv);try{check(argc==2,"Need case name");std::string test=argv[1];QTemporaryDir temp;check(temp.isValid(),"Temp directory unavailable");fs::path root(temp.path().toStdWString());auto p=root/L"Test.comp";ProjectStore store(codec());auto d=blank();
 if(test=="blank_roundtrip"){d.selection=Selection{std::make_shared<GrayRaster>(GrayRaster{1,1,{0}})};store.save(p,d,id(2));auto result=store.load(p);check(result.readVersion==7&&result.document.id==d.id&&result.activeLayer==id(2),"Identity lost");check(result.document.layers[0].transform==d.layers[0].transform,"Fractional transform lost");check(!result.document.selection&&result.document.layers[0].name==d.layers[0].name,"Session state or Unicode contract broken");auto m=json(p/L"manifest.json");check(m["version"]==7&&m["layers"].toArray()[0].toObject()["transform"].toObject()["origin"].isArray(),"Wrong wire shape");}
 else if(test=="raster_mask_roundtrip"){d.layers[0].raster=Raster::filled(17,13,{16,32,48,64});auto gray=std::make_shared<GrayRaster>(GrayRaster{3,2,{0,64,128,192,254,255}});d.layers[0].mask=Mask{gray,false,false,d.layers[0].transform};d.layers[0].opacity=.625;d.layers[0].blend=Blend::Luminosity;store.save(p,d,id(2));auto r=store.load(p).document.layers[0];check(r.raster->rgba()==d.layers[0].raster->rgba(),"Raster changed");check(r.mask->raster->pixels==gray->pixels&&!r.mask->enabled&&!r.mask->linked&&r.mask->placement==d.layers[0].mask->placement,"Mask contract lost");check(r.opacity==.625&&r.blend==Blend::Luminosity,"Appearance lost");d.layers[0].raster.reset();d.layers[0].mask.reset();store.save(p,d,id(2));check(fs::is_empty(p/L"images"),"Removed assets retained");}
 else if(test=="legacy_version_gates"){for(int version=1;version<=7;++version){store.save(p,d,id(2));mutate(p,[&](auto&o){o["version"]=version;o.remove("resolution");auto a=o["layers"].toArray();auto l=a[0].toObject();for(const char*k:{"opacity","blendMode","isGroup"})l.remove(k);a[0]=l;o["layers"]=a;});auto r=store.load(p);check(r.readVersion==version&&r.document.resolution==72&&r.document.layers[0].opacity==1,"Legacy default wrong");}store.save(p,d,id(2));mutate(p,[](auto&o){o["version"]=2;});mutateLayer(p,[](auto&l){l["opacity"]=.5;});rejects([&]{store.load(p);});store.save(p,d,id(2));mutate(p,[](auto&o){o["version"]=1;});mutateLayer(p,[](auto&l){l["isGroup"]=true;});rejects([&]{store.load(p);});}
 else if(test=="malformed_metadata"){for(const char*k:{"format","version","colorSpace","width","documentID","layers"}){store.save(p,d,id(2));mutate(p,[&](auto&o){o.remove(k);});rejects([&]{store.load(p);});}for(const char*k:{"rotation","flipX","flipY","sampling","origin","size"}){store.save(p,d,id(2));mutateLayer(p,[&](auto&l){auto t=l["transform"].toObject();t.remove(k);l["transform"]=t;});rejects([&]{store.load(p);});}store.save(p,d,id(2));mutateLayer(p,[](auto&l){l["imageFile"]="../../outside.png";});rejects([&]{store.load(p);});store.save(p,d,id(2));mutateLayer(p,[](auto&l){l["name"]="  \n";});rejects([&]{store.load(p);});store.save(p,d,id(2));mutateLayer(p,[](auto&l){l["isVisible"]=1;});rejects([&]{store.load(p);});}
 else if(test=="graph_boundaries"){Document tree=d;tree.layers.clear();for(int i=0;i<64;++i){Layer l;l.id=id(100+i);l.group=true;if(i)l.parentId=id(99+i);tree.layers.push_back(l);}Layer leaf;leaf.id=id(999);leaf.parentId=id(163);tree.layers.push_back(leaf);store.save(p,tree,leaf.id);check(store.load(p).document.layers.size()==65,"Valid depth64 leaf rejected");tree.layers.back().group=true;rejects([&]{store.save(p,tree,leaf.id);});Document chain=d;chain.layers.clear();for(int i=0;i<256;++i){Layer l;l.id=id(100+i);if(i<255)l.maskSourceId=id(101+i);chain.layers.push_back(l);}store.save(p,chain,id(100));check(store.load(p).document.layers.size()==256,"Valid 256-node chain rejected");chain.layers.back().maskSourceId=chain.layers.front().id;rejects([&]{store.save(p,chain,id(100));});chain.layers.back().maskSourceId=id(800);Layer extra;extra.id=id(800);chain.layers.push_back(extra);rejects([&]{store.save(p,chain,id(100));});chain.layers.resize(2);chain.layers[0].maskSourceId=chain.layers[1].id;chain.layers[1].maskSourceId.clear();chain.layers[1].group=true;rejects([&]{store.save(p,chain,id(100));});}
 else if(test=="rollback_faults"){for(auto point:{SaveFaultPoint::AfterStage,SaveFaultPoint::AfterJournal,SaveFaultPoint::AfterBackup,SaveFaultPoint::AfterInstall,SaveFaultPoint::BeforeCleanup}){store.save(p,d,id(2));auto before=read(p/L"manifest.json");auto changed=d;changed.layers[0].name="Edited";ProjectStore faults(codec(),[&](auto actual){if(actual==point)throw std::runtime_error("injected");});rejects([&]{faults.save(p,changed,id(2));});check(read(p/L"manifest.json")==before,"Failed save changed prior project");check(!fs::exists(suffix(p,".compositor-save.json")),"Rollback left journal");for(auto&e:fs::directory_iterator(root))check(e.path()==p,"Rollback leaked staging files");}}
 else if(test=="crash_recovery"){store.save(p,d,id(2));std::string tx=id(700);auto stage=suffix(p,".stage-"+tx),backup=suffix(p,".backup-"+tx);auto changed=d;changed.layers[0].name="Edited";store.save(stage,changed,id(2));write(stage/L".compositor-transaction",QByteArray::fromStdString(tx));journal(p,tx,"backed_up",true);fs::rename(p,backup);store.recover(p);check(store.load(p).document.layers[0].name==d.layers[0].name,"Missing-target recovery did not restore original");store.save(stage,changed,id(2));write(stage/L".compositor-transaction",QByteArray::fromStdString(tx));fs::rename(p,backup);fs::rename(stage,p);journal(p,tx,"installed",true);store.recover(p);check(store.load(p).document.layers[0].name=="Edited"&&!fs::exists(backup),"Installed recovery failed");}
 else if(test=="allocation_preflight"){d.layers[0].raster=Raster::filled(1,1,{0,0,0,0});store.save(p,d,id(2));write(p/L"images"/fs::path(id(2)+".png"),header(30000,4000,false));int reads=0;ProjectStore guarded(codec(&reads));rejects([&]{guarded.load(p);});check(reads==0,"Oversized image reached decoder");}
 else if(test=="hostile_journal"){store.save(p,d,id(2));auto before=read(p/L"manifest.json");journal(p,id(700),"prepared",true);auto f=suffix(p,".compositor-save.json");auto j=json(f);j["stage"]="../unrelated";json(f,j);rejects([&]{store.recover(p);});check(read(p/L"manifest.json")==before&&fs::exists(f),"Unsafe journal mutated project");}
 else if(test=="reparse_rejection"){store.save(p,d,id(2));auto link=root/L"Link.comp";if(!CreateSymbolicLinkW(link.c_str(),p.c_str(),SYMBOLIC_LINK_FLAG_DIRECTORY|0x2)&&!junction(link,p)){std::cout<<"SKIP: symbolic link and junction creation unavailable\n";return 77;}rejects([&]{store.load(link);});fs::remove(link);}
 else if(test=="real_png_exchange"){ProjectStore actual(makeWicProjectCodec());d.layers[0].raster=Raster::filled(17,13,{16,32,48,64});auto gray=std::make_shared<GrayRaster>(GrayRaster{3,2,{0,64,128,192,254,255}});d.layers[0].mask=Mask{gray,false,false,d.layers[0].transform};actual.save(p,d,id(2));auto result=actual.load(p);check(result.document.layers[0].raster->rgba()==d.layers[0].raster->rgba(),"WIC project pixels changed");check(result.document.layers[0].mask->raster->pixels==gray->pixels,"WIC mask coverage changed");auto encoded=read(p/L"images"/fs::path(id(2)+".mask.png"));check(encoded.size()>33&&encoded[24]==8&&encoded[25]==0,"Mask PNG is not gray8");}
 else throw std::runtime_error("Unknown test");std::cout<<"PASS "<<test<<"\n";return 0;
 }catch(const std::exception&e){std::cerr<<"FAIL "<<e.what()<<"\n";return 1;}}
