#include "ui/DocumentPreview.h"
#include "ui/AdjustmentDialog.h"
#include "effects/Adjustments.h"
#include <QApplication>
#include <QDialog>
#include <QDialogButtonBox>
#include <QElapsedTimer>
#include <QJsonDocument>
#include <QJsonObject>
#include <QLabel>
#include <QPushButton>
#include <QTimer>
#include <iostream>
#include <map>
#include <limits>
#include <stdexcept>
using namespace compositor;
#define REQUIRE(...) do{if(!(__VA_ARGS__))throw std::runtime_error(std::string("line ")+std::to_string(__LINE__)+": " #__VA_ARGS__);}while(false)
Document fixture(int w=30000,int h=30000){Document d;d.id="preview";d.width=w;d.height=h;Layer l;l.id="image";l.raster=Raster::filled(32,16,{70,180,120,255});l.transform={double(w/2-16),double(h/2-8),32,16};d.layers.push_back(l);return d;}
void fitted_geometry(){auto d=fixture(30000,20000);d.layers[0].transform={0,0,30000,20000};auto image=fittedDocumentPreview(d,{600,460});REQUIRE(image.size()==QSize(600,400)&&image.sizeInBytes()==960000);REQUIRE(image.pixelColor(0,0)==QColor(70,180,120,255)&&image.pixelColor(599,399)==QColor(70,180,120,255));auto skinny=fixture(30000,1);skinny.layers[0].transform={0,0,30000,1};auto row=fittedDocumentPreview(skinny,{600,460});REQUIRE(row.size()==QSize(600,1)&&row.pixelColor(599,0)==QColor(70,180,120,255));}
void small_thumbnail_identity(){auto d=fixture(32,16);auto image=fittedDocumentPreview(d,{640,420});REQUIRE(image.size()==QSize(640,320));REQUIRE(image.pixelColor(0,0)==QColor(70,180,120,255)&&image.pixelColor(639,319)==QColor(70,180,120,255));}
void histogram_small_source_budget(){auto d=fixture();DocumentHistogramStats stats;Raster::resetMaterializationCount();auto bins=documentLevelsHistogram(d,{},&stats);REQUIRE(bins[1][70]==512&&bins[2][180]==512&&bins[3][120]==512);REQUIRE(stats.maxTilePixels==65536&&stats.renderedPixels<=262144&&stats.skippedTiles>13000);REQUIRE(Raster::materializationCount()==0);std::cout<<"histogram rendered_pixels="<<stats.renderedPixels<<" max_tile_pixels="<<stats.maxTilePixels<<" skipped_tiles="<<stats.skippedTiles<<'\n';}
std::shared_ptr<const Raster> patterned(int w,int h){std::vector<uint8_t> bytes(size_t(w)*h*4);for(int y=0;y<h;++y)for(int x=0;x<w;++x){auto i=(size_t(y)*w+x)*4;const int a=(x*11+y*13)%256;bytes[i]=uint8_t((x%256)*a/255);bytes[i+1]=uint8_t((y%256)*a/255);bytes[i+2]=uint8_t(((x+y)%256)*a/255);bytes[i+3]=uint8_t(a);}return Raster::fromRgba(w,h,bytes.data(),size_t(w)*4);}
void compareHistogram(const Document&d){auto full=SoftwareRenderer().render(d,0,0,d.width,d.height);const auto expected=effects_tools::levelsHistogram(*full);REQUIRE(documentLevelsHistogram(d)==expected);}
void histogram_full_tile_order(){auto d=fixture(513,519);d.layers[0].raster=patterned(513,519);d.layers[0].transform={0,0,513,519};compareHistogram(d);}
void histogram_rotated_reduced_alignment(){auto d=fixture(701,523);auto source=std::make_shared<Raster>(*patterned(517,263));source->samplingOriginX=-7;source->samplingOriginY=5;d.layers[0].raster=source;d.layers[0].transform={251.25,241.75,127,70,27,true,false,Transform::Sampling::High};compareHistogram(d);}
void histogram_masks_clips_adjustment(){auto d=fixture(517,519);Layer group;group.id="folder";group.group=true;group.transform={0,0,517,519};group.mask=Mask{std::make_shared<GrayRaster>(GrayRaster{1,1,{128}})};d.layers.insert(d.layers.begin(),group);d.layers[1].raster=patterned(300,300);d.layers[1].transform={131.5,125.5,300,300};d.layers[1].parentId=group.id;Layer top;top.id="clipped";top.raster=Raster::filled(12,12,{90,50,10,128});top.transform={140,130,280,290};top.maskSourceId="image";top.parentId=group.id;d.layers.push_back(top);Layer grain;grain.id="grain";grain.adjustmentJson=effects::defaultAdjustmentJson("Grain");grain.parentId=group.id;d.layers.push_back(grain);compareHistogram(d);}
void histogram_transparent_and_invalid(){auto d=fixture();d.layers.clear();DocumentHistogramStats stats;REQUIRE(documentLevelsHistogram(d,{},&stats)==effects_tools::LevelsHistogram{}&&stats.renderedTiles==0);Layer bad;bad.id="invalid";bad.adjustmentJson="{}";d.layers.push_back(bad);bool failed=false;try{documentLevelsHistogram(d);}catch(const std::exception&){failed=true;}REQUIRE(failed);d.layers[0].visible=false;REQUIRE(documentLevelsHistogram(d)==effects_tools::LevelsHistogram{});}
void histogram_cancellation(){auto d=fixture();d.layers[0].transform={0,0,30000,30000};int calls=0;DocumentHistogramStats stats;bool cancelled=false;try{documentLevelsHistogram(d,[&]{return ++calls>3;},&stats);}catch(const std::runtime_error&e){cancelled=std::string(e.what())=="Histogram cancelled";}REQUIRE(cancelled&&stats.renderedTiles==1&&stats.maxTilePixels==65536);}
void original_pixel_sampling(){auto d=fixture();auto rgb=sampleDocumentOriginalRGB(d,{15000.99,15000.99});REQUIRE(rgb&&(*rgb)[0]==70./255&&(*rgb)[1]==180./255&&(*rgb)[2]==120./255);REQUIRE(!sampleDocumentOriginalRGB(d,{1,1})&&!sampleDocumentOriginalRGB(d,{-1,0})&&!sampleDocumentOriginalRGB(d,{std::numeric_limits<double>::quiet_NaN(),0}));}
std::optional<AdjustmentDialogResult> dialog(const Document&d,const QString& kind,bool live,bool apply,const AdjustmentDialogOptions& options={}){
    bool ready=false,timedOut=false;QTimer poll;QElapsedTimer elapsed;elapsed.start();poll.setInterval(20);QObject::connect(&poll,&QTimer::timeout,[&]{auto* dialog=qobject_cast<QDialog*>(QApplication::activeModalWidget());if(!dialog)return;auto* buttons=dialog->findChild<QDialogButtonBox*>();if(!buttons)return;auto* preview=dialog->findChild<QLabel*>("adjustmentPreview");auto* histogram=dialog->findChild<QPushButton*>("levelsAutoContrast");if(buttons->button(QDialogButtonBox::Apply)->isEnabled()&&(!histogram||histogram->isEnabled())){ready=preview&&preview->pixmap().size()==QSize(460,460);(apply?buttons->button(QDialogButtonBox::Apply):buttons->button(QDialogButtonBox::Cancel))->click();}else if(elapsed.elapsed()>10000){timedOut=true;dialog->reject();}});poll.start();auto result=showAdjustmentDialog(nullptr,d,"image",kind,live,false,options);poll.stop();REQUIRE(!timedOut&&ready);return result;
}
void adjustment_dialog_source_grid(){auto d=fixture();const auto before=d;auto object=QJsonDocument::fromJson(QByteArray::fromStdString(effects::defaultAdjustmentJson("Exposure"))).object();object["exposureSettings"]=QJsonObject{{"exposure",1},{"offset",0},{"gamma",1}};const auto json=QJsonDocument(object).toJson(QJsonDocument::Compact).toStdString();AdjustmentDialogOptions options;options.initialAdjustmentJson=json;auto expected=effects::applyAdjustment(d.layers[0].raster,json);auto result=dialog(d,"Exposure",false,true,options);REQUIRE(result&&d==before&&result->document.width==30000&&result->document.height==30000);auto& layer=result->document.layers[0];REQUIRE(layer.raster->width==32&&layer.raster->height==16&&layer.transform==d.layers[0].transform);REQUIRE(layer.raster->rgba()==expected->rgba()&&layer.raster!=d.layers[0].raster);}
void adjustment_dialog_live_levels(){auto d=fixture();const auto original=d;auto result=dialog(d,"Levels",true,true);REQUIRE(result&&result->document.layers.size()==2&&result->document.layers[0]==d.layers[0]&&d==original);REQUIRE(!result->document.layers[1].adjustmentJson.empty());}
void adjustment_dialog_cancel(){auto d=fixture();const auto original=d;REQUIRE(!dialog(d,"Levels",true,false)&&d==original);}
int main(int argc,char**argv){QApplication app(argc,argv);std::map<std::string,void(*)()> tests{{"fitted_geometry",fitted_geometry},{"small_thumbnail_identity",small_thumbnail_identity},{"histogram_small_source_budget",histogram_small_source_budget},{"histogram_full_tile_order",histogram_full_tile_order},{"histogram_rotated_reduced_alignment",histogram_rotated_reduced_alignment},{"histogram_masks_clips_adjustment",histogram_masks_clips_adjustment},{"histogram_transparent_and_invalid",histogram_transparent_and_invalid},{"histogram_cancellation",histogram_cancellation},{"original_pixel_sampling",original_pixel_sampling},{"adjustment_dialog_source_grid",adjustment_dialog_source_grid},{"adjustment_dialog_live_levels",adjustment_dialog_live_levels},{"adjustment_dialog_cancel",adjustment_dialog_cancel}};int failed=0;for(const auto&[name,test]:tests){if(argc>1&&name!=argv[1])continue;try{test();std::cout<<"PASS "<<name<<'\n';}catch(const std::exception&e){++failed;std::cout<<"FAIL "<<name<<": "<<e.what()<<'\n';}}if(argc>1&&!tests.contains(argv[1]))return 2;return failed?1:0;}
