#include "ui/MainWindow.h"
#include <QApplication>
#include <QFile>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QMouseEvent>
#include <QStatusBar>
#include <QTest>
#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <dwmapi.h>
#include <dxgi1_4.h>
#include <psapi.h>
using namespace compositor;
using Clock=std::chrono::steady_clock;
using Microsoft::WRL::ComPtr;
namespace {
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
double ms(Clock::time_point a,Clock::time_point b){return std::chrono::duration<double,std::milli>(b-a).count();}
QJsonArray numbers(const std::vector<double>& values){QJsonArray result;for(double v:values)result.append(v);return result;}
QJsonObject summary(std::vector<double> values){std::sort(values.begin(),values.end());require(!values.empty(),"Missing timing values");return {{"p50_ms",values[values.size()/2]},{"p95_ms",values[size_t(std::ceil(.95*values.size()))-1]},{"max_ms",values.back()}};}
struct Adapter {ComPtr<IDXGIAdapter3> object;QString name;quint64 local{},nonlocal{};bool available{};};
std::vector<Adapter> adapters(){ComPtr<IDXGIFactory1> factory;std::vector<Adapter> result;if(FAILED(CreateDXGIFactory1(IID_PPV_ARGS(&factory))))return result;for(UINT i=0;;++i){ComPtr<IDXGIAdapter1> adapter;if(factory->EnumAdapters1(i,&adapter)==DXGI_ERROR_NOT_FOUND)break;DXGI_ADAPTER_DESC1 desc{};if(FAILED(adapter->GetDesc1(&desc)))continue;Adapter row;row.name=QString::fromWCharArray(desc.Description);adapter.As(&row.object);result.push_back(std::move(row));}return result;}
void sample(std::vector<Adapter>& rows){for(auto& row:rows)if(row.object){DXGI_QUERY_VIDEO_MEMORY_INFO a{},b{};if(SUCCEEDED(row.object->QueryVideoMemoryInfo(0,DXGI_MEMORY_SEGMENT_GROUP_LOCAL,&a))&&SUCCEEDED(row.object->QueryVideoMemoryInfo(0,DXGI_MEMORY_SEGMENT_GROUP_NON_LOCAL,&b))){row.available=true;row.local=std::max(row.local,quint64(a.CurrentUsage));row.nonlocal=std::max(row.nonlocal,quint64(b.CurrentUsage));}}}
QJsonArray memory(const std::vector<Adapter>& rows){QJsonArray result;for(const auto& row:rows)result.append(QJsonObject{{"adapter",row.name},{"available",row.available},{"sampled_max_local_bytes",row.available?QJsonValue(qint64(row.local)):QJsonValue()},{"sampled_max_nonlocal_bytes",row.available?QJsonValue(qint64(row.nonlocal)):QJsonValue()}});return result;}
Document fixture(const QString& kind){Document d;d.id="native-brush-performance";d.width=d.height=4000;const int count=kind=="multiple"?3:1;for(int i=0;i<count;++i){Layer layer;layer.id="layer-"+std::to_string(i);layer.name=layer.id;layer.transform={0,0,4000,4000};layer.raster=Raster::filled(4000,4000,kind=="transparent"?Pixel{}:Pixel{80,100,160,255});if(kind=="mask"&&i==0)layer.mask=Mask{std::make_shared<GrayRaster>(GrayRaster{4000,4000,std::vector<uint8_t>(16000000,255)})};d.layers.push_back(std::move(layer));}return d;}
QAction* action(MainWindow& w,const QString& id){for(auto* a:w.findChildren<QAction*>())if(a->property("commandId").toString()==id&&a->isEnabled()&&a->isVisible())return a;throw std::runtime_error("Registered action unavailable");}
void number(MainWindow& w,const QString& name,double value){for(auto* n:w.findChildren<QDoubleSpinBox*>())if(n->accessibleName()==name){require(n->isEnabled(),"Brush control disabled");n->setValue(value);require(n->value()==value,"Brush control rejected value");return;}throw std::runtime_error("Brush control missing");}
Point trajectory(int i){return i<=60?Point{700.,3200.-i*40.}:Point{700.+(i-60)*40.,800.};}
struct EventTime {double dispatch,present,flush,total;};
EventTime deliver(NativeCanvas& canvas,QEvent::Type type,Point document,Qt::MouseButton button,Qt::MouseButtons held){auto p=canvas.viewMapping().toView(document);QPointF local(p.x,p.y);require(canvas.rect().contains(local.toPoint()),"Trajectory left fixed viewport");QMouseEvent event(type,local,canvas.mapToGlobal(local),button,held,Qt::NoModifier);const auto begin=Clock::now();QApplication::sendEvent(&canvas,&event);const auto dispatched=Clock::now();canvas.repaint();const auto presented=Clock::now();require(SUCCEEDED(DwmFlush()),"DwmFlush unavailable");const auto flushed=Clock::now();require(canvas.deviceReady()&&canvas.deviceError().isEmpty(),"Native presentation error");return {ms(begin,dispatched),ms(dispatched,presented),ms(presented,flushed),ms(begin,flushed)};}
}
int main(int argc,char** argv){QApplication app(argc,argv);if(argc!=4){std::fprintf(stderr,"Usage: native_brush_performance transparent|opaque|small|mask|multiple warp|hardware report.json\n");return 2;}const QString kind=QString::fromLocal8Bit(argv[1]);const bool warp=QString::fromLocal8Bit(argv[2])=="warp";QJsonObject report{{"schema","NATIVE_BRUSH_PERFORMANCE_V1"},{"case",kind},{"requested_backend",warp?"WARP":"hardware"},{"actual_backend_confirmed",warp},{"actual_adapter_identity",QJsonValue()},{"dispatch_gate_p95_ms",16.7},{"physical_scanout_measured",false},{"allocation_counts",QJsonValue()}};int exit=2;try{
    require(QStringList{"transparent","opaque","small","mask","multiple"}.contains(kind),"Unknown case");require(warp||QString::fromLocal8Bit(argv[2])=="hardware","Unknown backend");
    QStringList diagnostics;MainWindow window(warp);auto& project=window.addProject(fixture(kind));auto& canvas=*project.canvas;canvas.setFixedSize(640,640);window.resize(1120,880);window.show();window.activateWindow();canvas.setFocus();QTest::qWait(200);require(canvas.devicePixelRatioF()==1,"Native corpus requires DPR1");action(window,"tool.brush")->trigger();number(window,"Brush diameter",kind=="small"?20:800);number(window,"Brush hardness",kind=="small"?100:0);number(window,"Brush opacity",100);
    if(kind=="mask"){QComboBox* target=nullptr;for(auto* c:window.findChildren<QComboBox*>())if(c->accessibleName()=="Editing target")target=c;require(target,"Mask target missing");target->setCurrentIndex(1);auto* white=window.findChild<QCheckBox*>("paintMaskWhite");require(white,"Mask paint control missing");white->setChecked(false);require(project.maskSelected,"Mask target not selected");}
    canvas.zoomAt(.15,{320,320});canvas.pan={0,0};canvas.repaint();require(canvas.deviceReady()&&canvas.deviceError().isEmpty(),"Initial native display unavailable");require(SUCCEEDED(DwmFlush()),"DwmFlush unavailable");QObject::connect(window.statusBar(),&QStatusBar::messageChanged,[&](const QString& text){if(text.contains("software brush",Qt::CaseInsensitive)||text.contains("fail",Qt::CaseInsensitive)||text.contains("error",Qt::CaseInsensitive))diagnostics.append(text);});
    std::vector<double> dispatch,present,flush,total,presses,releases;auto gpuMemory=adapters();sample(gpuMemory);Raster::resetMaterializationCount();const auto original=*project.document;require(project.active==original.layers.back().id,"Unexpected active layer in fixture");const auto corner=original.layers.back().raster->pixel(3500,3500);size_t shared=0;QJsonArray perPass;
    for(int pass=0;pass<2;++pass){const auto before=*project.document;auto first=deliver(canvas,QEvent::MouseButtonPress,trajectory(0),Qt::LeftButton,Qt::LeftButton);presses.push_back(first.total);require(bool(project.brushPreview),"Press failed to start live brush");const auto canvasAdapter=canvas.adapterName(),brushAdapter=window.brushAdapterName();require(!canvasAdapter.isEmpty()&&!brushAdapter.isEmpty(),"Actual adapter identity unavailable");report["actual_canvas_adapter"]=canvasAdapter;report["actual_brush_adapter"]=brushAdapter;report["actual_backend_confirmed"]=true;report["actual_adapter_identity"]=QJsonArray{canvasAdapter,brushAdapter};for(int i=1;i<=120;++i){auto time=deliver(canvas,QEvent::MouseMove,trajectory(i),Qt::NoButton,Qt::LeftButton);dispatch.push_back(time.dispatch);present.push_back(time.present);flush.push_back(time.flush);total.push_back(time.total);std::printf("PROGRESS pass=%d event=%d dispatch_ms=%.4f present_ms=%.4f flush_ms=%.4f\n",pass,i,time.dispatch,time.present,time.flush);std::fflush(stdout);require(bool(project.brushPreview),"Live brush ended during movement");require(*project.document==before,"Live brush changed canonical document");sample(gpuMemory);}auto release=deliver(canvas,QEvent::MouseButtonRelease,trajectory(120),Qt::LeftButton,Qt::NoButton);releases.push_back(release.total);require(!project.brushPreview,"Release kept a live brush preview");require(project.history.undoCount()>=1,"Release did not commit history");perPass.append(QJsonObject{{"pass",pass},{"press_dispatch_ms",first.dispatch},{"press_total_ms",first.total},{"release_dispatch_ms",release.dispatch},{"release_total_ms",release.total}});sample(gpuMemory);}
    for(size_t i=0;i+1<original.layers.size();++i)require(project.document->layers[i]==original.layers[i],"Non-target layer changed");const auto& painted=project.document->layers.back();require(painted.raster->pixel(3500,3500)==corner,"Far pixel changed");if(kind=="mask")require(painted.mask->raster->pixel(700,2000)<255&&painted.mask->raster->pixel(3500,3500)==255,"Mask paint or far coverage wrong");else require(painted.raster->pixel(700,2000)!=original.layers.back().raster->pixel(700,2000),"Painted center unchanged");for(size_t i=0;i<painted.raster->tiles.size();++i)if(painted.raster->tiles[i]==original.layers.back().raster->tiles[i])++shared;require(diagnostics.empty(),"Brush fallback or failure reported");require(Raster::materializationCount()==0,"Full rgba materialization observed");
    PROCESS_MEMORY_COUNTERS_EX counters{};require(GetProcessMemoryInfo(GetCurrentProcess(),reinterpret_cast<PROCESS_MEMORY_COUNTERS*>(&counters),sizeof(counters)),"Process memory counter unavailable");const auto dispatchSummary=summary(dispatch);const bool met=dispatchSummary["p95_ms"].toDouble()<=16.7;report["status"]="valid";report["dispatch_gate_met"]=met;report["dispatch"]=dispatchSummary;report["repaint_to_present_return"]=summary(present);report["dwm_flush"]=summary(flush);report["event_to_dwm_flush"]=summary(total);report["dispatch_ms"]=numbers(dispatch);report["present_ms"]=numbers(present);report["flush_ms"]=numbers(flush);report["event_total_ms"]=numbers(total);report["passes"]=perPass;report["viewport_dips"]=QJsonArray{640,640};report["dpr"]=1;report["zoom_physical_per_document_pixel"] =.15;report["peak_working_set_bytes"]=qint64(counters.PeakWorkingSetSize);report["private_bytes_at_end"]=qint64(counters.PrivateUsage);report["peak_pagefile_bytes"]=qint64(counters.PeakPagefileUsage);report["video_memory"]=memory(gpuMemory);report["unchanged_tiles_shared"]=qint64(shared);report["full_rgba_materializations"]=qint64(Raster::materializationCount());report["events"]=240;report["sync"]="Present(1,0) return then DwmFlush; no physical scanout claim";exit=met?0:1;
}catch(const std::exception& e){report["status"]="invalid";report["error"]=e.what();}QFile output(QString::fromLocal8Bit(argv[3]));if(!output.open(QIODevice::WriteOnly)||output.write(QJsonDocument(report).toJson())<0)return 2;std::printf("%s\n",QJsonDocument(report).toJson(QJsonDocument::Compact).constData());return exit;}
