#include "ui/MainWindow.h"
#include "ui/EditPanelSession.h"
#include "ui/AdjustmentAdvancedControls.h"
#include "effects/Adjustments.h"
#include "filters/PixelFilters.h"
#include <QApplication>
#include <QCheckBox>
#include <QDialogButtonBox>
#include <QElapsedTimer>
#include <QEventLoop>
#include <QPushButton>
#include <QJsonDocument>
#include <QTest>
#include <QTimer>
#include <cstdio>
#include <cmath>
#include <algorithm>
#include <map>

using namespace compositor;
namespace {
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
template<class Fn>void wait(Fn predicate,const char* message){QElapsedTimer elapsed;elapsed.start();while(!predicate()){if(elapsed.elapsed()>6000)throw std::runtime_error(message);QApplication::processEvents(QEventLoop::AllEvents,20);QTest::qWait(1);}}
QAction* action(MainWindow& window,const char* id){for(auto* value:window.findChildren<QAction*>())if(value->property("commandId")==id)return value;throw std::runtime_error(std::string("missing action ")+id);}
void trigger(MainWindow& window,const char* id){auto* value=action(window,id);require(value->isEnabled(),"requested action enabled");value->trigger();}
template<class T>T* control(QObject& owner,const char* name){for(auto* object:owner.findChildren<QObject*>())if(object->objectName()==name)if(auto* result=dynamic_cast<T*>(object))return result;throw std::runtime_error("named panel control");}
QDoubleSpinBox* field(QDialog& panel,const QString& name){for(auto* value:panel.findChildren<QDoubleSpinBox*>())if(value->accessibleName()==name)return value;throw std::runtime_error("named number field");}
QPushButton* apply(QDialog& panel){auto* buttons=panel.findChild<QDialogButtonBox*>();require(buttons,"panel buttons");auto* result=buttons->button(QDialogButtonBox::Apply);require(result,"panel Apply");return result;}
void ready(QDialog& panel){wait([&]{return apply(panel)->isEnabled();},"preview did not become ready");}
QCheckBox* preview(QDialog& panel){for(auto* box:panel.findChildren<QCheckBox*>())if(box->text()=="Preview")return box;throw std::runtime_error("source Preview checkbox is missing");}
Document fixture(Pixel pixel={80,100,120,255}){Document d;d.id="nonmodal-document";d.width=64;d.height=48;Layer l;l.id="pixels";l.name="Pixels";l.transform={16,12,32,24};l.raster=Raster::filled(32,24,pixel);d.layers={l};return d;}
struct Fixture {MainWindow window{true};EditorProject& project;Document before;
    explicit Fixture(Document d=fixture()):project(window.addProject(d)),before(std::move(d)){window.show();QApplication::processEvents();}
    Pixel visible(int x=30,int y=20){auto view=project.canvas->viewportProvider(0,0,64,48,1);require(bool(view.raster),"main canvas raster");return view.raster->pixel(x,y);}
    void unchanged(){require(project.document==before&&project.history.undoCount()==0&&!project.history.modified(),"draft changed canonical document/history");}
    void click(Point point){auto view=project.canvas->viewMapping().toView(point);QTest::mouseClick(project.canvas,Qt::LeftButton,{},QPoint(int(view.x),int(view.y)));QApplication::processEvents();}
};
template<class Fn>void panel(MainWindow& window,const char* command,const QString& title,Fn body){
    QEventLoop loop;QTimer poll;poll.setInterval(10);QElapsedTimer elapsed;elapsed.start();std::exception_ptr failure;bool visited=false;
    QObject::connect(&poll,&QTimer::timeout,&window,[&]{QPointer<QDialog> found;for(auto* candidate:window.findChildren<QDialog*>())if(candidate->isVisible()&&candidate->windowTitle()==title){found=candidate;break;}
        if(!found){if(elapsed.elapsed()<6000)return;poll.stop();failure=std::make_exception_ptr(std::runtime_error("owned editor panel did not open"));if(auto* modal=qobject_cast<QDialog*>(QApplication::activeModalWidget()))modal->reject();loop.quit();return;}
        poll.stop();visited=true;try{body(*found);}catch(...){failure=std::current_exception();}if(found&&found->isVisible())found->reject();loop.quit();});
    poll.start();QTimer::singleShot(0,&window,[&]{try{trigger(window,command);}catch(...){failure=std::current_exception();poll.stop();loop.quit();}});loop.exec();if(failure)std::rethrow_exception(failure);require(visited,"actual editor panel visited");QApplication::processEvents();
}
Pixel exposurePixel(const Document& doc,double amount){auto json=effects::defaultAdjustmentJson("Exposure");auto object=QJsonDocument::fromJson(QByteArray::fromStdString(json)).object();auto settings=object["exposureSettings"].toObject();settings["exposure"]=amount;settings["offset"]=0;settings["gamma"]=1;object["exposureSettings"]=settings;auto output=doc;output.layers[0].raster=effects::applyAdjustment(output.layers[0].raster,QJsonDocument(object).toJson(QJsonDocument::Compact).toStdString());return SoftwareRenderer().render(output,0,0,64,48)->pixel(30,20);}
void adjustment_nonmodal(){Fixture f;panel(f.window,"adjust.exposure","Exposure",[&](QDialog& p){require(!QApplication::activeModalWidget()&&p.windowModality()==Qt::NonModal,"source adjustment panel is nonmodal");require(f.project.canvas->isEnabled(),"main canvas enabled during edit");f.unchanged();});f.unchanged();}
void filter_nonmodal(){Fixture f;panel(f.window,"filter.gaussian","Gaussian Blur",[&](QDialog& p){require(!QApplication::activeModalWidget()&&p.windowModality()==Qt::NonModal,"source filter panel is nonmodal");f.unchanged();});f.unchanged();}
void adjustment_canvas_preview(){Fixture f;const auto expected=exposurePixel(f.before,1);panel(f.window,"adjust.exposure","Exposure",[&](QDialog& p){field(p,"Exposure")->setValue(1);ready(p);f.unchanged();require(f.visible()==expected,"main canvas shows adjustment preview");});f.unchanged();require(f.visible()==Pixel{80,100,120,255},"Cancel restores original canvas");}
void adjustment_preview_toggle(){Fixture f;const auto expected=exposurePixel(f.before,1);panel(f.window,"adjust.exposure","Exposure",[&](QDialog& p){field(p,"Exposure")->setValue(1);ready(p);require(f.visible()==expected,"preview before toggle");preview(p)->setChecked(false);QApplication::processEvents();require(f.visible()==Pixel{80,100,120,255},"Preview off restores original immediately");preview(p)->setChecked(true);ready(p);require(f.visible()==expected,"Preview on restores current adjustment");f.unchanged();});f.unchanged();}
void adjustment_apply_undo(){Fixture f;const auto expected=exposurePixel(f.before,1);panel(f.window,"adjust.exposure","Exposure",[&](QDialog& p){field(p,"Exposure")->setValue(1);ready(p);apply(p)->click();wait([guard=QPointer<QDialog>(&p)]{return !guard||!guard->isVisible();},"Apply did not finish");});require(f.visible()==expected&&f.project.history.undoCount()==1,"Apply commits rendered result once");trigger(f.window,"edit.undo");f.unchanged();}
void adjustment_close_cancel(){Fixture f;panel(f.window,"adjust.exposure","Exposure",[&](QDialog& p){field(p,"Exposure")->setValue(1);ready(p);p.close();});f.unchanged();require(f.visible()==Pixel{80,100,120,255},"window close restores original canvas");}
void adjustment_position(){Fixture f;QPoint position;panel(f.window,"adjust.exposure","Exposure",[&](QDialog& p){p.move(131,147);position=p.pos();});panel(f.window,"adjust.exposure","Exposure",[&](QDialog& p){require(p.pos()==position,"reopened panel retains source position");});f.unchanged();}
void levels_canvas_original_sample(){Fixture f(fixture({80,80,80,255}));panel(f.window,"adjust.levels","Levels",[&](QDialog& p){control<QDoubleSpinBox>(p,"levelsValue3")->setValue(160);ready(p);control<QPushButton>(p,"levelsSampleBlack")->click();f.click({30,20});auto settings=effects_tools::levelsFromAdjustmentJson(control<LevelsAdvancedControls>(p,"levelsAdvancedControls")->adjustmentJson());for(size_t c=1;c<4;++c)require(settings.ranges[c].black==80,"main canvas Levels samples original80 rather than preview");f.unchanged();});f.unchanged();}
void hue_canvas_sample(){Fixture f(fixture({0,255,0,255}));panel(f.window,"adjust.hue_saturation","Hue/Saturation",[&](QDialog& p){control<QComboBox>(p,"hueRange")->setCurrentIndex(int(effects_tools::ColorRange::Reds));auto* controls=control<HueAdvancedControls>(p,"hueAdvancedControls");auto before=effects_tools::hueFromAdjustmentJson(controls->adjustmentJson());control<QPushButton>(p,"hueSampleColor")->click();f.click({30,20});const auto actual=effects_tools::hueFromAdjustmentJson(controls->adjustmentJson());const auto expected=effects_tools::sampleHueRange(before,120,effects_tools::HueSample::Replace);require(actual==expected&&actual!=before,"main canvas Hue samples visible green");f.unchanged();});f.unchanged();}
void hue_canvas_target(){Fixture f(fixture({100,160,100,255}));panel(f.window,"adjust.hue_saturation","Hue/Saturation",[&](QDialog& p){auto* controls=control<HueAdvancedControls>(p,"hueAdvancedControls");auto expected=effects_tools::hueFromAdjustmentJson(controls->adjustmentJson());auto drag=effects_tools::beginHueTargeting(expected,effects_tools::PaletteColor{100/255.,160/255.,100/255.});require(drag.has_value(),"targeting fixture");control<QPushButton>(p,"hueTargetedAdjustment")->click();auto at=f.project.canvas->viewMapping().toView({30,20});QPoint start(int(at.x),int(at.y));QTest::mousePress(f.project.canvas,Qt::LeftButton,{},start);QTest::mouseMove(f.project.canvas,start+QPoint(20,0));QTest::mouseRelease(f.project.canvas,Qt::LeftButton,{},start+QPoint(20,0));QApplication::processEvents();expected=effects_tools::dragHueTargeting(expected,*drag,20,false);require(effects_tools::hueFromAdjustmentJson(controls->adjustmentJson())==expected,"main canvas targeted Hue drag uses view-pixel delta");f.unchanged();});f.unchanged();}
void filter_canvas_preview(){Fixture f;filters::Request job;job.kind=filters::Kind::GaussianBlur;job.source=f.before.layers[0].raster;job.transform=f.before.layers[0].transform;job.settings.radius=3;job.preview=true;auto result=filters::apply(job);auto expected=f.before;expected.layers[0].raster=result.raster;expected.layers[0].transform=result.transform;const auto pixel=SoftwareRenderer().render(expected,0,0,64,48)->pixel(16,12);panel(f.window,"filter.gaussian","Gaussian Blur",[&](QDialog& p){field(p,"Radius")->setValue(3);ready(p);f.unchanged();require(f.visible(16,12)==pixel,"main canvas shows filter preview at layer edge");});f.unchanged();}
void filter_apply_undo(){Fixture f;panel(f.window,"filter.gaussian","Gaussian Blur",[&](QDialog& p){field(p,"Radius")->setValue(3);ready(p);apply(p)->click();wait([guard=QPointer<QDialog>(&p)]{return !guard||!guard->isVisible();},"full filter Apply did not finish");});require(f.project.document!=f.before&&f.project.history.undoCount()==1,"full filter commits one edit");trigger(f.window,"edit.undo");f.unchanged();}
void filter_preview_checkbox(){Fixture f;panel(f.window,"filter.gaussian","Gaussian Blur",[&](QDialog& p){field(p,"Radius")->setValue(3);ready(p);preview(p)->setChecked(false);QApplication::processEvents();require(f.visible(16,12)==Pixel{80,100,120,255},"filter Preview off restores original canvas");f.unchanged();});f.unchanged();}
void filter_mask_growth(){auto d=fixture();auto mask=std::make_shared<GrayRaster>();mask->width=32;mask->height=24;mask->pixels.assign(32*24,255);for(int y=0;y<24;++y)for(int x=0;x<16;++x)mask->pixels[size_t(y)*32+x]=0;d.layers[0].mask=Mask{mask,false,true,{}};Fixture f(d);panel(f.window,"filter.gaussian","Gaussian Blur",[&](QDialog& p){field(p,"Radius")->setValue(3);ready(p);apply(p)->click();wait([guard=QPointer<QDialog>(&p)]{return !guard||!guard->isVisible();},"masked filter Apply did not finish");});const auto& layer=f.project.document->layers[0];require(layer.raster->width!=32,"blur fixture grows source grid");require(layer.mask&&layer.mask->raster->width==layer.raster->width&&layer.mask->raster->height==layer.raster->height,"grown filter carries attached mask to output grid");require(!layer.mask->enabled&&layer.mask->linked&&!layer.mask->placement,"mask growth preserves enabled/link/placement metadata");trigger(f.window,"edit.undo");f.unchanged();}
void pending_edit_guards(){Fixture f;panel(f.window,"adjust.exposure","Exposure",[&](QDialog& p){require(!QApplication::activeModalWidget(),"pending guard checked for real nonmodal session");require(!action(f.window,"adjust.levels")->isEnabled()&&!action(f.window,"layer.new")->isEnabled(),"pending edit blocks second adjustment and layer mutation");auto old=f.project.canvas->zoom;trigger(f.window,"view.actual");require(f.project.canvas->zoom==1&&old>0,"View Actual Pixels remains available");require(p.isVisible(),"navigation keeps panel open");f.unchanged();});f.unchanged();}
void existing_live_preview_cancel(){auto d=fixture();Layer adjustment;adjustment.id=newId();adjustment.name="Exposure";adjustment.transform={0,0,64,48};adjustment.adjustmentJson=effects::defaultAdjustmentJson("Exposure");d.layers.push_back(adjustment);Fixture f(d);const auto expected=exposurePixel(f.before,1);panel(f.window,"adjust.edit","Exposure",[&](QDialog& p){field(p,"Exposure")->setValue(1);ready(p);require(f.visible()==expected,"existing live adjustment previews in canvas");f.unchanged();});f.unchanged();}
void latest_preview_wins(){Fixture f;const auto expected=exposurePixel(f.before,.5);panel(f.window,"adjust.exposure","Exposure",[&](QDialog& p){auto* exposure=field(p,"Exposure");exposure->setValue(1);exposure->setValue(2);exposure->setValue(.5);ready(p);require(f.visible()==expected,"newest pending settings win canvas preview");f.unchanged();});f.unchanged();}

void adjustment_reduced_preview_full_apply(){auto d=fixture();d.width=4096;d.height=4;d.layers[0].transform={0,0,4096,4};d.layers[0].raster=Raster::filled(4096,4,{40,60,80,255});Fixture f(d);panel(f.window,"adjust.exposure","Exposure",[&](QDialog& p){field(p,"Exposure")->setValue(1);ready(p);require(f.project.effectPreview&&f.project.effectPreview->layers[0].raster->width==2048,"source FilterEdit preview limit2048");f.unchanged();apply(p)->click();wait([guard=QPointer<QDialog>(&p)]{return !guard||!guard->isVisible();},"source-size Apply completed");});require(f.project.document->layers[0].raster->width==4096&&f.project.history.undoCount()==1,"full Apply preserves original grid");trigger(f.window,"edit.undo");f.unchanged();}
void levels_reduced_preview_full_apply(){auto d=fixture();d.width=9001;d.height=3;d.layers[0].transform={0,0,9001,3};d.layers[0].raster=Raster::filled(9001,3,{80,80,80,255});Fixture f(d);panel(f.window,"adjust.levels","Levels",[&](QDialog& p){control<QDoubleSpinBox>(p,"levelsValue0")->setValue(40);ready(p);require(f.project.effectPreview&&f.project.effectPreview->layers[0].raster->width==8000,"source Levels preview limit8000");f.unchanged();apply(p)->click();wait([guard=QPointer<QDialog>(&p)]{return !guard||!guard->isVisible();},"source-size Levels Apply completed");});require(f.project.document->layers[0].raster->width==9001&&f.project.history.undoCount()==1,"Levels Apply preserves original grid");trigger(f.window,"edit.undo");f.unchanged();}
void worker_cancel_no_late_result(){auto d=fixture();d.width=2000;d.height=2000;d.layers[0].transform={0,0,2000,2000};d.layers[0].raster=Raster::filled(2000,2000,{40,60,80,255});Fixture f(d);panel(f.window,"adjust.exposure","Exposure",[&](QDialog& p){field(p,"Exposure")->setValue(2);p.reject();f.unchanged();require(!f.project.effectPreview,"Cancel clears canvas draft immediately");});wait([&]{for(auto* object:f.window.findChildren<QObject*>())if(dynamic_cast<ui::EditPanelSession*>(object))return false;return true;},"cancelled worker retired without publishing");f.unchanged();require(!f.project.effectPreview,"finished cancelled worker cannot resurrect draft");}
void palette_visible_preview(){Fixture f;const auto expected=exposurePixel(f.before,1);panel(f.window,"adjust.exposure","Exposure",[&](QDialog& p){field(p,"Exposure")->setValue(1);ready(p);trigger(f.window,"palette.foreground");PaletteDialog* picker=nullptr;for(auto* object:f.window.findChildren<QObject*>())if(auto* candidate=dynamic_cast<PaletteDialog*>(object);candidate&&candidate->isVisible())picker=candidate;require(picker,"source palette opens over active adjustment");f.click({30,20});auto actual=picker->color().quantized();require(actual.red==expected.r/255.&&actual.green==expected.g/255.&&actual.blue==expected.b/255.,"palette samples displayed adjustment rather than canonical pixels");picker->reject();f.unchanged();});f.unchanged();}
void filter_mask_placed_unchanged(){auto d=fixture();auto mask=std::make_shared<GrayRaster>();mask->width=2;mask->height=2;mask->pixels={0,64,128,255};d.layers[0].mask=Mask{mask,false,false,Transform{20,15,9,7}};const auto original=*d.layers[0].mask;Fixture f(d);panel(f.window,"filter.gaussian","Gaussian Blur",[&](QDialog& p){field(p,"Radius")->setValue(3);ready(p);apply(p)->click();wait([guard=QPointer<QDialog>(&p)]{return !guard||!guard->isVisible();},"placed-mask Apply completed");});require(f.project.document->layers[0].mask==original,"explicit mask placement and pixels preserved across filter growth");trigger(f.window,"edit.undo");f.unchanged();}
void filter_solid_mask_unchanged(){auto d=fixture();auto mask=std::make_shared<GrayRaster>();mask->width=mask->height=1;mask->pixels={255};d.layers[0].mask=Mask{mask,true,false,{}};const auto original=*d.layers[0].mask;Fixture f(d);panel(f.window,"filter.gaussian","Gaussian Blur",[&](QDialog& p){field(p,"Radius")->setValue(3);ready(p);apply(p)->click();wait([guard=QPointer<QDialog>(&p)]{return !guard||!guard->isVisible();},"solid-mask Apply completed");});require(f.project.document->layers[0].mask==original,"source uniform1x1 mask stays constant without growth allocation");trigger(f.window,"edit.undo");f.unchanged();}
void filter_mask_pretrim_order(){auto d=fixture();auto mask=std::make_shared<GrayRaster>();mask->width=32;mask->height=24;mask->pixels.assign(32*24,255);for(int y=0;y<24;++y)for(int x=0;x<16;++x)mask->pixels[size_t(y)*32+x]=0;d.layers[0].mask=Mask{mask,false,false,{}};Fixture f(d);panel(f.window,"filter.gaussian","Gaussian Blur",[&](QDialog& p){field(p,"Radius")->setValue(3);ready(p);require(f.project.effectPreview&&f.project.effectPreview->layers[0].mask->placement==d.layers[0].transform,"preview pins original attached mask placement");apply(p)->click();wait([guard=QPointer<QDialog>(&p)]{return !guard||!guard->isVisible();},"mask-order Apply completed");});const auto& out=f.project.document->layers[0];require(out.mask&&out.mask->raster&&out.raster->width<54&&out.raster->height<46,"blur was padded11 then trimmed");const auto& actual=*out.mask->raster;for(int y=0;y<actual.height;++y)for(int x=0;x<actual.width;++x){const double sx=-11+(x+.5)*54/actual.width,sy=-11+(y+.5)*46/actual.height;double expected=255;if(sx>=0&&sy>=0&&sx<32&&sy<24){const double fx=sx-.5;const int ix=int(std::floor(fx));const auto pixel=[](int xx){return std::clamp(xx,0,31)<16?0.:255.;};expected=pixel(ix)*(1-(fx-ix))+pixel(ix+1)*(fx-ix);}require(actual.pixel(x,y)==uint8_t(std::lround(expected)),"mask samples pretrim padded placement using final grid size");}require(!out.mask->enabled&&!out.mask->linked&&!out.mask->placement,"mask metadata survives exact carry");trigger(f.window,"edit.undo");f.unchanged();}
void property_step_and_slider(){Fixture f;panel(f.window,"adjust.exposure","Exposure",[&](QDialog& p){auto* exposure=field(p,"Exposure");exposure->setFocus();QTest::keyClick(exposure,Qt::Key_Up,Qt::ShiftModifier);require(exposure->value()==.1,"source Exposure precision2 uses Shift ten0.01 steps");bool found=false;for(auto* slider:p.findChildren<QSlider*>())if(slider->accessibleName()=="Exposure slider"){found=true;slider->setValue(5250);}require(found&&exposure->value()==1,"Exposure slider and exact field share state");f.unchanged();});f.unchanged();}
}
int main(int argc,char** argv){QApplication app(argc,argv);const std::map<std::string,void(*)()> cases{{"adjustment_reduced_preview_full_apply",adjustment_reduced_preview_full_apply},{"levels_reduced_preview_full_apply",levels_reduced_preview_full_apply},{"worker_cancel_no_late_result",worker_cancel_no_late_result},{"palette_visible_preview",palette_visible_preview},{"filter_mask_placed_unchanged",filter_mask_placed_unchanged},{"filter_solid_mask_unchanged",filter_solid_mask_unchanged},{"filter_mask_pretrim_order",filter_mask_pretrim_order},{"property_step_and_slider",property_step_and_slider},{"adjustment_nonmodal",adjustment_nonmodal},{"filter_nonmodal",filter_nonmodal},{"adjustment_canvas_preview",adjustment_canvas_preview},{"adjustment_preview_toggle",adjustment_preview_toggle},{"adjustment_apply_undo",adjustment_apply_undo},{"adjustment_close_cancel",adjustment_close_cancel},{"adjustment_position",adjustment_position},{"levels_canvas_original_sample",levels_canvas_original_sample},{"hue_canvas_sample",hue_canvas_sample},{"hue_canvas_target",hue_canvas_target},{"filter_canvas_preview",filter_canvas_preview},{"filter_apply_undo",filter_apply_undo},{"filter_preview_checkbox",filter_preview_checkbox},{"filter_mask_growth",filter_mask_growth},{"pending_edit_guards",pending_edit_guards},{"existing_live_preview_cancel",existing_live_preview_cancel},{"latest_preview_wins",latest_preview_wins}};try{require(argc==2&&cases.contains(argv[1]),"provide named nonmodal case");cases.at(argv[1])();std::printf("PASS %s\n",argv[1]);return 0;}catch(const std::exception& e){std::fprintf(stderr,"FAIL %s: %s\n",argc>1?argv[1]:"argument",e.what());return 1;}}
