#include "ui/MainWindow.h"
#include "ui/LayerPanel.h"
#include <QApplication>
#include <QCursor>
#include <QFont>
#include <QMouseEvent>
#include <QStyleOptionViewItem>
#include <QTest>
#include <iostream>
#include <stdexcept>
using namespace compositor;
namespace {
void check(bool value,const char*why){if(!value)throw std::runtime_error(why);}
void pixelsAvailable(const QImage& image){check(!image.isNull(),"source pixels #require thumbnail image");check(image.constBits()!=nullptr&&image.sizeInBytes()>=qint64(image.bytesPerLine())*image.height(),"source pixels #require backing bytes");}
QColor pixel(const QImage&image,int x,int y){pixelsAvailable(image);check(x>=0&&y>=0&&x<image.width()&&y<image.height(),"pixel reader index outside image");return QColor::fromRgba(image.pixel(x,y));}
void thumbnail_shapes(){check(ui::canvasThumbnailSize({400,200},36)==QSize(36,18),"400x200 fits36x18");check(ui::canvasThumbnailSize({300,600},36)==QSize(18,36),"300x600 fits18x36");check(ui::canvasThumbnailSize({},30)==QSize(30,30),"zero canvas falls back square");}
void thumbnail_layer_placement(){const auto red=Raster::filled(100,100,{255,0,0,255});check(red&&red->width==100&&red->height==100&&!red->tiles.empty()&&red->tiles.front(),"source image helper #require generated image");auto image=ui::canvasLayerThumbnail(red.get(),{0,0,100,100},{400,200},36);check(image.deviceIndependentSize()==QSizeF(36,18),"source logical thumbnail size");check(image.width()==72,"source fixed2x backing width");check(pixel(image,4,4)==QColor(255,0,0,255),"top-left layer placement");check(pixel(image,12,12).red()==255,"inside source layer");check(pixel(image,60,30).red()<200,"rest canvas checkerboard");check(pixel(image,4,30).red()<200,"bottom-left blank confirms orientation");const auto blank=ui::canvasLayerThumbnail(nullptr,{0,0,400,200},{400,200},36);check(pixel(blank,4,4).alpha()==255,"blank layer opaque checkerboard");}
void thumbnail_mask_edge(){const Transform transform{100,50,100,100};const QSizeF canvas{400,200};const GrayRaster hide{1,1,{0}};check(hide.width==1&&hide.height==1&&hide.pixels.size()==1,"source #require solid gray mask");auto hidden=ui::canvasMaskThumbnail(hide,transform,canvas,30);check(pixel(hidden,1,1).red()<10,"hide-all exterior black");check(pixel(hidden,55,25).red()<10,"hide-all remote exterior black");GrayRaster framed{20,20,std::vector<uint8_t>(400,255)};check(framed.width==20&&framed.height==20&&framed.pixels.size()==400,"source #require gray20x20 context storage");for(int y=5;y<15;++y)for(int x=5;x<15;++x)framed.pixels[size_t(y)*20+x]=0;check(framed.pixels.data()!=nullptr,"source #require framed mask image");check(ui::canvasMaskEdgeTone(framed)==1,"white frame edge tone");auto shown=ui::canvasMaskThumbnail(framed,transform,canvas,30);check(pixel(shown,2,2).red()>245,"white outside layer");check(pixel(shown,22,15).red()<10,"black center in document placement");}
Document example(){Document d;d.id=newId();d.width=400;d.height=300;for(const auto*id:{"a","b","c"}){Layer l;l.id=id;l.name=id;l.transform={0,0,100,100};l.raster=Raster::filled(100,100,{255,0,0,255});d.layers.push_back(l);}return d;}
QTreeWidget*tree(MainWindow&w){auto*t=w.findChild<QTreeWidget*>("layersTree");check(t,"missing tree");return t;}
ui::LayerPanelController*controller(MainWindow&w){auto*c=ui::LayerPanelController::find(tree(w));check(c,"missing controller");return c;}
QTreeWidgetItem*item(MainWindow&w,const char*id){for(QTreeWidgetItemIterator it(tree(w));*it;++it)if((*it)->data(0,Qt::UserRole).toString()==id)return *it;throw std::runtime_error("missing row");}
Layer&layer(EditorProject&p,const char*id){for(auto&l:p.document->layers)if(l.id==id)return l;throw std::runtime_error("missing layer");}
QPoint namePoint(MainWindow&w,const char*id){auto*view=tree(w);auto*row=item(w,id);view->scrollToItem(row);QApplication::processEvents();const auto rect=view->visualItemRect(row);return {view->columnViewportPosition(0)+view->columnWidth(0)/2,rect.top()+4};}
QPoint eyePoint(MainWindow&w,const char*id){auto*view=tree(w);auto*row=item(w,id);QStyleOptionViewItem option;option.initFrom(view);option.rect=view->visualRect(view->indexFromItem(row,0));option.features=QStyleOptionViewItem::HasCheckIndicator;option.checkState=row->checkState(0);return view->style()->subElementRect(QStyle::SE_ItemViewItemCheckIndicator,&option,view).center();}
void mouse(MainWindow&w,QEvent::Type type,QPoint point,Qt::MouseButton button,Qt::MouseButtons buttons,Qt::KeyboardModifiers flags={}){auto*view=tree(w)->viewport();QMouseEvent event(type,point,view->mapToGlobal(point),button,buttons,flags);QApplication::sendEvent(view,&event);}
void thumbnail_cache(){MainWindow w(true);auto&p=w.addProject(example());auto*c=controller(w);const auto count=c->thumbnailRenderCount();check(count>=3,"thumbnail initial renders");c->rebuild();check(c->thumbnailRenderCount()==count,"unchanged rebuild regenerated thumbnails");p.active="a";p.selected={"a"};c->updateSelection();check(c->thumbnailRenderCount()==count,"selection regenerated thumbnail pixels");layer(p,"a").visible=false;c->rebuild();check(c->thumbnailRenderCount()==count,"visibility regenerated thumbnail pixels");layer(p,"b").transform.x+=40;c->rebuild();check(c->thumbnailRenderCount()==count+1,"transform did not invalidate only one thumbnail");check(item(w,"a")->icon(1).actualSize({36,36})==QSize(36,27),"actual panel thumbnail ignores canvas ratio");}
void visibility_swipe(){MainWindow w(true);auto&p=w.addProject(example());w.show();QApplication::processEvents();const auto before=p.document;const auto active=p.active;auto start=eyePoint(w,"c"),middle=eyePoint(w,"b"),last=eyePoint(w,"a");mouse(w,QEvent::MouseButtonPress,start,Qt::LeftButton,Qt::LeftButton);check(!layer(p,"c").visible&&p.history.undoCount()==0,"press must preview first eye in open transaction");mouse(w,QEvent::MouseMove,middle,Qt::NoButton,Qt::LeftButton);mouse(w,QEvent::MouseMove,last,Qt::NoButton,Qt::LeftButton);mouse(w,QEvent::MouseMove,middle,Qt::NoButton,Qt::LeftButton);mouse(w,QEvent::MouseButtonRelease,QPoint(-15,-15),Qt::LeftButton,Qt::NoButton);check(!layer(p,"a").visible&&!layer(p,"b").visible&&!layer(p,"c").visible,"swipe must assign same state without toggling revisited rows");check(p.history.undoCount()==1&&p.history.undoName()=="Hide Layer"&&p.active==active,"eye swipe history or selection changed");const auto undo=p.history.undo();check(undo&&undo->document==before,"eye swipe Undo did not restore exact document");}
void source_cursor_conflict(){MainWindow w(true);auto d=example();for(auto&l:d.layers){l.raster.reset();l.transform={0,0,400,300};}w.addProject(d);w.show();QApplication::processEvents();auto*view=tree(w)->viewport();const auto name=namePoint(w,"c");mouse(w,QEvent::MouseMove,name,Qt::NoButton,Qt::NoButton,Qt::AltModifier);check(view->cursor().shape()==Qt::DragCopyCursor,"source Option name offers duplicate");auto*row=item(w,"c");const auto rect=tree(w)->visualItemRect(row);const auto size=row->icon(1).actualSize({36,36});check(size==QSize(36,27),"source thumbnail takes400x300canvas shape");const QPoint picture(tree(w)->columnViewportPosition(1)+tree(w)->columnWidth(1)/2,rect.center().y());mouse(w,QEvent::MouseMove,picture,Qt::NoButton,Qt::NoButton,Qt::AltModifier);const bool thumbnailAssertion=view->cursor().shape()!=Qt::DragCopyCursor;std::cout<<"SOURCE-TEST-CONFLICT CursorTests.optionOverALayerRowOffersDuplicatingExceptOverThumbnails row_top="<<rect.top()<<" row_height="<<rect.height()<<" thumbnail_center_y="<<picture.y()<<" clipping_boundary="<<rect.bottom()+1-rect.height()/4<<" actual_role="<<view->property("layerCursorRole").toString().toStdString()<<" expected=not-duplicate\n";mouse(w,QEvent::MouseMove,name,Qt::NoButton,Qt::NoButton);check(view->cursor().shape()==Qt::ArrowCursor,"source return to plain name restores arrow");check(thumbnailAssertion,"upstream expected Option at image thumbnail center not duplicate; literal pinned source route gives duplicate");}
void panel_cursors(){MainWindow w(true);auto&p=w.addProject(example());(void)p;w.show();QApplication::processEvents();auto*c=controller(w);auto*view=tree(w)->viewport();const auto name=namePoint(w,"c");view->setCursor(Qt::CrossCursor);mouse(w,QEvent::MouseMove,name,Qt::NoButton,Qt::NoButton);check(view->cursor().shape()==Qt::ArrowCursor,"tool cursor persisted in layer name");view->setCursor(Qt::CrossCursor);c->refreshCursor({},name);check(view->cursor().shape()==Qt::ArrowCursor,"cursor refresh failed to restore arrow");view->setCursor(Qt::CrossCursor);mouse(w,QEvent::MouseMove,name,Qt::NoButton,Qt::NoButton,Qt::ControlModifier);check(view->cursor().shape()==Qt::ArrowCursor,"Ctrl away from thumbnail changed cursor");view->setCursor(Qt::CrossCursor);c->refreshCursor({},QPoint(-50,-50));check(view->cursor().shape()==Qt::CrossCursor,"outside modifier refresh touched other view cursor");mouse(w,QEvent::MouseMove,name,Qt::NoButton,Qt::NoButton,Qt::AltModifier);check(view->cursor().shape()==Qt::DragCopyCursor&&view->property("layerCursorRole")=="duplicate","Alt row name did not offer duplicate");auto*row=item(w,"c");const QPoint picture(tree(w)->columnViewportPosition(1)+tree(w)->columnWidth(1)/2,tree(w)->visualItemRect(row).center().y());mouse(w,QEvent::MouseMove,picture,Qt::NoButton,Qt::NoButton,Qt::ControlModifier);check(view->property("layerCursorRole")=="load-selection","Ctrl image did not offer load selection");mouse(w,QEvent::MouseMove,name,Qt::NoButton,Qt::NoButton);check(view->cursor().shape()==Qt::ArrowCursor,"plain row failed to restore arrow");}
}
int main(int argc,char**argv){QApplication app(argc,argv);app.setFont(QFont("Segoe UI",10));try{check(argc==2,"provide one case");const std::string name=argv[1];if(name=="thumbnail_shapes")thumbnail_shapes();else if(name=="thumbnail_layer_placement")thumbnail_layer_placement();else if(name=="thumbnail_mask_edge")thumbnail_mask_edge();else if(name=="thumbnail_cache")thumbnail_cache();else if(name=="visibility_swipe")visibility_swipe();else if(name=="panel_cursors")panel_cursors();else if(name=="source_cursor_conflict")source_cursor_conflict();else throw std::runtime_error("unknown case");std::cout<<"PASS "<<name<<'\n';return 0;}catch(const std::exception&error){std::cerr<<"FAIL "<<error.what()<<'\n';return 1;}}
