#include "ui/MainWindow.h"
#include <QApplication>
#include <QKeyEvent>
#include <functional>
#include <iostream>
#include <stdexcept>
using namespace compositor;
namespace {
void require(bool condition,const char* message){if(!condition)throw std::runtime_error(message);}
void closeEnough(double a,double b,const char* message){require(std::abs(a-b)<1e-7,message);}
void key(MainWindow& window,int code,Qt::KeyboardModifiers modifiers=Qt::NoModifier){QKeyEvent event(QEvent::KeyPress,code,modifiers);QApplication::sendEvent(&window,&event);}
template<class T>T* control(MainWindow& window,const char* name){auto* value=window.findChild<T*>(name);require(value!=nullptr,"Brush pointer control missing");return value;}
Document example(){Document document;document.id=newId();document.width=64;document.height=48;Layer layer;layer.id=newId();layer.transform={0,0,64,48};layer.raster=Raster::filled(64,48,{0,0,255,255});document.layers.push_back(layer);return document;}
QList<QDoubleSpinBox*> brushTip(MainWindow& window){auto* bar=control<QToolBar>(window,"brushOptions");auto controls=bar->findChildren<QDoubleSpinBox*>();require(controls.size()==3,"Brush settings controls differ");return controls;}
void callbacks(NativeCanvas& canvas){require(bool(canvas.rightPointerDown)&&bool(canvas.rightPointerMove)&&bool(canvas.pointerHover)&&bool(canvas.pointerLeave)&&bool(canvas.navigationAllowed),"Root brush pointer callback missing");}
}
int main(int argc,char** argv){QApplication app(argc,argv);int passed=0,failed=0;auto test=[&](const char* name,const std::function<void()>& run){try{run();++passed;std::cout<<"PASS "<<name<<'\n';}catch(const std::exception& error){++failed;std::cout<<"FAIL "<<name<<": "<<error.what()<<'\n';}};
    test("brush_pointer_right_drag_size_hardness_original_baseline",[]{MainWindow window(true);auto& project=window.addProject(example());auto& canvas=*project.canvas;callbacks(canvas);key(window,Qt::Key_B);auto tip=brushTip(window);tip[0]->setValue(40);tip[1]->setValue(25);canvas.zoomAt(canvas.devicePixelRatioF()*2,{200,150});const auto original=project.document;require(canvas.rightPointerDown({100,100},{}),"Brush right drag refused");canvas.rightPointerMove({120,900},{},false);closeEnough(tip[0]->value(),60,"Size did not follow pointer in DIPs");closeEnough(tip[1]->value(),25,"Vertical movement changed hardness");canvas.rightPointerMove({140,100},Qt::ShiftModifier,false);closeEnough(tip[0]->value(),40,"Shift failed to restore press diameter");closeEnough(tip[1]->value(),45,"Hardness not original plus dx/200");canvas.rightPointerMove({140,-900},{},false);closeEnough(tip[0]->value(),80,"Modifier switch accumulated previous diameter");closeEnough(tip[1]->value(),25,"Size mode failed to restore press hardness");canvas.rightPointerMove({150,100},{},true);require(project.document==original&&project.history.undoCount()==0,"Tip gesture changed document/history");});
    test("brush_pointer_limits_and_tool_tip_families",[]{MainWindow window(true);auto& project=window.addProject(example());auto& canvas=*project.canvas;callbacks(canvas);key(window,Qt::Key_B);auto tip=brushTip(window);tip[0]->setValue(40);canvas.zoomAt(canvas.devicePixelRatioF(),{200,150});require(canvas.rightPointerDown({100,100},{}),"Size press refused");canvas.rightPointerMove({-10000,100},{},false);closeEnough(tip[0]->value(),1,"Minimum diameter");canvas.rightPointerMove({10000,100},{},false);closeEnough(tip[0]->value(),2000,"Maximum diameter");canvas.rightPointerMove({10000,100},{},true);control<QAction>(window,"retouchClone")->trigger();control<QDoubleSpinBox>(window,"retouchDiameter")->setValue(18);require(canvas.rightPointerDown({100,100},{}),"Clone tip press refused");canvas.rightPointerMove({108,100},{},false);closeEnough(control<QDoubleSpinBox>(window,"retouchDiameter")->value(),34,"Clone family tip unchanged");canvas.rightPointerMove({108,100},{},true);key(window,Qt::Key_B);closeEnough(tip[0]->value(),2000,"Clone tip contaminated Brush family");});
    test("brush_pointer_hover_leave_space_and_interruption",[]{MainWindow window(true);auto& project=window.addProject(example());auto& canvas=*project.canvas;callbacks(canvas);key(window,Qt::Key_B);canvas.pointerHover({100,100},{});require(canvas.cursor().shape()==Qt::BlankCursor,"Brush native pointer not hidden behind circle");canvas.pointerLeave();require(canvas.cursor().shape()!=Qt::BlankCursor,"Brush cursor survived leave");canvas.pointerHover({100,100},{});key(window,Qt::Key_Space);require(!canvas.rightPointerDown({100,100},{}),"Space allowed a tip edit");canvas.pointerInterrupted();require(canvas.rightPointerDown({100,100},{}),"Interruption did not clear Space");canvas.pointerInterrupted();require(canvas.cursor().shape()!=Qt::BlankCursor,"Interrupted brush cursor remained hidden");});
    test("brush_pointer_busy_raster_and_transform_navigation_guard",[]{MainWindow window(true);auto& project=window.addProject(example());auto& canvas=*project.canvas;callbacks(canvas);key(window,Qt::Key_B);project.canvas->pointerDown({20,20},{});require(!canvas.navigationAllowed(),"Navigation allowed during brush");require(!canvas.rightPointerDown({100,100},{}),"Tip changed during captured brush");project.canvas->pointerCancel();require(canvas.navigationAllowed(),"Brush cancellation retained navigation lock");key(window,Qt::Key_V);canvas.zoomAt(10,{200,150});control<QCheckBox>(window,"transformSnapping")->setChecked(false);canvas.pointerDown({32,24},{});require(!canvas.navigationAllowed(),"Navigation allowed during transform drag");canvas.pointerCancel();require(canvas.navigationAllowed(),"Transform cancel retained navigation lock");});
    std::cout<<"{\"suite\":\"brush_pointer_ui\",\"passed\":"<<passed<<",\"failed\":"<<failed<<",\"mac_differential\":false,\"visual_acceptance\":false}\n";return failed?1:0;
}
