// Reuse the unchanged actual-window harness and its frozen six before cases.
#define main rememberedSettingsBaseMain
#include "RememberedSettingsTests.cpp"
#undef main
#include "ui/AdjustmentAdvancedControls.h"
#include "imaging/wic_codec.h"
#include <QJsonDocument>
#include <QJsonArray>
#include <QTest>
#include <QMouseEvent>
#include <filesystem>
namespace {
QCheckBox* flag(QDialog& dialog,const char* label){for(auto* c:dialog.findChildren<QCheckBox*>())if(c->text()==label)return c;throw std::runtime_error(std::string("missing checkbox ")+label);}
void pixel_family_bundle(){Fixture f;f.modal("filter.motion",[](QDialog& d){field<QDoubleSpinBox>(d,"Angle")->setValue(23);field<QDoubleSpinBox>(d,"Distance")->setValue(15);},true);
 f.modal("filter.noise",[](QDialog& d){field<QDoubleSpinBox>(d,"Amount")->setValue(29);flag(d,"Gaussian")->setChecked(true);flag(d,"Monochromatic")->setChecked(true);},true);
 f.modal("filter.motion",[](QDialog& d){require(field<QDoubleSpinBox>(d,"Angle")->value()==23&&field<QDoubleSpinBox>(d,"Distance")->value()==15,"another filter preserves motion fields");});
 f.modal("filter.noise",[](QDialog& d){require(field<QDoubleSpinBox>(d,"Amount")->value()==29&&flag(d,"Gaussian")->isChecked()&&flag(d,"Monochromatic")->isChecked(),"noise numeric and both flags restored");});
 f.modal("filter.gaussian",[](QDialog& d){require(field<QDoubleSpinBox>(d,"Radius")->value()==1,"unrelated radius retains source default");});
 f.select(f.b);f.modal("filter.noise",[](QDialog& d){require(field<QDoubleSpinBox>(d,"Amount")->value()==10&&!flag(d,"Gaussian")->isChecked()&&!flag(d,"Monochromatic")->isChecked(),"other project noise defaults");});
}
void neutral_commits(){Fixture f;
 f.modal("filter.lens",[](QDialog& d){field<QDoubleSpinBox>(d,"Distortion")->setValue(15);},true);const auto lensDocument=f.a->document;const auto lensHistory=f.a->history.undoCount();
 f.modal("filter.lens",[](QDialog& d){field<QDoubleSpinBox>(d,"Distortion")->setValue(0);},true);require(f.a->document==lensDocument&&f.a->history.undoCount()==lensHistory&&f.a->toolState.filterSettings.pixels.distortion==15,"neutral lens Apply cancels and retains prior settings");
 f.modal("adjust.exposure",[](QDialog& d){field<QDoubleSpinBox>(d,"Exposure")->setValue(1.25);},true);const auto exposureDocument=f.a->document;const auto exposureHistory=f.a->history.undoCount();
 f.modal("adjust.exposure",[](QDialog& d){field<QDoubleSpinBox>(d,"Exposure")->setValue(0);},true);require(f.a->document==exposureDocument&&f.a->history.undoCount()==exposureHistory&&f.a->toolState.filterSettings.exposure["exposure"].toDouble()==1.25,"neutral exposure Apply retains applied1.25");
 f.modal("adjust.grain",[](QDialog& d){field<QDoubleSpinBox>(d,"Amount")->setValue(38);},true);const auto grainDocument=f.a->document;const auto grainHistory=f.a->history.undoCount();
 f.modal("adjust.grain",[](QDialog& d){field<QDoubleSpinBox>(d,"Amount")->setValue(0);},true);require(f.a->document==grainDocument&&f.a->history.undoCount()==grainHistory&&f.a->toolState.filterSettings.grain["amount"].toDouble()==38,"zero grain Apply retains applied38");
}
void curves_grain(){Fixture f;f.modal("adjust.curves",[](QDialog& d){field<QComboBox>(d,"curvesChannel")->setCurrentIndex(2);auto* graph=field<QWidget>(d,"curvesGraph");QTest::mouseClick(graph,Qt::LeftButton,{},QPoint(graph->width()/2,graph->height()/3));},true);
 const auto saved=f.a->toolState.filterSettings.curves;require(saved["channel"].toString()=="Green"&&saved["channels"].toArray()[2].toArray().size()==3,"curve channel and inserted graph point remembered");
 f.modal("adjust.curves",[&](QDialog& d){require(field<QComboBox>(d,"curvesChannel")->currentIndex()==2,"remembered graph channel visible");const auto json=QJsonDocument::fromJson(QByteArray::fromStdString(dynamic_cast<CurvesAdvancedControls*>(field<QWidget>(d,"curvesAdvancedControls"))->adjustmentJson())).object();require(json["curves"].toObject()==saved,"all saved curve points restored");});
 f.modal("adjust.grain",[](QDialog& d){field<QDoubleSpinBox>(d,"Amount")->setValue(31);field<QDoubleSpinBox>(d,"Size")->setValue(2.75);field<QDoubleSpinBox>(d,"Roughness")->setValue(67);},true);
 f.modal("adjust.grain",[](QDialog& d){require(field<QDoubleSpinBox>(d,"Amount")->value()==31&&field<QDoubleSpinBox>(d,"Size")->value()==2.75&&field<QDoubleSpinBox>(d,"Roughness")->value()==67,"all three grain controls restored");});require(f.a->toolState.filterSettings.curves==saved,"grain preserves curves");
 f.select(f.b);f.modal("adjust.curves",[](QDialog& d){require(field<QComboBox>(d,"curvesChannel")->currentIndex()==0,"other project default RGB curve");});f.select(f.a);require(f.a->toolState.filterSettings.curves==saved,"curve points survive tab roundtrip");
}
void gradient_palette(){Fixture f;f.select(f.b);f.a->toolState.foreground=QColor(255,0,0);f.a->toolState.background=QColor(0,0,255);f.select(f.a);
 f.modal("adjust.gradient_map",[](QDialog& d){bool red=false,blue=false;for(auto* button:d.findChildren<QPushButton*>()){red|=button->text()=="#ff0000";blue|=button->text()=="#0000ff";}require(red&&blue&&!flag(d,"Reverse")->isChecked(),"gradient starts from project foreground/background");flag(d,"Reverse")->setChecked(true);},true);
 require(f.a->toolState.filterSettings.gradientMap["reversed"].toBool(),"applied gradient map stored");f.select(f.b);f.a->toolState.foreground=QColor(0,255,0);f.a->toolState.background=QColor(255,255,0);f.select(f.a);
 f.modal("adjust.gradient_map",[](QDialog& d){bool green=false,yellow=false;for(auto* button:d.findChildren<QPushButton*>()){green|=button->text()=="#00ff00";yellow|=button->text()=="#ffff00";}require(green&&yellow&&!flag(d,"Reverse")->isChecked(),"new Gradient Map discards remembered endpoints and reverse for current palette");});require(f.a->toolState.filterSettings.gradientMap["reversed"].toBool(),"Cancel does not replace remembered map");
}
void live_independence(){Fixture f;f.modal("adjust.exposure",[](QDialog& d){field<QDoubleSpinBox>(d,"Exposure")->setValue(1.5);},true);const auto saved=f.a->toolState.filterSettings.exposure;
 f.modal("adjust.new.exposure",[](QDialog& d){require(field<QDoubleSpinBox>(d,"Exposure")->value()==0,"new live adjustment starts neutral");field<QDoubleSpinBox>(d,"Exposure")->setValue(2.5);},true);require(f.a->toolState.filterSettings.exposure==saved,"live Apply does not overwrite destructive filter memory");
 f.modal("adjust.edit",[](QDialog& d){require(field<QDoubleSpinBox>(d,"Exposure")->value()==2.5,"existing live adjustment uses layer metadata");field<QDoubleSpinBox>(d,"Exposure")->setValue(3.5);},true);require(f.a->toolState.filterSettings.exposure==saved,"edit live Apply does not overwrite destructive memory");
}
void crop_apply_ratio(){Fixture f;const auto original=f.a->document->layers.front().raster;f.trigger("tool.crop");field<QComboBox>(f.window,"cropRatioChoice")->setCurrentText("4:3");f.trigger("crop.apply");require(f.a->document->width==40&&f.a->document->height==30,"crop ratio keeps width and changes height around middle");require(f.a->document->layers.front().transform.y==5&&f.a->document->layers.front().raster==original,"crop ratio expansion moves placement without resampling");require(f.a->history.undoCount()==1,"Apply Crop one undo entry");}
void crop_full_frame_create(){Fixture f;f.window.show();QApplication::processEvents();const auto before=f.a->document;f.trigger("tool.crop");auto send=[&](QEvent::Type type,Point point){auto* canvas=f.a->canvas;const auto view=canvas->viewMapping().toView(point);const QPointF at(view.x,view.y);QMouseEvent event(type,at,canvas->mapToGlobal(at.toPoint()),Qt::LeftButton,type==QEvent::MouseButtonRelease?Qt::NoButton:Qt::LeftButton,Qt::NoModifier);QApplication::sendEvent(canvas,&event);};send(QEvent::MouseButtonPress,{10,5});send(QEvent::MouseMove,{30,15});send(QEvent::MouseButtonRelease,{30,15});require(f.a->document==before&&f.a->history.undoCount()==0,"crop gesture preview leaves canonical document unchanged");f.trigger("crop.apply");std::cout<<"full_frame_drag_result="<<f.a->document->width<<'x'<<f.a->document->height<<'\n';require(f.a->document->width==20&&f.a->document->height==10,"EditorCanvas1750 full-frame interior drag creates a smaller crop");require(f.a->history.undoCount()==1,"created crop has one history entry");}
void amount_controls(){Fixture f;f.a->document->selection=editing::rasterSelection(editing::SelectionOutline::rectangle({10,5,10,6}),40,20);f.trigger("tool.marquee");auto* expand=field<QSpinBox>(f.window,"selectionExpandAmount");auto* contract=field<QSpinBox>(f.window,"selectionContractAmount");require(expand->isEnabled()&&contract->isEnabled(),"amount controls enabled with selection");expand->setValue(3);contract->setValue(2);auto* bar=f.window.findChild<QToolBar*>("selectionOptions");bool invoked=false;for(auto* action:bar->actions())if(action->text()=="Expand"){action->trigger();invoked=true;break;}require(invoked&&f.a->history.undoCount()==1,"direct Expand button performs one selection edit");auto bounds=editing::coverageBounds(*f.a->document->selection->coverage);require(bounds.x==7&&bounds.y==2&&bounds.width==16&&bounds.height==12,"Expand button uses remembered3 pixels");f.trigger("selection.deselect");require(!expand->isEnabled()&&!contract->isEnabled()&&expand->value()==3&&contract->value()==2,"disabled controls retain independent amounts");}
void background_remembering(){Fixture f;auto root=std::filesystem::path(__FILE__).parent_path().parent_path().parent_path();const auto source=imaging::WicCodec::decode(root/L"evidence/imaging/astronaut.png").image;auto& layer=f.a->document->layers.front();layer.raster=Raster::fromRgba(int(source.width),int(source.height),source.pixels.data(),source.stride);layer.transform={0,0,40,20};f.trigger("tool.move");
 bool configured=false,applied=false,finished=false;std::exception_ptr failure;QPointer<QDialog> panel;QMetaObject::Connection completion;QEventLoop wait;QTimer poll;poll.setInterval(20);QElapsedTimer elapsed;elapsed.start();
 QObject::connect(&poll,&QTimer::timeout,&f.window,[&]{try{if(elapsed.elapsed()>30000)throw std::runtime_error("background Apply exceeded frozen30-second deadline");if(!panel){for(auto* candidate:f.window.findChildren<QDialog*>())if(candidate->objectName()=="subjectPanel"&&candidate->isVisible()){panel=candidate;completion=QObject::connect(panel,&QDialog::finished,&wait,[&]{finished=true;wait.quit();});break;}}auto* dialog=panel.data();if(!dialog)return;
  if(!configured){configured=true;require(field<QComboBox>(*dialog,"backgroundQuality")->currentIndex()==0&&field<QDoubleSpinBox>(*dialog,"Refine")->value()==12&&field<QDoubleSpinBox>(*dialog,"Contrast")->value()==25&&field<QDoubleSpinBox>(*dialog,"Shift Edge")->value()==0,"source background defaults");field<QComboBox>(*dialog,"backgroundQuality")->setCurrentIndex(1);field<QDoubleSpinBox>(*dialog,"Refine")->setValue(3);field<QDoubleSpinBox>(*dialog,"Contrast")->setValue(41);field<QDoubleSpinBox>(*dialog,"Shift Edge")->setValue(-2);}
  auto* apply=field<QPushButton>(*dialog,"applySubjectMask");if(!applied&&apply->isEnabled()){applied=true;apply->click();}
  if(elapsed.elapsed()>30000)throw std::runtime_error("background Apply exceeded frozen30-second deadline");
 }catch(...){failure=std::current_exception();poll.stop();if(panel)panel->reject();wait.quit();}});poll.start();f.trigger("filter.subject");if(!finished&&!failure)wait.exec();poll.stop();QObject::disconnect(completion);if(failure)std::rethrow_exception(failure);require(configured&&applied&&f.a->document->layers.front().mask.has_value(),"real provider and Apply complete");
 const auto& remembered=f.a->toolState.filterSettings.background;require(remembered.advanced&&remembered.refineEdges==3&&remembered.contrast==41&&remembered.shiftEdge==-2,"full background tuple remembered");
 require(f.a->maskSelected,"Filters469 selects the committed background mask");f.trigger("mask.edit_image");
 f.modal("filter.subject",[](QDialog& d){require(field<QComboBox>(d,"backgroundQuality")->currentIndex()==1&&field<QDoubleSpinBox>(d,"Refine")->value()==3&&field<QDoubleSpinBox>(d,"Contrast")->value()==41&&field<QDoubleSpinBox>(d,"Shift Edge")->value()==-2,"background controls reopen applied state");field<QDoubleSpinBox>(d,"Refine")->setValue(9);});require(remembered.refineEdges==3,"Cancel retains applied background state");f.select(f.b);require(!f.b->toolState.filterSettings.background.advanced&&f.b->toolState.filterSettings.background.refineEdges==12,"background project isolation");
}
}
int main(int argc,char** argv){QApplication app(argc,argv);const std::map<std::string,void(*)()> cases{{"pixel_family_bundle",pixel_family_bundle},{"neutral_commits",neutral_commits},{"curves_grain",curves_grain},{"gradient_palette",gradient_palette},{"live_independence",live_independence},{"crop_apply_ratio",crop_apply_ratio},{"crop_full_frame_create",crop_full_frame_create},{"amount_controls",amount_controls},{"background_remembering",background_remembering}};try{require(argc==2&&cases.contains(argv[1]),"provide named case");cases.at(argv[1])();std::cout<<"PASS "<<argv[1]<<'\n';return 0;}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<'\n';return 1;}}
