#include "ui/ImportActions.h"
#include "ui/WorkspaceDropQueue.h"
#include "ui/MainWindow.h"
#include "imaging/wic_codec.h"
#include <QApplication>
#include <QDragEnterEvent>
#include <QDropEvent>
#include <QElapsedTimer>
#include <QFile>
#include <QMessageBox>
#include <QMimeData>
#include <QProgressDialog>
#include <QTemporaryDir>
#include <QTest>
#include <QThread>
#include <QUrl>
#include <atomic>
#include <cmath>
#include <iostream>
#include <map>
using namespace compositor;
namespace {
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
void until(const std::function<bool()>& ready){QElapsedTimer timer;timer.start();while(!ready()){if(timer.elapsed()>15000)throw std::runtime_error("Import test timed out");QTest::qWait(5);}QApplication::processEvents();}
std::filesystem::path path(const QString&s){return std::filesystem::path(s.toStdWString());}
QString image(const QString& directory,const QString& name,int width=64,int height=32){
    imaging::RgbaImage rgba{uint32_t(width),uint32_t(height),size_t(width)*4,std::vector<uint8_t>(size_t(width)*height*4)};
    for(int y=0;y<height;++y)for(int x=0;x<width/2;++x){auto*i=&rgba.pixels[size_t(y)*rgba.stride+x*4];i[0]=i[3]=255;}
    auto filename=directory+"/"+name;imaging::WicCodec::encode(path(filename),rgba);return filename;
}
Document document(int width=128,int height=128){Document d;d.id=newId();d.width=width;d.height=height;return d;}
struct Fixture {
    QObject target;ui::ImportState state;History history;bool blocked{},working{};int commits{},completions{},cancellations{};QStringList errors;
    ui::ImportQueue::Host host(){return {
        [this](QObject* who)->std::optional<ui::ImportState>{require(QThread::currentThread()==qApp->thread(),"Snapshot left GUI thread");return who==&target?std::optional(state):std::nullopt;},
        [this](QObject*){return blocked;},
        [this](QObject*,bool value){require(QThread::currentThread()==qApp->thread(),"Busy left GUI thread");working=value;},
        [this](QObject*,const ui::ImportResult&r){require(QThread::currentThread()==qApp->thread(),"Commit left GUI thread");if(state!=r.before)throw std::runtime_error("Destination changed");history.begin("Import Images",state.document,state.active);state=r.after;history.end(state.document,state.active);++commits;},
        [this](QObject*,const ui::ImportResult&r){require(QThread::currentThread()==qApp->thread(),"Completion left GUI thread");++completions;cancellations+=r.cancelled?1:0;errors.append(r.errors);}
    };}
};
bool drop(MainWindow&w,const QMimeData& mime,QPoint point){QDragEnterEvent enter(point,Qt::CopyAction,&mime,Qt::LeftButton,Qt::NoModifier);QApplication::sendEvent(&w,&enter);if(!enter.isAccepted())return false;QDropEvent event(point,Qt::CopyAction,&mime,Qt::LeftButton,Qt::NoModifier);QApplication::sendEvent(&w,&event);return event.isAccepted();}
void finish(MainWindow&w){auto*q=ui::ImportQueue::find(&w);require(q,"Missing actual UI import queue");until([&]{auto*d=ui::WorkspaceDropQueue::find(&w);return q->idle()&&(!d||d->idle());});for(auto*m:w.findChildren<QMessageBox*>())m->accept();QApplication::processEvents();}
QPoint canvasPoint(MainWindow&w,Point p){auto*c=w.canvas();const auto view=c->viewMapping().toView(p);return c->mapTo(&w,QPoint(int(std::round(view.x)),int(std::round(view.y))));}
}
int main(int argc,char**argv){QApplication app(argc,argv);int passed=0,failed=0;auto test=[&](const char* name,const std::function<void()>&run){try{run();++passed;std::cout<<"PASS "<<name<<'\n';}catch(const std::exception&e){++failed;std::cout<<"FAIL "<<name<<": "<<e.what()<<'\n';}};
    QTemporaryDir temporary;require(temporary.isValid(),"Missing temporary fixture directory");const auto first=image(temporary.path(),QString::fromUtf8("first-画像.png")),second=image(temporary.path(),"second.png"),missing=temporary.path()+"/missing.png";
    test("source_empty_partial_failure_one_undo",[&]{Fixture f;ui::ImportQueue q(f.host());q.enqueue(&f.target,{{path(first),path(missing),path(second)},Point{999,999}});until([&]{return q.idle();});require(f.state.document&&f.state.document->width==64&&f.state.document->height==32&&f.state.document->resolution==72,"First successful image dimensions/default DPI wrong");require(f.state.document->layers.size()==2&&f.state.document->layers[0].transform.x==0&&f.state.document->layers[0].transform.y==0,"Empty batch did not ignore drop point");require(f.state.document->layers[0].name==QString::fromUtf8("first-画像").toStdString()&&f.state.document->layers[1].name=="second","Provider order or Unicode basename lost");require(f.state.active==f.state.document->layers.back().id&&f.errors.size()==1&&!f.working,"Active/error/import state wrong");require(f.history.undoCount()==1,"Batch made more than one history entry");auto imported=f.state.document;auto pixels=imported->layers[0].raster;f.state.document=f.history.undo()->document;require(!f.state.document,"Undo did not restore empty project");auto redo=f.history.redo();f.state={redo->document,redo->activeLayer};require(f.state.document==imported&&f.state.document->layers[0].raster==pixels,"Redo lost original immutable imported pixels");q.enqueue(&f.target,{{path(missing)}});until([&]{return q.idle();});require(f.history.undoCount()==1&&f.commits==1,"All-failed batch added history");});
    test("source_floor_drop_parent_and_aggregate_budget",[&]{auto d=document(1000,800);Layer group;group.id="folder";group.group=true;group.transform={0,0,1000,800};d.layers={group};ui::ImportState before{d,"folder"};auto result=ui::prepareImportBatch(before,{{path(first),path(second)},Point{300.9,250.9}});require(result.after.document->layers[1].transform.x==268&&result.after.document->layers[1].transform.y==234,"Drop did not floor center minus half-size");require(result.after.document->layers[1].parentId=="folder"&&result.after.document->layers[2].parentId=="folder"&&result.expandedGroups.size()==2,"Active parent did not carry through ordered batch");require(before.document==d&&d.layers.size()==1,"Preparation mutated original");imaging::ImportOptions options;options.remainingPixels=4096;result=ui::prepareImportBatch({},{{path(first),path(second),path(first)}},ui::decodeImportImage,options);require(result.imported==2&&result.errors.size()==1,"Aggregate image budget not applied between files");});
    test("fifo_queued_batches_separate_undo_and_worker_thread",[&]{Fixture f;std::atomic_bool release{},entered{};auto decoder=[&](const auto&p,const auto&o){require(QThread::currentThread()!=qApp->thread(),"Decode ran on GUI thread");entered=true;while(!release&&!o.cancelled())QThread::msleep(1);return ui::decodeImportImage(p,o);};ui::ImportQueue q(f.host(),nullptr,decoder);q.enqueue(&f.target,{{path(first)}});q.enqueue(&f.target,{{path(second)}});until([&]{return entered.load();});require(q.busy(&f.target)&&q.contains(&f.target)&&!f.state.document,"Queued work exposed a partial document");release=true;until([&]{return q.idle();});require(f.completions==2&&f.history.undoCount()==2&&f.state.document->layers.size()==2,"FIFO lost a batch");require(f.history.undo()->document->layers.size()==1&&!f.history.undo()->document,"Queued batches did not undo separately");});
    test("project_busy_defers_and_cancel_discards_original",[&]{Fixture f;f.state.document=document();f.blocked=true;auto original=f.state;ui::ImportQueue q(f.host());q.enqueue(&f.target,{{path(first),path(second)}});QTest::qWait(60);require(!q.busy()&&!f.working&&f.state==original,"Project busy did not defer decoding");q.cancel(&f.target);require(q.idle()&&f.cancellations==1&&f.state==original&&f.history.undoCount()==0,"Queued cancellation changed state");f.blocked=false;q.enqueue(&f.target,{{path(first),path(second)}});q.cancel(&f.target);until([&]{return q.idle();});require(f.cancellations==2&&f.state==original&&f.history.undoCount()==0,"Active cancellation committed prepared images");});
    test("stale_destination_and_destroyed_target_do_not_commit",[&]{Fixture f;std::atomic_bool release{},entered{};auto decoder=[&](const auto&p,const auto&o){entered=true;while(!release&&!o.cancelled())QThread::msleep(1);return ui::decodeImportImage(p,o);};ui::ImportQueue q(f.host(),nullptr,decoder);q.enqueue(&f.target,{{path(first)}});until([&]{return entered.load();});f.state.document=document(77,33);release=true;until([&]{return q.idle();});require(f.state.document->width==77&&f.commits==0&&f.errors.size()==1,"Stale worker overwrote changed destination");QObject* target=new QObject;bool callback=false;auto host=f.host();host.snapshot=[&](QObject*){return std::optional(ui::ImportState{});};host.busy=[](QObject*,bool){};host.commit=[&](QObject*,const auto&){callback=true;};host.completed=[&](QObject*,const auto&){callback=true;};release=false;entered=false;ui::ImportQueue dead(host,nullptr,decoder);dead.enqueue(target,{{path(first)}});until([&]{return entered.load();});delete target;release=true;until([&]{return dead.idle();});require(!callback,"Destroyed target received worker completion");});
    test("real_wic_exif_and_profile_required_fixtures",[&]{const auto fixtures=std::filesystem::path(__FILE__).parent_path().parent_path().parent_path()/"evidence"/"imaging";auto oriented=fixtures/"orientation-6.tif";require(std::filesystem::is_regular_file(oriented),"Required EXIF fixture absent");const auto result=ui::prepareImportBatch({},{{oriented}});require(result.imported==1&&result.after.document->width==2&&result.after.document->height==3,"Import batch lost WIC EXIF orientation");auto profile=fixtures/"adobe-rgb.png";require(std::filesystem::is_regular_file(profile),"Required profile fixture absent");require(ui::decodeImportImage(profile,{}).metadata.profileStatus==imaging::ProfileStatus::ConvertedEmbeddedProfile,"Embedded profile was not normalized");});
    test("qt_canvas_batch_drop_document_coordinates_and_history",[&]{MainWindow w(true);auto&p=w.addProject(document(1000,800));w.show();QApplication::processEvents();w.canvas()->zoomAt(.75,w.canvas()->rect().center());w.canvas()->panBy({70,-35});const auto where=canvasPoint(w,{300,250});const auto actual=w.canvas()->documentPoint(w.canvas()->mapFrom(&w,where));QMimeData mime;mime.setUrls({QUrl::fromLocalFile(first),QUrl::fromLocalFile(second)});require(drop(w,mime,where),"Native drop rejected");finish(w);require(p.document->layers.size()==2&&p.history.undoCount()==2,"Source workspace drop must create one undo step per URL");const auto&l=p.document->layers[0];require(l.transform.x==std::floor(actual.x()-32)&&l.transform.y==std::floor(actual.y()-16),"Native canvas drop did not convert viewport coordinates");require(p.active==p.document->layers.back().id&&!p.maskSelected,"Import did not select final image target");});
    test("qt_cancel_preserves_existing_document_and_undo",[&]{MainWindow w(true);auto d=document();Layer old;old.id="old";old.transform={0,0,128,128};old.raster=Raster::filled(128,128,{20,30,40,255});d.layers={old};auto&p=w.addProject(d);w.show();QApplication::processEvents();const auto before=p.document;QMimeData mime;mime.setUrls({QUrl::fromLocalFile(first),QUrl::fromLocalFile(second)});require(drop(w,mime,canvasPoint(w,{64,64})),"Cancel test drop rejected");auto*q=ui::ImportQueue::find(&w);require(q,"Queue absent");q->cancel(p.canvas);finish(w);require(p.document==before&&p.history.undoCount()==0&&!p.importing,"Cancelled native import altered original/history");});
    test("qt_bitmap_drop_lifetime_and_empty_tab_external_routing",[&]{MainWindow w(true);auto&p=w.addProject(document());w.show();QApplication::processEvents();QImage bitmap(8,6,QImage::Format_ARGB32);bitmap.fill(QColor(255,0,0,128));{QMimeData mime;mime.setImageData(bitmap);require(drop(w,mime,canvasPoint(w,{64,64})),"Bitmap drop rejected");}finish(w);require(p.document->layers.size()==1&&p.document->layers[0].raster->width==8&&p.document->layers[0].raster->pixel(0,0)==Pixel{128,0,0,128},"Copied bitmap lifetime/premultiplication failed");MainWindow external(true);external.openPath(first);external.openPath(second);finish(external);auto*tabs=external.findChild<QTabWidget*>();require(tabs&&tabs->count()==2,"Rapid external images reused an already reserved empty tab");});
    test("default_100mp_budget_side_and_corrupt_partial_failure",[&]{auto d=document();Layer full;full.id="full-budget";full.transform={0,0,10000,10000};full.raster=Raster::filled(10000,10000);d.layers={full};ui::ImportState before{d,full.id};auto result=ui::prepareImportBatch(before,{{path(first)}});require(result.imported==0&&result.errors.size()==1&&result.after==before,"100MP document limit underflowed or changed original");imaging::ImportOptions tiny;tiny.maxSide=63;result=ui::prepareImportBatch({},{{path(first)}},ui::decodeImportImage,tiny);require(result.imported==0&&result.errors.size()==1,"Side budget bypassed by batch decoder");auto corrupt=temporary.filePath("corrupt.jpg");QFile file(corrupt);require(file.open(QIODevice::WriteOnly)&&file.write("not an image")==12,"Could not write corrupt fixture");file.close();result=ui::prepareImportBatch({},{{path(corrupt),path(first)}});require(result.imported==1&&result.errors.size()==1&&result.after.document->width==64,"Corrupt first image prevented later success");});
    test("qt_prebusy_bitmap_rejected_without_mutation",[&]{MainWindow w(true);auto&p=w.addProject(document());w.show();QApplication::processEvents();p.projectBusy=true;const auto before=p.document;QImage bitmap(7,5,QImage::Format_ARGB32);bitmap.fill(Qt::green);{QMimeData mime;mime.setImageData(bitmap);require(!drop(w,mime,canvasPoint(w,{64,64})),"ContentView102 must reject a prebusy bitmap drop");}require(ui::ImportQueue::find(&w)==nullptr,"Rejected bitmap must not allocate an import queue");QTest::keyClick(&w,Qt::Key_N,Qt::ControlModifier);QTest::keyClick(&w,Qt::Key_Z,Qt::ControlModifier);QTest::qWait(40);require(p.document==before&&p.history.undoCount()==0,"Busy native commands mutated the project");p.projectBusy=false;require(p.document->layers.empty(),"Rejected bitmap appeared after the busy state cleared");});
    std::cout<<"IMPORT_UI_SUMMARY passed="<<passed<<" failed="<<failed<<'\n';return failed?1:0;
}
