#include "ui/MainWindow.h"
#include "ui/CommandRegistry.h"
#include <QApplication>
#include <QFont>
#include <QJsonDocument>
#include <QLineEdit>
#include <QMenu>
#include <QMenuBar>
#include <QTest>
#include <QJsonObject>
#include <QSet>
#include <QToolButton>
#include <QWidgetAction>
#include <iostream>
#include <stdexcept>
using namespace compositor;
namespace {
void check(bool value,const char*why){if(!value)throw std::runtime_error(why);}
ui::CommandRegistry& registry(MainWindow&w){for(auto*object:w.findChildren<QObject*>())if(auto*r=dynamic_cast<ui::CommandRegistry*>(object))return *r;throw std::runtime_error("registry not installed");}
QAction*command(MainWindow&w,const char*id){for(auto*action:w.findChildren<QAction*>())if(action->property("commandId").toString()==id)return action;throw std::runtime_error(std::string("missing registered command ")+id);}
Document example(bool raster=true,bool visible=true){Document d;d.id=newId();d.width=96;d.height=64;Layer layer;layer.id=newId();layer.name="Image";layer.transform={0,0,96,64};layer.visible=visible;if(raster)layer.raster=Raster::filled(96,64,{140,70,35,255});d.layers.push_back(layer);return d;}
void gradient(MainWindow&w,EditorProject&p){command(w,"tool.gradient")->trigger();p.canvas->pointerDown({8,30},{});p.canvas->pointerMove({80,30},{});p.canvas->pointerUp({80,30},{});registry(w).refresh();check(command(w,"gradient.apply")->isEnabled(),"gradient was not left pending");}
void registered_actions(){MainWindow w(true);w.addProject(example());for(auto*object:w.findChildren<QObject*>())check(!object->property("unregisteredCommand").toBool(),"host requested an uncatalogued command");size_t leaves=0;for(auto*menu:w.findChildren<QMenu*>())for(auto*action:menu->actions())if(!action->menu()&&!action->isSeparator()){++leaves;check(!action->property("commandId").toString().isEmpty(),"menu leaf has no command id");}check(leaves>65,"menu inventory unexpectedly small");auto*tools=w.findChild<QToolBar*>("tools");check(tools,"tools toolbar missing");size_t paletteContainers=0;for(auto*action:tools->actions()){
    auto* container=qobject_cast<QWidgetAction*>(action);
    if(!container){check(!action->property("commandId").toString().isEmpty(),"tool rail action unregistered");continue;}
    auto* widget=container->defaultWidget();check(widget&&widget->objectName()=="paletteSwatches","unexpected tool rail widget container");++paletteContainers;
    QSet<QString> ids;const auto buttons=widget->findChildren<QToolButton*>();check(buttons.size()==4,"palette container must expose exactly four actionable controls");
    for(auto*button:buttons){auto* leaf=button->defaultAction();check(leaf,"palette control has no default action");const auto id=leaf->property("commandId").toString();check(!id.isEmpty()&&ui::commandSpecById(id),"palette control action is not catalogued");bool bound=false;for(const auto& entry:registry(w).manifest()){const auto object=entry.toObject();if(object["id"].toString()==id&&object["object_name"].toString()==leaf->objectName())bound=true;}check(bound,"palette control action is not registered");ids.insert(id);}
    check(ids==QSet<QString>{"palette.foreground","palette.background","palette.swap","palette.defaults"},"palette container commands are not the exact four source controls");
}check(paletteContainers==1,"palette tool rail container missing");std::cout<<"registered_actions="<<registry(w).manifest().size()<<" menu_leaves="<<leaves<<'\n';}
void pending_gradient_undo(){MainWindow w(true);auto&p=w.addProject(example());command(w,"layer.new")->trigger();check(p.history.undoCount()==1,"setup new layer history");const auto before=p.document;gradient(w,p);check(p.history.undoCount()==1&&command(w,"edit.undo")->isEnabled(),"pending gradient history eligibility");command(w,"edit.undo")->trigger();check(p.document==before&&p.history.undoCount()==1&&!command(w,"gradient.apply")->isEnabled(),"Undo must cancel gradient without undoing prior layer");command(w,"edit.undo")->trigger();check(p.document->layers.size()==1&&p.history.undoCount()==0,"second Undo should undo previous layer edit");}
void blocked_layers(){MainWindow w(true);auto&p=w.addProject(example());const auto before=p.document;gradient(w,p);const auto count=w.findChild<QTabWidget*>()->count();for(const char*id:{"layer.new","layer.group","layer.duplicate","selection.all","file.new","file.open","file.close"}){check(!command(w,id)->isEnabled(),"pending gradient command unexpectedly enabled");check(!registry(w).invoke(id),"pending gradient accepted blocked command");}check(w.findChild<QTabWidget*>()->count()==count&&p.history.undoCount()==0,"blocked commands changed workspace/history");command(w,"gradient.cancel")->trigger();check(p.document==before&&command(w,"layer.new")->isEnabled(),"cancel did not restore command eligibility");}
void import_busy(){MainWindow w(true);auto&p=w.addProject(example());const auto before=p.document;for(bool busy:{false,true}){p.importing=!busy;p.projectBusy=busy;registry(w).refresh();for(const char*id:{"layer.new","edit.undo","adjust.levels","tool.brush","file.save","selection.all"})check(!command(w,id)->isEnabled(),"import/busy command remained enabled");check(!registry(w).invoke("pixels.invert")&&p.document==before,"busy activation edited pixels");}p.importing=p.projectBusy=false;registry(w).refresh();check(command(w,"adjust.levels")->isEnabled(),"idle adjustment did not recover");}
void blank_hidden_transform(){for(auto pair:{std::pair{false,true},std::pair{true,false},std::pair{true,true}}){MainWindow w(true);auto&p=w.addProject(example(pair.first,pair.second));(void)p;check(command(w,"transform.free")->isEnabled()==(pair.first&&pair.second),"blank/hidden transform enablement mismatch");}}
void text_focus(){MainWindow w(true);auto&p=w.addProject(example());command(w,"layer.new")->trigger();const auto before=p.document;QLineEdit field(&w);field.setGeometry(300,100,220,30);w.show();field.show();field.setFocus();QApplication::processEvents();QTest::keyClicks(&field,"bml");check(field.text()=="bml"&&p.document==before,"document shortcut stole typed letters");QTest::keyClick(&field,Qt::Key_A,Qt::ControlModifier);check(field.selectedText()=="bml"&&!p.document->selection,"Select All escaped text field");QTest::keyClick(&field,Qt::Key_Z,Qt::ControlModifier);check(field.text().isEmpty()&&p.document==before&&p.history.undoCount()==1,"Undo escaped text field into document history");QTest::keyClicks(&field,"again");registry(w).invoke("selection.all");registry(w).invoke("clipboard.cut");check(field.text().isEmpty()&&p.document==before,"menu Cut escaped text field");}
void transform_draft(){MainWindow w(true);auto&p=w.addProject(example());const auto before=p.document;command(w,"transform.free")->trigger();check(command(w,"transform.apply")->isEnabled()&&!command(w,"edit.undo")->isEnabled()&&!command(w,"layer.new")->isEnabled(),"persistent transform gates");check(command(w,"transform.distort")->isEnabled(),"existing affine cannot become Distort");command(w,"transform.distort")->trigger();check(command(w,"transform.apply")->isEnabled()&&p.history.undoCount()==0,"draft distortion prematurely committed");command(w,"transform.cancel")->trigger();check(p.document==before&&p.history.undoCount()==0,"Cancel transform did not restore exact document");}
}
int main(int argc,char**argv){QApplication app(argc,argv);app.setFont(QFont("Segoe UI",10));try{check(argc==2,"one test name required");const std::string name=argv[1];if(name=="registered_actions")registered_actions();else if(name=="pending_gradient_undo")pending_gradient_undo();else if(name=="blocked_layers")blocked_layers();else if(name=="import_busy")import_busy();else if(name=="blank_hidden_transform")blank_hidden_transform();else if(name=="text_focus")text_focus();else if(name=="transform_draft")transform_draft();else throw std::runtime_error("unknown case");std::cout<<"PASS "<<name<<'\n';return 0;}catch(const std::exception&error){std::cerr<<"FAIL "<<error.what()<<'\n';return 1;}}
