#include "ui/MainWindow.h"
#include <QApplication>
#include <QKeyEvent>
#include <iostream>
#include <map>
#include <stdexcept>
using namespace compositor;
#define REQUIRE(...) do{if(!(__VA_ARGS__))throw std::runtime_error(std::string("line ")+std::to_string(__LINE__)+": " #__VA_ARGS__);}while(false)
Document fixture(){Document d;d.id="shape-witness";d.width=100;d.height=80;for(const char* id:{"bottom","middle","top"}){Layer l;l.id=id;l.name=id;l.transform={0,0,8,8};l.raster=Raster::filled(8,8,{50,60,70,255});d.layers.push_back(l);}return d;}
void shapeTool(MainWindow& w){for(auto* action:w.findChildren<QAction*>())if(action->text()=="Shape (U)"){action->trigger();return;}throw std::runtime_error("Shape tool absent");}
QDoubleSpinBox* radius(MainWindow&w){for(auto* value:w.findChildren<QDoubleSpinBox*>())if(value->accessibleName()=="Corner radius")return value;throw std::runtime_error("Shape radius absent");}
QComboBox* kind(MainWindow&w){auto* value=w.findChild<QComboBox*>("shapeKind");REQUIRE(value);return value;}
void down(EditorProject&p,Point at){p.canvas->pointerDown({at.x,at.y},{});}
void move(EditorProject&p,Point at,Qt::KeyboardModifiers flags={}){p.canvas->pointerMove({at.x,at.y},flags);}
void up(EditorProject&p,Point at,Qt::KeyboardModifiers flags={}){p.canvas->pointerUp({at.x,at.y},flags);}
void draw(EditorProject&p,Point start={10,12},Point end={20,24},Qt::KeyboardModifiers flags={}){down(p,start);move(p,end,flags);up(p,end,flags);}
const Layer& added(const EditorProject&p){auto it=std::find_if(p.document->layers.begin(),p.document->layers.end(),[&](const Layer& l){return l.id==p.active;});REQUIRE(it!=p.document->layers.end()&&!it->shapeJson.empty());return *it;}
void shape_insert_sibling(){MainWindow w(true);auto d=fixture();auto&p=w.addProject(d);p.active="middle";p.selected={p.active};shapeTool(w);draw(p);REQUIRE(p.document->layers.size()==4);REQUIRE(p.document->layers[2].id==p.active&&added(p).parentId.empty());REQUIRE(p.document->layers[3].id=="top");}
void shape_insert_folder(){MainWindow w(true);auto d=fixture();d.layers[0].raster.reset();d.layers[0].group=true;d.layers[1].parentId="bottom";auto&p=w.addProject(d);p.active="bottom";p.selected={p.active};p.collapsedGroups.insert("bottom");shapeTool(w);draw(p);REQUIRE(p.document->layers.size()==4);REQUIRE(p.document->layers[1].id==p.active&&added(p).parentId=="bottom");REQUIRE(p.document->layers[2].id=="middle"&&p.collapsedGroups.contains("bottom"));}
void shape_insert_nested_child(){MainWindow w(true);auto d=fixture();d.layers[0].raster.reset();d.layers[0].group=true;d.layers[1].parentId="bottom";auto&p=w.addProject(d);p.active="middle";p.selected={p.active};shapeTool(w);draw(p);REQUIRE(p.document->layers[2].id==p.active&&added(p).parentId=="bottom"&&p.document->layers[3].id=="top");}
void shape_fractional_anchor(){MainWindow w(true);auto&p=w.addProject(fixture());shapeTool(w);draw(p,{10.6,12.4},{20.2,22.6});REQUIRE(added(p).transform==Transform{11,12,9,11});REQUIRE(added(p).raster->width==9&&added(p).raster->height==11);}
void shape_center_square(){MainWindow w(true);auto&p=w.addProject(fixture());shapeTool(w);draw(p,{-10.6,12.4},{-4.2,16.4},Qt::ShiftModifier|Qt::AltModifier);REQUIRE(added(p).transform==Transform{-18,5,14,14});}
void shape_kind_change_cancels(){MainWindow w(true);auto d=fixture();auto&p=w.addProject(d);shapeTool(w);down(p,{10,12});move(p,{20,24});kind(w)->setCurrentIndex(1);up(p,{20,24});REQUIRE(p.document==d&&p.history.undoCount()==0);draw(p);REQUIRE(editing::decodeShapeStyle(added(p).shapeJson).kind==editing::ShapeKind::Ellipse);}
void shape_radius_limit(){MainWindow w(true);auto&p=w.addProject(fixture());shapeTool(w);REQUIRE(radius(w)->minimum()==0&&radius(w)->maximum()==5000);radius(w)->setValue(9000);REQUIRE(radius(w)->value()==5000);draw(p);REQUIRE(editing::decodeShapeStyle(added(p).shapeJson).cornerRadius==5000);}
void shape_radius_frozen(){MainWindow w(true);auto&p=w.addProject(fixture());shapeTool(w);radius(w)->setValue(3);down(p,{10,12});move(p,{20,24});radius(w)->setValue(8);up(p,{20,24});REQUIRE(editing::decodeShapeStyle(added(p).shapeJson).cornerRadius==3);REQUIRE(radius(w)->value()==8);}
void shape_draft_immutable(){MainWindow w(true);auto d=fixture();auto&p=w.addProject(d);const auto active=p.active;shapeTool(w);down(p,{10,12});move(p,{20,24});REQUIRE(p.document==d&&p.active==active&&p.history.undoCount()==0);p.canvas->pointerCancel();REQUIRE(p.document==d&&p.active==active&&p.history.undoCount()==0);}
void shape_click_noop(){MainWindow w(true);auto d=fixture();auto&p=w.addProject(d);shapeTool(w);down(p,{10.6,12.4});up(p,{10.6,12.4});REQUIRE(p.document==d&&p.history.undoCount()==0);}
void shape_history_selection(){MainWindow w(true);auto d=fixture();d.selection=editing::rasterSelection(editing::SelectionOutline::rectangle({1,2,3,4},false),100,80);d.layers.back().mask=Mask{std::make_shared<GrayRaster>(GrayRaster{1,1,{255}})};auto&p=w.addProject(d);p.maskSelected=true;shapeTool(w);draw(p);REQUIRE(p.document->selection==d.selection&&!p.maskSelected);REQUIRE(p.history.undoCount()==1&&p.history.undoName()=="Rectangle");auto snapshot=p.history.undo();REQUIRE(snapshot&&snapshot->document==d);}
int main(int argc,char**argv){QApplication app(argc,argv);std::map<std::string,void(*)()>tests{{"shape_insert_sibling",shape_insert_sibling},{"shape_insert_folder",shape_insert_folder},{"shape_insert_nested_child",shape_insert_nested_child},{"shape_fractional_anchor",shape_fractional_anchor},{"shape_center_square",shape_center_square},{"shape_kind_change_cancels",shape_kind_change_cancels},{"shape_radius_limit",shape_radius_limit},{"shape_radius_frozen",shape_radius_frozen},{"shape_draft_immutable",shape_draft_immutable},{"shape_click_noop",shape_click_noop},{"shape_history_selection",shape_history_selection}};int failed=0,passed=0;for(const auto&[name,test]:tests){if(argc>1&&argv[1]!=name)continue;try{test();++passed;std::cout<<"PASS "<<name<<'\n';}catch(const std::exception&e){++failed;std::cout<<"FAIL "<<name<<": "<<e.what()<<'\n';}}if(argc>1&&!tests.contains(argv[1]))return 2;std::cout<<"RESULT passed="<<passed<<" failed="<<failed<<'\n';return failed?1:0;}
