#include "editing/PixelEdits.h"
#include "editing/Shapes.h"
#include "editing/DocumentGeometry.h"
#include "graphics/StackRenderer.h"
#include <algorithm>
#include <iostream>
#include <limits>
#include <map>
#include <stdexcept>

using namespace compositor;
using namespace compositor::editing;
using compositor::graphics::StackRenderer;
#define REQUIRE(...) do { if(!(__VA_ARGS__))throw std::runtime_error(std::string(__FILE__)+":"+std::to_string(__LINE__)+": " #__VA_ARGS__); } while(false)
template<class F>void rejects(F action){bool failed=false;try{action();}catch(const std::exception&){failed=true;}REQUIRE(failed);}
Document document(int w=100,int h=40){Document d;d.id=newId();d.width=w;d.height=h;Layer l;l.id=newId();l.transform.width=w;l.transform.height=h;d.layers={l};return d;}
void select(Document& d,Rect r){d.selection=rasterSelection(SelectionOutline::rectangle(r),d.width,d.height);}
Pixel rendered(const Document& d,int x,int y){return StackRenderer().render(d,x,y,1,1)->pixel(0,0);}
SelectionOutline triangle(bool aa=true){std::vector<Point> p{{0,0},{100,0},{0,100}};return SelectionOutline::polygon(p,aa);}
void drag_box(){
    // SelectionTests.marqueeDrawsWholePixelRectanglesInAnyDirection and
    // marqueeShiftMakesSquaresAndCenteredDragsGrowFromTheAnchor.
    REQUIRE(dragBox({60,71},{20.2,30.3})==Rect{20,30,40,41});
    REQUIRE(dragBox({10,10},{40,20},true)==Rect{10,10,30,30});
    REQUIRE(dragBox({50,50},{60,55},false,true)==Rect{40,45,20,10});
    REQUIRE(dragBox({50,50},{45,58},true,true)==Rect{42,42,16,16});
    REQUIRE(dragBox({0,0},{-.5,.5})==Rect{-1,0,1,1});
    REQUIRE(selectionMode(false,false)==SelectionMode::Replace);REQUIRE(selectionMode(true,false)==SelectionMode::Add);REQUIRE(selectionMode(false,true)==SelectionMode::Subtract);REQUIRE(selectionMode(true,true)==SelectionMode::Subtract);
}
void geometry_combine(){
    std::optional<SelectionOutline> s;auto apply=[&](Rect r,SelectionMode mode=SelectionMode::Replace){s=applySelection(s,SelectionOutline::rectangle(r),mode,100,100);};
    auto c=[&](int x,int y){return s->rasterize(100,100)->pixel(x,y);};
    apply({10,10,40,40});REQUIRE(c(30,30)==255&&c(70,70)==0);apply({50,50,40,40},SelectionMode::Add);REQUIRE(c(30,30)==255&&c(70,70)==255);apply({20,20,20,20},SelectionMode::Subtract);REQUIRE(c(30,30)==0&&c(15,15)==255);
    apply({60,10,20,20});REQUIRE(c(70,20)==255&&c(70,70)==0&&c(15,15)==0);apply({-50,-50,100,100});REQUIRE(s->bounds()==Rect{0,0,50,50});
    apply({20,20,50,50},SelectionMode::Intersect);REQUIRE(s->bounds()==Rect{20,20,30,30});
    auto a=triangle();auto twice=a.combined(a,SelectionMode::Add,true);REQUIRE(a.rasterize(100,100)->pixels==twice.rasterize(100,100)->pixels);
}
void coverage_aa(){
    auto smooth=triangle().rasterize(100,100),hard=triangle(false).rasterize(100,100);bool partial=false;for(int x=0;x<100;++x){auto a=smooth->pixel(x,99-x);partial|=a>0&&a<255;auto b=hard->pixel(x,99-x);REQUIRE(b==0||b==255);}REQUIRE(partial);
    auto ellipse=SelectionOutline::ellipse({10,20,60,40});auto g=ellipse.rasterize(100,100);REQUIRE(g->pixel(40,40)==255&&g->pixel(11,21)==0);
    auto rectangle=SelectionOutline::rectangle({510,10,10,20},false).rasterize(1024,40);REQUIRE(rectangle->pixel(510,10)==255&&rectangle->pixel(519,29)==255&&rectangle->pixel(520,29)==0&&rectangle->pixel(511,15)==rectangle->pixel(512,15));
    std::vector<Point> points{{10,10}};REQUIRE(!appendLassoPoint(points,{10.1,10}));REQUIRE(appendLassoPoint(points,{90,10}));REQUIRE(appendLassoPoint(points,{50,50}));points.pop_back();appendLassoPoint(points,{90,90});appendLassoPoint(points,{10,90});auto poly=SelectionOutline::polygon(points).rasterize(100,100);REQUIRE(points.size()==4&&poly->pixel(80,80)==255&&poly->pixel(5,50)==0);
}
void empty_move_inverse(){
    std::optional<SelectionOutline> s;auto large=SelectionOutline::rectangle({0,0,60,60});REQUIRE(!applySelection(s,large,SelectionMode::Subtract,100,100));s=SelectionOutline::rectangle({10,10,20,20});auto empty=applySelection(s,large,SelectionMode::Subtract,100,100);REQUIRE(empty&&empty->empty());REQUIRE(empty->rasterize(100,100)->pixel(20,20)==0);REQUIRE(!finishSelection(s,SelectionOutline(),SelectionMode::Replace,100,100));REQUIRE(finishSelection(s,SelectionOutline(),SelectionMode::Add,100,100)->bounds()==s->bounds());
    auto outside=s->moved({-100.4,0});REQUIRE(coverageBounds(*outside.rasterize(100,100)).empty());auto back=outside.moved({100,0});REQUIRE(back.bounds()==s->bounds()&&back.rasterize(100,100)->pixels==s->rasterize(100,100)->pixels);
    auto inverse=inverseSelection(SelectionOutline::rectangle({0,0,50,50}),100,100)->rasterize(100,100);REQUIRE(inverse->pixel(25,25)==0&&inverse->pixel(75,75)==255);REQUIRE(!inverseSelection({},100,100));
    auto original=rasterSelection(s,100,100);auto moved=moveSelectionCoverage(original,{20.6,-5.3});REQUIRE(moved->coverage->pixel(31,5)==255&&moved->coverage->pixel(10,10)==0);REQUIRE(moveSelectionCoverage(original,{0,0})->coverage==original->coverage);
}
void mapping_transforms(){
    auto d=document(100,40);select(d,{0,0,50,40});auto t=d.layers[0].transform;auto g=mappedCoverage(d,t,50,20);REQUIRE(g->pixel(10,10)==255&&g->pixel(40,10)==0);t.flipX=true;g=mappedCoverage(d,t,50,20,false,CoverageSampling::Nearest);REQUIRE(g->pixel(10,10)==0&&g->pixel(40,10)==255);
    t.flipX=false;t.rotation=180;g=mappedCoverage(d,t,50,20);REQUIRE(g->pixel(10,10)==0&&g->pixel(40,10)==255);
    d.selection.reset();REQUIRE(!mappedCoverage(d,t,50,20));t.x=100;g=mappedCoverage(d,t,50,20,true);REQUIRE(coverageBounds(*g).empty());
    d=document(100,40);std::vector<Point> points{{0,0},{100,0},{0,40}};d.selection=rasterSelection(SelectionOutline::polygon(points),100,40);g=mappedCoverage(d,d.layers[0].transform,50,20);REQUIRE(std::any_of(g->pixels.begin(),g->pixels.end(),[](uint8_t v){return v>0&&v<255;}));
}
void fill_clear_crop(){
    auto d=document();select(d,{20,10,30,20});auto blank=d.layers[0];d.layers[0]=editLayer(blank,d,PixelEdit::Fill,{255,0,0,255});auto& layer=d.layers[0];REQUIRE(layer.raster->width==30&&layer.raster->height==20&&layer.transform.x==20&&layer.transform.y==10);REQUIRE(rendered(d,30,20)==Pixel{255,0,0,255}&&rendered(d,10,10).a==0);REQUIRE(!blank.raster);
    d.selection.reset();d.layers[0]=editLayer(layer,d,PixelEdit::Fill,{255,255,255,255});REQUIRE(d.layers[0].raster->width==100&&d.layers[0].raster->height==40&&rendered(d,5,5)==Pixel{255,255,255,255});
    auto original=d.layers[0];REQUIRE(editLayer(original,d,PixelEdit::Clear)==original);select(d,{20,10,30,20});d.layers[0]=editLayer(original,d,PixelEdit::Clear);REQUIRE(rendered(d,30,20).a==0&&rendered(d,5,5).a==255);REQUIRE(original.raster->pixel(30,20).a==255);
    d.selection=Selection{SelectionOutline().rasterize(100,40)};auto before=d.layers[0];for(auto op:{PixelEdit::Fill,PixelEdit::Clear,PixelEdit::Invert})REQUIRE(editLayer(before,d,op)==before);
}
void fill_growth_mask(){
    auto d=document();auto& layer=d.layers[0];layer.transform.x=40;layer.transform.y=10;layer.transform.width=20;layer.transform.height=20;layer.raster=Raster::filled(20,20,{255,0,0,255});auto gray=std::make_shared<GrayRaster>();gray->width=20;gray->height=20;gray->pixels.resize(400,0);layer.mask=Mask{gray};auto before=layer;
    layer=editLayer(layer,d,PixelEdit::Fill,{0,0,255,255});REQUIRE(layer.transform.x==0&&layer.transform.y==0&&layer.raster->width==100&&layer.raster->height==40);REQUIRE(layer.mask->raster->width==100&&layer.mask->raster->pixel(50,20)==0&&layer.mask->raster->pixel(5,5)==255);REQUIRE(before.mask->raster==gray&&before.raster->width==20);
}
void selected_immutable_invert(){
    auto d=document(512,256);auto& layer=d.layers[0];layer.raster=Raster::filled(512,256,{64,32,0,128});layer.shapeJson="retained until raster edit";auto source=layer.raster;select(d,{10,10,20,20});Raster::resetMaterializationCount();auto result=editLayer(layer,d,PixelEdit::Invert);REQUIRE(result.raster->pixel(15,15)==Pixel{64,96,128,128});REQUIRE(result.raster->pixel(300,15)==source->pixel(300,15));REQUIRE(result.raster->tiles[0]!=source->tiles[0]&&result.raster->tiles[1]==source->tiles[1]);REQUIRE(source->pixel(15,15)==Pixel{64,32,0,128}&&result.shapeJson.empty());REQUIRE(Raster::materializationCount()==0);
    auto empty=std::make_shared<GrayRaster>();empty->width=512;empty->height=256;empty->pixels.resize(512*256);d.selection=Selection{empty};REQUIRE(editLayer(layer,d,PixelEdit::Invert)==layer);
}
void uniform_mask_fill_invert(){
    auto d=document();auto& layer=d.layers[0];layer.raster=Raster::filled(100,40,{255,0,0,255});auto uniform=std::make_shared<GrayRaster>();uniform->width=uniform->height=1;uniform->pixels={255};layer.mask=Mask{uniform};select(d,{20,10,30,20});layer=editLayer(layer,d,PixelEdit::Fill,{0,0,0,255},true);REQUIRE(layer.mask->raster->width==100&&layer.mask->raster->pixel(30,20)==0&&layer.mask->raster->pixel(5,5)==255);layer=editLayer(layer,d,PixelEdit::Clear,{},true);REQUIRE(layer.mask->raster->pixel(30,20)==255);layer.mask->raster=uniform;layer=editLayer(layer,d,PixelEdit::Invert,{},true);REQUIRE(layer.mask->raster->width==100&&layer.mask->raster->pixel(30,20)==0&&layer.mask->raster->pixel(5,5)==255);REQUIRE(uniform->pixels==std::vector<uint8_t>{255});
    layer.mask->raster=uniform;d.selection.reset();layer=editLayer(layer,d,PixelEdit::Invert,{},true);REQUIRE(layer.mask->raster->width==1&&layer.mask->raster->pixels[0]==0);
}
Document twoColor(){auto d=document();d.layers[0].raster=Raster::filled(100,40,{0,0,255,255});select(d,{0,0,50,40});d.layers[0]=editLayer(d.layers[0],d,PixelEdit::Fill,{255,0,0,255});d.selection.reset();return d;}
void copy_current_merged(){
    auto d=twoColor();select(d,{40,10,20,20});auto copy=copyPixels(d,d.layers[0].id,StackRenderer());REQUIRE(copy&&copy->origin==Point{40,10}&&copy->raster->width==20&&copy->raster->height==20);REQUIRE(copy->raster->pixel(5,5)==Pixel{255,0,0,255}&&copy->raster->pixel(15,5)==Pixel{0,0,255,255});
    Layer green;green.id=newId();green.raster=Raster::filled(20,20,{0,255,0,255});green.transform.x=60;green.transform.y=10;green.transform.width=green.transform.height=20;green.opacity=.1;green.visible=false;d.layers.push_back(green);select(d,{55,5,30,30});auto current=copyPixels(d,green.id,StackRenderer());REQUIRE(current->raster->pixel(10,10)==Pixel{0,255,0,255}&&current->raster->pixel(1,1).a==0);auto merged=copyPixels(d,{},StackRenderer());REQUIRE(merged->raster->pixel(10,10)==Pixel{0,0,255,255});d.layers.back().visible=true;d.layers.back().opacity=1;merged=copyPixels(d,{},StackRenderer());REQUIRE(merged->raster->pixel(10,10)==Pixel{0,255,0,255}&&merged->raster->pixel(1,1)==Pixel{0,0,255,255});
}
void copy_lasso(){
    auto d=twoColor();std::vector<Point> p{{10,5},{40,5},{10,35}};auto outline=SelectionOutline::polygon(p);d.selection=rasterSelection(outline,100,40);auto c=copyPixels(d,d.layers[0].id,StackRenderer(),&outline);REQUIRE(c&&c->origin==Point{10,5}&&c->raster->width==30&&c->raster->height==30);REQUIRE(c->raster->pixel(2,2).a==255&&c->raster->pixel(28,28).a==0);bool edge=false;for(int x=0;x<30;++x){auto a=c->raster->pixel(x,29-x).a;edge|=a>0&&a<255;}REQUIRE(edge);
}
void selection_history(){auto d=document(100,100);std::optional<Document> snapshot=d;History history;history.begin("Lasso",snapshot,d.layers[0].id);snapshot->selection=rasterSelection(SelectionOutline::rectangle({10,10,40,40}),100,100);history.end(snapshot,d.layers[0].id);REQUIRE(history.undoCount()==1&&history.undoName()=="Lasso");auto undo=history.undo();REQUIRE(undo&&!undo->document->selection);auto redo=history.redo();REQUIRE(redo&&redo->document->selection->coverage->pixel(30,30)==255);}
void invalid_inputs(){rejects([]{SelectionOutline::rectangle({0,0,-1,2});});rejects([]{SelectionOutline().rasterize(30001,30000);});rejects([]{dragBox({0,0},{std::numeric_limits<double>::infinity(),0});});auto d=document();d.selection=Selection{};rejects([&]{editLayer(d.layers[0],d,PixelEdit::Fill);});d.selection.reset();rejects([&]{editLayer(d.layers[0],d,PixelEdit::Fill,{},true);});rejects([&]{copyPixels(d,"missing",StackRenderer());});}

void scaled_selection_clear(){
    auto d=document();d.layers[0].raster=Raster::filled(50,20,{255,0,0,255});std::vector<Point> p{{0,0},{100,0},{0,40}};d.selection=rasterSelection(SelectionOutline::polygon(p),100,40);auto before=d.layers[0];d.layers[0]=editLayer(before,d,PixelEdit::Clear);REQUIRE(rendered(d,10,10).a==0&&rendered(d,90,35).a==255);auto image=StackRenderer().render(d,0,0,100,40);bool partial=false;for(int x=0;x<100;++x){auto a=image->pixel(x,std::min(39,int((1-double(x)/100)*40))).a;partial|=a>0&&a<255;}REQUIRE(partial);
    d=twoColor();select(d,{0,0,100,20});d.layers[0]=editLayer(d.layers[0],d,PixelEdit::Invert);REQUIRE(rendered(d,10,5)==Pixel{0,255,255,255}&&rendered(d,90,5)==Pixel{255,255,0,255}&&rendered(d,10,30)==Pixel{255,0,0,255});
}
bool near(int a,int b,int tolerance=3){return std::abs(a-b)<=tolerance;}
void gradient_linear(){auto d=document(101,4);auto original=d.layers[0];GradientSettings settings;settings.style=GradientStyle::ForegroundToBackground;auto result=gradientLayer(original,d,{.5,2},{100.5,2},settings);REQUIRE(!original.raster);d.layers[0]=result;REQUIRE(near(rendered(d,0,0).r,0)&&rendered(d,0,0).a==255);REQUIRE(near(rendered(d,100,3).r,255)&&rendered(d,100,3).a==255);auto middle=rendered(d,50,1);REQUIRE(near(middle.r,128)&&middle.r==middle.g&&middle.a==255);}
void gradient_radial(){auto d=document(101,101);GradientSettings settings;settings.shape=GradientShape::Radial;settings.style=GradientStyle::ForegroundToBackground;d.layers[0]=gradientLayer(d.layers[0],d,{50.5,50.5},{90.5,50.5},settings);REQUIRE(near(rendered(d,50,50).r,0)&&rendered(d,50,50).a==255);std::vector<Point> p{{70,50},{30,50},{50,70},{50,30}};int first=rendered(d,70,50).r;for(auto q:p)REQUIRE(near(rendered(d,int(q.x),int(q.y)).r,128,5)&&near(rendered(d,int(q.x),int(q.y)).r,first,1));REQUIRE(near(rendered(d,100,50).r,255)&&near(rendered(d,0,0).r,255));}
void gradient_reverse_transparent(){auto d=document(101,4);GradientSettings s;s.style=GradientStyle::ForegroundToBackground;s.reversed=true;s.opacity=.5;d.layers[0]=gradientLayer(d.layers[0],d,{.5,2},{100.5,2},s);auto start=rendered(d,0,2),end=rendered(d,100,2);REQUIRE(near(start.a,128)&&near(start.r,start.a)&&near(end.r,0)&&near(end.a,128));d=document(101,4);d.layers[0].raster=Raster::filled(101,4,{255,0,0,255});s={};d.layers[0]=gradientLayer(d.layers[0],d,{.5,2},{100.5,2},s);REQUIRE(near(rendered(d,0,2).r,0)&&rendered(d,0,2).a==255);REQUIRE(near(rendered(d,100,2).r,255)&&rendered(d,100,2).a==255);auto mid=rendered(d,50,2);REQUIRE(near(mid.r,128)&&mid.g==0&&mid.a==255);}
void gradient_mask_preview(){auto d=document(101,4);d.layers[0].raster=Raster::filled(101,4,{0,0,0,255});auto gray=std::make_shared<GrayRaster>();gray->width=gray->height=1;gray->pixels={255};d.layers[0].mask=Mask{gray};auto original=d.layers[0];GradientSettings s;s.style=GradientStyle::ForegroundToBackground;auto first=gradientLayer(original,d,{.5,2},{100.5,2},s,{},Pixel{255,255,255,255},true);REQUIRE(near(first.mask->raster->pixel(0,2),0)&&near(first.mask->raster->pixel(100,2),255)&&near(first.mask->raster->pixel(50,2),128));auto second=gradientLayer(original,d,{100.5,2},{.5,2},s,{},Pixel{255,255,255,255},true);REQUIRE(near(second.mask->raster->pixel(0,2),255)&&near(second.mask->raster->pixel(100,2),0)&&original.mask->raster==gray);REQUIRE(gradientLayer(original,d,{10,2},{10.49,2},s)==original);s.opacity=0;REQUIRE(gradientLayer(original,d,{0,2},{100,2},s)==original);}

void transformed_outline(){GrayRaster gray{10,10,std::vector<uint8_t>(100,255)};for(int y=3;y<7;++y)for(int x=3;x<7;++x)gray.pixels[size_t(y)*10+x]=0;auto outline=SelectionOutline::fromCoverage(gray,false);Transform transform{-5.25,10.5,20,30,37,true,false};auto mapped=outline.transformed(transform,10,10);REQUIRE(!mapped.antialiased());REQUIRE(mapped.contains(transform.fromUnit({.15,.15}))&&!mapped.contains(transform.fromUnit({.45,.45})));auto expected=outline.transformed(Transform{-20,0,10,10},10,10);REQUIRE(expected.bounds()==Rect{-20,0,10,10});auto image=expected.moved({20,0}).rasterize(10,10);REQUIRE(image->pixels==gray.pixels);bool rejected=false;try{outline.transformed(transform,0,10);}catch(const std::exception&){rejected=true;}REQUIRE(rejected);}
void bitmap_outline(){GrayRaster gray;gray.width=gray.height=10;gray.pixels.resize(100);for(int y=1;y<9;++y)for(int x=1;x<9;++x)if(x<3||x>=7||y<3||y>=7)gray.pixels[y*10+x]=255;gray.pixels[0]=1;auto outline=SelectionOutline::fromCoverage(gray,false);auto image=outline.rasterize(10,10);REQUIRE(image->pixel(0,0)==255&&image->pixel(4,4)==0);for(int y=0;y<10;++y)for(int x=0;x<10;++x)REQUIRE(image->pixel(x,y)==(gray.pixel(x,y)?255:0));auto combined=outline.combined(SelectionOutline::rectangle({4,4,1,1}),SelectionMode::Add,false).rasterize(10,10);REQUIRE(combined->pixel(4,4)==255&&combined->pixel(5,5)==0);auto moved=moveSelectionCoverage(rasterSelection(outline,10,10),{-20,0});REQUIRE(moved->outline&&coverageBounds(*moved->coverage).empty());auto back=moveSelectionCoverage(moved,{20,0});REQUIRE(back->coverage->pixels==image->pixels);}
void expand_contract(){auto original=SelectionOutline::rectangle({30,30,20,20});auto expanded=original.resized(5,100,100);auto g=expanded.rasterize(100,100);REQUIRE(expanded.bounds()==Rect{25,25,30,30});REQUIRE(g->pixel(26,40)==255&&g->pixel(24,40)==0);auto contracted=original.resized(-5,100,100);REQUIRE(contracted.bounds()==Rect{35,35,10,10});REQUIRE(contracted.rasterize(100,100)->pixel(36,36)==255&&contracted.rasterize(100,100)->pixel(32,40)==0);REQUIRE(original.resized(-11,100,100).empty());auto atEdge=SelectionOutline::rectangle({0,0,20,20}).resized(10,100,100);REQUIRE(atEdge.bounds().x==0&&atEdge.bounds().y==0);REQUIRE(original.resized(501,100,100).bounds()==original.bounds());}

void shape_rectangle_ellipse(){auto d=document(100,80);ShapeStyle red{ShapeKind::Rectangle,1,0,0,0};auto layer=createShapeLayer({10,10,30,20},red,nextShapeName(d,red.kind));REQUIRE(layer&&layer->name=="Rectangle 1"&&layer->transform.x==10&&layer->transform.y==10);d.layers.push_back(*layer);REQUIRE(rendered(d,25,20)==Pixel{255,0,0,255}&&rendered(d,10,10)==Pixel{255,0,0,255}&&rendered(d,39,29)==Pixel{255,0,0,255});REQUIRE(rendered(d,9,20).a==0&&rendered(d,40,20).a==0&&rendered(d,25,30).a==0);REQUIRE(nextShapeName(d,red.kind)=="Rectangle 2");red.kind=ShapeKind::Ellipse;d.layers.push_back(*createShapeLayer(dragBox({50,40},{60,45},true,true),red,"Ellipse 1"));REQUIRE(rendered(d,50,40)==Pixel{255,0,0,255}&&rendered(d,41,40).a>0&&rendered(d,50,31).a>0);REQUIRE(rendered(d,40,30).a==0&&rendered(d,59,49).a==0);REQUIRE(!createShapeLayer({20,20,0,0},red,"Empty"));}
void shape_rounded_style(){auto d=document(100,80);ShapeStyle red{ShapeKind::Rectangle,1,0,0,8};d.layers.push_back(*createShapeLayer({10,10,40,30},red,"Rounded"));REQUIRE(rendered(d,10,10).a==0&&rendered(d,11,11).a==0&&rendered(d,13,13).a==255&&rendered(d,30,10).a==255&&rendered(d,30,25)==Pixel{255,0,0,255});REQUIRE(decodeShapeStyle(encodeShapeStyle(red))==red);red.cornerRadius=500;d.layers.push_back(*createShapeLayer({55,50,40,20},red,"Pill"));REQUIRE(rendered(d,55,50).a==0&&rendered(d,75,60)==Pixel{255,0,0,255});rejects([]{decodeShapeStyle("{\"kind\":\"Rectangle\",\"red\":1,\"green\":0,\"blue\":0}");});rejects([]{createShapeLayer({0,0,30000,30000},ShapeStyle{},"Huge");});}
void shape_redraw_mask(){ShapeStyle style{ShapeKind::Rectangle,1,0,0,8};auto layer=*createShapeLayer({0,0,40,30},style,"Rounded");auto gray=std::make_shared<GrayRaster>();gray->width=gray->height=1;gray->pixels={255};layer.mask=Mask{gray};auto old=layer.raster;layer.transform.width=80;auto resized=redrawShape(layer);REQUIRE(resized.raster->width==80&&resized.raster->height==30&&resized.raster!=old&&resized.mask->raster==gray&&resized.mask->placement==layer.transform);REQUIRE(decodeShapeStyle(resized.shapeJson).cornerRadius==8);REQUIRE(redrawShape(resized)==resized);style.red=0;style.blue=1;auto blue=restyleShape(resized,style);REQUIRE(blue.raster->pixel(40,15)==Pixel{0,0,255,255}&&resized.raster->pixel(40,15)==Pixel{255,0,0,255});auto d=document(80,30);d.layers={blue};auto painted=editLayer(blue,d,PixelEdit::Invert);REQUIRE(painted.shapeJson.empty());rejects([&]{restyleShape(painted,style);});}
void shape_preview(){auto layer=*createShapeLayer({0,0,40,30},{ShapeKind::Rectangle,1,0,0,8},"Rounded");auto transform=layer.transform;REQUIRE(!shapeTransformPreview(layer,transform));transform.width=4000;transform.height=2000;auto preview=shapeTransformPreview(layer,transform);REQUIRE(preview&&preview->width==2048&&preview->height==1024&&layer.raster->width==40);}
void canvas_anchors(){auto d=document(64,32);d.layers[0].raster=Raster::filled(64,32,{255,0,0,255});d.layers[0].transform.rotation=37;d.layers[0].transform.flipX=true;auto original=d.layers[0];for(int delta:{5,-5})for(int anchor=0;anchor<9;++anchor){auto result=canvasResize(d,{64+delta,32+delta,anchor});int expected[]={0,delta==5?2:-3,delta};REQUIRE(result.layers[0].transform.x==original.transform.x+expected[anchor%3]&&result.layers[0].transform.y==original.transform.y+expected[anchor/3]);REQUIRE(result.layers[0].transform.width==64&&result.layers[0].transform.height==32&&result.layers[0].transform.rotation==37&&result.layers[0].transform.flipX);REQUIRE(result.layers[0].id==original.id&&result.layers[0].raster==original.raster);}REQUIRE(canvasResize(d,{64,32})==d);}
void canvas_units(){CanvasSizeDraft draft(1000,500,100);draft.relative=true;draft.locked=true;draft.set(200,true);REQUIRE(draft.width==1200&&draft.height==600&&draft.displayed(false)==100);draft.set(-250,false);REQUIRE(draft.width==500&&draft.height==250);draft.relative=false;draft.unit=CanvasUnit::Inches;draft.set(10,true);REQUIRE(draft.width==1000&&draft.height==500);draft.unit=CanvasUnit::Percent;draft.set(50,true);REQUIRE(draft.width==500&&draft.height==250);draft.unit=CanvasUnit::Centimeters;REQUIRE(std::abs(draft.displayed(true)-12.7)<.001);draft.unit=CanvasUnit::Pixels;draft.set(0,true);REQUIRE(!draft.valid());}
void canvas_extension(){auto d=document(4,4);select(d,{0,0,2,2});auto output=canvasResize(d,{8,2,4,Pixel{255,0,0,255}});REQUIRE(output.layers.size()==2&&output.layers[0].name=="Canvas Extension"&&!output.selection);REQUIRE(rendered(output,0,0)==Pixel{255,0,0,255}&&rendered(output,3,0).a==0&&rendered(output,7,1).a==255);REQUIRE(output.layers[1].id==d.layers[0].id&&d.width==4&&d.selection);}
void canvas_allocation_free(){auto d=document(4,4);d.layers.clear();Raster::resetMaterializationCount();auto large=canvasResize(d,{30000,30000});REQUIRE(large.layers.empty()&&large.width==30000&&Raster::materializationCount()==0);auto small=canvasResize(d,{2,2,4,Pixel{255,255,255,255}});REQUIRE(small.layers.empty());rejects([&]{canvasResize(d,{30000,30000,4,Pixel{255,255,255,255}});});}
void crop_geometry(){auto rect=createCrop({100,100},{20,60},2);REQUIRE(rect==Rect{20,60,80,40});CropDrag move{{40,70},rect,CropDrag::Mode::Move};REQUIRE(move.updated({30,40})==Rect{10,30,80,40});const Point handles[]={{0,0},{.5,0},{1,0},{1,.5},{1,1},{.5,1},{0,1},{0,.5}};for(int index=0;index<8;++index){auto u=handles[index];Point start{rect.x+u.x*rect.width,rect.y+u.y*rect.height};CropDrag drag{start,rect,CropDrag::Mode::Resize,index};auto next=drag.updated({start.x+(u.x*2-1)*20,start.y+(u.y*2-1)*10},2);REQUIRE(validCrop(next)&&std::abs(next.width/next.height-2)<.05&&next!=rect);}auto symmetric=createCrop({50,50},{60,55},{},true);REQUIRE(symmetric==Rect{40,45,20,10});REQUIRE(snappedCrop({10.2,10.2,-5,-4})==Rect{5,6,5,4});}
void crop_snapping(){CropSnap snap{{0,200,50,150},{0,100,20,80},6};Rect rect{10,10,60,40};CropDrag move{{30,30},rect,CropDrag::Mode::Move};Point point{26,34};REQUIRE(snap.apply(move.updated(point),move,point)==Rect{0,20,60,40});CropDrag resize{{70,50},rect,CropDrag::Mode::Resize,4};point={146,83};REQUIRE(snap.apply(resize.updated(point),resize,point)==Rect{10,10,140,70});point={120,60};REQUIRE(snap.apply(resize.updated(point),resize,point)==Rect{10,10,110,50});REQUIRE(snap.apply({10,10,138,69},resize,{148,79},2)==Rect{10,10,138,69});CropDrag create{{52,18},{},CropDrag::Mode::Create};point={147,77};REQUIRE(snap.apply(create.updated(point),create,point)==Rect{52,18,98,62});auto d=document(400,300);d.layers[0].raster=Raster::filled(100,60);d.layers[0].transform={150,120,100,60};auto targets=cropSnapTargets(d,6);std::sort(targets.xs.begin(),targets.xs.end());std::sort(targets.ys.begin(),targets.ys.end());REQUIRE(targets.xs==std::vector<double>{0,150,250,400}&&targets.ys==std::vector<double>{0,120,180,300});}
void crop_commit(){auto d=document(64,32);d.layers[0].raster=Raster::filled(64,32,{255,0,0,255});auto source=d.layers[0].raster;auto result=cropDocument(d,{8,4,32,16});REQUIRE(result.width==32&&result.height==16&&result.layers[0].transform.x==-8&&result.layers[0].transform.y==-4&&result.layers[0].raster==source);d=document(100,50);result=cropDocument(d,{-20,10,100,50});REQUIRE(result.layers[0].transform.x==20&&result.layers[0].transform.y==-10);result=cropDocument(result,{-10,-10,140,80});REQUIRE(result.width==140&&result.height==80&&result.layers[0].transform.x==30&&result.layers[0].transform.y==0);}
void image_resize(){auto d=document(64,32);d.layers[0].raster=Raster::filled(64,32);select(d,{0,0,32,32});d.layers[0]=editLayer(d.layers[0],d,PixelEdit::Fill,{255,0,0,255});d.selection.reset();auto source=d.layers[0].raster;auto output=imageResize(d,{128,96,300,Transform::Sampling::Nearest});REQUIRE(output.width==128&&output.height==96&&output.resolution==300&&output.layers[0].id==d.layers[0].id);REQUIRE(rendered(output,0,0).r==255&&rendered(output,127,0).a==0&&d.layers[0].raster==source);}
void image_resolution_only(){auto d=document(32,16);d.layers[0].raster=Raster::filled(32,16,{128,128,128,255});d.layers[0].transform.rotation=30;auto resized=imageResize(d,{32,16,300});REQUIRE(resized.resolution==300&&resized.layers[0].transform==d.layers[0].transform&&resized.layers[0].raster==d.layers[0].raster);rejects([&]{imageResize(d,{32,16,0});});}
void image_rotated_hidden(){auto d=document(64,32);auto& layer=d.layers[0];layer.raster=Raster::filled(64,32,{255,0,0,255});layer.visible=false;layer.transform={-16,4,64,32,90};auto gray=std::make_shared<GrayRaster>();gray->width=gray->height=1;gray->pixels={255};layer.mask=Mask{gray};auto out=imageResize(d,{128,96,72,Transform::Sampling::Nearest});auto& result=out.layers[0];REQUIRE(!result.visible&&result.transform.rotation==0&&std::abs(result.transform.width-64)<=1&&std::abs(result.transform.height-192)<=1&&result.transform.y<0&&result.mask->raster==gray);rejects([&]{imageResize(d,{30000,30000,72});});}
void flip_canvas(){auto d=twoColor();select(d,{0,0,20,20});auto source=d.layers[0].raster;auto flipped=flipCanvas(d,true);REQUIRE(flipped.layers[0].raster==source&&rendered(flipped,5,5)==Pixel{0,0,255,255}&&rendered(flipped,95,5)==Pixel{255,0,0,255});REQUIRE(flipped.selection->outline&&flipped.selection->coverage->pixel(90,5)==255&&flipped.selection->coverage->pixel(5,5)==0);auto twice=flipCanvas(flipped,true);REQUIRE(twice.layers==d.layers&&twice.selection->coverage->pixels==d.selection->coverage->pixels);}
void flip_layer_masks(){auto d=twoColor();auto gray=std::make_shared<GrayRaster>();gray->width=100;gray->height=40;gray->pixels.resize(4000,255);auto& layer=d.layers[0];layer.mask=Mask{gray,true,false,{}};auto old=layer.transform;std::vector<std::string> ids{layer.id};auto flipped=flipLayers(d,ids,true);REQUIRE(flipped.layers[0].transform.flipX&&flipped.layers[0].mask->placement==old&&flipped.layers[0].mask->raster==gray);layer.mask->linked=true;flipped=flipLayers(d,ids,true);REQUIRE(!flipped.layers[0].mask->placement);layer.mask->placement=Transform{10,5,60,20,30};flipped=flipLayers(d,ids,true);auto placed=*flipped.layers[0].mask->placement;for(auto p:{Point{0,0},Point{1,0},Point{0,1}}){auto before=layer.mask->placement->fromUnit(p),after=placed.fromUnit(p);REQUIRE(std::abs(after.x-(100-before.x))<1e-8&&std::abs(after.y-before.y)<1e-8);}}
void flip_group(){auto d=document();d.layers.clear();Layer group;group.id=newId();group.group=true;d.layers.push_back(group);for(int x:{0,60,90}){Layer layer;layer.id=newId();layer.parentId=group.id;layer.raster=Raster::filled(20,20,{255,0,0,255});layer.transform={double(x),0,20,20};layer.visible=x!=90;d.layers.push_back(layer);}std::vector<std::string> ids{group.id};auto flipped=flipLayers(d,ids,true);REQUIRE(flipped.layers[0]==d.layers[0]&&flipped.layers[1].transform.x==60&&flipped.layers[2].transform.x==0&&flipped.layers[3]==d.layers[3]);}
int main(int argc,char** argv){std::map<std::string,void(*)()> tests{{"transformed_outline",transformed_outline},{"drag_box",drag_box},{"geometry_combine",geometry_combine},{"coverage_aa",coverage_aa},{"empty_move_inverse",empty_move_inverse},{"mapping_transforms",mapping_transforms},{"fill_clear_crop",fill_clear_crop},{"fill_growth_mask",fill_growth_mask},{"selected_immutable_invert",selected_immutable_invert},{"uniform_mask_fill_invert",uniform_mask_fill_invert},{"copy_current_merged",copy_current_merged},{"copy_lasso",copy_lasso},{"selection_history",selection_history},{"invalid_inputs",invalid_inputs},{"scaled_selection_clear",scaled_selection_clear},{"gradient_linear",gradient_linear},{"gradient_radial",gradient_radial},{"gradient_reverse_transparent",gradient_reverse_transparent},{"gradient_mask_preview",gradient_mask_preview},{"bitmap_outline",bitmap_outline},{"expand_contract",expand_contract},{"shape_rectangle_ellipse",shape_rectangle_ellipse},{"shape_rounded_style",shape_rounded_style},{"shape_redraw_mask",shape_redraw_mask},{"shape_preview",shape_preview},{"canvas_anchors",canvas_anchors},{"canvas_units",canvas_units},{"canvas_extension",canvas_extension},{"canvas_allocation_free",canvas_allocation_free},{"crop_geometry",crop_geometry},{"crop_snapping",crop_snapping},{"crop_commit",crop_commit},{"image_resize",image_resize},{"image_resolution_only",image_resolution_only},{"image_rotated_hidden",image_rotated_hidden},{"flip_canvas",flip_canvas},{"flip_layer_masks",flip_layer_masks},{"flip_group",flip_group}};try{if(argc!=2||!tests.contains(argv[1]))throw std::runtime_error("Specify one editing test case");tests.at(argv[1])();std::cout<<"PASS "<<argv[1]<<"\n";return 0;}catch(const std::exception& error){std::cerr<<"FAIL "<<(argc>1?argv[1]:"arguments")<<": "<<error.what()<<"\n";return 1;}}
