#include "editing/GradientPreview.h"
#include "graphics/StackRenderer.h"
#include "graphics/SamplingSource.h"
#include <iostream>
#include <map>
#include <stdexcept>
#include <cmath>
using namespace compositor;
using namespace compositor::editing;
using compositor::graphics::StackRenderer;
#define REQUIRE(...) do{if(!(__VA_ARGS__))throw std::runtime_error(std::string("line ")+std::to_string(__LINE__)+": " #__VA_ARGS__);}while(false)
Document fixture(int w,int h){Document d;d.id="gradient";d.width=w;d.height=h;Layer l;l.id="target";l.transform={0,0,double(w),double(h)};d.layers={l};return d;}
GradientSettings opaque(){GradientSettings s;s.style=GradientStyle::ForegroundToBackground;return s;}
bool near(int a,int b,int tolerance=3){return std::abs(a-b)<=tolerance;}
void equal(const Raster& a,const Raster& b,int tolerance=0){REQUIRE(a.width==b.width&&a.height==b.height);for(int y=0;y<a.height;++y)for(int x=0;x<a.width;++x){auto p=a.pixel(x,y),q=b.pixel(x,y);REQUIRE(near(p.r,q.r,tolerance)&&near(p.g,q.g,tolerance)&&near(p.b,q.b,tolerance)&&near(p.a,q.a,tolerance));}}
std::shared_ptr<const Raster> render(const Document& d,const GradientPreview& g,int x=0,int y=0,int w=0,int h=0){return StackRenderer({},g.renderPreview()).render(d,x,y,w?w:d.width,h?h:d.height);}
void previewCommit(const Document& d,const GradientPreview& g,int tolerance=0){auto live=render(d,g);auto committed=d;committed.layers[0]=g.materializeLayer();equal(*live,*StackRenderer().render(committed,0,0,d.width,d.height),tolerance);}
void source_linear(){auto d=fixture(101,4);const auto original=d;GradientPreview g(d.layers[0],d,{.5,2},{100.5,2},opaque());auto p=render(d,g);REQUIRE(d==original&&!d.layers[0].raster);REQUIRE(near(p->pixel(0,0).r,0)&&p->pixel(0,0).a==255);REQUIRE(near(p->pixel(100,3).r,255)&&p->pixel(100,3).a==255);auto m=p->pixel(50,1);REQUIRE(near(m.r,128)&&m.r==m.g&&m.a==255);previewCommit(d,g);}
void source_radial(){auto d=fixture(101,101);auto s=opaque();s.shape=GradientShape::Radial;GradientPreview g(d.layers[0],d,{50.5,50.5},{90.5,50.5},s);auto p=render(d,g);REQUIRE(near(p->pixel(50,50).r,0));int first=p->pixel(70,50).r;for(Point q:std::initializer_list<Point>{{70,50},{30,50},{50,70},{50,30}})REQUIRE(near(p->pixel(int(q.x),int(q.y)).r,128,5)&&near(p->pixel(int(q.x),int(q.y)).r,first,1));REQUIRE(near(p->pixel(100,50).r,255)&&near(p->pixel(0,0).r,255));previewCommit(d,g);}
void source_reverse_opacity(){auto d=fixture(101,4);auto s=opaque();s.reversed=true;s.opacity=.5;GradientPreview g(d.layers[0],d,{.5,2},{100.5,2},s);auto p=render(d,g);REQUIRE(near(p->pixel(0,2).a,128)&&near(p->pixel(0,2).r,p->pixel(0,2).a));REQUIRE(near(p->pixel(100,2).r,0)&&near(p->pixel(100,2).a,128));previewCommit(d,g);}
void source_transparent(){auto d=fixture(101,4);d.layers[0].raster=Raster::filled(101,4,{255,0,0,255});GradientPreview g(d.layers[0],d,{.5,2},{100.5,2},{});auto p=render(d,g);REQUIRE(near(p->pixel(0,2).r,0)&&p->pixel(0,2).a==255);REQUIRE(near(p->pixel(100,2).r,255)&&p->pixel(100,2).a==255);REQUIRE(near(p->pixel(50,2).r,128)&&p->pixel(50,2).g==0);previewCommit(d,g);}
void immutable_redrag(){auto d=fixture(101,4);std::shared_ptr<const LayerRenderPreview> retained;{GradientPreview a(d.layers[0],d,{.5,2},{100.5,2},opaque());retained=a.renderPreview();}GradientPreview b(d.layers[0],d,{100.5,2},{.5,2},opaque());auto q=render(d,b),p=StackRenderer({},retained).render(d,0,0,101,4);REQUIRE(p->pixel(0,2).r==0&&p->pixel(100,2).r==255);REQUIRE(q->pixel(0,2).r==255&&q->pixel(100,2).r==0);REQUIRE(!d.layers[0].raster);}
void click_empty_selection(){auto d=fixture(64,32);GradientPreview click(d.layers[0],d,{0,0},{.49,0},opaque());REQUIRE(!click.renderPreview()&&click.materializeLayer()==d.layers[0]);auto g=std::make_shared<GrayRaster>(GrayRaster{64,32,std::vector<uint8_t>(2048)});d.selection=Selection{g};GradientPreview empty(d.layers[0],d,{0,0},{63,0},opaque());REQUIRE(!empty.renderPreview()&&empty.materializeLayer()==d.layers[0]);}
void source_mask(){auto d=fixture(101,4);d.layers[0].raster=Raster::filled(101,4,{0,0,0,255});d.layers[0].mask=Mask{std::make_shared<GrayRaster>(GrayRaster{1,1,{255}})};GradientPreview g(d.layers[0],d,{.5,2},{100.5,2},opaque(),{0,0,0,255},{255,255,255,255},true);auto p=render(d,g);REQUIRE(near(p->pixel(0,2).a,0)&&near(p->pixel(100,2).a,255)&&near(p->pixel(50,2).a,128));previewCommit(d,g);REQUIRE(d.layers[0].mask->raster->width==1);}
void transformed_half_selection(){auto d=fixture(80,64);d.layers[0].transform={20,10,32,48,90,true,false,Transform::Sampling::Nearest};d.layers[0].raster=Raster::filled(16,24,{80,40,20,255});auto selection=std::make_shared<GrayRaster>(GrayRaster{80,64,std::vector<uint8_t>(5120,128)});d.selection=Selection{selection};GradientPreview g(d.layers[0],d,{0,32},{80,32},opaque(),{200,0,0,255},{200,0,0,255});auto out=g.materializeLayer();for(int y=0;y<24;++y)for(int x=0;x<16;++x){auto point=d.layers[0].transform.fromUnit({(x+.5)/16,(y+.5)/24});if(point.x>=0&&point.y>=0&&point.x<80&&point.y<64){auto u=out.transform.toUnit(point);auto p=out.raster->pixel(int(u.x*out.raster->width),int(u.y*out.raster->height));REQUIRE(p==Pixel{140,20,10,255});}}previewCommit(d,g);}
void scaled_large_canvas(){auto d=fixture(30000,30000);d.layers[0].raster=Raster::filled(64,64,{40,20,10,255});GradientPreview g(d.layers[0],d,{0,0},{30000,0},opaque());REQUIRE(g.allocatedPixelCount()==4096&&g.previewOwnedPixelBytes()==0);auto p=render(d,g,14999,14999,2,2);REQUIRE(near(p->pixel(0,0).r,128,1)&&p->pixel(0,0).a==255);auto final=g.materializeLayer();REQUIRE(final.raster->width==64&&final.raster->height==64&&final.transform==d.layers[0].transform);REQUIRE(Raster::materializationCount()==0);}
void wide_lazy_source(){auto d=fixture(30000,16);GradientPreview g(d.layers[0],d,{.5,8},{29999.5,8},opaque());auto preview=g.renderPreview();REQUIRE(preview->imageSource->width==30000&&preview->imageSource->height==16&&g.previewOwnedPixelBytes()==0);auto p=render(d,g,29990,0,10,16);REQUIRE(p->pixel(9,8)==Pixel{255,255,255,255});REQUIRE(!d.layers[0].raster);}
void mask_small_grid_large_image(){auto d=fixture(64,32);d.layers[0].raster=Raster::filled(10000,10000,{40,20,10,255});auto gray=std::make_shared<GrayRaster>(GrayRaster{8,8,std::vector<uint8_t>(64,255)});d.layers[0].mask=Mask{gray,true,true,Transform{20,8,16,16}};GradientPreview g(d.layers[0],d,{20,8},{36,8},opaque(),{0,0,0,255},{255,255,255,255},true);auto result=g.materializeLayer();REQUIRE(g.allocatedPixelCount()==64&&result.raster==d.layers[0].raster&&result.mask->placement==d.layers[0].mask->placement);previewCommit(d,g,1);}
void unplaced_mask_expansion(){auto d=fixture(64,32);d.layers[0].transform={8,8,16,16};d.layers[0].raster=Raster::filled(16,16,{40,20,10,255});d.layers[0].mask=Mask{std::make_shared<GrayRaster>(GrayRaster{16,16,std::vector<uint8_t>(256,0)})};GradientPreview g(d.layers[0],d,{0,16},{63,16},opaque(),{200,0,0,255},{200,0,0,255});auto r=g.materializeLayer();REQUIRE(r.mask->raster->width==64&&r.mask->raster->height==32);REQUIRE(r.mask->raster->pixel(8,8)==0&&r.mask->raster->pixel(40,16)==255);previewCommit(d,g);}
void preserves_outside_canvas(){auto d=fixture(32,32);d.layers[0].transform={-8,-8,48,48};d.layers[0].raster=Raster::filled(48,48,{40,20,10,255});GradientPreview g(d.layers[0],d,{0,16},{32,16},opaque(),{200,0,0,255},{200,0,0,255});auto r=g.materializeLayer();REQUIRE(r.transform==d.layers[0].transform&&r.raster->pixel(0,0)==Pixel{40,20,10,255}&&r.raster->pixel(10,10)==Pixel{200,0,0,255});previewCommit(d,g);}
void commit_history_cancel(){auto d=fixture(64,32);std::optional<Document> current=d;History h;GradientPreview g(d.layers[0],d,{0,0},{63,0},opaque());REQUIRE(current==d&&h.undoCount()==0);auto next=d;next.layers[0]=g.materializeLayer();h.begin("Gradient",current,"target");current=next;h.end(current,"target");REQUIRE(h.undoCount()==1);auto undo=h.undo();REQUIRE(undo&&undo->document==d);auto redo=h.redo();REQUIRE(redo&&redo->document==next);}
int main(int argc,char**argv){Raster::resetMaterializationCount();std::map<std::string,void(*)()> cases{{"source_linear",source_linear},{"source_radial",source_radial},{"source_reverse_opacity",source_reverse_opacity},{"source_transparent",source_transparent},{"immutable_redrag",immutable_redrag},{"click_empty_selection",click_empty_selection},{"source_mask",source_mask},{"transformed_half_selection",transformed_half_selection},{"scaled_large_canvas",scaled_large_canvas},{"wide_lazy_source",wide_lazy_source},{"mask_small_grid_large_image",mask_small_grid_large_image},{"unplaced_mask_expansion",unplaced_mask_expansion},{"preserves_outside_canvas",preserves_outside_canvas},{"commit_history_cancel",commit_history_cancel}};int failed=0;for(const auto& [name,fn]:cases){if(argc>1&&name!=argv[1])continue;try{fn();std::cout<<"PASS "<<name<<'\n';}catch(const std::exception& e){++failed;std::cout<<"FAIL "<<name<<" "<<e.what()<<'\n';}}if(argc>1&&!cases.contains(argv[1]))return 2;std::cout<<"failed="<<failed<<" mac_differential=false\n";return failed?1:0;}
