// Behavior translated from Compositor a19db9011282399785dc18efcfded904627bdcc2.
// Copyright (c) 2026 Wonder Assembly LLC. MIT notice retained in upstream/LICENSE.
#include "LayerOperations.h"
#include "graphics/MaskSampling.h"
#include "graphics/RasterSampling.h"
#include <algorithm>
#include <cmath>
#include <stdexcept>

namespace compositor::layers {
namespace {
using IDs=std::unordered_set<std::string>;
std::size_t indexOf(const Document& d,const std::string& id){auto it=std::find_if(d.layers.begin(),d.layers.end(),[&](const Layer& l){return l.id==id;});return std::size_t(it-d.layers.begin());}
const Layer* find(const Document& d,const std::string& id){auto i=indexOf(d,id);return i==d.layers.size()?nullptr:&d.layers[i];}
std::vector<std::string> siblings(const Document& d,const std::string& parent){std::vector<std::string> out;for(const auto& l:d.layers)if(l.parentId==parent)out.push_back(l.id);return out;}
std::vector<std::string> ancestors(const Document& d,const std::string& id){std::vector<std::string> out;auto p=find(d,id);while(p&&!p->parentId.empty()){out.push_back(p->parentId);p=find(d,p->parentId);}out.push_back({});return out;}
SelectionState single(const std::string& id){return id.empty()?SelectionState{}:SelectionState{{id},id};}
EditResult result(const Document& before,Document after,SelectionState selected,std::string action){validateDocument(after);selected=normalizeSelection(after,std::move(selected));bool changed=before!=after;return {std::move(after),std::move(selected),changed,std::move(action)};}
void cancel(const Limits& limits){if(limits.cancelled&&limits.cancelled())throw std::runtime_error("Layer operation cancelled");}
void budget(int w,int h,const Limits& limits){if(w<1||h<1||w>30000||h>30000||std::uint64_t(w)*h>100000000)throw std::runtime_error("Layer operation exceeds raster dimensions");auto tileBytes=std::uint64_t((w+255)/256)*((h+255)/256)*sizeof(Raster::Tile);if(std::uint64_t(w)*h*16+tileBytes*2>limits.maxWorkingBytes)throw std::runtime_error("Layer operation exceeds working memory budget");}
std::string folderName(const Document& d){std::unordered_set<std::string> names;for(const auto& l:d.layers)names.insert(l.name);int n=1;while(names.contains("Folder "+std::to_string(n)))++n;return "Folder "+std::to_string(n);}
Layer newGroup(const Document& d){Layer out;out.id=newId();out.name=folderName(d);out.group=true;out.transform={0,0,double(d.width),double(d.height)};return out;}
void adoptClipping(Document& d,const std::string& id){auto at=indexOf(d,id);if(at==d.layers.size()||d.layers[at].group)return;auto stack=siblings(d,d.layers[at].parentId);auto it=std::find(stack.begin(),stack.end(),id);auto i=std::size_t(it-stack.begin());if(i==0||i+1>=stack.size())return;const auto& above=*find(d,stack[i+1]);const auto& below=*find(d,stack[i-1]);if(!above.maskSourceId.empty()&&above.maskSourceId!=id&&(below.id==above.maskSourceId||below.maskSourceId==above.maskSourceId))d.layers[at].maskSourceId=above.maskSourceId;}
void releaseDetached(Document& d){std::unordered_map<std::string,std::string> bases;IDs release;for(const auto& l:d.layers){auto& base=bases[l.parentId];if(!l.maskSourceId.empty()){if(l.maskSourceId!=base){release.insert(l.id);base=l.id;}}else base=l.group?std::string{}:l.id;}for(auto& l:d.layers)if(release.contains(l.id))l.maskSourceId.clear();}
std::uint8_t byte(double value){return std::uint8_t(std::clamp(std::lround(value),0L,255L));}
struct Dependency {
    const Layer* layer{};double background{};
    double alpha(Point point,double upstream)const{
        const auto& l=*layer;if(!l.raster)return 0;auto u=l.transform.toUnit(point);
        double alpha=graphics::sampleRaster(*l.raster,u,l.transform.sampling).a;
        double coverage=1;if(l.mask&&l.mask->enabled){const auto& m=*l.mask->raster;const auto& placed=l.mask->placement?*l.mask->placement:l.transform;auto mu=placed.toUnit(point);coverage=graphics::sampleMask(m,mu,placed.sampling,l.mask->placement?std::uint8_t(background):0);}
        return byte(alpha*l.opacity*coverage*upstream)/255.;
    }
};
}

SelectionState normalizeSelection(const Document& d,SelectionState selected){IDs requested(selected.ids.begin(),selected.ids.end());selected.ids.clear();for(const auto& l:d.layers)if(requested.contains(l.id))selected.ids.push_back(l.id);if(std::find(selected.ids.begin(),selected.ids.end(),selected.primary)==selected.ids.end())selected.primary=selected.ids.empty()?std::string{}:selected.ids.front();return selected;}
std::vector<Entry> entries(const Document& d,bool topFirst,const IDs& collapsed){validateDocument(d);std::unordered_map<std::string,std::vector<const Layer*>> children;for(const auto& l:d.layers)children[l.parentId].push_back(&l);std::vector<Entry> out;std::function<void(const std::string&,int,bool)> visit=[&](const std::string& parent,int depth,bool visible){auto stack=children[parent];if(topFirst)std::reverse(stack.begin(),stack.end());for(const auto* l:stack){bool effective=visible&&l->visible;out.push_back({l->id,depth,effective});if(l->group&&!collapsed.contains(l->id))visit(l->id,depth+1,effective);}};visit({},0,true);return out;}
IDs descendants(const Document& d,const std::string& id){validateDocument(d);IDs out;std::vector<std::string> pending{id};while(!pending.empty()){auto p=pending.back();pending.pop_back();for(const auto& l:d.layers)if(l.parentId==p&&out.insert(l.id).second)pending.push_back(l.id);}return out;}
EditResult addGroup(const Document& d,SelectionState selected){validateDocument(d);selected=normalizeSelection(d,std::move(selected));auto group=newGroup(d);auto active=find(d,selected.primary);if(active)group.parentId=active->group?active->id:active->parentId;auto at=indexOf(d,selected.primary);Document next=d;next.layers.insert(next.layers.begin()+std::min(at+1,next.layers.size()),group);return result(d,std::move(next),single(group.id),"New Folder");}
EditResult group(const Document& d,SelectionState selected){
    validateDocument(d);selected=normalizeSelection(d,std::move(selected));IDs picked(selected.ids.begin(),selected.ids.end()),roots;
    for(const auto& id:picked){auto path=ancestors(d,id);if(std::none_of(path.begin(),path.end(),[&](const auto& p){return picked.contains(p);}))roots.insert(id);}
    std::vector<std::string> ordered;for(const auto& entry:entries(d))if(roots.contains(entry.id))ordered.push_back(entry.id);
    auto wrapper=newGroup(d);if(!ordered.empty())for(const auto& candidate:ancestors(d,ordered.front())){bool shared=true;for(const auto& id:ordered){auto path=ancestors(d,id);shared&=std::find(path.begin(),path.end(),candidate)!=path.end();}if(shared){wrapper.parentId=candidate;break;}}
    IDs branches;for(auto id:ordered){while(!find(d,id)->parentId.empty()&&find(d,id)->parentId!=wrapper.parentId)id=find(d,id)->parentId;branches.insert(id);}
    std::size_t insertion=d.layers.size();for(std::size_t i=0;i<d.layers.size();++i)if(branches.contains(d.layers[i].id)){insertion=0;for(std::size_t j=0;j<=i;++j)insertion+=!roots.contains(d.layers[j].id);}
    Document next=d;std::erase_if(next.layers,[&](const Layer& l){return roots.contains(l.id);});next.layers.insert(next.layers.begin()+std::min(insertion,next.layers.size()),wrapper);
    for(const auto& id:ordered){auto child=*find(d,id);child.parentId=wrapper.id;next.layers.push_back(std::move(child));}return result(d,std::move(next),single(wrapper.id),"Group Layers");
}
bool canPlace(const Document& d,const std::string& id,const std::string& parent){try{validateDocument(d);if(!find(d,id))return false;if(parent.empty())return true;auto p=find(d,parent);return p&&p->group&&parent!=id&&!descendants(d,id).contains(parent);}catch(...){return false;}}
EditResult place(const Document& d,SelectionState,const std::string& id,const Placement& placement){if(!canPlace(d,id,placement.parent)||placement.above==id)throw std::runtime_error("Layer cannot be placed there");Document next=d;auto at=indexOf(next,id);auto moved=next.layers[at];next.layers.erase(next.layers.begin()+at);moved.parentId=placement.parent;std::size_t slot=placement.atBottom?0:next.layers.size();if(!placement.above.empty()){slot=indexOf(next,placement.above);if(slot==next.layers.size()||next.layers[slot].parentId!=placement.parent)throw std::runtime_error("Drop target is not a sibling");++slot;}next.layers.insert(next.layers.begin()+slot,moved);adoptClipping(next,id);releaseDetached(next);return result(d,std::move(next),single(id),"Move Layer");}
EditResult moveOut(const Document& d,SelectionState selected){validateDocument(d);selected=normalizeSelection(d,std::move(selected));auto l=find(d,selected.primary);if(!l||l->parentId.empty())return result(d,d,std::move(selected),"Move Layer");auto parent=find(d,l->parentId);return place(d,std::move(selected),l->id,{parent->parentId,parent->id,false});}
bool canMoveSibling(const Document& d,const std::string& id,int offset){try{validateDocument(d);auto l=find(d,id);if(!l)return false;auto stack=siblings(d,l->parentId);auto at=std::find(stack.begin(),stack.end(),id)-stack.begin();auto target=std::int64_t(at)+offset;return target>=0&&target<std::int64_t(stack.size());}catch(...){return false;}}
EditResult moveSibling(const Document& d,SelectionState selected,int offset){validateDocument(d);selected=normalizeSelection(d,std::move(selected));if(!canMoveSibling(d,selected.primary,offset))return result(d,d,std::move(selected),"Reorder Layers");auto l=find(d,selected.primary);auto stack=siblings(d,l->parentId);auto at=std::find(stack.begin(),stack.end(),l->id)-stack.begin();Document next=d;std::swap(next.layers[indexOf(d,l->id)],next.layers[indexOf(d,stack[std::size_t(at+offset)])]);return result(d,std::move(next),std::move(selected),"Reorder Layers");}
EditResult reorderTopFirst(const Document& d,SelectionState selected,std::vector<std::size_t> offsets,std::size_t destination){validateDocument(d);std::sort(offsets.begin(),offsets.end());offsets.erase(std::unique(offsets.begin(),offsets.end()),offsets.end());if(destination>d.layers.size()||(!offsets.empty()&&offsets.back()>=d.layers.size()))throw std::runtime_error("Invalid layer list move");Document next=d;std::reverse(next.layers.begin(),next.layers.end());std::vector<Layer> moved,kept;for(std::size_t i=0;i<next.layers.size();++i)(std::binary_search(offsets.begin(),offsets.end(),i)?moved:kept).push_back(next.layers[i]);auto slot=destination-std::size_t(std::count_if(offsets.begin(),offsets.end(),[&](auto i){return i<destination;}));kept.insert(kept.begin()+slot,moved.begin(),moved.end());std::reverse(kept.begin(),kept.end());next.layers=std::move(kept);return result(d,std::move(next),std::move(selected),"Reorder Layers");}
EditResult duplicateLayer(const Document& d,SelectionState,const std::string& id,std::optional<Placement> drop){validateDocument(d);auto original=find(d,id);if(!original||original->group)throw std::runtime_error("This operation duplicates one non-folder layer");if(drop&&!canPlace(d,id,drop->parent))throw std::runtime_error("Duplicate cannot be placed there");auto copy=*original;copy.id=newId();copy.name+=" copy";Document next=d;next.layers.insert(next.layers.begin()+indexOf(d,id)+1,copy);if(drop)next=place(next,single(copy.id),copy.id,*drop).document;return result(d,std::move(next),single(copy.id),"Duplicate Layer");}

bool canLink(const Document& d,const std::string& source,const std::string& target){try{validateDocument(d);auto s=find(d,source),t=find(d,target);if(!s||!t||source==target||s->group||t->group||!s->adjustmentJson.empty())return false;auto next=d;next.layers[indexOf(d,target)].maskSourceId=source;validateDocument(next);return true;}catch(...){return false;}}
EditResult link(const Document& d,SelectionState selected,const std::string& source,const std::string& target){if(!canLink(d,source,target))throw std::runtime_error("Invalid clipping dependency");auto next=d;next.layers[indexOf(d,target)].maskSourceId=source;return result(d,std::move(next),std::move(selected),"Create Clipping Mask");}
EditResult releaseClipping(const Document& d,SelectionState selected,const std::string& target){validateDocument(d);auto t=find(d,target);if(!t||t->maskSourceId.empty())return result(d,d,std::move(selected),"Release Clipping Mask");auto stack=siblings(d,t->parentId);auto start=std::find(stack.begin(),stack.end(),target);auto next=d;for(auto it=start;it!=stack.end();++it){auto& layer=next.layers[indexOf(next,*it)];if(layer.id!=target&&layer.maskSourceId!=t->maskSourceId)break;layer.maskSourceId.clear();}return result(d,std::move(next),std::move(selected),"Release Clipping Mask");}
bool canToggleClipping(const Document& d,const std::string& id){try{validateDocument(d);auto l=find(d,id);if(!l||l->group)return false;if(!l->maskSourceId.empty())return true;auto stack=siblings(d,l->parentId);auto at=std::find(stack.begin(),stack.end(),id);if(at==stack.begin())return false;auto below=find(d,*(at-1));return !below->group&&canLink(d,below->maskSourceId.empty()?below->id:below->maskSourceId,id);}catch(...){return false;}}
EditResult toggleClipping(const Document& d,SelectionState selected,const std::string& id){if(!canToggleClipping(d,id))return result(d,d,std::move(selected),"Create Clipping Mask");auto l=find(d,id);if(!l->maskSourceId.empty())return releaseClipping(d,std::move(selected),id);auto stack=siblings(d,l->parentId);auto below=find(d,*(std::find(stack.begin(),stack.end(),id)-1));return link(d,std::move(selected),below->maskSourceId.empty()?below->id:below->maskSourceId,id);}

DeletePlan deletionPlan(const Document& d,SelectionState selected){validateDocument(d);selected=normalizeSelection(d,std::move(selected));DeletePlan plan;plan.roots=selected.ids.size()>1?selected.ids:single(selected.primary).ids;for(const auto& id:plan.roots){plan.removed.insert(id);auto inside=descendants(d,id);plan.removed.insert(inside.begin(),inside.end());}for(const auto& l:d.layers)if(!plan.removed.contains(l.id)&&plan.removed.contains(l.maskSourceId))plan.dependents.push_back(l.id);return plan;}
std::shared_ptr<const Raster> bakeLiveMask(const Document& d,const std::string& target,const Limits& limits){
    validateDocument(d);cancel(limits);auto layer=find(d,target);if(!layer)throw std::runtime_error("Unknown bake target");if(!layer->raster)return {};if(layer->maskSourceId.empty())return layer->raster;
    const auto& original=*layer->raster;budget(original.width,original.height,limits);std::vector<Dependency> chain;auto source=layer->maskSourceId;
    while(!source.empty()){auto dependency=find(d,source);chain.push_back({dependency,dependency->mask&&dependency->mask->raster?double(graphics::cachedMaskBackground(dependency->mask->raster)):0.});source=dependency->maskSourceId;}
    auto bytes=original.rgba();for(int y=0;y<original.height;++y){cancel(limits);for(int x=0;x<original.width;++x){if((x&255)==0)cancel(limits);auto p=layer->transform.fromUnit({(x+.5)/original.width,(y+.5)/original.height});double alpha=1;for(auto it=chain.rbegin();it!=chain.rend();++it)alpha=it->alpha(p,alpha);auto i=(std::size_t(y)*original.width+x)*4;for(int c=0;c<4;++c)bytes[i+c]=byte(bytes[i+c]*alpha);}}
    return Raster::fromRgba(original.width,original.height,bytes.data(),std::size_t(original.width)*4);
}
EditResult erase(const Document& d,SelectionState selected,DeleteMode mode,const Limits& limits){
    validateDocument(d);selected=normalizeSelection(d,std::move(selected));auto plan=deletionPlan(d,selected);if(mode==DeleteMode::Cancel||plan.removed.empty())return result(d,d,std::move(selected),"Delete Layers");if(mode!=DeleteMode::Bake&&mode!=DeleteMode::RemoveLinks)throw std::runtime_error("Invalid deletion choice");cancel(limits);
    std::unordered_map<std::string,std::shared_ptr<const Raster>> baked;std::uint64_t retained=0;if(mode==DeleteMode::Bake)for(const auto& id:plan.dependents){cancel(limits);auto remaining=limits;remaining.maxWorkingBytes-=retained;auto asset=bakeLiveMask(d,id,remaining);if(asset){retained+=asset->retainedBytes();if(retained>limits.maxWorkingBytes)throw std::runtime_error("Layer baking exceeds retained memory budget");baked[id]=std::move(asset);}}
    auto next=d;auto active=selected.primary;for(const auto& id:plan.roots){auto at=indexOf(next,id);if(at==next.layers.size())continue;auto removed=descendants(next,id);removed.insert(id);std::erase_if(next.layers,[&](const Layer& l){return removed.contains(l.id);});for(auto& l:next.layers)if(removed.contains(l.maskSourceId)){l.maskSourceId.clear();if(auto it=baked.find(l.id);it!=baked.end())l.raster=it->second;}if(removed.contains(active))active=next.layers.empty()?std::string{}:next.layers[std::min(at,next.layers.size()-1)].id;}
    cancel(limits);return result(d,std::move(next),single(active),plan.roots.size()>1?"Delete Layers":"Delete Layer");
}
CopyResult copySubtree(const Document& source,const std::string& id,const Document& destination,std::optional<Point> point,const Limits& limits){
    validateDocument(source);validateDocument(destination);cancel(limits);auto root=find(source,id);if(!root)throw std::runtime_error("Unknown copied layer");auto included=descendants(source,id);included.insert(id);auto center=point.value_or(Point{destination.width/2.,destination.height/2.});if(!std::isfinite(center.x)||!std::isfinite(center.y))throw std::runtime_error("Invalid copy position");auto anchor=root->transform.fromUnit({.5,.5});double dx=center.x-anchor.x,dy=center.y-anchor.y;
    std::vector<Layer> copied;CopyResult output;for(const auto& l:source.layers)if(included.contains(l.id)){copied.push_back(l);output.ids[l.id]=newId();}
    std::uint64_t imagePixels=0,maskPixels=0;auto tally=[&](const Layer& l){if(l.raster)imagePixels+=std::uint64_t(l.raster->width)*l.raster->height;if(l.mask)maskPixels+=std::uint64_t(l.mask->raster->width)*l.mask->raster->height;};for(const auto& l:destination.layers)tally(l);for(const auto& l:copied)tally(l);if(imagePixels>100000000||maskPixels>100000000||destination.layers.size()+copied.size()>10000)throw std::runtime_error("Copied layers exceed the project budget");
    std::uint64_t retained=0;for(auto& l:copied){cancel(limits);if(!l.maskSourceId.empty()&&!included.contains(l.maskSourceId)){if(l.adjustmentJson.empty()){auto remaining=limits;remaining.maxWorkingBytes-=retained;l.raster=bakeLiveMask(source,l.id,remaining);if(l.raster){retained+=l.raster->retainedBytes();if(retained>limits.maxWorkingBytes)throw std::runtime_error("Copied layers exceed the working memory budget");}}l.maskSourceId.clear();}l.id=output.ids.at(l.id);l.parentId=output.ids.contains(l.parentId)?output.ids.at(l.parentId):std::string{};l.maskSourceId=output.ids.contains(l.maskSourceId)?output.ids.at(l.maskSourceId):std::string{};l.transform.x+=dx;l.transform.y+=dy;if(l.mask&&l.mask->placement){l.mask->placement->x+=dx;l.mask->placement->y+=dy;}}
    auto next=destination;next.layers.insert(next.layers.end(),copied.begin(),copied.end());cancel(limits);output.edit=result(destination,std::move(next),single(output.ids.at(id)),"Copy Layers from Project");return output;
}

std::optional<MergePlan> mergePlan(const Document& d,SelectionState selected){
    validateDocument(d);selected=normalizeSelection(d,std::move(selected));auto active=find(d,selected.primary);if(!active)return {};MergePlan plan;
    if(selected.ids.size()>1){IDs picked(selected.ids.begin(),selected.ids.end());for(const auto& id:selected.ids){auto inside=descendants(d,id);picked.insert(inside.begin(),inside.end());}const Layer* top=nullptr;bool pixels=false;for(const auto& l:d.layers)if(picked.contains(l.id)){plan.ids.push_back(l.id);pixels|=!l.group;if(std::find(selected.ids.begin(),selected.ids.end(),l.id)!=selected.ids.end())top=&l;}if(!pixels||!top)return {};plan.removed=std::move(picked);plan.name=top->name;plan.parent=top->parentId;plan.anchor=top->id;plan.action="Merge Layers";return plan;}
    if(active->group){auto inside=descendants(d,active->id);bool pixels=false;for(const auto& l:d.layers)if(inside.contains(l.id)||l.id==active->id){plan.ids.push_back(l.id);pixels|=!l.group;}if(!pixels)return {};plan.removed=IDs(plan.ids.begin(),plan.ids.end());plan.name=active->name;plan.parent=active->parentId;plan.anchor=active->id;plan.action="Merge Group";return plan;}
    const Layer* below=nullptr;for(std::size_t i=0;i<indexOf(d,active->id);++i)if(d.layers[i].parentId==active->parentId)below=&d.layers[i];if(!below||below->group)return {};plan.ids={below->id,active->id};plan.removed=IDs(plan.ids.begin(),plan.ids.end());plan.name=below->name;plan.parent=active->parentId;plan.anchor=active->id;plan.action="Merge Down";return plan;
}
EditResult merge(const Document& d,SelectionState selected,const IRasterBackend& backend,const Limits& limits){
    auto plan=mergePlan(d,selected);if(!plan)return result(d,d,std::move(selected),"Merge Down");cancel(limits);budget(d.width,d.height,limits);Document subset=d;std::erase_if(subset.layers,[&](const Layer& l){return !plan->removed.contains(l.id);});for(auto& l:subset.layers){if(!plan->removed.contains(l.parentId))l.parentId.clear();if(!plan->removed.contains(l.maskSourceId))l.maskSourceId.clear();}subset.selection.reset();
    // Keep each uncancellable backend call bounded. The document and result
    // remain private until every tile, crop and metadata edit has succeeded.
    auto tiled=std::make_shared<Raster>();tiled->width=d.width;tiled->height=d.height;
    tiled->tiles.reserve(size_t((d.width+255)/256)*size_t((d.height+255)/256));
    for(int y=0;y<d.height;y+=256)for(int x=0;x<d.width;x+=256){
        cancel(limits);const int width=std::min(256,d.width-x),height=std::min(256,d.height-y);
        const auto tile=backend.render(subset,x,y,width,height);cancel(limits);
        if(!tile||tile->width!=width||tile->height!=height||tile->tiles.size()!=1||!tile->tiles[0])throw std::runtime_error("Merge renderer returned invalid dimensions");
        tiled->tiles.push_back(tile->tiles[0]);
    }
    std::shared_ptr<const Raster> full=std::move(tiled);int loX=d.width,loY=d.height,hiX=0,hiY=0;for(int y=0;y<d.height;++y){cancel(limits);for(int x=0;x<d.width;++x)if(full->pixel(x,y).a){loX=std::min(loX,x);loY=std::min(loY,y);hiX=std::max(hiX,x+1);hiY=std::max(hiY,y+1);}}
    if(hiX<=loX||hiY<=loY){loX=loY=0;hiX=d.width;hiY=d.height;}int w=hiX-loX,h=hiY-loY;auto pixels=full;if(w!=d.width||h!=d.height){std::vector<std::uint8_t> bytes(std::size_t(w)*h*4);for(int y=0;y<h;++y){cancel(limits);for(int x=0;x<w;++x){auto p=full->pixel(x+loX,y+loY);auto i=(std::size_t(y)*w+x)*4;bytes[i]=p.r;bytes[i+1]=p.g;bytes[i+2]=p.b;bytes[i+3]=p.a;}}pixels=Raster::fromRgba(w,h,bytes.data(),std::size_t(w)*4);}
    Layer merged;merged.id=newId();merged.name=plan->name;merged.parentId=plan->parent;merged.raster=std::move(pixels);merged.transform={double(loX),double(loY),double(w),double(h)};auto next=d;std::erase_if(next.layers,[&](const Layer& l){return plan->removed.contains(l.id);});for(auto& l:next.layers)if(plan->removed.contains(l.maskSourceId))l.maskSourceId=merged.id;auto anchor=indexOf(d,plan->anchor);std::size_t slot=0;for(std::size_t i=0;i<anchor;++i)slot+=!plan->removed.contains(d.layers[i].id);next.layers.insert(next.layers.begin()+std::min(slot,next.layers.size()),merged);cancel(limits);return result(d,std::move(next),single(merged.id),plan->action);
}
}


