#include "ui/MainWindow.h"
#include <QApplication>
#include <cstdio>
#include <map>
#include <stdexcept>
using namespace compositor;
namespace {
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
QAction* command(MainWindow& window,const char* id){for(auto* action:window.findChildren<QAction*>())if(action->property("commandId")==id)return action;throw std::runtime_error("missing selection command");}
void invoke(MainWindow& window,const char* id){auto* action=command(window,id);require(action->isEnabled(),"selection command disabled");action->trigger();QApplication::processEvents();}
Document document(){Document d;d.id=newId();d.width=d.height=30000;Layer l;l.id=newId();l.transform={0,0,30000,30000};d.layers.push_back(l);return d;}
struct Fixture{MainWindow window{true};EditorProject& project;Fixture():project(window.addProject(document())){window.show();QApplication::processEvents();}void rectangle(){invoke(window,"tool.marquee");project.canvas->pointerDown({15000,12000},{});project.canvas->pointerMove({15012,12014},{});project.canvas->pointerUp({15012,12014},{});}int pixel(int x,int y)const{return project.document->selection?project.document->selection->coverage->pixel(x,y):-1;}};
void allInverseUndo(){Fixture f;const auto before=f.project.document;invoke(f.window,"selection.all");require(f.pixel(2,2)==255&&f.pixel(29999,29999)==255,"large Select All");require(f.project.history.undoCount()==1,"Select All owns one history entry");invoke(f.window,"selection.inverse");require(f.project.document->selection&&!f.project.document->selection->coverage->hasCoverage(),"inverse All stays explicitly empty");invoke(f.window,"edit.undo");require(f.pixel(2,2)==255,"Undo inverse restores full coverage");invoke(f.window,"edit.undo");require(f.project.document==before,"Undo Select All restores exact document");}
void marqueeHistory(){Fixture f;const auto before=f.project.document;f.rectangle();require(f.pixel(15006,12005)==255&&f.pixel(14999,12005)==0,"large canvas marquee coverage");require(f.project.history.undoCount()==1,"marquee single history entry");invoke(f.window,"edit.undo");require(f.project.document==before,"large marquee undo exact");invoke(f.window,"edit.redo");require(f.pixel(15006,12005)==255,"large marquee redo");}
void clippedBrush(){Fixture f;f.rectangle();const auto before=f.project.document;invoke(f.window,"tool.brush");f.project.canvas->pointerDown({15006,12007},{});f.project.canvas->pointerMove({15008,12008},{});f.project.canvas->pointerUp({15008,12008},{});require(f.project.document->layers[0].raster&&f.project.history.undoCount()==2,"selected brush commits on large blank canvas");auto selected=SoftwareRenderer().render(*f.project.document,15006,12007,1,1),outside=SoftwareRenderer().render(*f.project.document,14999,12007,1,1);require(selected->pixel(0,0).a>0&&outside->pixel(0,0).a==0,"large brush honors selection");invoke(f.window,"edit.undo");require(f.project.document==before,"brush Undo restores exact selection and blank source");}
void emptyBrush(){Fixture f;invoke(f.window,"selection.all");invoke(f.window,"selection.inverse");const auto before=f.project.document;const auto history=f.project.history.undoCount();invoke(f.window,"tool.brush");f.project.canvas->pointerDown({15006,12007},{});f.project.canvas->pointerMove({15008,12008},{});f.project.canvas->pointerUp({15008,12008},{});require(f.project.document==before&&f.project.history.undoCount()==history,"explicit empty selection must suppress brush and history");}
}
int main(int argc,char** argv){QApplication app(argc,argv);const std::map<std::string,void(*)()> cases{{"all_inverse_undo",allInverseUndo},{"marquee_history",marqueeHistory},{"clipped_brush",clippedBrush},{"empty_brush",emptyBrush}};try{require(argc==2&&cases.contains(argv[1]),"provide sparse UI case");cases.at(argv[1])();std::printf("PASS %s\n",argv[1]);return 0;}catch(const std::exception& e){std::fprintf(stderr,"FAIL %s\n",e.what());return 1;}}
