#include "editing/Selection.h"
#include "editing/PixelEdits.h"
#include "editing/GradientPreview.h"
#include "editing_transform/PixelTransform.h"
#include "graphics/GrowingBrushSession.h"
#include <QCoreApplication>
#include <cstdio>
#include <map>
#include <stdexcept>
using namespace compositor;
using namespace compositor::editing;
namespace {
void require(bool okay,const char* text){if(!okay)throw std::runtime_error(text);}
Document large(){Document d;d.id="sparse-selection";d.width=d.height=30000;Layer l;l.id="source";l.transform={0,0,30000,30000};d.layers.push_back(l);return d;}
void choose(Document& d,SelectionOutline outline){d.selection=rasterSelection(outline,d.width,d.height);validateDocument(d);require(d.selection&&d.selection->coverage,"present selection coverage");require(d.selection->coverage->pixels.size()<=1024*1024,"small selection allocated more than one MiB of stored coverage");}
void smallRoi(){auto d=large();choose(d,SelectionOutline::rectangle({15000,12000,12,14},false));auto& c=*d.selection->coverage;require(c.width==30000&&c.height==30000,"coverage uses document coordinates");require(c.pixel(15005,12005)==255&&c.pixel(14999,12005)==0&&c.pixel(15012,12005)==0,"placed rectangle coverage mismatch");}
void presentEmpty(){auto d=large();choose(d,SelectionOutline{});require(d.selection&&d.selection->coverage->pixel(15000,15000)==0&&coverageBounds(*d.selection->coverage).empty(),"explicit empty selection must stay present and empty");require(editLayer(d.layers[0],d,PixelEdit::Fill,{255,0,0,255})==d.layers[0],"empty selection must touch no pixels");}
void antialiasMapping(){auto d=large();auto outline=SelectionOutline::ellipse({15000.25,12000.5,14.5,12.25});choose(d,outline);auto reference=outline.moved({-14848,-11776}).rasterize(512,512);for(int y=11998;y<12016;++y)for(int x=14998;x<15018;++x)require(d.selection->coverage->pixel(x,y)==reference->pixel(x-14848,y-11776),"large ROI antialias differs from same translated dense outline");Transform t{14995.25,11996.5,32,28,13};auto mapped=mappedCoverage(d,t,32,28);Document small;small.id="reference";small.width=small.height=512;small.selection=Selection{reference};t.x-=14848;t.y-=11776;auto expected=mappedCoverage(small,t,32,28);require(mapped->pixels==expected->pixels,"transformed selection interpolation changed");}
void moveOutBack(){auto d=large();choose(d,SelectionOutline::rectangle({29990,40,8,9},false));const auto original=d.selection;auto outside=moveSelectionCoverage(original,{20,0});require(outside&&coverageBounds(*outside->coverage).empty(),"selection should clip outside canvas");auto restored=moveSelectionCoverage(outside,{-20,0});require(restored&&restored->coverage->pixel(29993,44)==255,"moving back must preserve vector geometry outside canvas");require(original->coverage->pixel(29993,44)==255,"move mutated original coverage");}
void inverse(){auto d=large();auto shape=SelectionOutline::rectangle({15000,12000,12,14},false);choose(d,*inverseSelection(shape,d.width,d.height));require(d.selection->coverage->pixel(15005,12005)==0&&d.selection->coverage->pixel(2,2)==255&&d.selection->coverage->pixel(29999,29999)==255,"inverse selection must represent large uniform exterior and hole");auto mapped=mappedCoverage(d,Transform{14998,11998,20,20},20,20);require(mapped->pixel(0,0)==255&&mapped->pixel(5,5)==0,"inverse source mapping");}
void fillSmallBlank(){auto d=large();choose(d,SelectionOutline::rectangle({15000,12000,12,14},false));const auto before=d;auto filled=editLayer(d.layers[0],d,PixelEdit::Fill,{255,0,0,255});require(filled.raster&&uint64_t(filled.raster->width)*filled.raster->height<=1024*1024,"small fill allocated a whole canvas");Document out=d;out.layers[0]=filled;require(SoftwareRenderer().render(out,15005,12005,1,1)->pixel(0,0)==Pixel{255,0,0,255},"small blank fill missing");require(SoftwareRenderer().render(out,14999,12005,1,1)->pixel(0,0)==Pixel{},"fill escaped selection");require(d==before,"fill mutated input document");}
void gradientSmallBlank(){auto d=large();choose(d,SelectionOutline::rectangle({15000,12000,12,14},false));GradientSettings settings;settings.style=GradientStyle::ForegroundToBackground;GradientPreview preview(d.layers[0],d,{15000,12000},{15012,12000},settings,{0,0,0,255},{255,255,255,255},false);auto layer=preview.materializeLayer();require(layer.raster&&uint64_t(layer.raster->width)*layer.raster->height<=1024*1024,"selected gradient allocated whole canvas");Document out=d;out.layers[0]=layer;auto pixel=SoftwareRenderer().render(out,15006,12005,1,1)->pixel(0,0);require(pixel.a==255&&pixel.r>100&&pixel.r<160,"selected gradient color");require(SoftwareRenderer().render(out,14999,12005,1,1)->pixel(0,0)==Pixel{},"gradient escaped selection");}
void brushSmallBlank(){auto d=large();choose(d,SelectionOutline::rectangle({15000,12000,12,14},false));graphics::BrushSessionSettings settings;settings.radius=20;settings.color={255,0,0};graphics::GrowingBrushSession session(d.layers[0],settings,d.width,d.height,{},d.selection->coverage);require(session.begin({15006,12007}),"brush should begin inside selected ROI");auto layer=session.commit()->materializeLayer();Document out=d;out.layers[0]=layer;require(layer.raster&&uint64_t(layer.raster->width)*layer.raster->height<=1024*1024,"selected brush allocated whole canvas");require(SoftwareRenderer().render(out,15006,12007,1,1)->pixel(0,0).a>0&&SoftwareRenderer().render(out,14999,12007,1,1)->pixel(0,0).a==0,"brush clipping changed");}
void copyRoi(){auto d=large();d.layers[0].transform={14996,11996,32,32};d.layers[0].raster=Raster::filled(32,32,{80,120,160,255});choose(d,SelectionOutline::rectangle({15000,12000,12,14},false));auto copied=copyPixels(d,std::string_view("source"),SoftwareRenderer());require(copied&&copied->origin==Point{15000,12000}&&copied->raster->width==12&&copied->raster->height==14,"Copy selection extent must remain bounded and placed");require(copied->raster->pixel(5,5)==Pixel{80,120,160,255},"selected copy content");}
void pixelMove(){auto d=large();d.layers[0].transform={14996,11996,32,32};d.layers[0].raster=Raster::filled(32,32,{80,120,160,255});choose(d,SelectionOutline::rectangle({15000,12000,12,14},false));editing_transform::PixelTransformSession session(d.layers[0],d.selection->coverage);require(session.begin(),"selected pixel move begin");session.move({3,4});auto result=session.apply();require(result.selection&&result.selection->pixel(15005,12005)==255&&result.selection->pixel(15000,12000)==0,"moved selection coverage must use bounded document coordinates");require(result.layer.raster&&uint64_t(result.layer.raster->width)*result.layer.raster->height<=1024*1024,"selected pixel move allocated whole canvas");}
}
int main(int argc,char** argv){QCoreApplication app(argc,argv);const std::map<std::string,void(*)()> cases{{"small_roi",smallRoi},{"present_empty",presentEmpty},{"antialias_mapping",antialiasMapping},{"move_out_back",moveOutBack},{"inverse",inverse},{"fill_small_blank",fillSmallBlank},{"gradient_small_blank",gradientSmallBlank},{"brush_small_blank",brushSmallBlank},{"copy_roi",copyRoi},{"pixel_move",pixelMove}};int failed=0;for(const auto& [name,test]:cases){if(argc>1&&argv[1]!=name)continue;try{test();std::printf("PASS %s\n",name.c_str());}catch(const std::exception& error){++failed;std::printf("FAIL %s: %s\n",name.c_str(),error.what());}}if(argc>1&&!cases.contains(argv[1]))return 2;return failed?1:0;}
