#include "ui/MainWindow.h"
#include "editing/Shapes.h"
#include <QApplication>
#include <QInputDialog>
#include <QTimer>
#include <QElapsedTimer>
#include <iostream>
#include <map>
#include <stdexcept>
using namespace compositor;
#define REQUIRE(...) do{if(!(__VA_ARGS__))throw std::runtime_error(std::string("line ")+std::to_string(__LINE__)+": " #__VA_ARGS__);}while(false)
Document fixture(){Document d;d.id="inspector";d.width=100;d.height=80;Layer l;l.id="image";l.raster=Raster::filled(32,16,{70,180,120,255});l.transform={8,8,64,32};d.layers.push_back(l);return d;}
template<class T>T* control(MainWindow&w,const char*name){auto*p=w.findChild<T*>(name);REQUIRE(p);return p;}
void action(MainWindow&w,const char*name){control<QAction>(w,name)->trigger();}
void field(MainWindow&w,const char*name,double value){for(auto*spin:w.findChildren<QDoubleSpinBox*>())if(spin->accessibleName()==name){spin->setValue(value);QMetaObject::invokeMethod(spin,"editingFinished",Qt::DirectConnection);return;}throw std::runtime_error("Inspector field missing");}
void moveTool(MainWindow&w){for(auto*a:w.findChildren<QAction*>())if(a->text()=="Move (V)"){a->trigger();return;}throw std::runtime_error("Move tool missing");}
void scale(MainWindow&w,double percent){QAction* command=nullptr;for(auto*a:w.findChildren<QAction*>())if(a->text()=="Scale…")command=a;REQUIRE(command);bool seen=false;QTimer poll;poll.setInterval(5);QObject::connect(&poll,&QTimer::timeout,[&]{auto*dialog=qobject_cast<QInputDialog*>(QApplication::activeModalWidget());if(dialog){seen=true;dialog->setDoubleValue(percent);dialog->accept();}});poll.start();command->trigger();poll.stop();REQUIRE(seen);}
void inspector_numeric_cancel(){MainWindow w(true);auto d=fixture();auto&p=w.addProject(d);field(w,"X",14.25);REQUIRE(p.history.undoCount()==0&&control<QAction>(w,"cancelTransform")->isEnabled());REQUIRE(p.document->layers[0].transform.x==14.25);action(w,"cancelTransform");REQUIRE(p.document==d&&p.history.undoCount()==0);}
void inspector_multiple_fields_one_apply(){MainWindow w(true);auto d=fixture();auto&p=w.addProject(d);field(w,"X",14);field(w,"Y",17);field(w,"Angle",450);REQUIRE(p.history.undoCount()==0&&p.document->layers[0].transform.rotation==90);action(w,"applyTransform");REQUIRE(p.history.undoCount()==1&&p.document->layers[0].raster==d.layers[0].raster);auto undo=p.history.undo();REQUIRE(undo&&undo->document==d);}
void inspector_sampling_mask_scope(){MainWindow w(true);auto d=fixture();d.layers[0].mask=Mask{std::make_shared<GrayRaster>(GrayRaster{8,4,std::vector<uint8_t>(32,255)}),true,false,Transform{20,12,16,8}};auto&p=w.addProject(d);p.maskSelected=true;moveTool(w);control<QComboBox>(w,"transformSampling")->setCurrentIndex(0);REQUIRE(p.history.undoCount()==0&&p.document->layers[0].transform==d.layers[0].transform);REQUIRE(p.document->layers[0].mask->placement->sampling==Transform::Sampling::Nearest);action(w,"cancelTransform");REQUIRE(p.document==d);}
void inspector_flip_cancel(){MainWindow w(true);auto d=fixture();auto&p=w.addProject(d);action(w,"transformFlipH");REQUIRE(p.history.undoCount()==0&&p.document->layers[0].transform.flipX);action(w,"cancelTransform");REQUIRE(p.document==d);}
void inspector_group_scale_scope(){MainWindow w(true);auto d=fixture();Layer folder;folder.id="folder";folder.group=true;d.layers[0].parentId=folder.id;d.layers[0].transform={10,10,20,10};Layer second=d.layers[0];second.id="second";second.transform={40,10,20,10};d.layers.insert(d.layers.begin(),folder);d.layers.push_back(second);auto&p=w.addProject(d);p.active=folder.id;p.selected={folder.id};moveTool(w);action(w,"freeTransform");scale(w,150);REQUIRE(p.history.undoCount()==0);REQUIRE(p.document->layers[1].transform.x==-2.5&&p.document->layers[1].transform.width==30&&p.document->layers[1].transform.height==15);REQUIRE(p.document->layers[2].transform.x==42.5);action(w,"cancelTransform");REQUIRE(p.document==d);}
void inspector_mask_scale_reference(){MainWindow w(true);auto d=fixture();d.layers[0].mask=Mask{std::make_shared<GrayRaster>(GrayRaster{8,4,std::vector<uint8_t>(32,255)}),true,false,Transform{20,12,16,8}};auto&p=w.addProject(d);p.maskSelected=true;moveTool(w);scale(w,100);REQUIRE(p.history.undoCount()==0&&p.document->layers[0].transform==d.layers[0].transform);const auto m=p.document->layers[0].mask->placement;REQUIRE(m&&m->x==-4&&m->y==0&&m->width==64&&m->height==32);action(w,"cancelTransform");REQUIRE(p.document==d);}
void inspector_floating_scale_reference(){MainWindow w(true);auto d=fixture();auto coverage=std::make_shared<GrayRaster>(GrayRaster{100,80,std::vector<uint8_t>(8000)});for(int y=10;y<18;++y)for(int x=20;x<30;++x)coverage->pixels[size_t(y)*100+x]=255;d.selection=Selection{coverage};auto&p=w.addProject(d);action(w,"freeTransform");REQUIRE(p.document->layers.size()==2);scale(w,200);REQUIRE(p.history.undoCount()==0&&p.document->layers.size()==2);const auto t=p.document->layers[1].transform;REQUIRE(t.x==15&&t.y==6&&t.width==20&&t.height==16);action(w,"cancelTransform");REQUIRE(p.document==d);}
void inspector_live_rounded_shape(){MainWindow w(true);auto d=fixture();auto shape=editing::createShapeLayer({10,10,22,18},{editing::ShapeKind::Rectangle,1,0,0,6},"Rounded");REQUIRE(shape);shape->id="image";d.layers[0]=*shape;auto&p=w.addProject(d);action(w,"freeTransform");field(w,"Width",44);const auto expected=editing::shapeTransformPreview(d.layers[0],p.document->layers[0].transform);REQUIRE(expected&&p.document->layers[0].raster->width==44);REQUIRE(p.document->layers[0].raster->rgba()==expected->rgba()&&d.layers[0].raster->width==22&&p.history.undoCount()==0);action(w,"cancelTransform");REQUIRE(p.document==d);}
int main(int argc,char**argv){QApplication app(argc,argv);std::map<std::string,void(*)()>tests{{"inspector_numeric_cancel",inspector_numeric_cancel},{"inspector_multiple_fields_one_apply",inspector_multiple_fields_one_apply},{"inspector_sampling_mask_scope",inspector_sampling_mask_scope},{"inspector_flip_cancel",inspector_flip_cancel},{"inspector_group_scale_scope",inspector_group_scale_scope},{"inspector_mask_scale_reference",inspector_mask_scale_reference},{"inspector_floating_scale_reference",inspector_floating_scale_reference},{"inspector_live_rounded_shape",inspector_live_rounded_shape}};int failed=0;for(const auto&[name,test]:tests){if(argc>1&&argv[1]!=name)continue;try{test();std::cout<<"PASS "<<name<<'\n';}catch(const std::exception&e){++failed;std::cout<<"FAIL "<<name<<": "<<e.what()<<'\n';}}if(argc>1&&!tests.contains(argv[1]))return 2;return failed?1:0;}
