// The four directory-drop assertions are reused without alteration from the
// frozen baseline witness. New APIs and native picker checks are separate cases.
#define main frozenBeforeWitnessMain
#include "BeforeOpenBatchTests.cpp"
#undef main
#include "ui/ProjectOpenDialog.h"
#include "ui/ImportActions.h"
#include "ui/VisualStyle.h"
#include <Windows.h>
#include <ShObjIdl.h>
#include <wrl/client.h>
#include <QFile>
#include <QElapsedTimer>
#include <QSpinBox>
#include <QTest>
#include <QListWidget>
#include <QLineEdit>
#include <QDialogButtonBox>
#include <QPushButton>

namespace {
void themed_picker(){
    Fixture f;bool visited=false;std::exception_ptr failure;
    QTimer::singleShot(80,&f.window,[&]{
        auto* dialog=qobject_cast<QDialog*>(QApplication::activeModalWidget());
        try{
            require(dialog&&dialog->windowFlags().testFlag(Qt::FramelessWindowHint)==ui::macTitleBarEnabled(),"picker respects selected title bar");
            auto* list=dialog->findChild<QListWidget*>("projectFolders");QLineEdit* path=nullptr;
            for(auto* edit:dialog->findChildren<QLineEdit*>())if(edit->accessibleName()=="Folder path")path=edit;
            auto* box=dialog->findChild<QDialogButtonBox*>();require(list&&path&&box,"picker controls");
            path->setText(f.directory.path());QTest::keyClick(path,Qt::Key_Return);
            require(!box->button(QDialogButtonBox::Open)->isEnabled(),"browse does not accept an ordinary folder");
            for(int i=0;i<list->count();++i){auto* item=list->item(i);const auto value=item->data(Qt::UserRole).toString();if(value==f.a||value==f.b)item->setSelected(true);}
            require(list->selectedItems().size()==2&&box->button(QDialogButtonBox::Open)->isEnabled(),"multiple packages are selectable");
            const auto output=qEnvironmentVariable("COMPOSITOR_UI_CAPTURE");if(!output.isEmpty())require(dialog->grab().save(output+"/project-picker.png"),"picker capture");
            visited=true;box->button(QDialogButtonBox::Open)->click();
        }catch(...){failure=std::current_exception();if(dialog)dialog->reject();}
    });
    const auto selected=ui::chooseProjectDirectories(&f.window);if(failure)std::rethrow_exception(failure);
    require(visited&&selected&&selected->size()==2&&selected->contains(f.a)&&selected->contains(f.b),"picker returns both package paths");
    QTimer::singleShot(80,&f.window,[]{if(auto* dialog=qobject_cast<QDialog*>(QApplication::activeModalWidget()))dialog->close();});
    require(!ui::chooseProjectDirectories(&f.window),"close cancels picker");
    QTimer::singleShot(80,&f.window,[&]{if(auto* dialog=qobject_cast<QDialog*>(QApplication::activeModalWidget()))for(auto* edit:dialog->findChildren<QLineEdit*>())if(edit->accessibleName()=="Folder path"){edit->setText(f.a);QTest::keyClick(edit,Qt::Key_Return);break;}});
    const auto typed=ui::chooseProjectDirectories(&f.window);require(typed&&*typed==QStringList{f.a},"typed package is opened atomically");
}
void batch_empty(){Fixture f;auto* initial=f.tabs()->currentWidget();require(!f.window.openProjectPaths({}),"empty selection returns false");require(f.tabs()->count()==1&&f.tabs()->currentWidget()==initial&&command(f.window,"file.open")->isEnabled(),"empty selection preserves welcome and releases command eligibility");}
void batch_order(){Fixture f;require(f.window.openProjectPaths({f.b,f.a}),"batch returns any-success true");require(f.tabs()->count()==2&&f.tabs()->currentIndex()==1&&f.tabs()->tabText(0).contains("B.comp")&&f.tabs()->tabText(1).contains("A.comp"),"batch preserves supplied order and selects final successful project");require(command(f.window,"file.open")->isEnabled(),"completed batch releases guard");}
void batch_existing(){Fixture f;f.window.openPath(f.a);command(f.window,"pixels.invert")->trigger();auto* initial=f.tabs()->currentWidget();auto* canvas=f.window.canvas();require(f.window.openProjectPaths({f.b,f.a,f.b,f.a}),"duplicate batch succeeds");require(f.tabs()->count()==2&&f.tabs()->currentWidget()==initial&&f.window.canvas()==canvas&&command(f.window,"edit.undo")->isEnabled(),"duplicate batch preserves original unsaved session and order");}
void batch_mixed_failure(){Fixture f;require(f.window.openProjectPaths({f.broken,f.a,f.broken,f.b}),"mixed batch returns success despite failures");require(f.errors==2&&f.tabs()->count()==2&&f.tabs()->currentIndex()==1&&f.tabs()->tabText(0).contains("A.comp")&&f.tabs()->tabText(1).contains("B.comp"),"each failed package is reported once and later packages still open");}
void batch_all_fail(){Fixture f;auto* initial=f.tabs()->currentWidget();require(!f.window.openProjectPaths({f.broken,f.directory.filePath("missing.comp")}),"all failures return false");require(f.errors==2&&f.tabs()->count()==1&&f.tabs()->currentWidget()==initial&&qobject_cast<QStackedWidget*>(initial)->currentWidget()->objectName()=="newCanvasWelcome","failed loads preserve original empty welcome without broken tabs");require(command(f.window,"file.open")->isEnabled(),"failure releases guard");}
void batch_pending_guard(){Fixture f;f.window.openPath(f.a);command(f.window,"tool.gradient")->trigger();auto* canvas=f.window.canvas();canvas->pointerDown({4,10},{});canvas->pointerMove({25,10},{});canvas->pointerUp({25,10},{});require(command(f.window,"gradient.apply")->isEnabled(),"pending gradient fixture");require(!f.window.openProjectPaths({f.b}),"pending batch rejected");require(f.tabs()->count()==1&&f.errors==0&&command(f.window,"gradient.apply")->isEnabled(),"guard leaves draft, tab and errors unchanged");}
void batch_busy_guard(){for(bool busy:{false,true}){Fixture f;auto& project=f.window.addProject(sample(32),"Busy");project.projectBusy=busy;project.importing=!busy;const auto before=project.document;require(!f.window.openProjectPaths({f.a,f.b}),"busy or importing batch rejected");require(f.tabs()->count()==1&&project.document==before&&f.errors==0,"busy guard preserves current document");project.projectBusy=project.importing=false;}}
void batch_error_reentrancy(){Fixture f;bool observed=false,rejected=false;QTimer probe;probe.setInterval(1);QObject::connect(&probe,&QTimer::timeout,&f.window,[&]{for(auto* box:f.window.findChildren<QMessageBox*>("projectOpenError"))if(box->isVisible()&&!observed){observed=true;const auto count=f.tabs()->count();rejected=!f.window.openProjectPaths({f.b});f.window.openPath(f.b);rejected=rejected&&f.tabs()->count()==count;}});probe.start();require(f.window.openProjectPaths({f.a,f.broken,f.b}),"outer batch succeeds");require(observed&&rejected&&f.errors==1&&f.tabs()->count()==2&&command(f.window,"file.open")->isEnabled(),"error dialog blocks reentrant opens and completion restores eligibility");}
void welcome_fresh_session(){Fixture f;auto& previous=f.window.addEmptyProject();auto* canvas=previous.canvas;auto* page=previous.page;auto* amount=f.window.findChild<QSpinBox*>("selectionExpandAmount");require(amount,"welcome remembered setting control");amount->setValue(17);previous.collapsedGroups.insert("old welcome setting");previous.cloneSampleAllLayers=true;require(f.window.openProjectPaths({f.a}),"new package opens");require(f.tabs()->count()==1&&f.tabs()->currentWidget()!=page&&f.window.canvas()!=canvas,"successful open replaces sole welcome identity with a fresh session");require(amount->value()==1&&command(f.window,"file.open")->isEnabled(),"fresh loaded session restores source remembered default and releases guard");require(!page->isEnabled(),"retired welcome cannot dispatch controls while queued for deletion");QCoreApplication::sendPostedEvents(nullptr,QEvent::DeferredDelete);command(f.window,"file.new")->trigger();require(f.tabs()->count()==2&&f.tabs()->tabText(f.tabs()->currentIndex())=="Untitled 2","named loaded session does not consume next Untitled number");}
void welcome_failure_preserves_session(){Fixture f;auto& previous=f.window.addEmptyProject();auto* canvas=previous.canvas;auto* page=previous.page;auto* amount=f.window.findChild<QSpinBox*>("selectionExpandAmount");require(amount,"welcome remembered setting control");amount->setValue(23);previous.collapsedGroups.insert("retained welcome setting");previous.cloneSampleAllLayers=true;require(!f.window.openProjectPaths({f.broken}),"failed open returns false");require(f.tabs()->count()==1&&f.tabs()->currentWidget()==page&&f.window.canvas()==canvas&&!previous.document&&previous.collapsedGroups.contains("retained welcome setting")&&previous.cloneSampleAllLayers&&amount->value()==23,"failed load preserves empty session identity, settings and document absence");}
void welcome_project_then_image_skipped(){
    Fixture f;auto& welcome=f.window.addEmptyProject();QPointer<QWidget> oldPage=welcome.page;QPointer<NativeCanvas> oldCanvas=welcome.canvas;
    f.window.resize(900,700);f.window.show();QApplication::processEvents();
    const auto point=welcome.page->mapTo(&f.window,welcome.page->rect().center());require(welcome.page->rect().contains(welcome.page->mapFrom(&f.window,point)),"explicit welcome drop destination");
    const auto imagePath=f.directory.filePath("Later image.png");QImage image(4,4,QImage::Format_RGBA8888);image.fill(Qt::red);require(image.save(imagePath,"PNG"),"retained valid dropped image fixture");
    require(ui::ImportQueue::find(&f.window)==nullptr,"fixture has no import queue");
    QMimeData mime;mime.setUrls({QUrl::fromLocalFile(f.a),QUrl::fromLocalFile(imagePath)});QDragEnterEvent enter(point,Qt::CopyAction,&mime,Qt::LeftButton,{});QApplication::sendEvent(&f.window,&enter);require(enter.isAccepted(),"mixed project/image drag accepted");QDropEvent drop(QPointF(point),Qt::CopyAction,&mime,Qt::LeftButton,{});QApplication::sendEvent(&f.window,&drop);require(drop.isAccepted(),"mixed project/image drop handled");
    require(f.tabs()->count()==1&&f.tabs()->tabText(0).contains("A.comp")&&f.tabs()->currentWidget()!=oldPage&&f.window.canvas()!=oldCanvas,"project replaces captured welcome session");
    require(ui::ImportQueue::find(&f.window)==nullptr,"later image targeting removed welcome is skipped before creating an import queue");
    QCoreApplication::sendPostedEvents(nullptr,QEvent::DeferredDelete);QTest::qWait(100);
    auto* layers=f.window.findChild<QTreeWidget*>();require(oldPage.isNull()&&oldCanvas.isNull(),"retired welcome widgets are destroyed");require(layers&&layers->topLevelItemCount()==1&&f.tabs()->count()==1&&!command(f.window,"edit.undo")->isEnabled()&&ui::ImportQueue::find(&f.window)==nullptr&&f.errors==0,"posted events leave only the loaded project's layer, no import/history/error callback");
}
void package_policy(){Fixture f;const auto nested=f.a+"/assets";require(QDir().mkdir(nested),"nested package directory");require(ui::isProjectPackageDirectory(f.a)&&ui::isProjectPackageDirectory(f.a.toUpper()),"existing case-insensitive comp directories selectable");require(!ui::isProjectPackageDirectory(f.directory.path())&&!ui::isProjectPackageDirectory(f.directory.filePath("absent.comp")),"ordinary and missing directories not selectable");require(ui::canNavigateProjectFolder(f.directory.path())&&!ui::canNavigateProjectFolder(f.a)&&!ui::canNavigateProjectFolder(nested),"normal folder navigation allowed but package and descendants denied");QFile file(f.directory.filePath("File.comp"));require(file.open(QIODevice::WriteOnly),"file fixture");file.write("not a package");file.close();require(!ui::isProjectPackageDirectory(file.fileName()),"regular file with comp suffix rejected");}
void native_options(){const auto initialized=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);require(SUCCEEDED(initialized),"STA initialization");struct Cleanup{~Cleanup(){CoUninitialize();}} cleanup;Microsoft::WRL::ComPtr<IFileOpenDialog> dialog;require(SUCCEEDED(CoCreateInstance(CLSID_FileOpenDialog,nullptr,CLSCTX_INPROC_SERVER,IID_PPV_ARGS(&dialog))),"real Windows file dialog creation");FILEOPENDIALOGOPTIONS before{},after{};require(SUCCEEDED(dialog->GetOptions(&before)),"initial native options");ui::configureProjectOpenDialog(dialog.Get());require(SUCCEEDED(dialog->GetOptions(&after)),"configured native options");std::cout<<"native_options_before="<<before<<" after="<<after<<'\n';require((after&before)==before&&(after&(FOS_PICKFOLDERS|FOS_ALLOWMULTISELECT|FOS_FORCEFILESYSTEM))==(FOS_PICKFOLDERS|FOS_ALLOWMULTISELECT|FOS_FORCEFILESYSTEM),"real dialog enables folder/multiple/filesystem options and preserves defaults");}
struct CancelProbe {HWND owner{};DWORD thread{};bool seen{},owned{};int ticks{};};
thread_local CancelProbe* cancelProbe{};
void CALLBACK cancelNative(HWND,UINT,UINT_PTR, DWORD){auto* probe=cancelProbe;if(!probe)return;++probe->ticks;EnumThreadWindows(probe->thread,[](HWND window,LPARAM value)->BOOL{auto* p=reinterpret_cast<CancelProbe*>(value);wchar_t title[256]{};GetWindowTextW(window,title,256);if(std::wstring_view(title)==L"Open Compositor Projects"&&IsWindowVisible(window)){p->seen=true;p->owned=GetWindow(window,GW_OWNER)==p->owner;PostMessageW(window,WM_COMMAND,MAKEWPARAM(IDCANCEL,BN_CLICKED),reinterpret_cast<LPARAM>(GetDlgItem(window,IDCANCEL)));}return TRUE;},reinterpret_cast<LPARAM>(probe));}
void native_dialog_cancel(){Fixture f;f.window.show();QApplication::processEvents();auto* initial=f.tabs()->currentWidget();CancelProbe probe{reinterpret_cast<HWND>(f.window.winId()),GetCurrentThreadId()};cancelProbe=&probe;const auto timer=SetTimer(nullptr,0,50,cancelNative);require(timer!=0,"owned dialog cancellation timer");command(f.window,"file.open")->trigger();KillTimer(nullptr,timer);cancelProbe=nullptr;std::cout<<"dialog_seen="<<probe.seen<<" dialog_owned="<<probe.owned<<" timer_ticks="<<probe.ticks<<'\n';require(probe.seen&&probe.owned&&f.tabs()->count()==1&&f.tabs()->currentWidget()==initial&&command(f.window,"file.open")->isEnabled(),"actual native owned dialog Cancel preserves welcome and releases guard");}
}
int main(int argc,char** argv){QApplication app(argc,argv);std::cout<<std::unitbuf;QDir().mkpath(QFileInfo(QString::fromUtf8(__FILE__)).dir().filePath("fixtures"));const std::map<std::string,void(*)()> cases{{"themed_picker",themed_picker},{"drop_order",drop_order},{"drop_mixed_failure",drop_mixed_failure},{"drop_existing",drop_existing},{"drop_pending_guard",drop_pending_guard},{"batch_empty",batch_empty},{"batch_order",batch_order},{"batch_existing",batch_existing},{"batch_mixed_failure",batch_mixed_failure},{"batch_all_fail",batch_all_fail},{"batch_pending_guard",batch_pending_guard},{"batch_busy_guard",batch_busy_guard},{"batch_error_reentrancy",batch_error_reentrancy},{"welcome_fresh_session",welcome_fresh_session},{"welcome_failure_preserves_session",welcome_failure_preserves_session},{"welcome_project_then_image_skipped",welcome_project_then_image_skipped},{"package_policy",package_policy},{"native_options",native_options},{"native_dialog_cancel",native_dialog_cancel}};try{require(argc==2&&cases.contains(argv[1]),"provide named batch case");std::cout<<"START "<<argv[1]<<'\n';cases.at(argv[1])();std::cout<<"PASS "<<argv[1]<<'\n';return 0;}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<'\n';return 1;}}
