#include "ui/ProjectOpenDialog.h"
#include <QApplication>
#include <QDir>
#include <QFileInfo>
#include <QTemporaryDir>
#include <QWidget>
#include <Windows.h>
#include <CommCtrl.h>
#include <functional>
#include <iostream>
#include <string>
#include <set>
namespace {
struct Probe{HWND owner{};DWORD thread{};bool seen{},owned{},inspected{},submitted{},thisPc{},navigationConfirmed{};QStringList paths;std::set<HWND> windows;};
thread_local Probe* active{};
void CALLBACK tick(HWND,UINT,UINT_PTR,DWORD){if(!active)return;EnumThreadWindows(active->thread,[](HWND window,LPARAM data)->BOOL{auto* probe=reinterpret_cast<Probe*>(data);wchar_t title[256]{};GetWindowTextW(window,title,256);if(std::wstring_view(title)!=L"Open Compositor Projects"||!IsWindowVisible(window))return TRUE;if(probe->windows.insert(window).second){std::cout<<"dialog_owner_match="<<(GetWindow(window,GW_OWNER)==probe->owner)<<'\n';EnumChildWindows(window,[](HWND child,LPARAM)->BOOL{wchar_t text[1024]{},kind[128]{};GetClassNameW(child,kind,128);GetWindowTextW(child,text,1024);if(std::wstring_view(kind)==L"Static")std::cout<<"static="<<QString::fromWCharArray(text).toStdString()<<'\n';return TRUE;},0);}probe->seen=true;probe->owned=GetWindow(window,GW_OWNER)==probe->owner;if(!probe->owned)return TRUE;
    if(!probe->inspected){probe->inspected=true;EnumChildWindows(window,[](HWND child,LPARAM)->BOOL{wchar_t name[512]{},kind[128]{};GetClassNameW(child,kind,128);GetWindowTextW(child,name,512);std::cout<<"control id="<<GetDlgCtrlID(child)<<" class="<<QString::fromWCharArray(kind).toStdString()<<" visible="<<bool(IsWindowVisible(child))<<" name="<<QString::fromWCharArray(name).toStdString()<<'\n';return TRUE;},0);}
    if(probe->thisPc){
        if(!probe->submitted){HWND tree{};EnumChildWindows(window,[](HWND child,LPARAM value)->BOOL{wchar_t kind[128]{};GetClassNameW(child,kind,128);if(std::wstring_view(kind)==L"SysTreeView32"&&IsWindowVisible(child))*reinterpret_cast<HWND*>(value)=child;return TRUE;},reinterpret_cast<LPARAM>(&tree));
            if(tree){HTREEITEM target{};std::function<void(HTREEITEM)> visit=[&](HTREEITEM item){for(;item;item=TreeView_GetNextSibling(tree,item)){wchar_t name[512]{};TVITEMW value{};value.mask=TVIF_TEXT;value.hItem=item;value.pszText=name;value.cchTextMax=512;SendMessageW(tree,TVM_GETITEMW,0,reinterpret_cast<LPARAM>(&value));std::cout<<"navigation_item="<<QString::fromWCharArray(name).toStdString()<<'\n';if(std::wstring_view(name)==L"This PC")target=item;visit(TreeView_GetChild(tree,item));}};visit(TreeView_GetRoot(tree));if(target){probe->submitted=true;TreeView_SelectItem(tree,target);}}
        }else{EnumChildWindows(window,[](HWND child,LPARAM value)->BOOL{wchar_t name[512]{};GetWindowTextW(child,name,512);if(GetDlgCtrlID(child)==1001&&std::wstring_view(name)==L"Address: This PC")*reinterpret_cast<bool*>(value)=true;return TRUE;},reinterpret_cast<LPARAM>(&probe->navigationConfirmed));if(probe->navigationConfirmed){std::cout<<"navigation_address=Address: This PC\n";PostMessageW(window,WM_COMMAND,MAKEWPARAM(IDCANCEL,BN_CLICKED),reinterpret_cast<LPARAM>(GetDlgItem(window,IDCANCEL)));}}
        return TRUE;
    }
    if(probe->paths.isEmpty()){PostMessageW(window,WM_COMMAND,MAKEWPARAM(IDCANCEL,BN_CLICKED),reinterpret_cast<LPARAM>(GetDlgItem(window,IDCANCEL)));}
    else if(!probe->submitted){std::pair<HWND,HWND> controls;EnumChildWindows(window,[](HWND child,LPARAM value)->BOOL{wchar_t kind[128]{};GetClassNameW(child,kind,128);if(GetDlgCtrlID(child)==1152&&std::wstring_view(kind)==L"Edit"&&IsWindowVisible(child))reinterpret_cast<std::pair<HWND,HWND>*>(value)->first=child;if(GetDlgCtrlID(child)==IDOK&&std::wstring_view(kind)==L"Button"&&IsWindowVisible(child))reinterpret_cast<std::pair<HWND,HWND>*>(value)->second=child;return TRUE;},reinterpret_cast<LPARAM>(&controls));if(controls.first&&controls.second){QStringList quoted;for(const auto& path:probe->paths)quoted.append('"'+QDir::toNativeSeparators(path)+'"');const auto text=quoted.join(' ').toStdWString();SendMessageW(controls.first,WM_SETTEXT,0,reinterpret_cast<LPARAM>(text.c_str()));probe->submitted=true;std::cout<<"submitted="<<quoted.join(' ').toStdString()<<'\n';PostMessageW(controls.second,BM_CLICK,0,0);}}
    return TRUE;},reinterpret_cast<LPARAM>(active));}
}
int main(int argc,char** argv){QApplication app(argc,argv);std::cout<<std::unitbuf;try{if(argc!=2||(std::string_view(argv[1])!="cancel"&&std::string_view(argv[1])!="multiple"&&std::string_view(argv[1])!="this_pc"))throw std::runtime_error("provide cancel or multiple case");QWidget owner;owner.setWindowTitle("Compositor isolated Open witness");owner.resize(420,220);owner.show();QApplication::processEvents();Probe probe;probe.owner=reinterpret_cast<HWND>(owner.winId());probe.thread=GetCurrentThreadId();probe.thisPc=std::string_view(argv[1])=="this_pc";std::unique_ptr<QTemporaryDir> fixtures;
if(std::string_view(argv[1])=="multiple"){const auto root=QFileInfo(QString::fromUtf8(__FILE__)).dir().filePath("fixtures");QDir().mkpath(root);fixtures=std::make_unique<QTemporaryDir>(root+"/native-XXXXXX");if(!fixtures->isValid())throw std::runtime_error("native package fixture root");fixtures->setAutoRemove(false);probe.paths={fixtures->filePath(QString::fromUtf8("First 実証.comp")),fixtures->filePath("Second space.comp")};for(const auto& path:probe.paths)if(!QDir().mkdir(path))throw std::runtime_error("native package fixture creation");std::cout<<"fixture="<<fixtures->path().toStdString()<<'\n';}active=&probe;const auto timer=SetTimer(nullptr,0,100,tick);if(!timer)throw std::runtime_error("owned timer creation failed");const auto result=compositor::ui::chooseProjectDirectories(&owner);KillTimer(nullptr,timer);active=nullptr;std::cout<<"seen="<<probe.seen<<" owned="<<probe.owned<<" cancelled="<<!result<<'\n';if(!probe.seen||!probe.owned)throw std::runtime_error("native ownership failed");if(probe.thisPc&&(!probe.submitted||!probe.navigationConfirmed))throw std::runtime_error("native This PC navigation failed");if(probe.paths.isEmpty()){if(result)throw std::runtime_error("native cancellation failed");}else{if(result)for(const auto& path:*result)std::cout<<"selected="<<path.toStdString()<<'\n';if(!result||result->size()!=2)throw std::runtime_error("native multiple selection count");for(qsizetype i=0;i<probe.paths.size();++i)if(QFileInfo(result->at(i)).canonicalFilePath()!=QFileInfo(probe.paths.at(i)).canonicalFilePath())throw std::runtime_error("native multiple result order/path");}std::cout<<"PASS "<<argv[1]<<'\n';return 0;}catch(const std::exception& error){std::cerr<<"FAIL "<<error.what()<<'\n';return 1;}}
