#include "graphics/SamplingSource.h"
#include "graphics/GrowingBrushSession.h"
#include <algorithm>
#include <iostream>
#include <map>
#include <stdexcept>
using namespace compositor;
using namespace compositor::graphics;
namespace {
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
std::shared_ptr<const Raster> pattern(int width,int height){std::vector<Pixel> pixels(size_t(width)*height);for(int y=0;y<height;++y)for(int x=0;x<width;++x)pixels[size_t(y)*width+x]={uint8_t((x*17+y*7)%256),uint8_t((x*5+y*13)%256),uint8_t((x*11+y*19)%256),255};return Raster::fromRgba(width,height,reinterpret_cast<const uint8_t*>(pixels.data()),size_t(width)*4);}
std::shared_ptr<SamplingSource> source(std::shared_ptr<const Raster> image,std::shared_ptr<const void> domain,bool gray=false){auto out=std::make_shared<SamplingSource>(*samplingSource(image));if(gray){out->rgba={};out->gray=[image](int x,int y){return image->pixel(x,y).r;};}out->reuseDomain=std::move(domain);out->dependencies=[image](int x,int y,int width,int height){std::vector<std::shared_ptr<const void>> tokens;const int columns=(image->width+255)/256;for(int ty=y/256;ty<=(y+height-1)/256;++ty)for(int tx=x/256;tx<=(x+width-1)/256;++tx)tokens.push_back(image->tiles[size_t(ty)*columns+tx]);return tokens;};return out;}
void exact(ReducedSourceCache& cache,const std::shared_ptr<const SamplingSource>& input,int level){auto unshared=std::make_shared<SamplingSource>(*input);unshared->reuseDomain.reset();unshared->dependencies={};unshared->readRow={};ReducedSourceCache control;auto actual=cache.resolve(input,level),expected=control.resolve(unshared,level);require(actual->grid().width==expected->grid().width&&actual->grid().height==expected->grid().height,"grid differs");for(int y=0;y<actual->grid().height;++y)for(int x=0;x<actual->grid().width;++x)require(actual->pixel(x,y)==expected->pixel(x,y),"reused pixel differs from uncached immutable reference");}
void unchanged(){for(int level:{1,3}){ReducedSourceCache cache;auto domain=std::make_shared<int>(1);auto first=pattern(1101,79);exact(cache,source(first,domain),level);auto count=cache.generatedTiles();auto second=std::make_shared<Raster>(*first);exact(cache,source(second,domain),level);require(cache.generatedTiles()==count,"unchanged source regenerated reductions");require(cache.reusedTiles()>0,"unchanged dependencies did not reuse");}}
void halo(){for(bool gray:{false,true})for(int level=1;level<=4;++level){ReducedSourceCache cache;auto domain=std::make_shared<int>(1);auto first=pattern(1051,73);exact(cache,source(first,domain,gray),level);std::vector<Pixel> patch(29*9,{255,0,0,255});auto second=first->replacing(503,21,29,9,patch.data(),29);exact(cache,source(second,domain,gray),level);require(cache.generatedTiles()>0,"missing generated reductions");}}
void isolation(){ReducedSourceCache cache;auto domain=std::make_shared<int>(1);auto image=pattern(91,47);exact(cache,source(image,domain),2);const auto reused=cache.reusedTiles();auto other=source(std::make_shared<Raster>(*image),std::make_shared<int>(2));exact(cache,other,2);require(cache.reusedTiles()==reused,"cross-domain reuse");auto aligned=source(std::make_shared<Raster>(*image),domain);aligned->alignmentX=-3;aligned->alignmentY=5;exact(cache,aligned,2);require(cache.reusedTiles()==reused,"cross-alignment reuse");exact(cache,source(std::make_shared<Raster>(*image),domain,true),2);require(cache.reusedTiles()==reused,"cross-type reuse");exact(cache,source(pattern(92,47),domain),2);require(cache.reusedTiles()==reused,"cross-dimension reuse");}
void eviction(){for(size_t budget:{size_t(1),size_t(3),size_t(8)}){ReducedSourceCache cache(budget,2);auto domain=std::make_shared<int>(1);auto image=pattern(577,35);for(int pass=0;pass<4;++pass){auto copy=std::make_shared<Raster>(*image);exact(cache,source(copy,domain),1);require(cache.retainedTiles()<=budget&&cache.retainedSources()<=2,"cache budget exceeded");}cache.clear();require(!cache.retainedTiles()&&!cache.retainedSources()&&!cache.generatedTiles()&&!cache.reusedTiles(),"clear did not reset cache");}}
void lifetime(){ReducedSourceCache cache;std::weak_ptr<const void> domain;std::weak_ptr<const Raster> pixels;{auto token=std::make_shared<int>(1);domain=token;auto image=pattern(63,31);pixels=image;exact(cache,source(image,token),1);}require(!domain.expired()&&!pixels.expired(),"cache did not own source");cache.clear();require(domain.expired()&&pixels.expired(),"cache retained released source");}
void brush(){for(bool mask:{false,true}){Layer layer;layer.id="sampling-reuse-brush";layer.transform={0,0,1100,180};layer.raster=pattern(1100,180);if(mask)layer.mask=Mask{std::make_shared<GrayRaster>(GrayRaster{1100,180,std::vector<uint8_t>(1100*180,255)})};BrushSessionSettings settings{12,.4,.8,{13,70,150},false};GrowingBrushSession stroke(layer,settings,1100,180,{},{},mask);ReducedSourceCache cache;for(int event=0;event<5;++event){if(event)stroke.append({80.+event*10,90});else stroke.begin({80,90});auto preview=stroke.preview()->renderPreview();auto input=mask?preview->maskSource:preview->imageSource;exact(cache,input,1);}require(cache.reusedTiles()>0,"brush snapshots did not reuse unaffected reduction tiles");}}
}
int main(int argc,char** argv){std::map<std::string,void(*)()> cases{{"unchanged",unchanged},{"halo",halo},{"isolation",isolation},{"eviction",eviction},{"lifetime",lifetime},{"brush",brush}};int passed=0,failed=0;for(auto [name,run]:cases){if(argc>1&&name!=argv[1])continue;try{run();++passed;std::cout<<"PASS "<<name<<'\n';}catch(const std::exception& e){++failed;std::cout<<"FAIL "<<name<<": "<<e.what()<<'\n';}}std::cout<<passed<<" passed, "<<failed<<" failed\n";return failed||!passed?1:0;}
