find_package(Qt6 6.8.3 EXACT REQUIRED COMPONENTS Network)
set(PRODUCT_ROOT "${CMAKE_SOURCE_DIR}/../product")
execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_SOURCE_DIR}/../scripts/native/generate-updater.py" "${CMAKE_BINARY_DIR}/production" COMMAND_ERROR_IS_FATAL ANY)
add_library(production_update "${CMAKE_BINARY_DIR}/production/Updater.cpp" "${PRODUCT_ROOT}/ProductionNetwork.cpp")
target_include_directories(production_update PUBLIC "${CMAKE_BINARY_DIR}/production" "${PRODUCT_ROOT}")
target_compile_options(production_update PRIVATE /utf-8 /W4)
target_compile_definitions(production_update PUBLIC NOMINMAX WIN32_LEAN_AND_MEAN)
target_link_libraries(production_update PUBLIC Qt6::Core Qt6::Network bcrypt winhttp)
if(NOT DEFINED PRODUCT_VERSION)
  set(PRODUCT_VERSION "0.2.0")
endif()
add_executable(CompositorProduct WIN32 "${PRODUCT_ROOT}/ProductMain.cpp" "${PRODUCT_ROOT}/Locale.cpp" "${PRODUCT_ROOT}/UpdateDialog.cpp" "${PRODUCT_ROOT}/Gates.cpp" "${CMAKE_SOURCE_DIR}/src/resources.rc")
set_target_properties(CompositorProduct PROPERTIES OUTPUT_NAME "Compositor")
# The reference executable keeps its original source and gets a separate build path.
set_target_properties(Compositor PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/reference/$<CONFIG>")
qt_add_resources(CompositorProduct product_assets PREFIX "/product" BASE "${PRODUCT_ROOT}" FILES "${PRODUCT_ROOT}/zh-CN.json")
target_include_directories(CompositorProduct PRIVATE "${PRODUCT_ROOT}")
target_compile_options(CompositorProduct PRIVATE /utf-8 /W4)
target_compile_definitions(CompositorProduct PRIVATE PRODUCT_VERSION="${PRODUCT_VERSION}")
target_link_options(CompositorProduct PRIVATE "/MANIFESTINPUT:${CMAKE_SOURCE_DIR}/src/app.manifest")
target_link_libraries(CompositorProduct PRIVATE compositor_ui production_update)
add_executable(CompositorStart WIN32 "${PRODUCT_ROOT}/Launcher.cpp" "${CMAKE_SOURCE_DIR}/src/resources.rc")
target_compile_options(CompositorStart PRIVATE /utf-8)
target_link_libraries(CompositorStart PRIVATE production_update shell32 user32)
