#include "ui/MainWindow.h"
#include "ui/ImportActions.h"
#include "persistence/ProjectStore.h"
#include <QApplication>
#include <QDir>
#include <QDragEnterEvent>
#include <QDropEvent>
#include <QFile>
#include <QFileInfo>
#include <QImage>
#include <QMessageBox>
#include <QMimeData>
#include <QProgressDialog>
#include <QPushButton>
#include <QTemporaryDir>
#include <QTabBar>
#include <QTest>
#include <QTimer>
#include <QUrl>
#include <iostream>
#include <map>
#ifdef DROP_SEQUENCE_AFTER
#include "ui/WorkspaceDropQueue.h"
#endif
using namespace compositor;
namespace {
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
QAction* command(MainWindow& w,const char* id){for(auto* action:w.findChildren<QAction*>())if(action->property("commandId").toString()==id)return action;throw std::runtime_error("missing command");}
Document sample(){Document d;d.id=newId();d.width=64;d.height=48;Layer l;l.id=newId();l.name="Original";l.transform={0,0,64,48};l.raster=Raster::filled(64,48,{20,30,40,255});d.layers={l};return d;}
struct Fixture {
    MainWindow window{true};EditorProject* original{};QTemporaryDir directory{QFileInfo(QString::fromUtf8(__FILE__)).dir().filePath("fixtures/drop-XXXXXX")};QString first,second,project,broken;QStringList errors;QTimer dismiss;
    Fixture(){require(directory.isValid(),"retained fixture root");directory.setAutoRemove(false);first=directory.filePath("First.png");second=directory.filePath("Second.png");project=directory.filePath("Saved.comp");broken=directory.filePath("Broken.comp");QImage a(7,5,QImage::Format_RGBA8888);a.fill(QColor(Qt::red));require(a.save(first,"PNG"),"first image fixture");QImage b(9,6,QImage::Format_RGBA8888);b.fill(QColor(Qt::blue));require(b.save(second,"PNG"),"second image fixture");auto d=sample();ProjectStore(makeWicProjectCodec()).save(std::filesystem::path(project.toStdWString()),d,d.layers[0].id);require(QDir().mkdir(broken),"bad project fixture");original=&window.addProject(sample(),"Original");window.show();QApplication::processEvents();dismiss.setInterval(5);QObject::connect(&dismiss,&QTimer::timeout,&window,[this]{for(auto* message:window.findChildren<QMessageBox*>())if(message->isVisible()){errors.append(message->text());message->accept();}});dismiss.start();std::cout<<"fixture="<<directory.path().toStdString()<<'\n';}
    QTabWidget* tabs(){return window.findChild<QTabWidget*>();}
    QPoint where()const{return original->canvas->mapTo(&window,original->canvas->rect().center());}
    bool drop(const QStringList& paths,bool external=false){QMimeData mime;QList<QUrl> urls;for(const auto& path:paths)urls.append(QUrl::fromLocalFile(path));mime.setUrls(urls);return dropMime(mime,external?QPoint(1,1):where());}
    bool dropMime(const QMimeData& mime,QPoint point){QDragEnterEvent enter(point,Qt::CopyAction,&mime,Qt::LeftButton,{});QApplication::sendEvent(&window,&enter);if(!enter.isAccepted())return false;QDropEvent event(point,Qt::CopyAction,&mime,Qt::LeftButton,{});QApplication::sendEvent(&window,&event);return event.isAccepted();}
    void finish(){QElapsedTimer elapsed;elapsed.start();for(;;){QTest::qWait(5);auto* imports=ui::ImportQueue::find(&window);bool ready=!imports||imports->idle();
#ifdef DROP_SEQUENCE_AFTER
        auto* drops=ui::WorkspaceDropQueue::find(&window);ready=ready&&(!drops||drops->idle());
#endif
        if(ready)break;if(elapsed.elapsed()>10000)throw std::runtime_error("drop did not finish");}QApplication::processEvents();}
    void gradient(){command(window,"tool.gradient")->trigger();original->canvas->pointerDown({5,20},{});original->canvas->pointerMove({55,20},{});original->canvas->pointerUp({55,20},{});require(command(window,"gradient.apply")->isEnabled(),"pending gradient fixture");}
};
void mixed_image_project_order(){Fixture f;require(f.drop({f.first,f.project,f.second}),"accepted mixed drop");f.finish();std::cout<<"tabs="<<f.tabs()->count()<<" layers="<<f.original->document->layers.size()<<" undo="<<f.original->history.undoCount()<<'\n';require(f.tabs()->count()==2&&f.tabs()->currentWidget()==f.original->page,"project between images opens and final image reselects captured target");require(f.original->document->layers.size()==3&&f.original->document->layers[1].name=="First"&&f.original->document->layers[2].name=="Second"&&f.original->history.undoCount()==2,"sequential images retain order and individual undo steps");}
void images_have_separate_undo(){Fixture f;const auto original=f.original->document;require(f.drop({f.first,f.second}),"accepted image drop");f.finish();std::cout<<"undo="<<f.original->history.undoCount()<<'\n';require(f.original->history.undoCount()==2,"workspace imports each URL in its own history edit");command(f.window,"edit.undo")->trigger();require(f.original->document->layers.size()==2&&f.original->document->layers.back().name=="First","first undo removes only last image");command(f.window,"edit.undo")->trigger();require(f.original->document==original,"second undo restores original document");}
void pending_ui_drop_rejected(){Fixture f;f.gradient();const auto original=f.original->document;const bool accepted=f.drop({f.first,f.project});std::cout<<"accepted="<<accepted<<" pending="<<command(f.window,"gradient.apply")->isEnabled()<<" undo="<<f.original->history.undoCount()<<'\n';require(!accepted,"preblocked ContentView drop must be rejected");QTest::qWait(60);require(f.tabs()->count()==1&&f.original->document==original&&f.original->history.undoCount()==0&&command(f.window,"gradient.apply")->isEnabled(),"rejected drop preserves pending edit and original document");}
void busy_ui_bitmap_rejected(){Fixture f;f.original->projectBusy=true;QImage image(7,5,QImage::Format_RGBA8888);image.fill(QColor(Qt::green));QMimeData mime;mime.setImageData(image);const bool accepted=f.dropMime(mime,f.where());std::cout<<"accepted="<<accepted<<" queue="<<bool(ui::ImportQueue::find(&f.window))<<'\n';require(!accepted&&ui::ImportQueue::find(&f.window)==nullptr,"prebusy UI bitmap drop rejects without queued data or mutation");f.original->projectBusy=false;}
void project_error_then_image_then_project(){Fixture f;require(f.drop({f.broken,f.first,f.project}),"accepted error-containing drop");f.finish();std::cout<<"tabs="<<f.tabs()->count()<<" errors="<<f.errors.size()<<'\n';require(f.errors.size()==1&&f.original->document->layers.size()==2&&f.tabs()->count()==2&&f.tabs()->currentWidget()!=f.original->page,"project failure is reported and later image/project complete in order");}
void external_mixed_items_create_ordered_tabs(){Fixture f;require(f.drop({f.first,f.project,f.second},true),"accepted new-tab drop");f.finish();std::cout<<"tabs="<<f.tabs()->count()<<'\n';require(f.tabs()->count()==4&&f.tabs()->tabText(2).contains("Saved.comp")&&f.tabs()->currentIndex()==3,"new-tab image/project/image receive creates one project per image in order");}
void active_import_prevents_tab_close(){Fixture f;require(f.drop({f.first,f.project}),"accepted mixed drop");f.tabs()->tabCloseRequested(0);require(f.tabs()->count()==1,"active managed drop blocks tab close");f.finish();require(f.tabs()->count()==2&&f.original->document->layers.size()==2,"close attempt cannot consume remaining project input");}
#ifdef DROP_SEQUENCE_AFTER
void accepted_payload_waits_for_gradient(){Fixture f;auto* captured=f.original->canvas;const auto before=f.original->document;f.gradient();f.window.receiveDropPaths({f.first,f.project},captured);auto* queue=ui::WorkspaceDropQueue::find(&f.window);require(queue&&!queue->idle()&&!ui::ImportQueue::find(&f.window),"resolved accepted input waits before creating decoder work");QTest::qWait(75);require(f.original->document==before&&f.original->history.undoCount()==0&&f.tabs()->count()==1&&command(f.window,"gradient.apply")->isEnabled(),"accepted request cannot apply or cancel a later gradient");command(f.window,"gradient.cancel")->trigger();f.finish();require(f.original->document->layers.size()==2&&f.original->history.undoCount()==1&&f.tabs()->count()==2&&f.tabs()->currentWidget()!=f.original->page,"queued request resumes in URL order after explicit gradient cancellation");}
void accepted_bitmap_retains_temporary_copy(){Fixture f;f.window.receiveDropPaths({},f.original->canvas);auto* queue=ui::WorkspaceDropQueue::find(&f.window);require(queue,"accepted payload queue");f.original->projectBusy=true;auto temporary=std::make_shared<QTemporaryDir>(f.directory.path()+"/provider-XXXXXX");require(temporary->isValid()&&temporary->path().startsWith(f.directory.path()+"/"),"owned temporary provider directory");const auto path=temporary->filePath("Copied.png");require(QFile::copy(f.first,path),"copy provider bytes before MIME lifetime ends");std::weak_ptr<QTemporaryDir> weak=temporary;ui::WorkspaceDropRequest request;request.paths={path};request.destination=f.original->canvas;request.hasDestination=true;request.point=Point{31,21};request.lifetime=temporary;temporary.reset();queue->enqueue(std::move(request));QTest::qWait(70);require(!weak.expired()&&!ui::ImportQueue::find(&f.window),"pending request retains provider copy and does not decode while busy");f.original->projectBusy=false;f.finish();require(weak.expired()&&!QFileInfo::exists(path),"temporary provider lifetime ends after import completion");const auto& layer=f.original->document->layers.back();require(layer.raster->width==7&&layer.transform.x==27&&layer.transform.y==18&&f.original->history.undoCount()==1,"copied bitmap imports once at captured document point");}
void cancelled_waiting_payload_releases_lifetime(){Fixture f;f.original->projectBusy=true;f.window.receiveDropPaths({},f.original->canvas);auto* queue=ui::WorkspaceDropQueue::find(&f.window);auto temporary=std::make_shared<QTemporaryDir>(f.directory.path()+"/cancelled-provider-XXXXXX");require(temporary->isValid()&&temporary->path().startsWith(f.directory.path()+"/"),"owned cancelled provider directory");const auto path=temporary->filePath("Copied.png");require(QFile::copy(f.first,path),"cancelled provider copy");std::weak_ptr<QTemporaryDir> weak=temporary;ui::WorkspaceDropRequest request;request.paths={path,f.project};request.destination=f.original->canvas;request.hasDestination=true;request.lifetime=temporary;temporary.reset();queue->enqueue(std::move(request));require(!queue->idle()&&!weak.expired(),"deferred request retains temporary bytes");queue->cancel(f.original->canvas);require(queue->idle()&&weak.expired()&&!QFileInfo::exists(path),"waiting cancellation releases matching request and temporary copy");f.original->projectBusy=false;QTest::qWait(80);require(f.tabs()->count()==1&&f.original->document->layers.size()==1&&f.original->history.undoCount()==0&&!ui::ImportQueue::find(&f.window),"cancelled waiting payload cannot revive when guard clears");}
void cancel_button_stops_remaining_items(){Fixture f;const auto before=f.original->document;require(f.drop({f.first,f.project,f.second}),"accepted cancellable mixed input");auto* progress=f.window.findChild<QProgressDialog*>("imageImportProgress");require(progress,"actual import progress control exists");auto* button=progress->findChild<QPushButton*>();require(button,"actual progress Cancel button exists");button->click();f.finish();require(f.tabs()->count()==1&&f.original->document==before&&f.original->history.undoCount()==0&&!f.original->importing,"Cancel discards in-flight image and remaining mixed input");require(command(f.window,"file.open")->isEnabled(),"Cancel releases workspace ownership");}
void closed_captured_destination_skips_images(){Fixture f;QPointer<NativeCanvas> captured=f.original->canvas;f.original->projectBusy=true;f.window.receiveDropPaths({f.first,f.project,f.second},captured);f.original->projectBusy=false;f.tabs()->tabCloseRequested(0);f.original=nullptr;QCoreApplication::sendPostedEvents(nullptr,QEvent::DeferredDelete);require(captured.isNull(),"captured destination actually closed before deferred delivery");f.finish();auto* layers=f.window.findChild<QTreeWidget*>();require(f.tabs()->count()==1&&f.tabs()->tabText(0).contains("Saved.comp")&&layers&&layers->topLevelItemCount()==1&&!ui::ImportQueue::find(&f.window),"missing captured destination skips images while project URL still opens");}
void deferred_requests_remain_fifo(){Fixture f;f.original->projectBusy=true;f.window.receiveDropPaths({f.first,f.project},f.original->canvas);f.window.receiveDropPaths({f.second},f.original->canvas);QTest::qWait(65);require(f.tabs()->count()==1&&f.original->document->layers.size()==1,"queued gestures remain deferred");f.original->projectBusy=false;f.finish();require(f.tabs()->count()==2&&f.tabs()->currentWidget()==f.original->page&&f.original->history.undoCount()==2&&f.original->document->layers[1].name=="First"&&f.original->document->layers[2].name=="Second","queued gestures finish FIFO with captured destination and distinct edits");}
void image_error_does_not_consume_later_project(){Fixture f;require(f.drop({f.directory.filePath("Missing.png"),f.project,f.first}),"accepted image error fixture");f.finish();require(f.errors.size()==1&&f.tabs()->count()==2&&f.original->document->layers.size()==2&&f.original->history.undoCount()==1&&f.tabs()->currentWidget()==f.original->page,"image failure reports once and later project/image still finish");}
void destroyed_window_stops_deferred_callbacks(){QPointer<ui::WorkspaceDropQueue> weak;{auto window=std::make_unique<MainWindow>(true);auto& project=window->addProject(sample());project.projectBusy=true;window->receiveDropPaths({"must-never-open.comp"},project.canvas);weak=ui::WorkspaceDropQueue::find(window.get());require(weak&&!weak->idle(),"owned deferred work fixture");window.reset();}require(weak.isNull(),"window destructor deletes deferred queue before project members");QTest::qWait(75);}
void nonselected_tab_captures_destination(){Fixture f;auto& other=f.window.addProject(sample(),"Other");require(f.tabs()->currentWidget()==other.page,"second tab selected before drop");QMimeData mime;mime.setUrls({QUrl::fromLocalFile(f.first),QUrl::fromLocalFile(f.project),QUrl::fromLocalFile(f.second)});auto* bar=f.tabs()->tabBar();const auto point=bar->mapTo(&f.window,bar->tabRect(0).center());require(f.dropMime(mime,point),"drop on nonselected tab accepted");f.finish();require(f.tabs()->count()==3&&f.tabs()->currentWidget()==f.original->page&&f.original->document->layers.size()==3&&f.original->history.undoCount()==2,"all image URLs target captured tab around intervening project open");require(other.document->layers.size()==1&&other.history.undoCount()==0,"previously selected tab retains document and history");}
#endif
}
int main(int argc,char** argv){QApplication app(argc,argv);std::cout<<std::unitbuf;QDir().mkpath(QFileInfo(QString::fromUtf8(__FILE__)).dir().filePath("fixtures"));const std::map<std::string,void(*)()> cases{{"mixed_image_project_order",mixed_image_project_order},{"images_have_separate_undo",images_have_separate_undo},{"pending_ui_drop_rejected",pending_ui_drop_rejected},{"busy_ui_bitmap_rejected",busy_ui_bitmap_rejected},{"project_error_then_image_then_project",project_error_then_image_then_project},{"external_mixed_items_create_ordered_tabs",external_mixed_items_create_ordered_tabs},{"active_import_prevents_tab_close",active_import_prevents_tab_close}
#ifdef DROP_SEQUENCE_AFTER
    ,{"accepted_payload_waits_for_gradient",accepted_payload_waits_for_gradient},{"accepted_bitmap_retains_temporary_copy",accepted_bitmap_retains_temporary_copy},{"cancelled_waiting_payload_releases_lifetime",cancelled_waiting_payload_releases_lifetime},{"cancel_button_stops_remaining_items",cancel_button_stops_remaining_items},{"closed_captured_destination_skips_images",closed_captured_destination_skips_images},{"deferred_requests_remain_fifo",deferred_requests_remain_fifo},{"image_error_does_not_consume_later_project",image_error_does_not_consume_later_project},{"destroyed_window_stops_deferred_callbacks",destroyed_window_stops_deferred_callbacks},{"nonselected_tab_captures_destination",nonselected_tab_captures_destination}
#endif
    };try{require(argc==2&&cases.contains(argv[1]),"provide named drop case");std::cout<<"START "<<argv[1]<<'\n';cases.at(argv[1])();std::cout<<"PASS "<<argv[1]<<'\n';return 0;}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<'\n';return 1;}}
