#include "ui/AdjustmentDialog.h"
#include "ui/AdjustmentAdvancedControls.h"
#include "effects/Adjustments.h"
#include <QApplication>
#include <QCheckBox>
#include <QComboBox>
#include <QDialog>
#include <QDialogButtonBox>
#include <QDoubleSpinBox>
#include <QElapsedTimer>
#include <QFontDatabase>
#include <QLabel>
#include <QPushButton>
#include <QTest>
#include <QTimer>
#include <filesystem>
#include <cmath>
#include <iostream>
#include <map>
#include <stdexcept>
using namespace compositor;
using namespace compositor::effects_tools;
#define REQUIRE(...) do{if(!(__VA_ARGS__))throw std::runtime_error(std::string(__FILE__)+":"+std::to_string(__LINE__)+": " #__VA_ARGS__);}while(false)
Document document(Pixel color={128,128,128,255}){Document d;d.id=newId();d.width=64;d.height=32;Layer layer;layer.id=newId();layer.raster=Raster::filled(d.width,d.height,color);layer.transform={0,0,double(d.width),double(d.height)};d.layers={layer};return d;}
QPushButton* apply(QDialog* dialog){return dialog->findChild<QDialogButtonBox*>()->button(QDialogButtonBox::Apply);}
std::optional<AdjustmentDialogResult> drive(const Document& d,const std::string& active,const QString& kind,bool live,bool existing,std::function<void(QDialog*,int&)> action){QTimer timer;timer.setInterval(20);QElapsedTimer elapsed;elapsed.start();int step=0;std::string failure;QObject::connect(&timer,&QTimer::timeout,[&]{auto* modal=qobject_cast<QDialog*>(QApplication::activeModalWidget());if(!modal)return;try{if(elapsed.elapsed()>20000)throw std::runtime_error("Dialog test timed out at step "+std::to_string(step));action(modal,step);}catch(const std::exception& error){failure=error.what();modal->reject();}});timer.start();auto result=showAdjustmentDialog(nullptr,d,active,kind,live,existing);timer.stop();if(!failure.empty())throw std::runtime_error(failure);REQUIRE(step>0);return result;}
void levels_cancel(){auto d=document();auto original=d;auto source=d.layers[0].raster;auto result=drive(d,d.layers[0].id,"Levels",false,false,[](QDialog* dialog,int& step){auto* automatic=dialog->findChild<QPushButton*>("levelsAutoContrast");if(!automatic->isEnabled()||!apply(dialog)->isEnabled())return;dialog->findChild<QComboBox*>("levelsChannel")->setCurrentIndex(1);dialog->findChild<QDoubleSpinBox*>("levelsValue4")->setValue(0);REQUIRE(!apply(dialog)->isEnabled());++step;dialog->reject();});REQUIRE(!result&&d==original&&d.layers[0].raster==source);}
void curves_apply(){auto d=document();d.layers[0].shapeJson="original style marker";auto before=d;auto result=drive(d,d.layers[0].id,"Curves",false,false,[](QDialog* dialog,int& step){if(!apply(dialog)->isEnabled())return;if(step==0){dialog->findChild<QComboBox*>("curvesChannel")->setCurrentIndex(1);auto* graph=dialog->findChild<QWidget*>("curvesGraph");QPoint point(int(8+128./255*(graph->width()-16)),int(8+(1-220./255)*(graph->height()-16)));QTest::mouseClick(graph,Qt::LeftButton,{},point);REQUIRE(!apply(dialog)->isEnabled());++step;return;}auto path=std::filesystem::path(__FILE__).parent_path()/"curves-dialog.png";REQUIRE(dialog->grab().save(QString::fromStdWString(path.wstring())));apply(dialog)->click();});REQUIRE(result&&d==before);auto pixel=result->document.layers[0].raster->pixel(0,0);REQUIRE(pixel.r>200&&pixel.g==128&&pixel.b==128&&pixel.a==255);REQUIRE(result->document.layers[0].shapeJson.empty());}
void hue_targeting(){auto d=document({0,0,255,255});auto before=d;auto result=drive(d,d.layers[0].id,"Hue/Saturation",true,false,[](QDialog* dialog,int& step){if(!apply(dialog)->isEnabled())return;auto* controls=dynamic_cast<HueAdvancedControls*>(dialog->findChild<QWidget*>("hueAdvancedControls"));auto* preview=dialog->findChild<QLabel*>("adjustmentPreview");REQUIRE(controls&&preview);if(step==0){dialog->findChild<QComboBox*>("hueRange")->setCurrentIndex(3);dialog->findChild<QPushButton*>("hueSampleColor")->click();QTest::mouseClick(preview,Qt::LeftButton,{},preview->rect().center());auto settings=hueFromAdjustmentJson(controls->adjustmentJson());REQUIRE(settings.bands[3].weight(240)==1&&settings.bands[3].weight(120)==0);dialog->findChild<QPushButton*>("hueReset")->click();++step;return;}if(step==1){dialog->findChild<QPushButton*>("hueTargetedAdjustment")->click();auto anchor=preview->rect().center();QTest::mousePress(preview,Qt::LeftButton,{},anchor);QTest::mouseMove(preview,anchor+QPoint(40,0));QTest::mouseRelease(preview,Qt::LeftButton,{},anchor+QPoint(40,0));auto settings=hueFromAdjustmentJson(controls->adjustmentJson());REQUIRE(settings.range==ColorRange::Blues&&settings.adjustments[5].saturation==20);REQUIRE(dialog->findChild<QComboBox*>("hueRange")->currentIndex()==5);++step;return;}auto path=std::filesystem::path(__FILE__).parent_path()/"hue-dialog.png";REQUIRE(dialog->grab().save(QString::fromStdWString(path.wstring())));apply(dialog)->click();});REQUIRE(result&&d==before&&result->document.layers.size()==2);auto settings=hueFromAdjustmentJson(result->document.layers[1].adjustmentJson);REQUIRE(settings.range==ColorRange::Blues&&settings.adjustments[5].saturation==20);}
void live_levels_input(){auto d=document();d.width=2;d.height=1;Layer folder;folder.id=newId();folder.group=true;folder.transform={0,0,2,1};Layer low=d.layers[0];low.parentId=folder.id;low.transform={0,0,2,1};uint8_t pixels[]{20,20,20,255,200,200,200,255};low.raster=Raster::fromRgba(2,1,pixels,8);Layer edit;edit.id=newId();edit.parentId=folder.id;edit.adjustmentJson=effects::defaultAdjustmentJson("Levels");edit.transform={0,0,2,1};Layer dependency;dependency.id=newId();dependency.raster=Raster::filled(2,1,{255,255,255,255});dependency.transform={0,0,2,1};low.maskSourceId=dependency.id;Layer above=dependency;above.id=newId();above.raster=Raster::filled(2,1,{0,0,255,255});d.layers={low,edit,folder,dependency,above};d.selection=Selection{std::make_shared<GrayRaster>(GrayRaster{2,1,{0,0}})};validateDocument(d);auto original=d;auto result=drive(d,edit.id,"Levels",true,true,[](QDialog* dialog,int& step){auto* automatic=dialog->findChild<QPushButton*>("levelsAutoContrast");if(!automatic->isEnabled()||!apply(dialog)->isEnabled())return;if(step==0){automatic->click();auto* controls=dynamic_cast<LevelsAdvancedControls*>(dialog->findChild<QWidget*>("levelsAdvancedControls"));auto typed=levelsFromAdjustmentJson(controls->adjustmentJson());REQUIRE(typed.ranges[0].black==20&&typed.ranges[0].white==200);++step;return;}apply(dialog)->click();});REQUIRE(result&&d==original&&result->document.layers.size()==original.layers.size());for(size_t i=0;i<d.layers.size();++i)if(i!=1)REQUIRE(result->document.layers[i]==original.layers[i]);REQUIRE(levelsFromAdjustmentJson(result->document.layers[1].adjustmentJson).ranges[0].black==20);}
void live_folder_insert(){auto d=document({200,0,0,255});Layer folder;folder.id=newId();folder.group=true;folder.transform={0,0,64,32};d.layers[0].parentId=folder.id;d.layers.insert(d.layers.begin(),folder);d.selection=Selection{std::make_shared<GrayRaster>(GrayRaster{64,32,std::vector<uint8_t>(64*32,255)})};auto original=d;auto result=drive(d,folder.id,"Curves",true,false,[](QDialog* dialog,int& step){if(!apply(dialog)->isEnabled())return;++step;apply(dialog)->click();});REQUIRE(result&&d==original&&result->document.layers.size()==3);REQUIRE(result->document.layers[1].parentId==folder.id&&!result->document.layers[1].mask);REQUIRE(result->document.selection==d.selection);}

void preview_off_apply(){auto d=document();auto before=d;auto result=drive(d,d.layers[0].id,"Curves",false,false,[](QDialog* dialog,int& step){if(!apply(dialog)->isEnabled())return;if(step==0){auto* graph=dialog->findChild<QWidget*>("curvesGraph");QPoint point(int(8+128./255*(graph->width()-16)),int(8+(1-220./255)*(graph->height()-16)));QTest::mouseClick(graph,Qt::LeftButton,{},point);dialog->findChild<QCheckBox*>("adjustmentPreviewEnabled")->setChecked(false);REQUIRE(!apply(dialog)->isEnabled());++step;return;}auto* preview=dialog->findChild<QLabel*>("adjustmentPreview");auto image=preview->pixmap().toImage();auto pixel=image.pixelColor(image.width()/2,image.height()/2);REQUIRE(pixel.red()==128&&pixel.green()==128&&pixel.blue()==128);apply(dialog)->click();});REQUIRE(result&&d==before&&result->document.layers[0].raster->pixel(0,0).r>200);}


void levels_sampler_apply(){auto d=document({64,96,128,255});auto before=d;auto result=drive(d,d.layers[0].id,"Levels",false,false,[](QDialog* dialog,int& step){if(!apply(dialog)->isEnabled()||!dialog->findChild<QPushButton*>("levelsAutoContrast")->isEnabled())return;auto* controls=dynamic_cast<LevelsAdvancedControls*>(dialog->findChild<QWidget*>("levelsAdvancedControls"));auto* preview=dialog->findChild<QLabel*>("adjustmentPreview");if(step==0){dialog->findChild<QPushButton*>("levelsSampleGray")->click();auto original=controls->adjustmentJson();QTest::mouseClick(preview,Qt::LeftButton,{},QPoint(1,1));REQUIRE(controls->adjustmentJson()==original);QTest::mouseClick(preview,Qt::LeftButton,{},preview->rect().center());auto settings=levelsFromAdjustmentJson(controls->adjustmentJson());REQUIRE(std::abs(settings.apply(64./255,LevelsChannel::Red)-.5)<.0001);++step;return;}if(step==1){auto original=controls->adjustmentJson();QTest::mouseClick(preview,Qt::LeftButton,{},preview->rect().center());REQUIRE(controls->adjustmentJson()==original);auto path=std::filesystem::path(__FILE__).parent_path()/"levels-dialog.png";REQUIRE(dialog->grab().save(QString::fromStdWString(path.wstring())));++step;}apply(dialog)->click();});REQUIRE(result&&d==before);auto pixel=result->document.layers[0].raster->pixel(0,0);REQUIRE(std::abs(int(pixel.r)-128)<=1&&std::abs(int(pixel.g)-128)<=1&&std::abs(int(pixel.b)-128)<=1);}
void hue_colorize_reset(){auto d=document({255,0,0,255});auto result=drive(d,d.layers[0].id,"Hue/Saturation",true,false,[](QDialog* dialog,int& step){if(!apply(dialog)->isEnabled())return;auto* controls=dynamic_cast<HueAdvancedControls*>(dialog->findChild<QWidget*>("hueAdvancedControls"));if(step==0){auto* range=dialog->findChild<QComboBox*>("hueRange");range->setCurrentIndex(3);dialog->findChild<QDoubleSpinBox*>("hueValue0")->setValue(80);dialog->findChild<QCheckBox*>("hueColorize")->setChecked(true);auto settings=hueFromAdjustmentJson(controls->adjustmentJson());REQUIRE(settings==HueSettings::colorizeStart()&&!range->isEnabled());REQUIRE(dialog->findChild<QDoubleSpinBox*>("hueValue0")->maximum()==360);dialog->findChild<QDoubleSpinBox*>("hueValue0")->setValue(270);dialog->findChild<QPushButton*>("hueReset")->click();REQUIRE(hueFromAdjustmentJson(controls->adjustmentJson())==HueSettings::colorizeStart());dialog->findChild<QCheckBox*>("hueColorize")->setChecked(false);REQUIRE(hueFromAdjustmentJson(controls->adjustmentJson())==HueSettings{}&&range->isEnabled());++step;return;}apply(dialog)->click();});REQUIRE(result&&hueFromAdjustmentJson(result->document.layers[1].adjustmentJson)==HueSettings{});}

int main(int argc,char** argv){QApplication app(argc,argv);int font=QFontDatabase::addApplicationFont(qEnvironmentVariable("WINDIR")+"/Fonts/segoeui.ttf");if(font<0)return 2;app.setFont(QFont("Segoe UI",9));std::map<std::string,void(*)()> tests{{"levels_sampler_apply",levels_sampler_apply},{"hue_colorize_reset",hue_colorize_reset},{"preview_off_apply",preview_off_apply},{"levels_cancel",levels_cancel},{"curves_apply",curves_apply},{"hue_targeting",hue_targeting},{"live_levels_input",live_levels_input},{"live_folder_insert",live_folder_insert}};try{if(argc!=2||!tests.contains(argv[1]))throw std::runtime_error("Specify dialog test");tests.at(argv[1])();std::cout<<"PASS "<<argv[1]<<"\n";return 0;}catch(const std::exception& error){std::cerr<<"FAIL "<<error.what()<<"\n";return 1;}}
