#include "effects_tools/Levels.h"
#include "effects_tools/Hue.h"
#include "effects_tools/Curves.h"
#include "graphics/StackRenderer.h"
#include "ui/AdjustmentAdvancedControls.h"
#include <QApplication>
#include <QJsonDocument>
#include <QFontDatabase>
#include <QFont>
#include <QJsonObject>
#include <QPushButton>
#include <QTest>
#include <algorithm>
#include <cmath>
#include <filesystem>
#include <iostream>
#include <limits>
#include <map>
#include <numeric>
#include <stdexcept>
using namespace compositor;
using namespace compositor::effects_tools;
#define REQUIRE(...) do {if(!(__VA_ARGS__))throw std::runtime_error(std::string(__FILE__)+":"+std::to_string(__LINE__)+": " #__VA_ARGS__);}while(false)
template<class F>void rejects(F action){bool failed=false;try{action();}catch(const std::exception&){failed=true;}REQUIRE(failed);}
std::string json(){return withLevelsSettings("{\"kind\":\"Levels\",\"preservedMetadata\":{\"name\":\"exact\"}}",{});}
std::shared_ptr<const Raster> raster(std::vector<Pixel> pixels){return Raster::fromRgba(int(pixels.size()),1,reinterpret_cast<const uint8_t*>(pixels.data()),pixels.size()*4);}
LevelsHistogram autoBins(){LevelsHistogram bins{};for(size_t c=1;c<4;++c){bins[c][20*c]=100;bins[c][200+c*10]=100;}return bins;}
void levels_normalization_handles(){auto invalid=LevelRange{300,std::numeric_limits<double>::quiet_NaN(),-1,-100,400}.normalized();REQUIRE(invalid.black<invalid.white&&invalid.gamma==1&&invalid.outputBlack==0&&invalid.outputWhite==255);auto handles=levelsInputHandles({0,2,255});REQUIRE(handles[1]==63.75);auto moved=moveLevelsHandle({},1,false,63.75);REQUIRE(std::abs(moved.gamma-2)<1e-12);REQUIRE(moveLevelsHandle({},0,false,300).black==254);REQUIRE(moveLevelsHandle({},1,true,-30).outputWhite==0);LevelsSettings s;s.ranges[1].gamma=2;s.ranges[0].black=40;s.ranges[0].white=210;auto expected=s.ranges[0].apply(s.ranges[1].apply(64./255));REQUIRE(s.apply(64./255,LevelsChannel::Red)==expected);}
void levels_histogram_weights(){auto source=raster({{255,0,0,255},{0,128,0,128},{0,0,0,0}});Raster::resetMaterializationCount();auto bins=levelsHistogram(*source);REQUIRE(bins[1][255]==1&&std::abs(bins[2][255]-128./255)<.00001);REQUIRE(std::abs(std::accumulate(bins[0].begin(),bins[0].end(),0.)-(1+128./255))<.00001);GrayRaster selected{3,1,{255,0,0}};bins=levelsHistogram(*source,&selected);REQUIRE(bins[1][255]==1&&bins[2][255]==0);selected.pixels={0,0,0};bins=levelsHistogram(*source,&selected);for(const auto& channel:bins)REQUIRE(std::all_of(channel.begin(),channel.end(),[](double v){return v==0;}));REQUIRE(Raster::materializationCount()==0);auto wide=Raster::filled(513,257,{128,0,0,128});bins=levelsHistogram(*wide);REQUIRE(std::abs(bins[1][255]-513.*257*128/255)<.00001);}
void levels_histogram_display(){std::array<double,256> bins;bins.fill(100);bins[255]=100000;REQUIRE(histogramDisplayScale(bins)==400);bins[0]=200000;REQUIRE(histogramDisplayScale(bins)==400);bins[128]=500000;REQUIRE(histogramDisplayScale(bins)==400&&bins[128]==500000);bins.fill(100);REQUIRE(histogramDisplayScale(bins)==100);bins.fill(0);REQUIRE(histogramDisplayScale(bins)==0);bins[255]=50;REQUIRE(histogramDisplayScale(bins)==50);bins[0]=100;REQUIRE(histogramDisplayScale(bins)==100);bins[128]=200;REQUIRE(histogramDisplayScale(bins)==200);}
void levels_auto_modes(){auto bins=autoBins();auto linked=autoLevels(bins,LevelsAuto::Contrast);REQUIRE(linked.ranges[0].black==20&&linked.ranges[0].white==230);auto color=autoLevels(bins,LevelsAuto::Color);REQUIRE(color.ranges[1].black==20&&color.ranges[3].black==60&&color.ranges[0]==LevelRange{});REQUIRE(autoLevels(bins,LevelsAuto::Neutral).ranges[1].gamma==1);for(auto mode:{LevelsAuto::Contrast,LevelsAuto::Color,LevelsAuto::Neutral})REQUIRE(autoLevels({},mode).identity());bins[1][0]=.1;REQUIRE(autoLevels(bins,LevelsAuto::Color).ranges[1].black==20);bins[1][20]=150;auto neutral=autoLevels(bins,LevelsAuto::Neutral);REQUIRE(neutral.ranges[1].gamma>1);}
void levels_sample_calibration(){std::array<double,3> rgb{.25,.4,.6};for(auto mode:{LevelsSample::Black,LevelsSample::Gray,LevelsSample::White}){auto settings=sampleLevels({},rgb,mode);double target=mode==LevelsSample::Black?0:mode==LevelsSample::White?1:.5;for(int i=0;i<3;++i)REQUIRE(std::abs(settings.apply(rgb[size_t(i)],LevelsChannel(i+1))-target)<.0001);}auto first=sampleLevels({},rgb,LevelsSample::Gray);REQUIRE(sampleLevels(first,rgb,LevelsSample::Gray)==first);LevelsSettings existing;existing.ranges[0].gamma=2;existing.ranges[1].outputBlack=40;auto sampled=sampleLevels(existing,{0,.5,1},LevelsSample::Gray);REQUIRE(sampled.ranges[0]==LevelRange{}&&sampled.ranges[1].outputBlack==40);}
void levels_original_sampler(){auto source=raster({{64,32,0,128},{0,0,0,0}});Transform t;t.width=20;t.height=10;auto sample=sampleOriginalRGB(*source,t,{5,5},20,10);REQUIRE(sample&&*sample==std::array<double,3>{.5,.25,0});REQUIRE(!sampleOriginalRGB(*source,t,{15,5},20,10));REQUIRE(!sampleOriginalRGB(*source,t,{-1,5},20,10));REQUIRE(!sampleOriginalRGB(*source,t,{20,5},20,10));t.flipX=true;REQUIRE(sampleOriginalRGB(*source,t,{15,5},20,10)==sample);}
void levels_json_preservation(){auto original=json();auto s=levelsFromAdjustmentJson(original);REQUIRE(s.identity());s.channel=LevelsChannel::Blue;s.ranges[3].gamma=2;auto updated=withLevelsSettings(original,s);REQUIRE(levelsFromAdjustmentJson(updated)==s);auto object=QJsonDocument::fromJson(QByteArray::fromStdString(updated)).object();REQUIRE(object["preservedMetadata"].toObject()["name"]=="exact"&&object["kind"]=="Levels");rejects([]{levelsFromAdjustmentJson("{}");});rejects([]{auto b=autoBins();b[1][0]=-1;autoLevels(b,LevelsAuto::Contrast);});}
void levels_widget_controls(){LevelsAdvancedControls widget;widget.setAdjustmentJson(json());widget.setHistogram(autoBins());int changes=0;widget.onChanged=[&](const std::string& value){++changes;REQUIRE(!value.empty());};auto* gray=widget.findChild<QPushButton*>("levelsSampleGray");REQUIRE(gray);gray->click();REQUIRE(widget.sampleMode()==LevelsSample::Gray);widget.applySample({.25,.4,.6});REQUIRE(changes==1&&std::abs(levelsFromAdjustmentJson(widget.adjustmentJson()).apply(.25,LevelsChannel::Red)-.5)<.0001);widget.findChild<QPushButton*>("levelsAutoContrast")->click();REQUIRE(changes==2&&!widget.sampleMode()&&levelsFromAdjustmentJson(widget.adjustmentJson()).ranges[0].black==20);widget.setAdjustmentJson(json());widget.resize(430,320);widget.show();QApplication::processEvents();auto* graph=widget.findChild<QWidget*>("levelsHistogramGraph");REQUIRE(graph);QTest::mousePress(graph,Qt::LeftButton,{},QPoint(10,156));QTest::mouseMove(graph,QPoint(60,156));QTest::mouseRelease(graph,Qt::LeftButton,{},QPoint(60,156));REQUIRE(levelsFromAdjustmentJson(widget.adjustmentJson()).ranges[0].black>0);auto display=autoBins();for(int i=0;i<256;++i)display[0][size_t(i)]=100*std::exp(-std::pow((i-80)/30.,2))+70*std::exp(-std::pow((i-185)/18.,2));widget.setHistogram(display);QApplication::processEvents();auto path=std::filesystem::path(__FILE__).parent_path()/"levels-controls.png";REQUIRE(widget.grab().save(QString::fromStdWString(path.wstring())));}

void hue_band_weights(){auto reds=defaultHueBand(ColorRange::Reds);REQUIRE(reds.weight(0)==1&&reds.weight(345)==1&&reds.weight(15)==1);REQUIRE(std::abs(reds.weight(330)-.5)<.001&&std::abs(reds.weight(30)-.5)<.001);REQUIRE(reds.weight(315)==0&&reds.weight(45)==0&&reds.weight(180)==0);REQUIRE(defaultHueBand(ColorRange::Master).weight(123)==1);auto band=defaultHueBand(ColorRange::Greens);band.setHandle(1,200);REQUIRE(band==defaultHueBand(ColorRange::Greens));band.setHandle(1,110);REQUIRE(band.rangeStart==110);}
void hue_sample_range(){HueSettings s;s.range=ColorRange::Greens;s.adjustments[3].hue=10;s=sampleHueRange(s,0,HueSample::Replace);REQUIRE(s.bands[3].weight(0)==1&&s.bands[3].weight(120)==0);s=sampleHueRange(s,240,HueSample::Add);REQUIRE(s.bands[3].weight(240)==1&&s.bands[3].weight(0)==1);s=sampleHueRange(s,240,HueSample::Remove);REQUIRE(s.bands[3].weight(240)==0);REQUIRE(s.adjustments[3].hue==10);auto master=HueSettings{};REQUIRE(sampleHueRange(master,0,HueSample::Replace)==master);}
void hue_target_drag(){HueSettings s;auto drag=beginHueTargeting(s,{0,0,1});REQUIRE(drag&&s.range==ColorRange::Blues);s=dragHueTargeting(s,*drag,60,false);REQUIRE(s.adjustments[5].saturation==30);s=dragHueTargeting(s,*drag,20,false);REQUIRE(s.adjustments[5].saturation==10);s=dragHueTargeting(s,*drag,-40,true);REQUIRE(s.adjustments[5].hue==-20);REQUIRE(!sampledHue({.5,.5,.5}));REQUIRE(!beginHueTargeting(s,{.5,.5,.5}));s=HueSettings::colorizeStart();REQUIRE(!beginHueTargeting(s,{0,0,1}));}
void hue_json_spectrum(){HueSettings s;s.adjustments[0].hue=30;s.range=ColorRange::Greens;REQUIRE(s.adjustments[3].hue==0);s.adjustments[3].hue=-40;REQUIRE(s.adjustments[0].hue==30&&!s.identity());s={};s.range=ColorRange::Greens;s.adjustments[3].hue=60;REQUIRE(std::abs(s.shiftedHue(120)-180)<.001&&std::abs(s.shiftedHue(0))<.001);auto text=withHueSettings(json(),s);REQUIRE(hueFromAdjustmentJson(text)==s);auto parsed=QJsonDocument::fromJson(QByteArray::fromStdString(text)).object();REQUIRE(parsed["hsvSettings"].toObject()["adjustments"].isArray()&&parsed["preservedMetadata"].toObject()["name"]=="exact");auto legacy=hueFromAdjustmentJson("{\"hue\":10,\"saturation\":20,\"lightness\":30,\"colorize\":false}");REQUIRE(legacy.adjustments[0]==RangeAdjustment{10,20,30});s.invertRange=true;REQUIRE(s.weight(ColorRange::Greens,120)==0&&s.weight(ColorRange::Greens,0)==1);}
void curves_graph_drag(){CurvesSettings s;auto graph=curveGraph(s);for(int i=0;i<256;++i)REQUIRE(std::abs(graph[size_t(i)].y-i)<1e-10);auto selected=beginCurveDrag(s,{128,190});REQUIRE(selected&&s.channels[0].size()==3);moveCurvePoint(s,*selected,{150,220});REQUIRE(s.channels[0][*selected]==Point{150,220});moveCurvePoint(s,0,{30,50});REQUIRE(s.channels[0][0]==Point{0,50});REQUIRE(!removeCurvePoint(s,0));REQUIRE(removeCurvePoint(s,*selected)&&s.channels[0].size()==2);resetCurve(s);REQUIRE(s.channels[0]==std::vector<Point>{{0,0},{255,255}});s.channels[0]={{0,255},{128,0},{255,255}};graph=curveGraph(s);REQUIRE(graph[128].y==0);for(auto p:graph)REQUIRE(p.y>=0&&p.y<=255);}
void curves_json(){CurvesSettings s;s.channel=LevelsChannel::Red;s.channels[1]={{0,10},{100,80},{255,230}};auto text=withCurvesSettings(json(),s);REQUIRE(curvesFromAdjustmentJson(text)==s);auto object=QJsonDocument::fromJson(QByteArray::fromStdString(text)).object();REQUIRE(object["preservedMetadata"].toObject()["name"]=="exact");s.channels[1][1].x=0;REQUIRE(!s.valid());rejects([&]{withCurvesSettings(json(),s);});}
void color_hex_hsb(){REQUIRE(PaletteColor::fromHex("#FF8000")==PaletteColor{1,128./255,0});REQUIRE(PaletteColor::fromHex("0f0")==PaletteColor{0,1,0});REQUIRE(PaletteColor::fromHex(" 00ff00 ")==PaletteColor{0,1,0});REQUIRE(!PaletteColor::fromHex("12345")&&!PaletteColor::fromHex("GGGGGG"));for(const char* text:{"000000","FFFFFF","FF0000","00FF00","0000FF","FF8000","7F3FA2","123456"}){PickerHSB picker;picker.setRGB(*PaletteColor::fromHex(text));REQUIRE(picker.rgb().quantized().hex()==text);}PickerHSB picker;picker.setRGB(*PaletteColor::fromHex("FF8000"));double hue=picker.hue;picker.setRGB(*PaletteColor::fromHex("808080"));REQUIRE(picker.hue==hue&&picker.saturation==0);picker.saturation=.5;picker.setRGB({0,0,0});REQUIRE(picker.hue==hue&&picker.saturation==.5&&picker.brightness==0);}
void color_sample_ring(){Document d;d.id=newId();d.width=2;d.height=1;Layer layer;layer.id=newId();layer.raster=raster({{64,32,0,128},{0,0,0,0}});layer.transform.width=2;layer.transform.height=1;d.layers={layer};auto sample=sampleCompositeColor(d,{.5,.5},graphics::StackRenderer());REQUIRE(sample&&sample->hex()=="804000");REQUIRE(!sampleCompositeColor(d,{1.5,.5},graphics::StackRenderer())&&!sampleCompositeColor(d,{-1,0},graphics::StackRenderer()));auto ring=sampleRingGeometry({20,30});REQUIRE(ring.origin==Point{-38,-28}&&ring.width==116&&ring.height==116&&ring.pathInset==15&&ring.outlineWidth==24&&ring.colorWidth==16&&ring.splitY==58);}

void hue_widget_controls(){
 HueAdvancedControls widget;HueSettings settings;settings.range=ColorRange::Greens;widget.setAdjustmentJson(withHueSettings(json(),settings));int changes=0;widget.onChanged=[&](const std::string&){++changes;};
 widget.findChild<QPushButton*>("hueSampleColor")->click();REQUIRE(widget.sampleMode()==HueSample::Replace);widget.applySample({1,0,0});auto sampled=hueFromAdjustmentJson(widget.adjustmentJson());REQUIRE(sampled.bands[3].weight(0)==1&&sampled.bands[3].weight(120)==0);
 widget.findChild<QPushButton*>("hueAddColor")->click();widget.applySample({0,0,1});sampled=hueFromAdjustmentJson(widget.adjustmentJson());REQUIRE(sampled.bands[3].weight(240)==1&&sampled.bands[3].weight(0)==1);
 widget.findChild<QPushButton*>("hueRemoveColor")->click();widget.applySample({0,0,1});REQUIRE(hueFromAdjustmentJson(widget.adjustmentJson()).bands[3].weight(240)==0);
 widget.setAdjustmentJson(withHueSettings(json(),{}));widget.findChild<QPushButton*>("hueTargetedAdjustment")->click();REQUIRE(widget.targeting()&&!widget.sampleMode());REQUIRE(widget.beginTarget({0,0,1}));widget.dragTarget(60,false);REQUIRE(hueFromAdjustmentJson(widget.adjustmentJson()).adjustments[5].saturation==30);widget.dragTarget(20,false);REQUIRE(hueFromAdjustmentJson(widget.adjustmentJson()).adjustments[5].saturation==10);widget.dragTarget(-40,true);REQUIRE(hueFromAdjustmentJson(widget.adjustmentJson()).adjustments[5].hue==-20);widget.endTarget();auto ended=widget.adjustmentJson();widget.dragTarget(80,false);REQUIRE(widget.adjustmentJson()==ended);
 settings=HueSettings{};settings.range=ColorRange::Greens;settings.adjustments[3].hue=60;widget.setAdjustmentJson(withHueSettings(json(),settings));widget.resize(520,160);widget.show();QApplication::processEvents();auto* graph=widget.findChild<QWidget*>("hueSpectrumGraph");REQUIRE(graph);auto point=[&](double hue){return QPoint(int(std::round(hue/360*graph->width())),31);};QTest::mousePress(graph,Qt::LeftButton,{},point(105));QTest::mouseMove(graph,point(110));QTest::mouseRelease(graph,Qt::LeftButton,{},point(110));REQUIRE(std::abs(hueFromAdjustmentJson(widget.adjustmentJson()).bands[3].rangeStart-110)<1);REQUIRE(changes>=8);QApplication::processEvents();auto path=std::filesystem::path(__FILE__).parent_path()/"hue-controls.png";REQUIRE(widget.grab().save(QString::fromStdWString(path.wstring())));
}
void curves_widget_controls(){
 CurvesAdvancedControls widget;widget.setAdjustmentJson(withCurvesSettings(json(),{}));int changes=0;widget.onChanged=[&](const std::string&){++changes;};widget.resize(430,370);widget.show();QApplication::processEvents();auto* graph=widget.findChild<QWidget*>("curvesGraph");REQUIRE(graph);auto point=[&](double x,double y){return QPoint(int(std::round(8+x/255*(graph->width()-16))),int(std::round(8+(1-y/255)*(graph->height()-16))));};QTest::mouseClick(graph,Qt::LeftButton,{},point(128,190));auto settings=curvesFromAdjustmentJson(widget.adjustmentJson());REQUIRE(settings.channels[0].size()==3&&std::abs(settings.channels[0][1].x-128)<1);QTest::mousePress(graph,Qt::LeftButton,{},point(128,190));QTest::mouseMove(graph,point(150,220));QTest::mouseRelease(graph,Qt::LeftButton,{},point(150,220));settings=curvesFromAdjustmentJson(widget.adjustmentJson());REQUIRE(std::abs(settings.channels[0][1].x-150)<1&&std::abs(settings.channels[0][1].y-220)<1);auto* remove=widget.findChild<QPushButton*>("curvesRemovePoint");REQUIRE(remove&&remove->isEnabled());remove->click();REQUIRE(curvesFromAdjustmentJson(widget.adjustmentJson()).channels[0].size()==2);QTest::mouseClick(graph,Qt::LeftButton,{},point(128,190));widget.findChild<QPushButton*>("curvesResetCurve")->click();REQUIRE(curvesFromAdjustmentJson(widget.adjustmentJson())==CurvesSettings{});settings.channels[0]={{0,0},{70,40},{150,205},{255,255}};widget.setAdjustmentJson(withCurvesSettings(json(),settings));REQUIRE(changes>=5);auto shown=widget.adjustmentJson();auto close=settings;close.channels[0]={{0,0},{.1,120},{.2,230},{255,255}};widget.setAdjustmentJson(withCurvesSettings(json(),close));auto beforeRejected=widget.adjustmentJson();QTest::mouseClick(graph,Qt::LeftButton,{},point(.1,120));REQUIRE(widget.adjustmentJson()==beforeRejected&&!graph->toolTip().isEmpty());widget.setAdjustmentJson(shown);QApplication::processEvents();auto path=std::filesystem::path(__FILE__).parent_path()/"curves-controls.png";REQUIRE(widget.grab().save(QString::fromStdWString(path.wstring())));
}

int main(int argc,char** argv){QApplication app(argc,argv);auto fontId=QFontDatabase::addApplicationFont(qEnvironmentVariable("WINDIR")+"/Fonts/segoeui.ttf");if(fontId<0){std::cerr<<"Native font fixture unavailable\n";return 2;}app.setFont(QFont("Segoe UI",9));std::map<std::string,void(*)()> tests{{"hue_widget_controls",hue_widget_controls},{"curves_widget_controls",curves_widget_controls},{"levels_normalization_handles",levels_normalization_handles},{"levels_histogram_weights",levels_histogram_weights},{"levels_histogram_display",levels_histogram_display},{"levels_auto_modes",levels_auto_modes},{"levels_sample_calibration",levels_sample_calibration},{"levels_original_sampler",levels_original_sampler},{"levels_json_preservation",levels_json_preservation},{"levels_widget_controls",levels_widget_controls},{"hue_band_weights",hue_band_weights},{"hue_sample_range",hue_sample_range},{"hue_target_drag",hue_target_drag},{"hue_json_spectrum",hue_json_spectrum},{"curves_graph_drag",curves_graph_drag},{"curves_json",curves_json},{"color_hex_hsb",color_hex_hsb},{"color_sample_ring",color_sample_ring}};try{if(argc!=2||!tests.contains(argv[1]))throw std::runtime_error("Specify one effects tools test");tests.at(argv[1])();std::cout<<"PASS "<<argv[1]<<"\n";return 0;}catch(const std::exception& error){std::cerr<<"FAIL: "<<error.what()<<"\n";return 1;}}
