// CanvasSize.swift, CanvasResizer.swift, Crop.swift and LayerFlip.swift at the
// pinned revision. Copyright (c) 2026 Wonder Assembly LLC; MIT notice in
// graphics/upstream/LICENSE. Raster and history ownership remains with callers.
#include "DocumentGeometry.h"
#include "graphics/RasterSampling.h"
#include <algorithm>
#include <cmath>
#include <numbers>
#include <stdexcept>
#include <unordered_map>
#include <unordered_set>

namespace compositor::editing {
namespace {
constexpr Point handles[]={{0,0},{.5,0},{1,0},{1,.5},{1,1},{.5,1},{0,1},{0,.5}};
void finitePoint(Point p){if(!std::isfinite(p.x)||!std::isfinite(p.y)||std::abs(p.x)>10000000||std::abs(p.y)>10000000)throw std::runtime_error("Invalid geometry coordinate");}
Rect transformBounds(const Transform& t){auto a=t.fromUnit({0,0}),b=t.fromUnit({1,0}),c=t.fromUnit({1,1}),d=t.fromUnit({0,1});double x=std::min({a.x,b.x,c.x,d.x}),y=std::min({a.y,b.y,c.y,d.y});return {x,y,std::max({a.x,b.x,c.x,d.x})-x,std::max({a.y,b.y,c.y,d.y})-y};}
std::unordered_map<std::string,const Layer*> indexLayers(const Document& doc){std::unordered_map<std::string,const Layer*> index;for(const auto& layer:doc.layers)index[layer.id]=&layer;return index;}
bool visible(const Layer& layer,const std::unordered_map<std::string,const Layer*>& index){const Layer* current=&layer;for(size_t depth=0;depth<=64;++depth){if(!current->visible)return false;if(current->parentId.empty())return true;current=index.at(current->parentId);}return false;}
Transform placing(const Transform& original,Point origin,Point right,Point bottom){
    double a=right.x-origin.x,b=right.y-origin.y,c=bottom.x-origin.x,d=bottom.y-origin.y,sign=original.flipX?-1:1;double angle=std::atan2(b*sign,a*sign),along=-c*std::sin(angle)+d*std::cos(angle);Point center{origin.x+(a+c)/2,origin.y+(b+d)/2};auto result=original;result.width=std::hypot(a,b);result.height=std::abs(along);double degrees=angle*180/std::numbers::pi;result.rotation=degrees+std::round((original.rotation-degrees)/360)*360;result.flipY=along<0;result.x=center.x-result.width/2;result.y=center.y-result.height/2;return result;
}
Transform following(const Transform& placement,const Transform& old,const Transform& next){auto map=[&](Point p){return next.fromUnit(old.toUnit(placement.fromUnit(p)));};return placing(placement,map({0,0}),map({1,0}),map({0,1}));}
bool samePlacement(Transform a,const Transform& b){a.sampling=b.sampling;return a==b;}
}
CanvasSizeDraft::CanvasSizeDraft(int w,int h,double dpi):originalWidth(w),originalHeight(h),resolution(dpi),width(w),height(h){if(w<1||h<1||!std::isfinite(dpi)||dpi<=0)throw std::runtime_error("Invalid original canvas dimensions");}
bool CanvasSizeDraft::valid()const{return std::isfinite(width)&&std::isfinite(height)&&std::round(width)>=1&&std::round(width)<=30000&&std::round(height)>=1&&std::round(height)<=30000;}
double CanvasSizeDraft::displayed(bool axis)const{double original=axis?originalWidth:originalHeight,pixels=(axis?width:height)-(relative?original:0);switch(unit){case CanvasUnit::Pixels:return pixels;case CanvasUnit::Percent:return pixels/original*100;case CanvasUnit::Inches:return pixels/resolution;case CanvasUnit::Centimeters:return pixels/resolution*2.54;}throw std::runtime_error("Invalid canvas unit");}
void CanvasSizeDraft::set(double value,bool axis){double original=axis?originalWidth:originalHeight,pixels{};switch(unit){case CanvasUnit::Pixels:pixels=value;break;case CanvasUnit::Percent:pixels=value/100*original;break;case CanvasUnit::Inches:pixels=value*resolution;break;case CanvasUnit::Centimeters:pixels=value/2.54*resolution;break;}double final=pixels+(relative?original:0);if(axis){width=final;if(locked)height=final*originalHeight/originalWidth;}else{height=final;if(locked)width=final*originalWidth/originalHeight;}}
Point CanvasSizeOptions::offset(int oldWidth,int oldHeight)const{if(contentOffset)return *contentOffset;return {std::floor(double(width-oldWidth)*(anchor%3)/2),std::floor(double(height-oldHeight)*(anchor/3)/2)};}
Document canvasResize(const Document& doc,const CanvasSizeOptions& options){
    validateDocument(doc);if(options.width<1||options.height<1||options.width>30000||options.height>30000||options.anchor<0||options.anchor>8)throw std::runtime_error("Invalid canvas dimensions or anchor");auto offset=options.offset(doc.width,doc.height);if(!std::isfinite(offset.x)||!std::isfinite(offset.y)||std::abs(offset.x)>1000000||std::abs(offset.y)>1000000)throw std::runtime_error("Invalid canvas offset");
    if(options.width==doc.width&&options.height==doc.height&&offset==Point{})return doc;
    auto result=doc;result.width=options.width;result.height=options.height;result.selection.reset();for(auto& layer:result.layers){layer.transform.x+=offset.x;layer.transform.y+=offset.y;if(!layer.transform.valid())throw std::runtime_error("Canvas translation exceeds transform limits");if(layer.mask&&layer.mask->placement){layer.mask->placement->x+=offset.x;layer.mask->placement->y+=offset.y;if(!layer.mask->placement->valid())throw std::runtime_error("Canvas translation exceeds mask transform limits");}}
    if(options.fill&&(options.width>doc.width||options.height>doc.height)){
        uint64_t used=0;for(const auto& layer:doc.layers)if(layer.raster)used+=uint64_t(layer.raster->width)*layer.raster->height;uint64_t next=uint64_t(options.width)*options.height;if(next>100000000||used>100000000-next||doc.layers.size()>=10000)throw std::runtime_error("Canvas extension exceeds project budget");
        Pixel color=*options.fill;color.a=255;auto raster=std::make_shared<Raster>(*Raster::filled(options.width,options.height,color));int columns=(options.width+255)/256;auto erased=SelectionOutline::rectangle({offset.x,offset.y,double(doc.width),double(doc.height)}).rasterize(options.width,options.height);
        for(size_t key=0;key<raster->tiles.size();++key){int left=int(key%columns)*256,top=int(key/columns)*256;std::shared_ptr<Raster::Tile> tile;for(int y=0;y<std::min(256,options.height-top);++y)for(int x=0;x<std::min(256,options.width-left);++x){uint8_t coverage=erased->pixel(left+x,top+y);if(coverage){if(!tile){tile=std::make_shared<Raster::Tile>(*raster->tiles[key]);raster->tiles[key]=tile;}auto scale=[&](uint8_t c){return uint8_t((unsigned(c)*(255-coverage)+127)/255);};tile->pixels[size_t(y)*256+x]={scale(color.r),scale(color.g),scale(color.b),uint8_t(255-coverage)};}}}
        Layer extension;extension.id=newId();extension.name="Canvas Extension";extension.transform.width=options.width;extension.transform.height=options.height;extension.raster=raster;result.layers.insert(result.layers.begin(),std::move(extension));
    }validateDocument(result);return result;
}
Document cropDocument(const Document& doc,Rect rect){if(!validCrop(rect))throw std::runtime_error("Invalid crop rectangle");return canvasResize(doc,CanvasSizeOptions{int(rect.width),int(rect.height),4,{},Point{-rect.x,-rect.y}});}
Document imageResize(const Document& doc,const ImageSizeOptions& options){
    validateDocument(doc);if(options.width<1||options.height<1||options.width>30000||options.height>30000||!std::isfinite(options.resolution)||options.resolution<1||options.resolution>9600)throw std::runtime_error("Invalid image dimensions or resolution");
    auto result=doc;result.width=options.width;result.height=options.height;result.resolution=options.resolution;result.selection.reset();if(doc.width==options.width&&doc.height==options.height)return result;
    if(uint64_t(options.width)*options.height>100000000)throw std::runtime_error("Resized image exceeds pixel budget");double sx=double(options.width)/doc.width,sy=double(options.height)/doc.height;
    struct Plan {int width,height;double left,top;Transform transform;};std::vector<Plan> plans;uint64_t imagePixels=0,maskPixels=0;
    // Validate every output allocation before creating the first resized raster.
    for(const auto& layer:doc.layers){auto box=transformBounds(layer.transform);double left=std::floor(box.x*sx),top=std::floor(box.y*sy),right=std::ceil((box.x+box.width)*sx),bottom=std::ceil((box.y+box.height)*sy);if(!std::isfinite(right-left)||!std::isfinite(bottom-top)||right-left<1||bottom-top<1||right-left>300000||bottom-top>300000)throw std::runtime_error("Resized layer transform exceeds limits");int width=int(right-left),height=int(bottom-top);Transform transform;transform.x=left;transform.y=top;transform.width=width;transform.height=height;transform.sampling=options.sampling;if(!transform.valid())throw std::runtime_error("Resized layer transform exceeds limits");
        auto allocate=[&](uint64_t& used){if(width<1||height<1||width>30000||height>30000||uint64_t(width)*height>100000000-used)throw std::runtime_error("Resized layers exceed pixel budget");used+=uint64_t(width)*height;};if(layer.raster)allocate(imagePixels);if(layer.mask&&!(layer.mask->raster->width==1&&layer.mask->raster->height==1)&&!layer.mask->placement)allocate(maskPixels);plans.push_back({width,height,left,top,transform});}
    for(size_t i=0;i<doc.layers.size();++i){const auto& layer=doc.layers[i];const auto& plan=plans[i];auto& resized=result.layers[i];resized.transform=plan.transform;resized.shapeJson.clear();
        auto origin=layer.transform.toUnit({plan.left/sx,plan.top/sy}),right=layer.transform.toUnit({(plan.left+plan.width)/sx,plan.top/sy}),bottom=layer.transform.toUnit({plan.left/sx,(plan.top+plan.height)/sy});Point stepX{(right.x-origin.x)/plan.width,(right.y-origin.y)/plan.width},stepY{(bottom.x-origin.x)/plan.height,(bottom.y-origin.y)/plan.height};auto unit=[&](int x,int y){return Point{origin.x+(x+.5)*stepX.x+(y+.5)*stepY.x,origin.y+(x+.5)*stepX.y+(y+.5)*stepY.y};};
        if(layer.raster){auto raster=std::make_shared<Raster>(*Raster::filled(plan.width,plan.height));int columns=(plan.width+255)/256;for(size_t key=0;key<raster->tiles.size();++key){int left=int(key%columns)*256,top=int(key/columns)*256;auto tile=std::make_shared<Raster::Tile>();for(int y=0;y<std::min(256,plan.height-top);++y)for(int x=0;x<std::min(256,plan.width-left);++x)tile->pixels[size_t(y)*256+x]=graphics::sampleRaster(*layer.raster,unit(left+x,top+y),options.sampling);raster->tiles[key]=tile;}resized.raster=raster;}
        if(layer.mask){auto& mask=*resized.mask;if(!(mask.raster->width==1&&mask.raster->height==1)&&!mask.placement){auto gray=std::make_shared<GrayRaster>();gray->width=plan.width;gray->height=plan.height;gray->pixels.resize(size_t(plan.width)*plan.height);for(int y=0;y<plan.height;++y)for(int x=0;x<plan.width;++x)gray->pixels[size_t(y)*plan.width+x]=uint8_t(std::clamp(std::lround(graphics::sampleGray(*layer.mask->raster,unit(x,y),options.sampling)*255),0L,255L));mask.raster=gray;}
            if(mask.placement){auto scale=[&](Point p){auto value=mask.placement->fromUnit(p);return Point{value.x*sx,value.y*sy};};mask.placement=placing(*mask.placement,scale({0,0}),scale({1,0}),scale({0,1}));}}
    }validateDocument(result);return result;
}
Transform mirroredTransform(const Transform& t,bool horizontal,double axis){if(!t.valid()||!std::isfinite(axis))throw std::runtime_error("Invalid mirror transform");auto result=t;if(horizontal){result.flipX=!result.flipX;result.x=2*axis-(t.x+t.width/2)-t.width/2;}else{result.flipY=!result.flipY;result.y=2*axis-(t.y+t.height/2)-t.height/2;}result.rotation=-t.rotation;if(!result.valid())throw std::runtime_error("Mirrored transform exceeds project limits");return result;}
Document flipCanvas(const Document& doc,bool horizontal){
    validateDocument(doc);auto result=doc;double axis=(horizontal?doc.width:doc.height)/2.;for(auto& layer:result.layers){layer.transform=mirroredTransform(layer.transform,horizontal,axis);if(layer.mask&&layer.mask->placement)layer.mask->placement=mirroredTransform(*layer.mask->placement,horizontal,axis);}
    if(doc.selection){
        if(!doc.selection->coverage)throw std::runtime_error("Present selection has no coverage");
        if(doc.selection->outline)result.selection=rasterSelection(doc.selection->outline->mirrored(horizontal,axis),doc.width,doc.height);
        else if(doc.selection->coverage->source){
            auto source=doc.selection->coverage;auto b=source->nonzeroBounds();if(horizontal)b.x=source->width-b.x-b.width;else b.y=source->height-b.y-b.height;
            std::shared_ptr<const SelectionOutline> outline;if(auto path=source->source->vectorOutline())outline=std::make_shared<SelectionOutline>(path->mirrored(horizontal,axis));
            result.selection=Selection{GrayRaster::sampled(source->width,source->height,b,[source,horizontal](int x,int y){return source->pixel(horizontal?source->width-1-x:x,horizontal?y:source->height-1-y);},source->retainedBytes(),std::move(outline))};
        }else{const auto& source=*doc.selection->coverage;auto gray=std::make_shared<GrayRaster>(source);for(int y=0;y<source.height;++y)for(int x=0;x<source.width;++x)gray->pixels[size_t(y)*source.width+x]=source.pixel(horizontal?source.width-1-x:x,horizontal?y:source.height-1-y);result.selection=Selection{gray};}
    }
    validateDocument(result);return result;
}
Document flipLayers(const Document& doc,std::span<const std::string> selected,bool horizontal){
    validateDocument(doc);if(selected.empty())return doc;auto index=indexLayers(doc);std::unordered_set<std::string> ids(selected.begin(),selected.end());for(const auto& id:ids)if(!index.contains(id))throw std::runtime_error("Selected mirror layer does not exist");bool group=ids.size()>1||index.at(*ids.begin())->group;std::vector<const Layer*> members;
    if(!group){const auto* layer=index.at(*ids.begin());if(visible(*layer,index))members.push_back(layer);}else for(const auto& layer:doc.layers){if(layer.group||!layer.raster||!visible(layer,index))continue;const Layer* current=&layer;for(size_t depth=0;depth<64;++depth){if(ids.contains(current->id)){members.push_back(&layer);break;}if(current->parentId.empty())break;current=index.at(current->parentId);}}
    if(members.empty())return doc;double left=INFINITY,top=INFINITY,right=-INFINITY,bottom=-INFINITY;for(auto* layer:members){auto box=transformBounds(layer->transform);left=std::min(left,box.x);top=std::min(top,box.y);right=std::max(right,box.x+box.width);bottom=std::max(bottom,box.y+box.height);}double axis=horizontal?(left+right)/2:(top+bottom)/2;
    std::unordered_set<std::string> moving;for(auto* layer:members)moving.insert(layer->id);auto result=doc;for(auto& layer:result.layers)if(moving.contains(layer.id)){auto old=layer.transform,next=mirroredTransform(old,horizontal,axis);if(layer.mask){auto& mask=*layer.mask;if(mask.raster->width==1&&mask.raster->height==1)mask.placement.reset();else if(mask.linked){if(mask.placement)mask.placement=following(*mask.placement,old,next);}else if(!mask.placement)mask.placement=old;if(mask.placement&&samePlacement(*mask.placement,next))mask.placement.reset();}layer.transform=next;}validateDocument(result);return result;
}
Rect snappedCrop(Rect r){finitePoint({r.x,r.y});finitePoint({r.x+r.width,r.y+r.height});if(r.width<0){r.x+=r.width;r.width=-r.width;}if(r.height<0){r.y+=r.height;r.height=-r.height;}double x=std::round(r.x),y=std::round(r.y);return {x,y,std::max(1.,std::round(r.x+r.width)-x),std::max(1.,std::round(r.y+r.height)-y)};}
bool validCrop(Rect r){return std::isfinite(r.x)&&std::isfinite(r.y)&&std::isfinite(r.width)&&std::isfinite(r.height)&&r.width>=1&&r.width<=30000&&r.height>=1&&r.height<=30000&&std::abs(r.x)<=1000000&&std::abs(r.y)<=1000000;}
Rect createCrop(Point start,Point end,std::optional<double> ratio,bool symmetric){finitePoint(start);finitePoint(end);double dx=end.x-start.x,dy=end.y-start.y;if(ratio){if(!std::isfinite(*ratio)||*ratio<=0)throw std::runtime_error("Invalid crop aspect ratio");if(std::abs(dx)>std::abs(dy)**ratio)dy=(dy<0?-1:1)*std::abs(dx)/ *ratio;else dx=(dx<0?-1:1)*std::abs(dy)**ratio;}return snappedCrop(symmetric?Rect{start.x-std::abs(dx),start.y-std::abs(dy),2*std::abs(dx),2*std::abs(dy)}:Rect{std::min(start.x,start.x+dx),std::min(start.y,start.y+dy),std::abs(dx),std::abs(dy)});}
Rect CropDrag::updated(Point point,std::optional<double> ratio,bool symmetric)const {
    finitePoint(point);finitePoint(start);if(mode==Mode::Create)return createCrop(start,point,ratio,symmetric);if(mode==Mode::Move)return snappedCrop({original.x+point.x-start.x,original.y+point.y-start.y,original.width,original.height});if(handle<0||handle>=8||!validCrop(original))throw std::runtime_error("Invalid crop resize handle");
    auto unit=handles[handle];Point anchorUnit=symmetric?Point{.5,.5}:Point{1-unit.x,1-unit.y};Point anchor{original.x+anchorUnit.x*original.width,original.y+anchorUnit.y*original.height};double span=symmetric?2:1,lx=(original.x+unit.x*original.width+point.x-start.x-anchor.x)*span,ly=(original.y+unit.y*original.height+point.y-start.y-anchor.y)*span,sx=unit.x*2-1,sy=unit.y*2-1;
    double width=sx==0?original.width:std::max(1.,lx*sx),height=sy==0?original.height:std::max(1.,ly*sy);if(ratio){double factor=sx==0?height/original.height:sy==0?width/original.width:std::max(1/std::min(original.width,original.height),(lx*sx*original.width+ly*sy*original.height)/(original.width*original.width+original.height*original.height));width=original.width*factor;height=original.height*factor;}
    Rect next{anchor.x-anchorUnit.x*width,anchor.y-anchorUnit.y*height,width,height};return snappedCrop(validCrop(next)?next:original);
}
Rect CropSnap::apply(Rect rect,const CropDrag& drag,Point point,std::optional<double> ratio,bool symmetric)const {
    if(!std::isfinite(tolerance)||tolerance<=0)return rect;auto nearest=[&](double value,const std::vector<double>& targets)->std::optional<double>{std::optional<double> best;for(double target:targets)if(std::abs(target-value)<=tolerance&&(!best||std::abs(*best-value)>std::abs(target-value)))best=target;return best;};
    if(drag.mode==CropDrag::Mode::Move){auto shift=[&](double a,double b,const std::vector<double>& targets){std::optional<double> best;for(double edge:{a,b})if(auto found=nearest(edge,targets)){double offset=*found-edge;if(!best||std::abs(offset)<std::abs(*best))best=offset;}return best.value_or(0);};return {rect.x+shift(rect.x,rect.x+rect.width,xs),rect.y+shift(rect.y,rect.y+rect.height,ys),rect.width,rect.height};}
    if(ratio)return rect;bool horizontal=true,vertical=true;if(drag.mode==CropDrag::Mode::Resize){if(drag.handle<0||drag.handle>=8)throw std::runtime_error("Invalid crop snap handle");horizontal=handles[drag.handle].x!=.5;vertical=handles[drag.handle].y!=.5;}
    auto result=rect;if(horizontal){if(std::abs(point.x-result.x)<=std::abs(point.x-result.x-result.width)){if(auto x=nearest(result.x,xs);x&&*x<result.x+result.width){result.width+=result.x-*x;result.x=*x;}}else if(auto x=nearest(result.x+result.width,xs);x&&*x>result.x)result.width=*x-result.x;}
    if(vertical){if(std::abs(point.y-result.y)<=std::abs(point.y-result.y-result.height)){if(auto y=nearest(result.y,ys);y&&*y<result.y+result.height){result.height+=result.y-*y;result.y=*y;}}else if(auto y=nearest(result.y+result.height,ys);y&&*y>result.y)result.height=*y-result.y;}
    if(symmetric){Point center=drag.mode==CropDrag::Mode::Create?drag.start:Point{drag.original.x+drag.original.width/2,drag.original.y+drag.original.height/2};if(horizontal){double half=point.x>=center.x?result.x+result.width-center.x:center.x-result.x;if(half>=.5){result.x=center.x-half;result.width=2*half;}}if(vertical){double half=point.y>=center.y?result.y+result.height-center.y:center.y-result.y;if(half>=.5){result.y=center.y-half;result.height=2*half;}}}return result;
}
CropSnap cropSnapTargets(const Document& doc,double tolerance){validateDocument(doc);CropSnap snap{{0,double(doc.width)},{0,double(doc.height)},tolerance};auto index=indexLayers(doc);for(const auto& layer:doc.layers)if(layer.raster&&visible(layer,index)){auto box=transformBounds(layer.transform);snap.xs.push_back(std::round(box.x));snap.xs.push_back(std::round(box.x+box.width));snap.ys.push_back(std::round(box.y));snap.ys.push_back(std::round(box.y+box.height));}return snap;}
}
