#include "retouch/RetouchSession.h"
#include "graphics/PixelAlgorithms.h"
#include <cmath>
#include <functional>
#include <iostream>
#include <limits>
#include <stdexcept>
using namespace compositor;
using namespace compositor::retouch;
namespace {
int passed=0,failed=0;
void require(bool b,const char* message){if(!b)throw std::runtime_error(message);}
template<class F>void test(const char* name,F body){try{body();++passed;std::cout<<"PASS "<<name<<'\n';}catch(const std::exception& e){++failed;std::cout<<"FAIL "<<name<<": "<<e.what()<<'\n';}}
std::shared_ptr<const Raster> raster(int w,int h,const std::function<Pixel(int,int)>& pixel){std::vector<Pixel> values(size_t(w)*h);for(int y=0;y<h;++y)for(int x=0;x<w;++x)values[size_t(y)*w+x]=pixel(x,y);return Raster::filled(w,h)->replacing(0,0,w,h,values.data(),w);}
Transform transform(int w,int h){return {0,0,double(w),double(h),0,false,false,Transform::Sampling::Nearest};}
std::shared_ptr<const Raster> colors(){return raster(80,40,[](int x,int y){if(x>=10&&x<20&&y>=15&&y<25)return Pixel{0,255,0,255};return x<40?Pixel{255,0,0,255}:Pixel{0,0,255,255};});}
std::shared_ptr<const GrayRaster> selection(int w,int h,const std::function<uint8_t(int,int)>& pixel){auto result=std::make_shared<GrayRaster>();result->width=w;result->height=h;result->pixels.resize(size_t(w)*h);for(int y=0;y<h;++y)for(int x=0;x<w;++x)result->pixels[size_t(y)*w+x]=pixel(x,y);return result;}
}
int main(int argc,char** argv){
    std::shared_ptr<graphics::D3D11BrushCoverage> gpu;
    if(argc>1){try{gpu=std::make_shared<graphics::D3D11BrushCoverage>(argv[1],true);std::cout<<"WARP adapter: "<<gpu->adapterName()<<'\n';}catch(const std::exception&e){std::cout<<"WARP initialization failed: "<<e.what()<<'\n';return 1;}}
    test("warp_document_preview_precedes_selection_commit_clip",[&]{auto original=raster(32,16,[](int x,int){return Pixel{uint8_t(x*7),0,0,255};});Settings settings;settings.mode=Mode::Smudge;settings.radius=3;settings.hardness=1;auto clip=selection(32,16,[](int x,int){return uint8_t(x<5?255:0);});RetouchSession stroke(original,transform(32,16),32,16,settings,{},clip,gpu);stroke.begin({10,8});stroke.append({11,8});auto document=stroke.warpDocumentPreview();require(document->pixel(11,8).r==70,"Live document smudge was selection clipped");require(stroke.preview()->pixel(11,8).r==77,"Commit preview ignored selection");require(stroke.warpDocumentPreview()==document,"Unchanged live document preview not cached");});
    test("source_clone_alignment_rounding_and_sample_crosshair",[]{CloneAlignment alignment;require(!alignment.strokeOffset({60,20}),"Missing source accepted");alignment.setSource({15,20});require(alignment.beginStroke({60,20})==Point{-45,0},"First aligned offset");require(alignment.beginStroke({66,20})==Point{-45,0},"Aligned offset reset");require(alignment.samplePoint({66,20})==Point{21,20},"Aligned source crosshair");alignment.aligned=false;require(alignment.beginStroke({50,10})==Point{-35,10},"Nonaligned stroke source");require(alignment.samplePoint({60,20})==Point{15,20},"Idle nonaligned crosshair");require(alignment.samplePoint({60,20},true)==Point{25,30},"Active nonaligned crosshair");alignment.setSource({15.5,20.5});require(alignment.beginStroke({17,19})==Point{-2,2},"Wholepixel offset rounding");});
    test("source_clone_stamp_three_strokes_and_immutable_source",[&]{auto original=colors();CloneAlignment alignment;alignment.setSource({15,20});Settings settings;settings.radius=3;settings.hardness=1;
        Sources source;source.cloneOffset=alignment.beginStroke({60,20});RetouchSession first(original,transform(80,40),80,40,settings,source,{},gpu);require(first.begin({60,20}),"First clone did not begin");first.append({60.5,20});auto preview=first.preview();auto after=first.commit();require(after->pixel(60,20)==Pixel{0,255,0,255},"Green source not copied");require(original->pixel(60,20)==Pixel{0,0,255,255},"Original mutated");require(after->pixel(70,5)==original->pixel(70,5),"Outside clone changed");require(first.commit()==after,"Commit not idempotent");require(preview->pixel(60,20)==Pixel{0,255,0,255},"Preview mutated");
        source.cloneOffset=alignment.beginStroke({66,20});RetouchSession second(after,transform(80,40),80,40,settings,source,{},gpu);second.begin({66,20});after=second.commit();require(after->pixel(66,20)==Pixel{255,0,0,255},"Second aligned stroke did not copy red");
        alignment.aligned=false;source.cloneOffset=alignment.beginStroke({50,10});RetouchSession third(after,transform(80,40),80,40,settings,source,{},gpu);third.begin({50,10});require(third.commit()->pixel(50,10)==Pixel{0,255,0,255},"Nonaligned stroke source differs");});
    test("clone_all_layers_frozen_sample_and_source_over_opacity_cap",[&]{auto original=Raster::filled(32,16,{0,0,255,255});Settings settings;settings.radius=5;settings.hardness=1;settings.opacity=.5;settings.sampleAllLayers=true;Sources source;source.allLayers=Raster::filled(32,16,{128,0,0,128});source.cloneOffset=Point{};
        RetouchSession stroke(original,transform(32,16),32,16,settings,source,{},gpu);stroke.begin({10,8});for(Point p:std::array<Point,4>{{{20,8},{10,8},{20,8},{10,8}}})stroke.append(p);auto result=stroke.commit();require(result->pixel(10,8)==Pixel{64,0,191,255},"Clone opacity accumulated or wrong premultiplication");require(source.allLayers->pixel(10,8)==Pixel{128,0,0,128},"Frozen sample changed");
        settings.sampleAllLayers=false;RetouchSession current(original,transform(32,16),32,16,settings,source);current.begin({10,8});require(current.commit()->pixel(10,8)==original->pixel(10,8),"Current-layer clone used all-layer sample");});
    test("selection_multiplication_once_empty_and_cancel",[&]{auto original=Raster::filled(32,16,{0,0,255,255});Settings settings;settings.radius=5;settings.hardness=1;settings.opacity=.5;Sources source;source.currentLayer=Raster::filled(32,16,{255,0,0,255});source.cloneOffset=Point{};auto clip=selection(32,16,[](int x,int){return uint8_t(x<16?128:0);});
        RetouchSession stroke(original,transform(32,16),32,16,settings,source,clip,gpu);stroke.begin({10,8});stroke.append({22,8});auto preview=stroke.preview();require(preview->pixel(10,8)==Pixel{64,0,191,255},"Selection applied twice or omitted");require(preview->pixel(22,8)==original->pixel(22,8),"Selection exterior edited");require(stroke.cancel()==original,"Cancel did not return original");require(preview->pixel(10,8)==Pixel{64,0,191,255},"Cancel mutated published preview");
        RetouchSession empty(original,transform(32,16),32,16,settings,source,selection(32,16,[](int,int){return uint8_t{0};}),gpu);require(!empty.begin({10,8})&&empty.commit()==original,"Explicit empty selection edited");});
    for(Mode mode:{Mode::HealContentAware,Mode::HealCreateTexture,Mode::HealProximity})test(mode==Mode::HealContentAware?"source_heal_content_aware":mode==Mode::HealCreateTexture?"source_heal_create_texture":"source_heal_proximity",[&,mode]{
        auto original=raster(120,80,[](int x,int y){const bool blemish=x>=55&&x<65&&y>=35&&y<45;const auto gray=uint8_t(x%4<2?100:112);return blemish?Pixel{230,20,20,255}:Pixel{gray,gray,gray,255};});Settings settings;settings.mode=mode;settings.radius=12;settings.hardness=1;settings.healingSeed=0x12345678;
        RetouchSession stroke(original,transform(120,80),120,80,settings,{}, {},gpu);stroke.begin({60,40});auto wash=stroke.preview();require(wash->pixel(60,40).r<original->pixel(60,40).r,"Healing wash missing");stroke.append({60.5,40});auto healed=stroke.commit();
        for(Point p:std::array<Point,3>{{{60,40},{56,36},{64,44}}}){auto value=healed->pixel(int(p.x),int(p.y));require(int(value.r)-value.g<30&&value.g>=80&&value.g<=130&&value.a==255,"Source blemish not healed into gray texture");}
        for(Point p:std::array<Point,5>{{{10,10},{90,40},{30,40},{60,10},{60,70}}})require(healed->pixel(int(p.x),int(p.y))==original->pixel(int(p.x),int(p.y)),"Opaque pixels outside brush changed");
        require(original->pixel(60,40)==Pixel{230,20,20,255},"Healing mutated source");require(stroke.metrics().healingRegionPixels>0,"Healing region not measured");
    });
    test("healing_translucent_source_copy_preserves_outside_coverage",[&]{auto original=Raster::filled(80,80,{50,50,50,128});Settings settings;settings.mode=Mode::HealProximity;settings.radius=3;settings.hardness=1;RetouchSession stroke(original,transform(80,80),80,80,settings,{}, {},gpu);stroke.begin({40,40});auto after=stroke.commit();require(after->pixel(10,10)==Pixel{50,50,50,128},"BrushRaster.draw copy semantics lost");require(original->pixel(10,10).a==128,"Source mutated input");});
    test("blur_distinct_soft_sample_frozen_within_stroke",[&]{auto original=raster(64,32,[](int x,int){return x<32?Pixel{0,0,0,255}:Pixel{255,255,255,255};});Settings settings;settings.mode=Mode::Blur;settings.radius=10;settings.hardness=1;RetouchSession stroke(original,transform(64,32),64,32,settings,{}, {},gpu);stroke.begin({31,16});auto once=stroke.preview()->pixel(31,16);require(once.r>50&&once.r<128,"Blur did not soften edge");stroke.append({32,16});stroke.append({31,16});auto result=stroke.commit();require(result->pixel(31,16)==once,"Blur compounds within stroke");require(result->pixel(2,16)==original->pixel(2,16),"Blur outside tip changed");RetouchSession second(result,transform(64,32),64,32,settings);second.begin({31,16});require(second.commit()->pixel(31,16).r>once.r,"New blur stroke failed to compound");});
    test("blur_mask_edges_selection_and_gray_snapshots",[&]{auto original=selection(40,20,[](int x,int){return uint8_t(x<20?0:255);});Settings settings;settings.mode=Mode::Blur;settings.radius=8;settings.hardness=1;RetouchSession stroke(original,transform(40,20),40,20,settings,{},gpu);stroke.begin({19,10});auto preview=stroke.previewMask();require(preview->pixel(19,10)>50&&preview->pixel(19,10)<128,"Gray blur edge");require(stroke.previewMask()==preview,"Gray preview cache missed");auto result=stroke.commitMask();require(result->pixel(2,2)==0&&result->pixel(38,18)==255,"Gray untouched area changed");require(stroke.cancelMask()==original&&original->pixel(19,10)==0,"Gray cancel mutated source");
        bool refused=false;try{settings.mode=Mode::Clone;RetouchSession rejected(original,transform(40,20),40,20,settings);}catch(const std::invalid_argument&){refused=true;}require(refused,"Clone mask target accepted");});
    test("smudge_and_liquify_first_dab_match_distinct_source_math",[&]{auto original=raster(32,24,[](int x,int){return Pixel{uint8_t(x*7),0,0,255};});
        for(Mode mode:{Mode::Smudge,Mode::Liquify}){Settings settings;settings.mode=mode;settings.radius=4;settings.hardness=1;settings.opacity=.5;RetouchSession stroke(original,transform(32,24),32,24,settings,{}, {},gpu);stroke.begin({10,12});require(stroke.preview()==original,"Warp click painted");stroke.append({11,12});auto result=stroke.commit();require(result->pixel(11,12).r==(mode==Mode::Smudge?70:74),"Warp source center formula differs");require(stroke.metrics().warpDabs==1,"Warp spacing source threshold");require(result->pixel(25,12)==original->pixel(25,12),"Warp changed outside footprint");require(original->pixel(11,12).r==77,"Warp source mutated");}
    });
    test("warp_spacing_accumulates_short_events_and_narrow_canvas_safe",[&]{Settings settings;settings.mode=Mode::Liquify;settings.radius=20;settings.hardness=.5;auto original=Raster::filled(1,12,{50,20,10,128});RetouchSession stroke(original,transform(1,12),1,12,settings,{}, {},gpu);stroke.begin({.5,4});require(!stroke.append({.5,4.5}),"Subspacing event advanced");require(stroke.append({.5,5}),"Accumulated spacing not reached");auto result=stroke.commit();for(int y=0;y<12;++y)require(result->pixel(0,y)==original->pixel(0,y),"One-column source guard violated");});
    test("warp_selection_commit_clears_alpha_via_copy",[&]{auto original=raster(40,20,[](int x,int){return x<10?Pixel{}:Pixel{255,0,0,255};});Settings settings;settings.mode=Mode::Smudge;settings.radius=4;settings.hardness=1;settings.opacity=1;auto clip=selection(40,20,[](int x,int){return uint8_t(x<16?255:0);});RetouchSession stroke(original,transform(40,20),40,20,settings,{},clip,gpu);stroke.begin({6,10});stroke.append({12,10});stroke.append({20,10});auto result=stroke.commit();require(result->pixel(12,10).a==0,"Warp copy retained original alpha");require(result->pixel(20,10)==original->pixel(20,10),"Warp selection commit escaped");});
    test("transformed_clone_document_sampling_and_tile_sharing",[&]{auto original=Raster::filled(768,32,{0,0,255,255});auto placement=transform(768,32);placement.x=20;placement.y=10;Sources source;source.currentLayer=Raster::filled(800,64,{255,0,0,255});source.cloneOffset=Point{};Settings settings;settings.radius=4;settings.hardness=1;RetouchSession stroke(original,placement,800,64,settings,source,{},gpu);Raster::resetMaterializationCount();stroke.begin({30,20});auto result=stroke.commit();require(result->pixel(10,10)==Pixel{255,0,0,255},"Document transform sample location");require(result->tiles[1]==original->tiles[1]&&result->tiles[2]==original->tiles[2],"Untouched source tiles not shared");require(Raster::materializationCount()==0,"Retouch called Raster::rgba");});
    test("retouch_invalid_lifecycle_and_missing_sources",[]{auto original=Raster::filled(16,16,{255,0,0,255});Settings settings;RetouchSession missing(original,transform(16,16),16,16,settings);bool refused=false;try{missing.begin({8,8});}catch(const std::invalid_argument&){refused=true;}require(refused,"Clone missing source not refused");settings.sampleAllLayers=true;Sources sources;sources.cloneOffset=Point{};RetouchSession allMissing(original,transform(16,16),16,16,settings,sources);refused=false;try{allMissing.begin({8,8});}catch(const std::invalid_argument&){refused=true;}require(refused,"Missing all-layer sample not refused");settings.mode=Mode::Liquify;RetouchSession cancelled(original,transform(16,16),16,16,settings);cancelled.cancel();refused=false;try{cancelled.begin({8,8});}catch(const std::logic_error&){refused=true;}require(refused,"Cancelled session restarted");});
    std::cout<<"{\"suite\":\"retouch\",\"passed\":"<<passed<<",\"failed\":"<<failed<<",\"mac_differential\":false,\"warp\":"<<(gpu?"true":"false")<<"}\n";return failed?1:0;
}
