#include "core/Document.h"
#include "graphics/GrowingBrushSession.h"
#include "effects/Adjustments.h"
#include <cmath>
#include <functional>
#include <iostream>
#include <limits>
#include <map>
#include <stdexcept>
using namespace compositor;using namespace compositor::graphics;
namespace {
void require(bool value,const char* why){if(!value)throw std::runtime_error(why);}
void close(double a,double b,const char* why){require(std::abs(a-b)<1e-10,why);}
void equal(const Raster& a,const Raster& b){require(a.width==b.width&&a.height==b.height,"extent agreement");for(int y=0;y<a.height;++y)for(int x=0;x<a.width;++x)if(a.pixel(x,y)!=b.pixel(x,y))throw std::runtime_error("pixel disagreement "+std::to_string(x)+","+std::to_string(y));}
Layer image(int width=321,int height=181){Layer layer;layer.id=newId();layer.transform={35,28,width*.3,height*.3};std::vector<Pixel> data(size_t(width)*height);uint32_t seed=19;for(auto& p:data){seed=1664525u*seed+1013904223u;p={uint8_t(seed>>24),uint8_t(seed>>16),uint8_t(seed>>8),255};}layer.raster=Raster::fromRgba(width,height,reinterpret_cast<const uint8_t*>(data.data()),size_t(width)*4);return layer;}
Document document(Layer layer){Document d;d.width=192;d.height=144;d.layers={std::move(layer)};return d;}
void lattice(){for(double units:{1.,.5,.25,1/10.749,1/32.,1.7})for(double rotation:{0.,180.,25.}){auto layer=image();layer.transform.rotation=rotation;layer.transform.flipX=true;auto d=document(layer);CompositeCache cache;auto view=cache.renderViewport(d,55.375,40.25,std::min(130.,512*units),std::min(100.,384*units),units,64,256);require(bool(view.raster),"viewport exists");close(view.unitsPerPixel,units,"exact requested units");close((view.documentX-55.375)/units,std::round((view.documentX-55.375)/units),"physical X phase");close((view.documentY-40.25)/units,std::round((view.documentY-40.25)/units),"physical Y phase");equal(*view.raster,*SoftwareRenderer().renderScaled(d,view.documentX,view.documentY,view.raster->width,view.raster->height,units));}}
void cache_identity_and_phase(){auto layer=image(800,400);layer.transform={0,0,800,400};auto d=document(layer);d.width=800;d.height=400;CompositeCache cache;auto first=cache.renderViewport(d,0,0,256,128,.5,64,256);auto again=cache.renderViewport(d,0,0,256,128,.5,64,256);require(first.raster->tiles==again.raster->tiles,"same grid cache identity");auto shifted=cache.renderViewport(d,128,0,256,128,.5,64,256);require(shifted.raster->tiles.front()==first.raster->tiles[1],"integer physical tile pan reuses overlap");auto fractional=cache.renderViewport(d,128.125,.0625,256,128,.5,64,256);require(fractional.raster->tiles.front()!=shifted.raster->tiles.front(),"fractional phase invalidates grid");equal(*fractional.raster,*SoftwareRenderer().renderScaled(d,fractional.documentX,fractional.documentY,fractional.raster->width,fractional.raster->height,.5));}
void sparse_30k_bounds(){Document d;d.width=d.height=30000;CompositeCache cache;Raster::resetMaterializationCount();for(int i=0;i<140;++i){auto view=cache.renderViewport(d,10000+i*8.,12000,16,16,1/32.,64,256);require(view.raster&&view.raster->tiles.size()<=64,"visible tile bound");require(cache.viewportRetainedTiles()<=256&&cache.viewportMetadataEntries()<=256,"retained sparse metadata bound");require(view.raster->pixel(10,10)==Pixel{},"blank pixels");}require(cache.viewportMetadataEntries()==256,"cache reaches retained budget without global metadata");require(Raster::materializationCount()==0,"30k no whole RGBA");auto all=cache.renderViewport(d,.1,.2,30000,30000,1/32.,64,256);require(all.raster->tiles.size()<=64&&cache.viewportMetadataEntries()<=256,"full extent coarsens within tile limits");require(all.unitsPerPixel>=1/32.,"coarsening never increases work");}
void canonical_damage(){auto layer=image(769,513);layer.transform={0,0,769,513};auto d=document(layer);d.width=769;d.height=513;CompositeCache cache;auto first=cache.renderViewport(d,0,0,769,513,.5);Pixel blue{0,0,255,255};d.layers[0].raster=d.layers[0].raster->replacing(600,300,1,1,&blue,1);auto after=cache.renderViewport(d,0,0,769,513,.5);require(first.raster->tiles.front()==after.raster->tiles.front(),"unaffected canonical tile reused");equal(*after.raster,*SoftwareRenderer().renderScaled(d,after.documentX,after.documentY,after.raster->width,after.raster->height,.5));}
void immutable_preview(){for(bool mask:{false,true}){auto layer=image(97,63);layer.transform={40,30,24.25,15.75,17,true,false};layer.mask=Mask{std::make_shared<GrayRaster>(GrayRaster{97,63,std::vector<uint8_t>(97*63,255)})};auto d=document(layer);CompositeCache cache;for(int pass=0;pass<2;++pass){const auto original=d;BrushSessionSettings settings;settings.radius=3;settings.hardness=.4;settings.color=mask?std::array<uint8_t,3>{0,0,0}:std::array<uint8_t,3>{0,0,255};GrowingBrushSession stroke(d.layers[0],settings,d.width,d.height,{},{},mask);auto t=d.layers[0].transform;stroke.begin(t.fromUnit({-.02,.4}));stroke.append(t.fromUnit({.1,.5}));auto snapshot=stroke.preview();auto preview=snapshot->renderPreview();auto committed=d;committed.layers[0]=snapshot->materializeLayer();for(double units:{.25,.75}){auto view=cache.renderViewport(d,5.125,9.375,160,100,units,64,256,preview);equal(*view.raster,*SoftwareRenderer(preview).renderScaled(d,view.documentX,view.documentY,view.raster->width,view.raster->height,view.unitsPerPixel));equal(*view.raster,*SoftwareRenderer().renderScaled(committed,view.documentX,view.documentY,view.raster->width,view.raster->height,view.unitsPerPixel));}require(d==original,"canonical immutable during preview");d.layers[0]=stroke.commit()->materializeLayer();equal(*d.layers[0].raster,*committed.layers[0].raster);}}}
void subpixel_grain_partition(){auto d=document(image(128,96));Layer grain;grain.id=newId();grain.adjustmentJson=effects::defaultAdjustmentJson("Grain");grain.transform={0,0,192,144};d.layers.push_back(grain);SoftwareRenderer renderer;const double units=1/10.749,x=.137,y=.299;auto all=renderer.renderScaled(d,x,y,513,64,units),left=renderer.renderScaled(d,x,y,256,64,units),right=renderer.renderScaled(d,x+256*units,y,257,64,units);for(int yy=0;yy<64;++yy)for(int xx=0;xx<513;++xx)require(all->pixel(xx,yy)==(xx<256?left->pixel(xx,yy):right->pixel(xx-256,yy)),"grain physical tile partition");}
void guards(){auto d=document(image());CompositeCache cache;for(double units:{0.,-1.,1/64.,double(NAN),double(INFINITY),32769.}){bool rejected=false;try{cache.renderViewport(d,0,0,10,10,units);}catch(const std::invalid_argument&){rejected=true;}require(rejected,"invalid viewport step");}require(SoftwareRenderer().renderScaled(d,0,0,1,1,1/32.)!=nullptr,"minimum physical step accepted");cache.reset();require(cache.viewportRetainedTiles()==0&&cache.viewportMetadataEntries()==0,"reset releases sparse cache");}
}
int main(){std::cout<<std::unitbuf;int failed=0;for(auto [name,body]:std::map<std::string,void(*)()>{{"lattice",lattice},{"cache_identity_and_phase",cache_identity_and_phase},{"sparse_30k_bounds",sparse_30k_bounds},{"canonical_damage",canonical_damage},{"immutable_preview",immutable_preview},{"subpixel_grain_partition",subpixel_grain_partition},{"guards",guards}}){try{body();std::cout<<"PASS "<<name<<'\n';}catch(const std::exception& e){++failed;std::cout<<"FAIL "<<name<<": "<<e.what()<<'\n';}}return failed?1:0;}
