if(NOT DEFINED EXECUTABLE OR NOT DEFINED CASE OR NOT DEFINED EVIDENCE_ROOT)
  message(FATAL_ERROR "EXECUTABLE, CASE and EVIDENCE_ROOT are required")
endif()
set(cases clipping_color option_stack hidden_source persistence_bake moved_chain)
set(counts 24 16 10 15 9)
list(FIND cases "${CASE}" index)
if(index LESS 0)
  message(FATAL_ERROR "Unknown LiveMask source invocation")
endif()
list(GET counts ${index} expected)
string(TIMESTAMP stamp "%Y%m%d-%H%M%S" UTC)
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
set(directory "${EVIDENCE_ROOT}/${CASE}/${stamp}-${nonce}")
file(MAKE_DIRECTORY "${directory}")
execute_process(COMMAND "${EXECUTABLE}" "${CASE}" "${directory}/result.json"
  RESULT_VARIABLE status OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
file(WRITE "${directory}/stdout.log" "${stdout}")
file(WRITE "${directory}/stderr.log" "${stderr}")
message("${stdout}${stderr}")
if(NOT EXISTS "${directory}/result.json")
  message(FATAL_ERROR "Source report missing; process=${status}")
endif()
file(READ "${directory}/result.json" report)
string(JSON outcome GET "${report}" status)
string(JSON count LENGTH "${report}" checks)
message("SOURCE_REPORT ${directory}/result.json checks=${count}")
if(NOT status EQUAL 0 OR NOT outcome STREQUAL "passed" OR NOT count EQUAL expected)
  message(FATAL_ERROR "LiveMask source result=${outcome}, process=${status}, checks=${count}/${expected}")
endif()
