#include "editing_transform/Distortion.h"
#include <cmath>
#include <iostream>
#include <stdexcept>
using namespace compositor;
using namespace compositor::editing_transform;
namespace {
int passed=0,failed=0;
void require(bool condition,const char* message){if(!condition)throw std::runtime_error(message);}
void near(Point a,Point b,const char* message){require(std::hypot(a.x-b.x,a.y-b.y)<1e-7,message);}
template<class F>void test(const char* name,F body){try{body();++passed;std::cout<<"PASS "<<name<<'\n';}catch(const std::exception&e){++failed;std::cout<<"FAIL "<<name<<": "<<e.what()<<'\n';}}
Layer layer(int w=20,int h=20){Layer out;out.id="original";out.name="Original";out.raster=Raster::filled(w,h,{255,0,0,255});out.transform={10,10,double(w),double(h),0,false,false,Transform::Sampling::Nearest};return out;}
std::shared_ptr<const GrayRaster> gray(int w,int h,uint8_t value){auto out=std::make_shared<GrayRaster>();out->width=w;out->height=h;out->pixels.assign(size_t(w)*h,value);return out;}
const Corners shape{{{10,10},{60,10},{30,30},{10,30}}};
}
int main(){
    test("source_homography_corners_inverse_and_invalid_shapes",[]{auto map=Homography::fromCorners(shape),inverse=map.inverse();const Corners units{{{0,0},{1,0},{1,1},{0,1}}};for(size_t i=0;i<4;++i){near(map.map(units[i]),shape[i],"Corner mapping differs");near(inverse.map(shape[i]),units[i],"Inverse mapping differs");}near(inverse.map(map.map({.23,.79})),{.23,.79},"Perspective inverse interior");auto twisted=shape;std::swap(twisted[1],twisted[2]);bool rejected=false;try{(void)Homography::fromCorners(twisted);}catch(const std::invalid_argument&){rejected=true;}require(rejected,"Twisted shape accepted");});
    test("source_shape_bounds_inside_outside_and_alpha",[]{auto original=layer();auto result=distortLayer(original,original.transform,shape);require(result.transform.x==10&&result.transform.y==10&&result.transform.width==50&&result.transform.height==20&&result.transform.rotation==0,"Source output bounds differ");require(result.raster->pixel(40,2).a==255&&result.raster->pixel(5,15).a==255,"Source inside pixels differ");require(result.raster->pixel(40,18).a==0,"Outside slanted edge opaque");require(result.id==original.id&&result.name==original.name&&result.raster!=original.raster,"Identity metadata lost or source reused");require(original.raster->pixel(0,0)==Pixel{255,0,0,255},"Original mutated");});
    test("source_alpha_trim_and_matching_mask_crop",[]{auto original=layer(40,20);std::vector<Pixel> pixels(800);for(int y=5;y<15;++y)for(int x=15;x<25;++x)pixels[size_t(y)*40+x]={255,0,0,255};original.raster=Raster::filled(40,20)->replacing(0,0,40,20,pixels.data(),40);original.mask=Mask{gray(40,20,128)};const Corners target{{{10,10},{60,10},{50,30},{10,30}}};auto result=distortLayer(original,original.transform,target);require(result.transform.width<20&&result.transform.height<=12&&result.transform.x>=20&&result.transform.y>=14,"Source cutout trim bounds differ");require(result.mask->raster->width==result.raster->width&&result.mask->raster->height==result.raster->height,"Local mask did not crop with image");require(!result.mask->placement,"Local mask became independently placed");require(result.mask->raster->pixel(result.mask->raster->width/2,result.mask->raster->height/2)==128,"Local mask tone changed");});
    test("identity_and_flip_image_corner_order",[]{auto original=layer(4,2);const std::array<Pixel,8> values{{{255,0,0,255},{0,255,0,255},{0,0,255,255},{128,128,0,128},{10,20,30,40},{40,30,20,50},{0,0,0,0},{1,1,1,255}}};original.raster=Raster::filled(4,2)->replacing(0,0,4,2,values.data(),4);for(bool fx:{false,true})for(bool fy:{false,true}){auto draft=original.transform;draft.flipX=fx;draft.flipY=fy;auto result=warpRaster(original.raster,draft,corners(draft));for(int y=0;y<2;++y)for(int x=0;x<4;++x)require(result.raster->pixel(x,y)==original.raster->pixel(fx?3-x:x,fy?1-y:y),"Image corners did not preserve flips");require(!result.transform.flipX&&!result.transform.flipY&&result.transform.sampling==draft.sampling,"Baked placement flags/sampling");}});
    test("source_uniform_mask_pointer_survives_warp",[]{auto original=layer();auto uniform=gray(1,1,255);original.mask=Mask{uniform};original.mask->enabled=false;auto result=distortLayer(original,original.transform,shape);require(result.mask->raster==uniform&&!result.mask->enabled,"Uniform mask identity/enabled state changed");});
    test("linked_placed_mask_carried_and_unlinked_stays_document_fixed",[]{auto original=layer();original.mask=Mask{gray(6,6,255)};original.mask->placement=Transform{12,12,6,6,0,false,false,Transform::Sampling::Nearest};const auto placed=*original.mask->placement;auto linked=distortLayer(original,original.transform,shape);require(linked.mask->placement&&*linked.mask->placement!=placed&&linked.mask->linked,"Linked placed mask failed to follow perspective");auto map=Homography::fromCorners(shape);auto carried=carriedCorners(placed,original.transform,shape);near(carried[0],map.map(original.transform.toUnit({12,12})),"Linked mask corner mapping");
        original.mask->linked=false;auto unlinked=distortLayer(original,original.transform,shape);require(unlinked.mask->raster==original.mask->raster&&unlinked.mask->placement==original.mask->placement,"Unlinked mask moved or resampled");original.mask->placement.reset();auto implicit=distortLayer(original,original.transform,shape);require(implicit.mask->placement==original.transform,"Implicit unlinked mask did not freeze original placement");});
    test("gray_warp_exterior_white_and_black",[]{auto source=gray(20,20,128);auto transform=layer().transform;auto white=warpGray(source,transform,shape,255),black=warpGray(source,transform,shape,0);require(white.raster->pixel(40,18)==255&&black.raster->pixel(40,18)==0,"Placed mask exterior differs");require(white.raster->pixel(5,5)==128&&black.raster->pixel(5,5)==128,"Mask inside tone differs");});
    test("preview_limit_bounds_and_cancel_transaction",[]{auto original=layer();DistortionSession session(original);require(session.update(original.transform,shape),"Valid update refused");auto invalid=shape;invalid[1]=invalid[0];require(!session.update(original.transform,invalid)&&session.shape()==shape,"Invalid update overwrote last valid corners");auto preview=session.preview(10);require(preview.raster->width==10&&preview.raster->height==4&&preview.transform.width==50,"Preview reduction changed document bounds");int checks=0;bool cancelled=false;try{session.apply([&]{return ++checks>=4;});}catch(const TransformCancelled&){cancelled=true;}require(cancelled&&checks==4,"Row cancellation not observed");auto cancelledLayer=session.cancel();require(cancelledLayer==original,"Cancel failed original exact restoration");require(session.apply()==original,"Finished cancel reapplied");});
    test("apply_idempotence_empty_alpha_and_budget_rejection",[]{auto original=layer();DistortionSession session(original);session.update(original.transform,shape);auto applied=session.apply();require(session.apply()==applied,"Apply not idempotent");original.raster=Raster::filled(20,20);auto empty=distortLayer(original,original.transform,shape);require(empty.transform.width==50&&empty.transform.height==20,"Empty warp must retain full bounds");auto huge=shape;huge[1].x=40010;huge[2].x=40010;bool rejected=false;try{warpRaster(original.raster,original.transform,huge);}catch(const std::invalid_argument&){rejected=true;}require(rejected,"Oversized warp accepted");});
    std::cout<<"{\"suite\":\"distortion\",\"passed\":"<<passed<<",\"failed\":"<<failed<<",\"mac_differential\":false}\n";return failed?1:0;
}
