#include "editing_transform/PixelTransform.h"
#include <iostream>
#include <stdexcept>
using namespace compositor;
using namespace compositor::editing_transform;
namespace {
int passed=0,failed=0;
void require(bool b,const char* message){if(!b)throw std::runtime_error(message);}
template<class F>void test(const char* name,F body){try{body();++passed;std::cout<<"PASS "<<name<<'\n';}catch(const std::exception&e){++failed;std::cout<<"FAIL "<<name<<": "<<e.what()<<'\n';}}
Layer layer(int w=100,int h=40){Layer out;out.id="original";out.name="Colors";out.transform={0,0,double(w),double(h),0,false,false,Transform::Sampling::Nearest};std::vector<Pixel> pixels(size_t(w)*h);for(int y=0;y<h;++y)for(int x=0;x<w;++x)pixels[size_t(y)*w+x]=x<w/2?Pixel{255,0,0,255}:Pixel{0,0,255,255};out.raster=Raster::filled(w,h)->replacing(0,0,w,h,pixels.data(),w);return out;}
std::shared_ptr<const GrayRaster> select(int w,int h,int x0,int y0,int rw,int rh,uint8_t coverage=255){auto out=std::make_shared<GrayRaster>();out->width=w;out->height=h;out->pixels.resize(size_t(w)*h);for(int y=y0;y<y0+rh;++y)for(int x=x0;x<x0+rw;++x)out->pixels[size_t(y)*w+x]=coverage;return out;}
}
int main(){
    test("selection_preview_matches_apply_and_cancels_independently",[]{auto original=layer();auto selection=select(100,40,10,10,10,10);PixelTransformSession session(original,selection,PixelTransformKind::Affine);require(session.selectionPreview()==selection,"Unstarted selection preview changed source");session.begin();auto draft=session.draft();draft.x+=25;draft.rotation=15;session.update(draft);int checks=0;bool stopped=false;try{session.selectionPreview([&]{return ++checks==3;});}catch(const TransformCancelled&){stopped=true;}require(stopped,"Selection-only preview missed cancellation");auto preview=session.selectionPreview();auto applied=session.apply();require(preview->pixels==applied.selection->pixels,"Selection-only preview differs from committed coverage");require(session.selectionPreview()==applied.selection,"Finished selection preview did not retain result");});
    test("floating_preview_preserves_source_stack_mask_and_blend_scope",[]{auto original=layer();original.opacity=.5;original.blend=Blend::Multiply;original.mask=Mask{select(1,1,0,0,1,1)};auto selection=select(100,40,10,10,10,10);PixelTransformSession session(original,selection,PixelTransformKind::Affine);session.begin();auto preview=session.floatingPreview();require(preview.clearedLayer.raster->pixel(15,15).a==0&&preview.clearedLayer.mask==original.mask,"Cleared source mask/pixels wrong");require(preview.floatingLayer.opacity==.5&&preview.floatingLayer.blend==Blend::Multiply&&!preview.floatingLayer.mask&&preview.floatingLayer.maskSourceId.empty(),"Floating layer inherited unintended mask/link");require(preview.floatingLayer.raster->pixel(5,5)==Pixel{255,0,0,255},"Floating pixels premultiplied by layer opacity");require(session.floatingPreview().floatingLayer.id==preview.floatingLayer.id,"Floating preview identity changed");});
    test("source_move_pixels_and_outline_from_original_each_preview",[]{auto original=layer();auto selection=select(100,40,10,10,10,10);PixelTransformSession move(original,selection);require(move.begin(),"Move failed to lift");move.move({30.4,0});move.preview();move.move({40.4,0});auto first=move.preview();move.move({60.2,5});auto result=move.apply();require(result.layer.raster->pixel(15,15).a==0,"Source hole missing");require(result.layer.raster->pixel(75,20)==Pixel{255,0,0,255},"Moved red missing");require(result.layer.raster->pixel(85,20)==Pixel{0,0,255,255}&&result.layer.raster->pixel(5,5)==Pixel{255,0,0,255},"Outside move altered");require(result.layer.raster->pixel(55,15)==original.raster->pixel(55,15),"Earlier preview ghost remained");require(result.selection->pixel(75,20)==255&&result.selection->pixel(15,15)==0,"Selection outline did not move");require(result.selectionBounds.x==70&&result.selectionBounds.y==15&&result.selectionBounds.width==10,"Source outline bounds");require(first.layer.raster->pixel(55,15)==Pixel{255,0,0,255},"Published earlier preview mutated");require(original.raster->pixel(15,15).a==255,"Original source changed");});
    test("source_duplicate_keeps_original_and_new_pixels",[]{auto original=layer();auto selection=select(100,40,10,10,10,10);PixelTransformSession copy(original,selection,PixelTransformKind::Move,true);copy.begin();copy.move({60,5});auto result=copy.apply();require(result.layer.raster->pixel(15,15)==Pixel{255,0,0,255}&&result.layer.raster->pixel(75,20)==Pixel{255,0,0,255},"Duplicate removed original or failed destination");auto cancelled=copy.cancel();require(cancelled.layer==original&&cancelled.selection==selection,"Cancellation did not restore exact source pointers");});
    test("source_affine_move_selected_pixels",[]{auto original=layer();auto selection=select(100,40,10,10,10,10);PixelTransformSession session(original,selection,PixelTransformKind::Affine);require(session.begin(),"Affine lift failed");auto draft=session.draft();require(draft.x==10&&draft.y==10&&draft.width==10&&draft.height==10,"Floating image document bounds");draft.x=70;draft.y=20;session.update(draft);auto result=session.apply();require(result.layer.raster->pixel(15,15).a==0&&result.layer.raster->pixel(75,25)==Pixel{255,0,0,255},"Source affine selected move");require(result.layer.id==original.id&&result.layer.name==original.name,"Selected transform replaced layer identity");require(result.selection->pixel(75,25)==255&&result.selectionBounds.x==70&&result.selectionBounds.y==20,"Affine selection did not move");});
    test("source_unchanged_soft_selection_is_exact_noop",[]{auto original=layer();auto selection=select(100,40,10,5,30,25,128);for(auto kind:{PixelTransformKind::Move,PixelTransformKind::Affine}){PixelTransformSession session(original,selection,kind);session.begin();auto result=session.apply();require(result.layer==original&&result.selection==selection,"Unchanged soft selection modified document");}});
    test("source_affine_growth_and_mask_reveals_new_area",[]{auto original=layer();auto localMask=std::make_shared<GrayRaster>();localMask->width=localMask->height=1;localMask->pixels={0};original.mask=Mask{localMask};auto selection=select(100,40,0,0,10,10);PixelTransformSession session(original,selection,PixelTransformKind::Affine);session.begin();auto draft=session.draft();draft.width=draft.height=20;draft.x=90;draft.y=30;session.update(draft);auto result=session.apply();require(result.layer.raster->width==110&&result.layer.raster->height==50&&result.layer.transform.width==110&&result.layer.transform.height==50,"Floating merge source extent");require(result.layer.raster->pixel(95,35)==Pixel{255,0,0,255}&&result.layer.raster->pixel(5,5).a==0,"Growth pixels wrong");require(result.layer.mask->raster->pixel(105,45)==255&&result.layer.mask->raster->pixel(5,5)==0,"Grown local mask did not reveal new area");require(result.selectionBounds.x==90&&result.selectionBounds.width==20&&result.selectionBounds.height==20,"Unclipped selection bounds lost");});
    test("move_extends_imported_grid_within_canvas_and_far_move_clips",[]{auto original=layer(10,10);original.transform.x=20;original.transform.y=20;auto selection=select(100,60,20,20,5,5);PixelTransformSession session(original,selection);session.begin();session.move({40,0});auto result=session.apply();require(result.layer.raster->width==45&&result.layer.transform.x==20&&result.layer.transform.width==45,"Imported grid did not grow to moved pixels");require(result.layer.raster->pixel(42,2)==Pixel{255,0,0,255},"Moved imported pixels missing");PixelTransformSession far(original,selection);far.begin();far.move({10000,0});auto removed=far.apply();require(removed.layer.raster->width==10&&removed.layer.raster->pixel(2,2).a==0,"Far move must clear original and clip destination to workspace");});
    test("scaled_layer_whole_document_move_can_be_fractional_source",[]{auto original=layer(10,10);original.transform.width=original.transform.height=20;auto selection=select(20,20,0,0,10,20);PixelTransformSession session(original,selection);session.begin();session.move({1,0});auto result=session.apply();require(result.layer.raster->pixel(0,4).a>0&&result.layer.raster->pixel(0,4).a<255,"Half-source-pixel move must interpolate boundary");require(result.selection->pixel(0,4)==0&&result.selection->pixel(1,4)==255,"Document selection move wrong");});
    test("affine_flip_and_distortion_selection_mapping",[]{auto original=layer(20,10);auto selection=select(20,10,0,0,20,10);PixelTransformSession flip(original,selection,PixelTransformKind::Affine);flip.begin();auto draft=flip.draft();draft.flipX=true;flip.update(draft);auto flipped=flip.apply();require(flipped.layer.raster->pixel(2,5)==Pixel{0,0,255,255}&&flipped.layer.raster->pixel(17,5)==Pixel{255,0,0,255},"Selected image flip orientation");
        PixelTransformSession perspective(original,selection,PixelTransformKind::Affine);perspective.begin();const Corners shape{{{0,0},{20,0},{10,10},{0,10}}};perspective.update(perspective.draft(),shape);require(perspective.selectionPreview({},true)==selection,"Source live distorted outline should retain affine placement until Apply");require(perspective.selectionPreview()->pixel(18,8)==0,"Final distorted selection preview ignored homography");auto warped=perspective.apply();require(warped.layer.raster->pixel(18,8).a==0&&warped.selection->pixel(18,8)==0,"Distorted pixels/selection exterior");auto p=perspective.mapSelectionPoint({20,10});require(p==Point{10,10},"Perspective selection endpoint");});
    test("shared_unaffected_tiles_and_midrender_cancel",[]{auto original=layer(768,32);auto selection=select(768,32,5,5,10,10);PixelTransformSession session(original,selection);session.begin();session.move({20,0});auto result=session.preview();require(result.layer.raster->tiles[1]==original.raster->tiles[1]&&result.layer.raster->tiles[2]==original.raster->tiles[2],"Untouched tiles not retained");session.move({30,0});int checks=0;bool didCancel=false;try{session.preview([&]{return ++checks==3;});}catch(const TransformCancelled&){didCancel=true;}require(didCancel,"Pixel preview cancellation not checked");auto cancelled=session.cancel();require(cancelled.layer==original&&cancelled.selection==selection,"Cancelled pixel session lost originals");});
    test("empty_selection_invalid_draft_and_apply_idempotence",[]{auto original=layer();PixelTransformSession empty(original,select(100,40,0,0,0,0));require(!empty.begin()&&empty.apply().layer==original,"Empty selection edited");PixelTransformSession session(original,select(100,40,10,10,10,10),PixelTransformKind::Affine);session.begin();auto draft=session.draft();draft.width=0;require(!session.update(draft),"Invalid affine draft accepted");draft=session.draft();draft.x+=10;session.update(draft);auto applied=session.apply();require(session.apply().layer==applied.layer,"Pixel apply not idempotent");});
    std::cout<<"{\"suite\":\"pixel_transform\",\"passed\":"<<passed<<",\"failed\":"<<failed<<",\"mac_differential\":false}\n";return failed?1:0;
}


