#include "ui/NativeCanvas.h"
#include <QApplication>
#include <QElapsedTimer>
#include <QImage>
#include <QMouseEvent>
#include <QTabletEvent>
#include <QWheelEvent>
#include <QNativeGestureEvent>
#include <QPointingDevice>
#include <QThread>
#include <functional>
#include <iostream>
#include <stdexcept>
using namespace compositor;
namespace {
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
void closeEnough(double a,double b,const char* message){require(std::abs(a-b)<1e-7,message);}
void closeEnough(QPointF a,QPointF b,const char* message){closeEnough(a.x(),b.x(),message);closeEnough(a.y(),b.y(),message);}
void flush(){QElapsedTimer timer;timer.start();do{QApplication::processEvents();QThread::msleep(5);}while(timer.elapsed()<40);}
void pointer(NativeCanvas& canvas,QEvent::Type type,QPointF position,Qt::MouseButton button,Qt::MouseButtons buttons){QMouseEvent event(type,position,canvas.mapToGlobal(position),button,buttons,Qt::NoModifier);QApplication::sendEvent(&canvas,&event);}
std::shared_ptr<const Raster> stripes(){std::vector<Pixel> pixels(16*16);for(int y=0;y<16;++y)for(int x=0;x<16;++x)pixels[size_t(y)*16+x]=x%2?Pixel{0,0,255,255}:Pixel{255,0,0,255};return Raster::fromRgba(16,16,reinterpret_cast<const uint8_t*>(pixels.data()),16*4);}
}
int main(int argc,char** argv){QApplication app(argc,argv);int passed=0,failed=0;auto test=[&](const char* name,const std::function<void()>& run){try{run();++passed;std::cout<<"PASS "<<name<<'\n';}catch(const std::exception& error){++failed;std::cout<<"FAIL "<<name<<": "<<error.what()<<'\n';}};
    test("native_actual_pixels_physical_dpr2",[&]{NativeCanvas canvas(true);canvas.resize(400,300);canvas.setRaster(stripes());canvas.show();flush();closeEnough(canvas.devicePixelRatioF(),2,"Run this physical-pixel witness with QT_SCALE_FACTOR=2 on the 100% display");canvas.zoomAt(1,QPointF(canvas.width()/2.,canvas.height()/2.));canvas.repaint();flush();canvas.repaint();flush();require(canvas.deviceReady(),"WARP canvas device unavailable");require(canvas.deviceError().isEmpty(),"WARP canvas draw failed");closeEnough(canvas.pointsPerPixel(),.5,"Widget uses DIP zoom");auto image=canvas.captureRendered();require(image.width()==800&&image.height()==600,"Swap chain dimensions do not follow physical pixels");auto origin=canvas.viewMapping().toView({0,0});const int left=int(std::lround(origin.x*2)),top=int(std::lround(origin.y*2));for(int x=0;x<16;++x){const auto actual=image.pixelColor(left+x,top+7),expected=x%2?QColor(0,0,255):QColor(255,0,0);if(actual!=expected)std::cout<<"Physical sample "<<x<<" actual "<<actual.red()<<','<<actual.green()<<','<<actual.blue()<<" origin "<<left<<','<<top<<'\n';require(actual==expected,"Document stripes are not exactly one physical pixel wide");}if(argc>1)require(image.save(QString::fromLocal8Bit(argv[1])),"Capture file save failed");std::cout<<"WARP capture "<<image.width()<<'x'<<image.height()<<" DPR "<<canvas.devicePixelRatioF()<<" document width physical 16\n";});
    test("native_fit_resize_pan_and_zoom_anchor",[]{NativeCanvas canvas(true);canvas.resize(896,696);canvas.setRaster(Raster::filled(400,300));canvas.show();flush();canvas.fit();closeEnough(canvas.zoom,4,"Widget initial source fit");canvas.resize(496,396);flush();closeEnough(canvas.zoom,2,"Widget followsFit resize");closeEnough(canvas.pan,{},"Fit pan");canvas.panBy({70,-20});require(!canvas.followsFit(),"Widget pan retained fit");auto centerDoc=canvas.documentPoint({canvas.width()/2.,canvas.height()/2.});canvas.resize(700,500);flush();closeEnough(canvas.documentPoint({canvas.width()/2.,canvas.height()/2.}),centerDoc,"Widget manual viewport resize shifted center");const QPointF anchor{87,124};auto doc=canvas.documentPoint(anchor);canvas.zoomAt(7,anchor);closeEnough(canvas.documentPoint(anchor),doc,"Widget anchored zoom moved document point");});
    test("native_repeated_hand_mouse_events_and_release",[]{NativeCanvas canvas(true);canvas.resize(400,300);canvas.setRaster(Raster::filled(600,400));canvas.show();flush();canvas.zoomAt(1,{200,150});QPointF press;int downs=0,moves=0,ups=0,cancels=0;canvas.pointerDown=[&](QPointF p,Qt::KeyboardModifiers){press=p;++downs;};canvas.pointerMove=[&](QPointF p,Qt::KeyboardModifiers){canvas.panBy((p-press)*canvas.pointsPerPixel());++moves;};canvas.pointerUp=[&](QPointF,Qt::KeyboardModifiers){++ups;};canvas.pointerCancel=[&]{++cancels;};pointer(canvas,QEvent::MouseButtonPress,{100,100},Qt::LeftButton,Qt::LeftButton);for(QPointF p:std::array<QPointF,4>{{{110,100},{120,100},{130,107},{125,112}}})pointer(canvas,QEvent::MouseMove,p,Qt::NoButton,Qt::LeftButton);pointer(canvas,QEvent::MouseButtonRelease,{125,112},Qt::LeftButton,Qt::NoButton);closeEnough(canvas.pan,{25,12},"Hand repeated mouse events stalled");require(downs==1&&moves==4&&ups==1&&cancels==0,"Normal release triggered cancellation");require(QWidget::mouseGrabber()!=&canvas,"Normal release kept mouse grab");pointer(canvas,QEvent::MouseButtonPress,{100,100},Qt::LeftButton,Qt::LeftButton);QEvent deactivate(QEvent::WindowDeactivate);QApplication::sendEvent(&canvas,&deactivate);require(cancels==1&&QWidget::mouseGrabber()!=&canvas,"Deactivation failed to cancel/release mouse exactly once");});
    test("native_viewport_patch_lod_uses_physical_scale",[]{NativeCanvas canvas(true);canvas.resize(400,300);canvas.setDocumentSize(30000,30000);double requestX=0,requestY=0,requestW=0,requestH=0,requestStep=0;int requests=0;canvas.viewportProvider=[&](double x,double y,double w,double h,double step){requestX=x;requestY=y;requestW=w;requestH=h;requestStep=step;++requests;return CompositeViewport{};};canvas.show();flush();canvas.zoomAt(.5,{200,150});canvas.repaint();flush();closeEnough(requestStep,2,"LOD counted DIPs instead of physical pixels");closeEnough(requestW,1600,"Viewport document width omitted backingScale");closeEnough(requestH,1200,"Viewport document height omitted backingScale");closeEnough(QPointF(requestX,requestY),canvas.documentPoint({0,0}),"Patch origin differs from event mapping");require(requests>0,"Viewport provider never called");canvas.setDocumentSize(0,0);const auto before=requests;canvas.repaint();flush();require(requests==before,"Empty document retained stale provider render");});
    test("native_gradient_overlay_outside_document_without_patch",[]{NativeCanvas canvas(true);canvas.resize(400,300);canvas.setDocumentSize(20,20);canvas.viewportProvider=[](double,double,double,double,double){return CompositeViewport{};};canvas.show();flush();canvas.zoomAt(2,{200,150});canvas.setGradientLine(std::pair{Point{-130,-40},Point{-30,-40}});canvas.repaint();flush();canvas.repaint();flush();require(canvas.deviceReady(),"Gradient canvas device unavailable");auto image=canvas.captureRendered();const auto midpoint=canvas.viewMapping().toView({-80,-40});const auto color=image.pixelColor(int(midpoint.x*2),int(midpoint.y*2));require(color.red()>220&&color.green()>220&&color.blue()>220,"Gradient line missing outside document or absent patch");const auto endpoint=canvas.viewMapping().toView({-130,-40});const auto handle=image.pixelColor(int((endpoint.x+3)*2),int(endpoint.y*2));require(handle.red()>220&&handle.green()>220&&handle.blue()>220,"Gradient endpoint missing");canvas.setGradientLine(std::nullopt);canvas.repaint();flush();canvas.repaint();flush();image=canvas.captureRendered();require(image.pixelColor(int(midpoint.x*2),int(midpoint.y*2)).red()<80,"Cancelled gradient line remained");});
    test("native_brush_ring_hardness_and_clone_marker_render",[&]{NativeCanvas canvas(true);canvas.resize(400,300);canvas.setDocumentSize(20,20);canvas.show();flush();canvas.setBrushCursor(Point{100,100},40,.5,Point{160,100});canvas.repaint();flush();canvas.repaint();flush();auto image=canvas.captureRendered();require(image.pixelColor(158,200).red()>180&&image.pixelColor(160,200).red()<80,"Outer brush ring white/black outline missing");bool inner=false;for(int y=178;y<=222;++y)for(int x=178;x<=222;++x){const double radius=std::hypot(x-200.,y-200.);if(radius>17&&radius<23&&image.pixelColor(x,y).red()>180)inner=true;}require(inner,"Hardness ring missing");require(image.pixelColor(320,200).red()<80&&image.pixelColor(324,202).red()>180,"Clone source crosshair missing");if(argc>1)require(image.save(QString::fromLocal8Bit(argv[1])+".brush.png"),"Brush cursor screenshot save failed");});
    test("native_precise_discrete_wheel_magnify_and_navigation_guard",[]{NativeCanvas canvas(true);canvas.resize(400,300);canvas.setDocumentSize(200,100);canvas.show();flush();canvas.zoomAt(1,{200,150});const auto initial=canvas.pan;const QPointF anchor{70,90};auto wheel=[&](QPoint pixel,QPoint angle,Qt::KeyboardModifiers modifiers){QWheelEvent event(anchor,canvas.mapToGlobal(anchor),pixel,angle,Qt::NoButton,modifiers,Qt::NoScrollPhase,false);QApplication::sendEvent(&canvas,&event);};wheel({3,7},{},{});closeEnough(canvas.pan,initial+QPointF(3,7),"Precise scroll lost DIP delta");wheel({},{120,-120},{});closeEnough(canvas.pan,initial+QPointF(15,-5),"Discrete scroll normalization differs");const auto document=canvas.documentPoint(anchor);wheel({0,10},{},Qt::AltModifier);closeEnough(canvas.zoom,std::exp(-.15),"Source exponential Alt zoom differs");closeEnough(canvas.documentPoint(anchor),document,"Wheel zoom moved anchor");QNativeGestureEvent magnify(Qt::ZoomNativeGesture,QPointingDevice::primaryPointingDevice(),2,anchor,anchor,canvas.mapToGlobal(anchor),.25,{});QApplication::sendEvent(&canvas,&magnify);closeEnough(canvas.zoom,std::exp(-.15)*1.25,"Native magnify not proportional");closeEnough(canvas.documentPoint(anchor),document,"Native magnify moved anchor");const double zoom=canvas.zoom;const auto pan=canvas.pan;canvas.navigationAllowed=[]{return false;};wheel({0,20},{},{});wheel({0,20},{},Qt::ControlModifier);QApplication::sendEvent(&canvas,&magnify);closeEnough(canvas.zoom,zoom,"Busy gesture allowed zoom");closeEnough(canvas.pan,pan,"Busy gesture allowed pan");});
    test("native_tablet_pointer_mapping_no_pressure_or_duplicate_mouse",[]{NativeCanvas canvas(true);canvas.resize(400,300);canvas.setDocumentSize(200,100);canvas.show();flush();canvas.zoomAt(1,{200,150});QPointingDevice pen("Synthetic witness",717,QInputDevice::DeviceType::Stylus,QPointingDevice::PointerType::Pen,QInputDevice::Capability::Position|QInputDevice::Capability::Pressure,1,3);int downs=0,moves=0,ups=0;QPointF first,last;canvas.pointerDown=[&](QPointF p,Qt::KeyboardModifiers){first=p;++downs;};canvas.pointerMove=[&](QPointF p,Qt::KeyboardModifiers){last=p;++moves;};canvas.pointerUp=[&](QPointF,Qt::KeyboardModifiers){++ups;};auto tablet=[&](QEvent::Type type,QPointF position,double pressure,Qt::MouseButton button,Qt::MouseButtons buttons){QTabletEvent event(type,&pen,position,canvas.mapToGlobal(position),pressure,0,0,0,0,0,Qt::NoModifier,button,buttons);QApplication::sendEvent(&canvas,&event);require(event.isAccepted(),"Tablet event allowed duplicate mouse synthesis");};tablet(QEvent::TabletPress,{100,100},.2,Qt::LeftButton,Qt::LeftButton);pointer(canvas,QEvent::MouseButtonPress,{100,100},Qt::LeftButton,Qt::LeftButton);tablet(QEvent::TabletMove,{110,106},.9,Qt::NoButton,Qt::LeftButton);tablet(QEvent::TabletRelease,{110,106},0,Qt::LeftButton,Qt::NoButton);require(downs==1&&moves==1&&ups==1,"Tablet generated duplicate or missing transaction events");closeEnough(first,canvas.documentPoint({100,100}),"Tablet initial document mapping");closeEnough(last,canvas.documentPoint({110,106}),"Tablet update document mapping");});
    std::cout<<"{\"suite\":\"native_viewport\",\"passed\":"<<passed<<",\"failed\":"<<failed<<",\"mac_differential\":false,\"backend\":\"D3D11_WARP\"}\n";return failed?1:0;
}
