#include "graphics/GrowingBrushSession.h"
#include "graphics/StackRenderer.h"
#include "effects/Adjustments.h"
#include <algorithm>
#include <iostream>
#include <map>
#include <stdexcept>

using namespace compositor;
using namespace compositor::graphics;
namespace {
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
Layer photo(int width,int height){Layer image;image.id=newId();image.transform={0,0,double(width),double(height)};std::vector<Pixel> data(size_t(width)*height);uint32_t state=3;for(auto& p:data){state=state*1664525u+1013904223u;p={uint8_t(state>>24),uint8_t(state>>16),uint8_t(state>>8),255};}image.raster=Raster::fromRgba(width,height,reinterpret_cast<const uint8_t*>(data.data()),size_t(width)*4);return image;}
void equal(const Raster& a,const Raster& b){require(a.width==b.width&&a.height==b.height,"dimensions");for(int y=0;y<a.height;++y)for(int x=0;x<a.width;++x)if(a.pixel(x,y)!=b.pixel(x,y))throw std::runtime_error("preview/committed pixel mismatch at "+std::to_string(x)+","+std::to_string(y));}
Document document(Layer layer,int width,int height){Document d;d.width=width;d.height=height;d.layers={std::move(layer)};return d;}
BrushSessionSettings tip(){BrushSessionSettings settings;settings.radius=6;settings.hardness=.4;settings.opacity=.73;settings.color={90,10,230};return settings;}
void compare(const Document& original,const GrowingBrushSnapshot& snapshot,double x,double y,int width,int height,double units=1){auto committed=original;auto source=snapshot.renderPreview();require(bool(source),"render preview exists");auto found=std::find_if(committed.layers.begin(),committed.layers.end(),[&](const Layer& l){return l.id==source->layer.id;});require(found!=committed.layers.end(),"target layer exists");*found=snapshot.materializeLayer();equal(*SoftwareRenderer(source).renderScaled(original,x,y,width,height,units),*SoftwareRenderer().renderScaled(committed,x,y,width,height,units));}
void photo_phase(){auto l=photo(2400,1800);l.transform={100,75,600,450};auto d=document(l,800,600);GrowingBrushSession session(l,tip(),800,600);session.begin({400,300});session.append({420,300});auto snapshot=session.preview();const auto before=session.metrics();auto source=snapshot->renderPreview();Raster::resetMaterializationCount();auto direct=SoftwareRenderer(source).render(d,0,0,800,600);require(session.metrics().materializedTiles==before.materializedTiles&&Raster::materializationCount()==0,"preview must not materialize source pixels");compare(d,*snapshot,0,0,800,600);compare(d,*snapshot,0,0,400,300,2);require(l.raster==d.layers[0].raster&&l.transform==d.layers[0].transform,"canonical document unchanged");}
void growth_transform_masks(){for(bool placed:{false,true})for(double rotation:{0.,31.}){auto l=photo(311,173);l.transform={170,90,155.5,86.5,rotation,true,false};auto gray=std::make_shared<GrayRaster>(GrayRaster{41,23,std::vector<uint8_t>(41*23)});for(size_t i=0;i<gray->pixels.size();++i)gray->pixels[i]=uint8_t(i%253);l.mask=Mask{gray};if(placed)l.mask->placement=Transform{120,60,220,160,13};auto d=document(l,600,360);GrowingBrushSession session(l,tip(),600,360);session.begin(l.transform.fromUnit({-.06,.5}));session.append(l.transform.fromUnit({.03,.5}));auto snapshot=session.preview();require(snapshot->sourceBounds().x<0,"negative source growth");compare(d,*snapshot,0,0,600,360);compare(d,*snapshot,0,0,300,180,2);}}
void mask_groups(){for(bool group:{false,true})for(bool placed:{false,true}){auto l=photo(360,180);l.transform={10,20,360,180};l.mask=Mask{std::make_shared<GrayRaster>(GrayRaster{61,47,std::vector<uint8_t>(61*47,255)})};if(placed&&!group)l.mask->placement=Transform{70,40,120,100,17};auto d=document(l,400,240);if(group){d.layers[0].group=true;d.layers[0].raster.reset();auto child=photo(400,240);child.parentId=l.id;d.layers.push_back(child);}auto settings=tip();settings.color={0,0,0};GrowingBrushSession session(d.layers[0],settings,400,240,{},{},true);session.begin({80,60});session.append({90,65});compare(d,*session.preview(),0,0,400,240);}}
void clipped_hidden_and_adjustment(){for(bool hidden:{false,true}){auto base=photo(400,200);base.opacity=.53;base.visible=!hidden;auto child=photo(400,200);child.maskSourceId=base.id;child.blend=Blend::Screen;child.opacity=.61;Document d=document(base,400,200);d.layers.push_back(child);Layer adjustment;adjustment.id=newId();adjustment.transform=base.transform;adjustment.adjustmentJson=effects::defaultAdjustmentJson("Exposure");adjustment.adjustmentJson.pop_back();adjustment.adjustmentJson+=R"(,"exposureSettings":{"exposure":0.7,"offset":0.03,"gamma":1.2}})";d.layers.push_back(adjustment);auto settings=tip();settings.erase=true;GrowingBrushSession session(base,settings,400,200);session.begin({200,100});session.append({210,100});compare(d,*session.preview(),0,0,400,200);}}
void snapshot_cache_lifecycle(){auto l=photo(520,260);auto d=document(l,520,260);GrowingBrushSession session(l,tip(),520,260);CompositeCache cache;auto before=cache.renderViewport(d,0,0,520,260);session.begin({100,100});auto first=session.preview();auto preview=cache.renderViewport(d,0,0,520,260,1,64,256,first->renderPreview());auto again=cache.renderViewport(d,0,0,520,260,1,64,256,first->renderPreview());require(preview.raster->tiles==again.raster->tiles,"same immutable snapshot should hit cache");session.append({400,100});auto second=session.preview();auto changed=cache.renderViewport(d,0,0,520,260,1,64,256,second->renderPreview());require(changed.raster->tiles!=preview.raster->tiles,"new snapshot identity must invalidate cache");compare(d,*first,0,0,520,260);compare(d,*second,0,0,520,260);auto restored=cache.renderViewport(d,0,0,520,260);equal(*restored.raster,*before.raster);require(Raster::materializationCount()==0,"no full rgba");}
void blank_bound_and_lifetime(){Layer l;l.id=newId();l.transform={0,0,30000,30000};auto d=document(l,30000,30000);std::shared_ptr<const LayerRenderPreview> source;{GrowingBrushSession session(l,tip(),30000,30000);session.begin({15000,15000});source=session.preview()->renderPreview();require(session.metrics().materializedTiles==0,"source preview allocations");}Raster::resetMaterializationCount();CompositeCache cache;auto view=cache.renderViewport(d,0,0,30000,30000,1,64,64,source);require(view.raster&&view.raster->tiles.size()<=64,"visible storage bound");auto close=cache.renderViewport(d,14900,14900,256,192,1,64,64,source);auto reference=SoftwareRenderer(source).renderScaled(d,close.documentX,close.documentY,close.raster->width,close.raster->height,close.unitsPerPixel);equal(*close.raster,*reference);require(Raster::materializationCount()==0,"blank preview full rgba");}
void damage_growth_cache(){for(double rotation:{0.,17.}){auto l=photo(311,173);l.transform={150,80,311,173,rotation,true,false};auto d=document(l,800,400);CompositeCache cache;cache.renderViewport(d,0,0,800,400);GrowingBrushSession stroke(l,tip(),800,400);for(int event=0;event<12;++event){auto point=l.transform.fromUnit({-.01-double(event%3)*.01,.25+event*.03});if(!event)stroke.begin(point);else stroke.append(point);auto source=stroke.preview()->renderPreview();auto view=cache.renderViewport(d,0,0,800,400,1,64,256,source);equal(*view.raster,*SoftwareRenderer(source).render(d,0,0,800,400));}auto restored=cache.renderViewport(d,0,0,800,400);equal(*restored.raster,*SoftwareRenderer().render(d,0,0,800,400));}}
}
int main(int argc,char** argv){std::map<std::string,void(*)()> cases{{"photo_phase",photo_phase},{"growth_transform_masks",growth_transform_masks},{"mask_groups",mask_groups},{"clipped_hidden_and_adjustment",clipped_hidden_and_adjustment},{"snapshot_cache_lifecycle",snapshot_cache_lifecycle},{"blank_bound_and_lifetime",blank_bound_and_lifetime},{"damage_growth_cache",damage_growth_cache}};int failed=0,passed=0;for(const auto& [name,body]:cases){if(argc>1&&name!=argv[1])continue;try{body();++passed;std::cout<<"PASS "<<name<<'\n';}catch(const std::exception& e){++failed;std::cout<<"FAIL "<<name<<": "<<e.what()<<'\n';}}std::cout<<passed<<" passed, "<<failed<<" failed\n";return failed||passed==0?1:0;}
