#include "platform/DisplayProfile.h"
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>
#include <algorithm>
#include <cmath>
#include <fstream>
#include <iostream>
#include <map>
using namespace compositor::platform;
using compositor::imaging::RgbaImage;
#define REQUIRE(...) do{if(!(__VA_ARGS__))throw std::runtime_error(std::string(__FILE__)+":"+std::to_string(__LINE__)+": " #__VA_ARGS__);}while(false)
std::filesystem::path fixture;
RgbaImage pixels(unsigned w=19,unsigned h=3){RgbaImage image{w,h,size_t(w)*4+12,std::vector<std::uint8_t>((size_t(w)*4+12)*h,0xDD)};for(unsigned y=0;y<h;++y)for(unsigned x=0;x<w;++x){auto* p=image.pixels.data()+y*image.stride+x*4;const auto a=std::uint8_t((x+y)%3==0?0:(x+y)%3==1?128:255);p[0]=std::uint8_t((x*11)%(a+1));p[1]=std::uint8_t((x*17)%(a+1));p[2]=std::uint8_t((x*23)%(a+1));p[3]=a;}return image;}
void same(const RgbaImage& a,const RgbaImage& b,int tolerance=0){REQUIRE(a.width==b.width&&a.height==b.height);for(unsigned y=0;y<a.height;++y)for(unsigned x=0;x<a.width*4;++x)REQUIRE(std::abs(int(a.pixels[y*a.stride+x])-int(b.pixels[y*b.stride+x]))<=(x%4==3?0:tolerance));}
std::filesystem::path srgb(){wchar_t system[MAX_PATH]{};REQUIRE(GetSystemDirectoryW(system,MAX_PATH));return std::filesystem::path(system)/L"spool/drivers/color/sRGB Color Space Profile.icm";}
void identity(){auto profile=loadDisplayProfile(srgb());REQUIRE(profile.kind==DisplayProfileKind::Icc&&profile.sha256.size()==64&&profile.diagnostic.empty());auto image=pixels(),before=image;DisplayColorConverter converter(true);auto result=converter.convert(image,profile);REQUIRE(result.converted&&!result.fallback&&result.profileHash==profile.sha256);same(image,result.pixels);REQUIRE(image.pixels==before.pixels);std::cout<<"adapter="<<converter.adapterName()<<" profile="<<profile.sha256<<'\n';}
void linear(){auto profile=loadDisplayProfile(fixture);REQUIRE(profile.kind==DisplayProfileKind::Icc);DisplayColorConverter converter(true);RgbaImage image{256,3,1024,std::vector<std::uint8_t>(256*3*4)};for(unsigned y=0;y<3;++y)for(unsigned x=0;x<256;++x){auto* p=image.pixels.data()+y*1024+x*4;const unsigned a=y==0?255:y==1?128:0;p[0]=p[1]=p[2]=std::uint8_t((x*a+127)/255);p[3]=std::uint8_t(a);}auto before=image;auto result=converter.convert(image,profile);REQUIRE(result.converted&&!result.fallback);int maximum=0;for(unsigned y=0;y<3;++y)for(unsigned x=0;x<256;++x){const auto* input=image.pixels.data()+y*1024+x*4;const auto* output=result.pixels.pixels.data()+y*1024+x*4;const double a=input[3]/255.;const double value=input[3]?double(input[0])/input[3]:0;const double linear=value<=.04045?value/12.92:std::pow((value+.055)/1.055,2.4);int expected=int(std::lround(linear*a*255));for(unsigned c=0;c<3;++c){maximum=std::max(maximum,std::abs(int(output[c])-expected));REQUIRE(output[c]<=output[3]);}REQUIRE(output[3]==input[3]);}std::cout<<"maximum_linear_error="<<maximum<<" limit=2\n";REQUIRE(maximum<=2);REQUIRE(result.pixels.pixels[128*4]>=53&&result.pixels.pixels[128*4]<=57);REQUIRE(image.pixels==before.pixels);}
void fallback(){auto profile=loadDisplayProfile(fixture.parent_path()/"required-absent.icc");REQUIRE(profile.kind==DisplayProfileKind::AssumedSrgb&&!profile.diagnostic.empty());DisplayColorConverter converter(true);auto image=pixels();auto result=converter.convert(image,profile);REQUIRE(result.fallback&&!result.converted&&!result.diagnostic.empty());same(image,result.pixels);profile=loadDisplayProfile(fixture);REQUIRE(profile.kind==DisplayProfileKind::Icc);profile.icc[36]='x';result=converter.convert(image,profile);REQUIRE(result.fallback&&!result.converted&&!result.diagnostic.empty());same(image,result.pixels);}
void tileBudget(){auto profile=loadDisplayProfile(fixture);REQUIRE(profile.kind==DisplayProfileKind::Icc);DisplayColorConverter converter(true);auto image=pixels(277,67);auto one=converter.convert(image,profile,{64*1024*1024,1024});auto many=converter.convert(image,profile,{64*1024*1024,17});REQUIRE(one.converted&&many.converted);same(one.pixels,many.pixels);bool rejected=false;try{converter.convert(image,profile,{1,17});}catch(const std::invalid_argument&){rejected=true;}REQUIRE(rejected);}
void monitor(){auto profile=discoverDisplayProfile(nullptr);REQUIRE(!profile.monitorDevice.empty());REQUIRE(profile.kind==DisplayProfileKind::Icc?(!profile.icc.empty()&&profile.sha256.size()==64):!profile.diagnostic.empty());std::cout<<"monitor_profile_kind="<<(profile.kind==DisplayProfileKind::Icc?"icc":"srgb_fallback")<<" profile="<<profile.sha256<<" diagnostic="<<profile.diagnostic<<'\n';}
void validation(){auto original=loadDisplayProfile(fixture);REQUIRE(original.kind==DisplayProfileKind::Icc);DisplayColorConverter converter(true);auto image=pixels();for(unsigned mode=0;mode<5;++mode){auto profile=original;if(mode==0)profile.icc[16]='C';if(mode==1)profile.icc[144]=0xff;if(mode==2)profile.icc.resize(130);if(mode==3)profile.icc[0]=0xff;if(mode==4)profile.sha256[0]=profile.sha256[0]=='0'?'1':'0';auto result=converter.convert(image,profile);REQUIRE(result.fallback&&!result.converted&&!result.diagnostic.empty());same(image,result.pixels);}auto bad=image;bad.pixels[0]=255;bool rejected=false;try{converter.convert(bad,original);}catch(const std::exception&){rejected=true;}REQUIRE(rejected);}
void switches(){auto standard=loadDisplayProfile(srgb()),linearProfile=loadDisplayProfile(fixture);REQUIRE(standard.kind==DisplayProfileKind::Icc&&linearProfile.kind==DisplayProfileKind::Icc&&standard.sha256!=linearProfile.sha256);DisplayColorConverter converter(true);auto image=pixels(),before=image;auto first=converter.convert(image,standard);auto second=converter.convert(image,linearProfile);auto third=converter.convert(image,standard);REQUIRE(first.converted&&second.converted&&third.converted);same(image,first.pixels);same(image,third.pixels);REQUIRE(first.pixels.pixels!=second.pixels.pixels&&image.pixels==before.pixels);}
int main(int argc,char**argv){try{REQUIRE(argc==3);fixture=std::filesystem::path(argv[2]);std::map<std::string,void(*)()> tests{{"srgb_identity",identity},{"linear_profile",linear},{"invalid_fallback",fallback},{"tile_budget",tileBudget},{"monitor_discovery",monitor},{"icc_validation",validation},{"profile_switch",switches}};REQUIRE(tests.contains(argv[1]));tests.at(argv[1])();std::cout<<"PASS "<<argv[1]<<'\n';return 0;}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<'\n';return 1;}}
